### ISSUE TITLE
error while test knowledge

### ISSUE THREAD

**Issue by ticoAg** [langgenius/dify#10012]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

config some proxy in `docker-compose.yaml`

```yaml
services:
  # API service
  api:
    image: langgenius/dify-api:0.10.2
    restart: always
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      # Startup mode, 'api' starts the API server.
      MODE: api
      HTTP_PROXY: http://192.168.0.100:7891
      HTTPS_PROXY: http://192.168.0.100:7891
      NO_PROXY: weaviate,qdrant,db,redis,web,worker,sandbox
    depends_on:
      - db
      - redis
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - ./volumes/app/storage:/app/api/storage
    networks:
      - ssrf_proxy_network
      - default

  # worker service
  # The Celery worker for processing the queue.
  worker:
    image: langgenius/dify-api:0.10.2
    restart: always
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      # Startup mode, 'worker' starts the Celery worker for processing the queue.
      MODE: worker
      NO_PROXY: localhost,127.0.0.1,172.17.*.*,.local,weaviate
    depends_on:
      - db
      - redis
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - ./volumes/app/storage:/app/api/storage
    networks:
      - ssrf_proxy_network
      - default
```

config openai api_key and silicon api_key
upload a file to knowledge
run hit test

### ✔️ Expected Behavior

recall relevant text chunk

### ❌ Actual Behavior

# web show
`Meta endpoint! Unexpected status code: 502, with response body: None.`

# docker-api-1's log
```text
2024-10-29 09:50:17,907.907 ERROR [Dummy-2] [hit_testing_base.py:84] - Hit testing failed.
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/hit_testing_base.py", line 57, in perform_hit_testing
    response = HitTestingService.retrieve(
  File "/app/api/services/hit_testing_service.py", line 46, in retrieve
    all_documents = RetrievalService.retrieve(
  File "/app/api/core/rag/datasource/retrieval_service.py", line 104, in retrieve
    raise Exception(exception_message)
Exception: Meta endpoint! Unexpected status code: 502, with response body: None.
2024-10-29 09:50:17,908.908 ERROR [Dummy-2] [app.py:838] - Exception on /console/api/datasets/174efb7c-1de5-4173-8d69-a3624addc5a5/hit-testing [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/hit_testing_base.py", line 57, in perform_hit_testing
    response = HitTestingService.retrieve(
  File "/app/api/services/hit_testing_service.py", line 46, in retrieve
    all_documents = RetrievalService.retrieve(
  File "/app/api/core/rag/datasource/retrieval_service.py", line 104, in retrieve
    raise Exception(exception_message)
Exception: Meta endpoint! Unexpected status code: 502, with response body: None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 92, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/datasets/hit_testing.py", line 21, in post
    return self.perform_hit_testing(dataset, args)
  File "/app/api/controllers/console/datasets/hit_testing_base.py", line 85, in perform_hit_testing
    raise InternalServerError(str(e))
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Meta endpoint! Unexpected status code: 502, with response body: None.
2024-10-29 09:53:18,840.840 ERROR [Dummy-4] [hit_testing_base.py:84] - Hit testing failed.
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/hit_testing_base.py", line 57, in perform_hit_testing
    response = HitTestingService.retrieve(
  File "/app/api/services/hit_testing_service.py", line 46, in retrieve
    all_documents = RetrievalService.retrieve(
  File "/app/api/core/rag/datasource/retrieval_service.py", line 104, in retrieve
    raise Exception(exception_message)
Exception: Meta endpoint! Unexpected status code: 502, with response body: None.
2024-10-29 09:53:18,841.841 ERROR [Dummy-4] [app.py:838] - Exception on /console/api/datasets/174efb7c-1de5-4173-8d69-a3624addc5a5/hit-testing [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/hit_testing_base.py", line 57, in perform_hit_testing
    response = HitTestingService.retrieve(
  File "/app/api/services/hit_testing_service.py", line 46, in retrieve
    all_documents = RetrievalService.retrieve(
  File "/app/api/core/rag/datasource/retrieval_service.py", line 104, in retrieve
    raise Exception(exception_message)
Exception: Meta endpoint! Unexpected status code: 502, with response body: None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 92, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/datasets/hit_testing.py", line 21, in post
    return self.perform_hit_testing(dataset, args)
  File "/app/api/controllers/console/datasets/hit_testing_base.py", line 85, in perform_hit_testing
    raise InternalServerError(str(e))
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Meta endpoint! Unexpected status code: 502, with response body: None.

```

**Comment by crazywoola** [comment]
Check the vdb status.
