### ISSUE TITLE
Pydantic error: `TIDB_ON_QDRANT_CLIENT_TIMEOUT`

### ISSUE THREAD

**Issue by RW21** [langgenius/dify#10023]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

c6e54c83c87917334a4c95fdb5599d1597f32e4c

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

`docker compose up` with the default config at c6e54c83c87917334a4c95fdb5599d1597f32e4c.
In the console, this occurs -> https://github.com/langgenius/dify/issues/10021

### ✔️ Expected Behavior

Runs.

### ❌ Actual Behavior

A lot of services are failing with an exception with the default config and docker compose. Perhaps related to this commit: https://github.com/langgenius/dify/commit/c6e54c83c87917334a4c95fdb5599d1597f32e4c

```
api-1         | Traceback (most recent call last):
api-1         |   File "/app/api/.venv/bin/flask", line 8, in <module>
api-1         |     sys.exit(main())
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 1105, in main
api-1         |     cli.main()
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
api-1         |     rv = self.invoke(ctx)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1682, in invoke
api-1         |     cmd_name, cmd, args = self.resolve_command(ctx, args)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1729, in resolve_command
api-1         |     cmd = self.get_command(ctx, cmd_name)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 611, in get_command
api-1         |     app = info.load_app()
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 335, in load_app
api-1         |     app = locate_app(import_name, name)
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
api-1         |     __import__(module_name)
api-1         |   File "/app/api/app.py", line 3, in <module>
api-1         |     from configs import dify_config
api-1         |   File "/app/api/configs/__init__.py", line 3, in <module>
api-1         |     dify_config = DifyConfig()
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 167, in __init__
api-1         |     super().__init__(
api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
api-1         |     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
api-1         | pydantic_core._pydantic_core.ValidationError: 1 validation error for DifyConfig
api-1         | TIDB_ON_QDRANT_CLIENT_TIMEOUT
api-1         |   Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='dify', input_type=str]
api-1         |     For further information visit https://errors.pydantic.dev/2.9/v/int_parsing
worker-1      | Traceback (most recent call last):
worker-1      |   File "/app/api/.venv/bin/flask", line 8, in <module>
worker-1      |     sys.exit(main())
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 1105, in main
worker-1      |     cli.main()
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
worker-1      |     rv = self.invoke(ctx)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1682, in invoke
worker-1      |     cmd_name, cmd, args = self.resolve_command(ctx, args)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1729, in resolve_command
worker-1      |     cmd = self.get_command(ctx, cmd_name)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 611, in get_command
worker-1      |     app = info.load_app()
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 335, in load_app
worker-1      |     app = locate_app(import_name, name)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
worker-1      |     __import__(module_name)
worker-1      |   File "/app/api/app.py", line 3, in <module>
worker-1      |     from configs import dify_config
worker-1      |   File "/app/api/configs/__init__.py", line 3, in <module>
worker-1      |     dify_config = DifyConfig()
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 167, in __init__
worker-1      |     super().__init__(
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
worker-1      |     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
worker-1      | pydantic_core._pydantic_core.ValidationError: 1 validation error for DifyConfig
worker-1      | TIDB_ON_QDRANT_CLIENT_TIMEOUT
worker-1      |   Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='dify', input_type=str]
worker-1      |     For further information visit https://errors.pydantic.dev/2.9/v/int_parsing
worker-1 exited with code 1
api-1 exited with code 1
```

**Comment by crazywoola** [comment]
Please switch to the v0.10.2 tag to start the application. We will fix it later.
