### ISSUE TITLE
LOG_TZ ValidationError

### ISSUE THREAD

**Issue by mayiming0708** [langgenius/dify#10061]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

bab5c542197f935d35fe75eb5d2c3301fbbf58b4

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

start and visit, if I revert this commit(bab5c542197f935d35fe75eb5d2c3301fbbf58b4),it will be ok

### ❌ Actual Behavior

Traceback (most recent call last):
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 948, in app
    raise err from None
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/.venv/lib/python3.10/site-packages/werkzeug/debug/__init__.py", line 342, in debug_application
    app_iter = self.app(environ, start_response)
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 948, in app
    raise err from None
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 937, in run_command
    app: WSGIApplication = info.load_app()
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 339, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/app.py", line 3, in <module>
    from configs import dify_config
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/configs/__init__.py", line 3, in <module>
    dify_config = DifyConfig()
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/.venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 167, in __init__
    super().__init__(
  File "/Users/antk/Documents/code/github.com/langgenius/dify/api/.venv/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for DifyConfig
LOG_TZ
  String should have at least 1 character [type=string_too_short, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/string_too_short

**Comment by mayiming0708** [comment]
LOG_TZ use default config `None`
