### ISSUE TITLE
Dify Send invite member mail failed

### ISSUE THREAD

**Issue by shaxiaozz** [langgenius/dify#10515]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

Version 0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.Add SMTP configuration in docker/.env (my SMTP is from Mailgun)
```
MAIL_TYPE=smtp
MAIL_DEFAULT_SEND_FROM=noreply@example.com
SMTP_SERVER=smtp.eu.mailgun.org
SMTP_PORT=465
SMTP_USERNAME=noreply@example.com
SMTP_PASSWORD=mailgun-api-key
SMTP_USE_TLS=true
SMTP_OPPORTUNISTIC_TLS=false
```

2.dify invites members via email
![image](https://github.com/user-attachments/assets/bdcb739b-0a98-4f41-9003-a96a2eb3cdad)

3.Observe the "docker-worker-1" container log
![image](https://github.com/user-attachments/assets/48603595-24ac-480e-8aa4-3ee29a7be4ea)

### ✔️ Expected Behavior

I think that after I configure SMTP correctly, I can send invitation emails to the target mailbox normally.

### ❌ Actual Behavior

However, after configuring SMTP, I invited members and found that there was no corresponding email in the member mailbox. And I observed that the "worker" container had an error log about SMTP~

1."docker-worker-1" container log
```
[2024-11-10 15:46:11,152: ERROR/MainProcess] Send invite member mail to dabige@4chian.com failed
Traceback (most recent call last):
  File "/app/api/libs/smtp.py", line 32, in send
    smtp.login(self.username, self.password)
  File "/usr/local/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/usr/local/lib/python3.10/smtplib.py", line 642, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/local/lib/python3.10/smtplib.py", line 432, in docmd
    return self.getreply()
  File "/usr/local/lib/python3.10/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/tasks/mail_invite_member_task.py", line 43, in send_invite_member_mail_task
    mail.send(to=to, subject="立即加入 Dify 工作空间", html=html_content)
  File "/app/api/extensions/ext_mail.py", line 77, in send
    self._client.send(
  File "/app/api/libs/smtp.py", line 52, in send
    smtp.quit()
  File "/usr/local/lib/python3.10/smtplib.py", line 1004, in quit
    res = self.docmd("quit")
  File "/usr/local/lib/python3.10/smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "/usr/local/lib/python3.10/smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/local/lib/python3.10/smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
[2024-11-10 15:46:11,176: INFO/MainProcess] Task tasks.mail_invite_member_task.send_invite_member_mail_task[a57a33b3-1762-4c9e-8c54-45b37e6a378d] succeeded in 0.6585999309991166s: None
```

According to the key information in the log "Connection unexpectedly closed", we may first suspect that this is a network problem, but I have already captured the packets at the network level to check. The network level is normal, but there is a problem here, that is, when the dify worker first performs a three-way handshake with the SMTP host, as long as the SMTP host does not respond to the first SYN, the dify worker will throw an exception. As shown in the following figure:
![image](https://github.com/user-attachments/assets/5569bb0e-36b8-4b74-b103-c1f6737d4256)

I don't understand what is causing this. If possible, can you help me? Or is there something I haven't configured properly about SMTP in Dify?

**Comment by shaxiaozz** [comment]
Thanks for reply~
1. **Verify SMTP Credentials:** I can be sure that this is available, because I can send emails normally on other software platforms with the agreed configuration~
2. **TLS/SSL Configuration:** As shown in my initial report: ```SMTP_USE_TLS=true``` is already enabled. I think ```SMTP_OPPORTUNISTIC_TLS=true``` is only applicable when the SMTP port is 587. Therefore, my SMTP configuration for these two items is: ```SMTP_USE_TLS=true, SMTP_OPPORTUNISTIC_TLS=false```
3. **Firewall and Network Settings:** I have used the telnet command on the server to test the network level. The test is normal~
![image](https://github.com/user-attachments/assets/6fd959f0-4d05-449b-86e8-a3734a392bd6)

4. **Mailgun Account Settings:** Mailgun does not have a whitelist or anything like that. By default, all are reachable because it authenticates based on username and password.
5. **SMTP Server Logs:** Since the Mailgun I use is a public service, I may not be able to directly observe the logs on the service side~
6. **Retry Mechanism:** Indeed, there is no retry function at present.
7. **openssl test:** ```openssl s_client -connect smtp.eu.mailgun.org:465 -crlf``` Here are the test results:
```
[root@dify-ai ~]# openssl s_client -connect smtp.eu.mailgun.org:465 -crlf                
Connecting to 34.111.145.192
CONNECTED(00000003)
depth=2 C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root G2
verify return:1
depth=1 C=US, O=DigiCert Inc, CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
verify return:1
depth=0 C=US, ST=Texas, L=San Antonio, O=MAILGUN TECHNOLOGIES, INC, CN=*.eu.mailgun.org
verify return:1
---
Certificate chain
 0 s:C=US, ST=Texas, L=San Antonio, O=MAILGUN TECHNOLOGIES, INC, CN=*.eu.mailgun.org
   i:C=US, O=DigiCert Inc, CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jun 24 00:00:00 2024 GMT; NotAfter: Jun 29 23:59:59 2025 GMT
 1 s:C=US, O=DigiCert Inc, CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
   i:C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root G2
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Mar 30 00:00:00 2021 GMT; NotAfter: Mar 29 23:59:59 2031 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIG9DCCBdygAwIBAgIQB3xvHAcil4vPJApAlZujKTANBgkqhkiG9w0BAQsFADBZ
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypE
aWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjQw
NjI0MDAwMDAwWhcNMjUwNjI5MjM1OTU5WjByMQswCQYDVQQGEwJVUzEOMAwGA1UE
CBMFVGV4YXMxFDASBgNVBAcTC1NhbiBBbnRvbmlvMSIwIAYDVQQKExlNQUlMR1VO
IFRFQ0hOT0xPR0lFUywgSU5DMRkwFwYDVQQDDBAqLmV1Lm1haWxndW4ub3JnMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnejJ9Jwamje5fGE5d5weWKAZ
kjVeKWXuPBrHCokdfoTTaeiqs3rDH76djNq05LW6QNMZfYrIh4pRwPtNT0ow5Mgx
62qIb8HPtzG4ND6cO4yxGF4zvmlegzsUq+aA5V3AuXfMWZXqar16jBxtFvolDIBF
9zVipDqYug0sBM8ibtfA6r78+onXb5RMyQFail6QjUmdUc/eH99LlNtH8CpkgoRx
mVttpwy7jC8u0hBT6QeI7pPl2KmgJRXg8Urrz42ZxPXTcydIihZN4uxfBt5sXN7y
5U5AkjTEVVfFyOp7vknOcSNp3VucfnIycB0FL+D8bnMh+NVLTezEOqJV0lHmTQID
AQABo4IDnTCCA5kwHwYDVR0jBBgwFoAUdIWAwGbH3zfez70pN6oDHb7tzRcwHQYD
VR0OBBYEFGCqx1NAd2cDEn2q2ztS7U0cj4zsMCsGA1UdEQQkMCKCECouZXUubWFp
bGd1bi5vcmeCDmV1Lm1haWxndW4ub3JnMD4GA1UdIAQ3MDUwMwYGZ4EMAQICMCkw
JwYIKwYBBQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNVHQ8B
Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGfBgNVHR8E
gZcwgZQwSKBGoESGQmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEds
b2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNybDBIoEagRIZCaHR0cDovL2Ny
bDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYyMDIw
Q0ExLTEuY3JsMIGHBggrBgEFBQcBAQR7MHkwJAYIKwYBBQUHMAGGGGh0dHA6Ly9v
Y3NwLmRpZ2ljZXJ0LmNvbTBRBggrBgEFBQcwAoZFaHR0cDovL2NhY2VydHMuZGln
aWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYyMDIwQ0ExLTEu
Y3J0MAwGA1UdEwEB/wQCMAAwggF/BgorBgEEAdZ5AgQCBIIBbwSCAWsBaQB2AE51
oydcmhDDOFts1N8/Uusd8OCOG41pwLH6ZLFimjnfAAABkErIcFUAAAQDAEcwRQIh
AMJPXWjL1RZoFuKSCKenRwApUacXqbp+4h3jhNvLvHcKAiBMeEQOv4A1++3znPj9
4Kna88pFMhREGjzIO1kc0AVjzgB2AObSMWNAd4zBEEEG13G5zsHSQPaWhIb7uocy
Hf0eN45QAAABkErIcHwAAAQDAEcwRQIhAIIiM0OQS0t6hjthvLN8DRF/n0Mdha1Y
33RObHQoDD+3AiAwl/tmuhWhXCLlEJHDDq5hJtDKOKze1U6Z6bnVnyPCVAB3AKLj
CuRF772tm3447Udnd1PXgluElNcrXhssxLlQpEfnAAABkErIcSsAAAQDAEgwRgIh
AKw3eJwVoysfS0S4ypZ7/7e3HAshgPp4G0vAOQPlLCqJAiEAjBHcm7/G5P+qvzui
tiHnMP+8M36TJxEYtPjGaAV6JAowDQYJKoZIhvcNAQELBQADggEBAHPayTPvyz3B
Zz/qBVypmlO4QNct816fXPRqTqTc4pXZwziaz/2ZAWCS9RULwYvjfI/5cAdrwyOj
LirBVHCWq0LE1LeJc7MtTg2tV2hY2WZjXWuTHrh8uHwC5DsxrWghE3+BRiz1mGem
lHzMs3nil7omXk/5T64tFZ/CbnNaOzeiWwdBEHYIVgKCAJv/K2S4ce2Q9OKzNnio
8UA/yovb47M2DTLorVQe3UnzVNRK5l0h8Me7b2yHzZOih8nKwsdZWHIPkKb6Cxcw
YirlPrQgrizijCpJR/FPHyg+P721vQmHatzhtT2lyc5+dvFN3qAczQ9uc9P1WVfI
JZYzQSKxMKI=
-----END CERTIFICATE-----
subject=C=US, ST=Texas, L=San Antonio, O=MAILGUN TECHNOLOGIES, INC, CN=*.eu.mailgun.org
issuer=C=US, O=DigiCert Inc, CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3603 bytes and written 423 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 6A8901FEB837B1D9328902CDAEA58018B0281A47BDD0A0516B02DF5A8EE46E12
    Session-ID-ctx: 
    Master-Key: 55D09FC90385B7F8EF4D43714D07B73C634B8723DF4A8D60334A9D09887AD4D46FE8E5143812310807AC95480904C24A
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket:
    0000 - d1 24 fd dd 31 e1 53 15-1f 43 d6 fd 8e 5e f9 0f   .$..1.S..C...^..
    0010 - 32 c9 85 1d 5b a4 bc d3-a5 b9 e0 2c c0 d9 a9 ac   2...[......,....
    0020 - 94 47 b5 b2 be 72 f1 01-56 0e 81 96 1f 45 7e f2   .G...r..V....E~.
    0030 - db 86 82 0c d4 3f 8b 03-88 6e 98 00 82 c2 6d e9   .....?...n....m.
    0040 - 7d 13 e5 07 9a 38 c0 ea-49 b2 47 47 94 7c 59 f3   }....8..I.GG.|Y.
    0050 - 2e 5f b6 44 4a f0 94 22-77 ac 4d dc dc 8b f6 63   ._.DJ.."w.M....c
    0060 - 09 c6 87 f9 28 c0 67 aa-af 16 15 1f dc a3 6e 5c   ....(.g.......n\
    0070 - e4 3c fc 6c ff 85 91 d1-7f 4f 54 e1 42 71 41 72   .<.l.....OT.BqAr
    0080 - 35                                                5

    Start Time: 1731293278
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
220 Mailgun Influx ready
```

**Comment by shaxiaozz** [comment]
I'm very sorry, I tried to use other email service providers to test TLS, and it was normal. So I understand that there should be a problem with Mailgun, and it has nothing to do with dify~
