### ISSUE TITLE
Celery not starting correctly when LOG_FILE is empty

### ISSUE THREAD

**Issue by fdb02983rhy** [langgenius/dify#10555]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Keep the LOG_FILE environment variable empty then run docker compose

### ✔️ Expected Behavior

Celery can starts successfully even the LOG_FILE is not set or empty. 

### ❌ Actual Behavior

Celery cannot starts successfully even the LOG_FILE is not set or empty. 
```
worker-1      | Traceback (most recent call last):
worker-1      |   File "/app/api/.venv/bin/celery", line 8, in <module>
worker-1      |     sys.exit(main())
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/__main__.py", line 15, in main
worker-1      |     sys.exit(_main())
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/celery.py", line 236, in main
worker-1      |     return celery(auto_envvar_prefix="CELERY")
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
worker-1      |     return self.main(*args, **kwargs)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
worker-1      |     rv = self.invoke(ctx)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
worker-1      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
worker-1      |     return ctx.invoke(self.callback, **ctx.params)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
worker-1      |     return __callback(*args, **kwargs)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
worker-1      |     return f(get_current_context(), *args, **kwargs)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/base.py", line 135, in caller
worker-1      |     return f(ctx, *args, **kwargs)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/worker.py", line 348, in worker
worker-1      |     worker = app.Worker(
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 98, in __init__
worker-1      |     self.setup_instance(**self.prepare_args(**kwargs))
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 131, in setup_instance
worker-1      |     self.on_init_blueprint()
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 116, in on_init_blueprint
worker-1      |     self._custom_logging = self.setup_logging()
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 180, in setup_logging
worker-1      |     return self.app.log.setup(
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 63, in setup
worker-1      |     handled = self.setup_logging_subsystem(
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 117, in setup_logging_subsystem
worker-1      |     self._configure_logger(
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 150, in _configure_logger
worker-1      |     self.setup_handlers(logger, logfile, format,
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 216, in setup_handlers
worker-1      |     handler = self._detect_handler(logfile)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 226, in _detect_handler
worker-1      |     return WatchedFileHandler(logfile, encoding='utf-8')
worker-1      |   File "/usr/local/lib/python3.10/logging/handlers.py", line 479, in __init__
worker-1      |     logging.FileHandler.__init__(self, filename, mode=mode,
worker-1      |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
worker-1      |     StreamHandler.__init__(self, self._open())
worker-1      |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
worker-1      |     return open_func(self.baseFilename, self.mode,
worker-1      | IsADirectoryError: [Errno 21] Is a directory: '/app/api'
```

**Comment by fujita-h** [comment]
I'm confirming the same issue.

**Comment by xiandan-erizo** [comment]
可以在环境变量中修改LOG_FILE，临时解决

**Comment by yuzp-work** [comment]
+1

**Comment by nicklhy** [comment]
+1

**Comment by rxue92** [comment]
FYI: If you don't need log file persistence and just want the worker container to start correctly, you can set the `LOG_FILE` variable in the `.env` file as shown below and run `docker compose up -d`.

```.env
# ------------------------------
# Server Configuration
# ------------------------------

# The log level for the application.
# Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
LOG_LEVEL=INFO
# Log file path
LOG_FILE=/app/logs/server.log
# Log file max size, the unit is MB
LOG_FILE_MAX_SIZE=20
# Log file max backup count
LOG_FILE_BACKUP_COUNT=5
# Log dateformat
LOG_DATEFORMAT=%Y-%m-%d %H:%M:%S
```
