### ISSUE TITLE
ValueError: Could not connect to a Chroma server. Are you sure it is running?

### ISSUE THREAD

**Issue by xyfZzz** [langgenius/dify#10604]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```
docker-worker-1      | [2024-11-12 14:02:26,856: ERROR/MainProcess] consume document failed
docker-worker-1      | Traceback (most recent call last):
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
docker-worker-1      |     sock = connection.create_connection(
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
docker-worker-1      |     raise err
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
docker-worker-1      |     sock.connect(sa)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/gevent/_socketcommon.py", line 590, in connect
docker-worker-1      |     self._internal_connect(address)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/gevent/_socketcommon.py", line 634, in _internal_connect
docker-worker-1      |     raise _SocketError(err, strerror(err))
docker-worker-1      | ConnectionRefusedError: [Errno 111] Connection refused
docker-worker-1      | 
docker-worker-1      | The above exception was the direct cause of the following exception:
docker-worker-1      | 
docker-worker-1      | Traceback (most recent call last):
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
docker-worker-1      |     response = self._make_request(
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 495, in _make_request
docker-worker-1      |     conn.request(
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 441, in request
docker-worker-1      |     self.endheaders()
docker-worker-1      |   File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
docker-worker-1      |     self._send_output(message_body, encode_chunked=encode_chunked)
docker-worker-1      |   File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
docker-worker-1      |     self.send(msg)
docker-worker-1      |   File "/usr/local/lib/python3.10/http/client.py", line 976, in send
docker-worker-1      |     self.connect()
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 279, in connect
docker-worker-1      |     self.sock = self._new_conn()
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 214, in _new_conn
docker-worker-1      |     raise NewConnectionError(
docker-worker-1      | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7b18dfebc0>: Failed to establish a new connection: [Errno 111] Connection refused
docker-worker-1      | 
docker-worker-1      | The above exception was the direct cause of the following exception:
docker-worker-1      | 
docker-worker-1      | Traceback (most recent call last):
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
docker-worker-1      |     resp = conn.urlopen(
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
docker-worker-1      |     retries = retries.increment(
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
docker-worker-1      |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
docker-worker-1      | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/v1/tenants/default_tenant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b18dfebc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
docker-worker-1      | 
docker-worker-1      | During handling of the above exception, another exception occurred:
docker-worker-1      | 
docker-worker-1      | Traceback (most recent call last):
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/chromadb/api/client.py", line 351, in _validate_tenant_database
docker-worker-1      |     self._admin_client.get_tenant(name=tenant)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/chromadb/api/client.py", line 399, in get_tenant
docker-worker-1      |     return self._server.get_tenant(name=name)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
docker-worker-1      |     return f(*args, **kwargs)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/chromadb/api/fastapi.py", line 132, in get_tenant
docker-worker-1      |     resp = self._session.get(
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
docker-worker-1      |     return self.request("GET", url, **kwargs)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
docker-worker-1      |     resp = self.send(prep, **send_kwargs)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
docker-worker-1      |     r = adapter.send(request, **kwargs)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
docker-worker-1      |     raise ConnectionError(e, request=request)
docker-worker-1      | requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/v1/tenants/default_tenant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b18dfebc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
docker-worker-1      | 
docker-worker-1      | During handling of the above exception, another exception occurred:
docker-worker-1      | 
docker-worker-1      | Traceback (most recent call last):
docker-worker-1      |   File "/app/api/core/indexing_runner.py", line 76, in run
docker-worker-1      |     self._load(
docker-worker-1      |   File "/app/api/core/indexing_runner.py", line 661, in _load
docker-worker-1      |     tokens += future.result()
docker-worker-1      |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
docker-worker-1      |     return self.__get_result()
docker-worker-1      |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
docker-worker-1      |     raise self._exception
docker-worker-1      |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
docker-worker-1      |     result = self.fn(*self.args, **self.kwargs)
docker-worker-1      |   File "/app/api/core/indexing_runner.py", line 718, in _process_chunk
docker-worker-1      |     index_processor.load(dataset, chunk_documents, with_keywords=False)
docker-worker-1      |   File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 59, in load
docker-worker-1      |     vector = Vector(dataset)
docker-worker-1      |   File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 35, in __init__
docker-worker-1      |     self._vector_processor = self._init_vector()
docker-worker-1      |   File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 56, in _init_vector
docker-worker-1      |     return vector_factory_cls().init_vector(self._dataset, self._attributes, self._embeddings)
docker-worker-1      |   File "/app/api/core/rag/datasource/vdb/chroma/chroma_vector.py", line 133, in init_vector
docker-worker-1      |     return ChromaVector(
docker-worker-1      |   File "/app/api/core/rag/datasource/vdb/chroma/chroma_vector.py", line 47, in __init__
docker-worker-1      |     self._client = chromadb.HttpClient(**self._client_config.to_chroma_params())
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/chromadb/__init__.py", line 204, in HttpClient
docker-worker-1      |     return ClientCreator(tenant=tenant, database=database, settings=settings)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/chromadb/api/client.py", line 60, in __init__
docker-worker-1      |     self._validate_tenant_database(tenant=tenant, database=database)
docker-worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/chromadb/api/client.py", line 353, in _validate_tenant_database
docker-worker-1      |     raise ValueError(
docker-worker-1      | ValueError: Could not connect to a Chroma server. Are you sure it is running?
```

**Comment by crazywoola** [comment]
Please use docker ps to check if the vdb service is up and running.
