### ISSUE TITLE
Documents in queue

### ISSUE THREAD

**Issue by xy3xy3** [langgenius/dify#10603]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1 

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Upload a documetnt via openai embedding or silicon flow.
Some error from docker-worker-1:
```
Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
Warning: Python 3.10 will not be supported in the next version.
Traceback (most recent call last):
  File "/app/api/.venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/app/api/.venv/lib/python3.10/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/celery.py", line 236, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/worker.py", line 348, in worker
    worker = app.Worker(
  File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 98, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 131, in setup_instance
    self.on_init_blueprint()
  File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 116, in on_init_blueprint
    self._custom_logging = self.setup_logging()
  File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 180, in setup_logging
    return self.app.log.setup(
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 63, in setup
    handled = self.setup_logging_subsystem(
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 117, in setup_logging_subsystem
    self._configure_logger(
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 150, in _configure_logger
    self.setup_handlers(logger, logfile, format,
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 216, in setup_handlers
    handler = self._detect_handler(logfile)
  File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 226, in _detect_handler
    return WatchedFileHandler(logfile, encoding='utf-8')
  File "/usr/local/lib/python3.10/logging/handlers.py", line 479, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
IsADirectoryError: [Errno 21] Is a directory: '/app/api'
```

### ✔️ Expected Behavior

The docuements can be processed.

### ❌ Actual Behavior

They are always in queue.

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/10597

**Comment by xy3xy3** [comment]
Problem solved:https://github.com/langgenius/dify/discussions/10602
