### ISSUE TITLE
[DOCKER] Repeated errors and restarts in worker-1 container

### ISSUE THREAD

**Issue by nne998** [langgenius/dify#10725]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm using docker compose deploying.

When checking the logs with `docker compose logs -n 100 -f` cmd, I see repeated errors:
```
orker-1      | /app/api/.venv/lib/python3.10/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
worker-1      | absolutely not recommended!
worker-1      | 
worker-1      | Please specify a different user using the --uid option.
worker-1      | 
worker-1      | User information: uid=0 euid=0 gid=0 egid=0
worker-1      | 
worker-1      |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
worker-1      | Warning: Python 3.10 will not be supported in the next version.
worker-1      | Traceback (most recent call last):
worker-1      |   File "/app/api/.venv/bin/celery", line 8, in <module>
worker-1      |     sys.exit(main())
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/__main__.py", line 15, in main
worker-1      |     sys.exit(_main())
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/celery.py", line 236, in main
worker-1      |     return celery(auto_envvar_prefix="CELERY")
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
worker-1      |     return self.main(*args, **kwargs)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
worker-1      |     rv = self.invoke(ctx)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
worker-1      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
worker-1      |     return ctx.invoke(self.callback, **ctx.params)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
worker-1      |     return __callback(*args, **kwargs)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
worker-1      |     return f(get_current_context(), *args, **kwargs)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/base.py", line 135, in caller
worker-1      |     return f(ctx, *args, **kwargs)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/bin/worker.py", line 348, in worker
worker-1      |     worker = app.Worker(
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 98, in __init__
worker-1      |     self.setup_instance(**self.prepare_args(**kwargs))
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/worker/worker.py", line 131, in setup_instance
worker-1      |     self.on_init_blueprint()
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 116, in on_init_blueprint
worker-1      |     self._custom_logging = self.setup_logging()
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/apps/worker.py", line 180, in setup_logging
worker-1      |     return self.app.log.setup(
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 63, in setup
worker-1      |     handled = self.setup_logging_subsystem(
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 117, in setup_logging_subsystem
worker-1      |     self._configure_logger(
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 150, in _configure_logger
worker-1      |     self.setup_handlers(logger, logfile, format,
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 216, in setup_handlers
worker-1      |     handler = self._detect_handler(logfile)
worker-1      |   File "/app/api/.venv/lib/python3.10/site-packages/celery/app/log.py", line 226, in _detect_handler
worker-1      |     return WatchedFileHandler(logfile, encoding='utf-8')
worker-1      |   File "/usr/local/lib/python3.10/logging/handlers.py", line 479, in __init__
worker-1      |     logging.FileHandler.__init__(self, filename, mode=mode,
worker-1      |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1169, in __init__
worker-1      |     StreamHandler.__init__(self, self._open())
worker-1      |   File "/usr/local/lib/python3.10/logging/__init__.py", line 1201, in _open
worker-1      |     return open_func(self.baseFilename, self.mode,
worker-1      | IsADirectoryError: [Errno 21] Is a directory: '/app/api'
```

### ✔️ Expected Behavior

No errors in worker-1 container

### ❌ Actual Behavior

Repeated errors and restarts in worker-1 container.

**Comment by crazywoola** [comment]
Duplicated
