### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'results'

### ISSUE THREAD

**Issue by guxiyang** [langgenius/dify#10852]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hello, I have a question on my end. I don't know what's going on. Can you help me take a look,
- Request:  https://dashscope.aliyuncs.com/api/v1/services/rerank/text-rerank/text-rerank   failed, status: 429, message: Requests rate limit exceeded, please try again later.
2024-11-19 08:42:18,689.689 ERROR [Thread-17368 (_generate_worker)] [node.py:72] - Node 1730856299318 failed to run
Traceback (most recent call last):
File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 42, in invoke
return self._invoke(model, credentials, query, docs, score_threshold, top_n, user)
File "/app/api/core/model_runtime/model_providers/tongyi/rerank/rerank.py", line 68, in _invoke
for _, result in enumerate(response.output.results):
AttributeError: 'NoneType' object has no attribute 'results'
During handling of the above exception, another exception occurred:

### ❌ Actual Behavior

无

**Comment by guxiyang** [comment]
From the information, did the other party limit the flow by calling Alibaba Cloud's interface



***@***.***
 
From: dosubot[bot]
Date: 2024-11-19 16:52
To: langgenius/dify
CC: 顾夕旸; Author
Subject: Re: [langgenius/dify] AttributeError: 'NoneType' object has no attribute 'results' (Issue #10852)
The error you're encountering, "AttributeError: 'NoneType' object has no attribute 'results'," suggests that the response.output is None, which means the results attribute cannot be accessed. This issue is likely related to the rate limiting error you mentioned, where the request to the rerank service failed with a 429 status code, indicating that the request rate limit was exceeded.
To address this issue, consider the following steps:
Rate Limiting: Since the error message indicates a rate limit issue, you should implement a retry mechanism with exponential backoff to handle 429 errors. This involves waiting for a certain period before retrying the request, and increasing the wait time with each subsequent failure.
Error Handling: Ensure that your code gracefully handles cases where the response is None. You can add a check before accessing the results attribute to prevent the application from crashing:
if response.output is None:
    raise ValueError("The response from the rerank service is None. Please check the service status and rate limits.")
Logging and Monitoring: Use logging to capture detailed information about the requests and responses, especially when rate limits are hit. This can help in diagnosing and resolving such issues more effectively.
Service Configuration: Review the configuration of the rerank service to ensure that it is set up to handle the expected load. If necessary, consider increasing the rate limit or optimizing the request patterns to reduce the load.
These steps should help mitigate the issue and improve the robustness of your application when dealing with rate limits and unexpected None responses.
To continue talking to Dosu, mention @dosu.

**Comment by guxiyang** [comment]
Hello, may I ask which Alibaba model is being called, the Lingji model or not?


***@***.***
 
From: dosubot[bot]
Date: 2024-11-19 17:07
To: langgenius/dify
CC: 顾夕旸; Mention
Subject: Re: [langgenius/dify] AttributeError: 'NoneType' object has no attribute 'results' (Issue #10852)
Hey @guxiyang! It looks like you're trying to respond to an email or message thread. I'm here to help with technical questions, bug fixes, and engineering knowledge, but handling email threads isn't quite my thing. If you think I should be able to help with this, feel free to reach out to the Dosu Team. They'll be happy to hear your feedback! 
To continue talking to Dosu, mention @dosu.
