### ISSUE TITLE
After the version upgrade and data migration, the knowledge base hit test reports an error

### ISSUE THREAD

**Issue by ricky977** [langgenius/dify#11165]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After upgrading from 0.6.8 to 0.10.2, and backing up the volumes folder to complete the data migration, but the knowledge base recall test after the upgrade keeps reporting errors
![报错](https://github.com/user-attachments/assets/97619290-8eac-4f91-8597-cfba55bf5896)

### ✔️ Expected Behavior

The knowledge base hit test can be retrieved normally

### ❌ Actual Behavior

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 92, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/datasets/hit_testing.py", line 21, in post
    return self.perform_hit_testing(dataset, args)
  File "/app/api/controllers/console/datasets/hit_testing_base.py", line 85, in perform_hit_testing
    raise InternalServerError(str(e))
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_eb93306a_b524_473b_b24f_e3b548353712_Node" on type "GetObjectsObj".', 'path': None}]

**Comment by crazywoola** [comment]
Sorry we do not fix bugs in previous versions any longer, please upgrade to v0.12.1.
Also, please make sure you have follow the release log to upgrade it. Since 0.10.x has some breaking changes.
