### ISSUE TITLE
API Error when using docker image built from source code

### ISSUE THREAD

**Issue by kevinsantiago-mnltechnology** [langgenius/dify#11191]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.0/0.12.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Create docker image - Docker build from source code API Dockerfile

*Expected behavior are the logs when using docker official image

### ✔️ Expected Behavior

```
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
/app/api/.venv/lib/python3.12/site-packages/tencentcloud/hunyuan/v20230901/models.py:5585: SyntaxWarning: invalid escape sequence '\_'
 """function名称，只能包含a-z，A-Z，0-9，\_或-
/app/api/.venv/lib/python3.12/site-packages/jieba/__init__.py:44: SyntaxWarning: invalid escape sequence '\.'
  re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%\-]+)", re.U)
/app/api/.venv/lib/python3.12/site-packages/jieba/__init__.py:46: SyntaxWarning: invalid escape sequence '\s'
  re_skip_default = re.compile("(\r\n|\s)", re.U)
/app/api/.venv/lib/python3.12/site-packages/jieba/finalseg/__init__.py:78: SyntaxWarning: invalid escape sequence '\.'
 re_skip = re.compile("([a-zA-Z0-9]+(?:\.\d+)?%?)")
/app/api/.venv/lib/python3.12/site-packages/jieba/posseg/__init__.py:16: SyntaxWarning: invalid escape sequence '\.'
  re_skip_detail = re.compile("([\.0-9]+|[a-zA-Z0-9]+)")
/app/api/.venv/lib/python3.12/site-packages/jieba/posseg/__init__.py:17: SyntaxWarning: invalid escape sequence '\.'
  re_han_internal = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._]+)")
/app/api/.venv/lib/python3.12/site-packages/jieba/posseg/__init__.py:18: SyntaxWarning: invalid escape sequence '\s'
   re_skip_internal = re.compile("(\r\n|\s)")
/app/api/.venv/lib/python3.12/site-packages/jieba/posseg/__init__.py:21: SyntaxWarning: invalid escape sequence '\.'
  re_num = re.compile("[\.0-9]+")
INFO [pre_load_builtin_providers_cache] [font_manager.py:1578] - generated new fontManager
Preparing database migration...
Database migration skipped
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[INFO] Starting gunicorn 22.0.0
[INFO] Listening at: http://0.0.0.0:5001 (1)
[INFO] Using worker: gevent
[INFO] Booting worker with pid: 65
```
### ❌ Actual Behavior

Running migrations
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
/app/api/.venv/lib/python3.12/site-packages/tencentcloud/hunyuan/v20230901/models.py:5585: SyntaxWarning: invalid escape sequence '\_'
"""function名称，只能包含a-z，A-Z，0-9，\_或-
/app/api/.venv/lib/python3.12/site-packages/jieba/__init__.py:44: SyntaxWarning: invalid escape sequence '\.'
re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%\-]+)", re.U)
/app/api/.venv/lib/python3.12/site-packages/jieba/__init__.py:46: SyntaxWarning: invalid escape sequence '\s'
re_skip_default = re.compile("(\r\n\|\s)", re.U)
/app/api/.venv/lib/python3.12/site-packages/jieba/finalseg/__init__.py:78: SyntaxWarning: invalid escape sequence '\.'
re_skip = re.compile("([a-zA-Z0-9]+(?:\.\d+)?%?)")
/app/api/.venv/lib/python3.12/site-packages/jieba/posseg/__init__.py:16: SyntaxWarning: invalid escape sequence '\.'
re_skip_detail = re.compile("([\.0-9]+\|[a-zA-Z0-9]+)")
/app/api/.venv/lib/python3.12/site-packages/jieba/posseg/__init__.py:17: SyntaxWarning: invalid escape sequence '\.'
re_han_internal = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._]+)")
/app/api/.venv/lib/python3.12/site-packages/jieba/posseg/__init__.py:18: SyntaxWarning: invalid escape sequence '\s'
re_skip_internal = re.compile("(\r\n\|\s)")
/app/api/.venv/lib/python3.12/site-packages/jieba/posseg/__init__.py:21: SyntaxWarning: invalid escape sequence '\.'
re_num = re.compile("[\.0-9]+")
2024-11-27 03:06:33,736.736 WARNING [MainThread] [ext_mail.py:21] - MAIL_TYPE is not set
2024-11-27 03:06:34,640.640 INFO [pre_load_builtin_providers_cache] [font_manager.py:1578] - generated new fontManager
Error: While importing 'app', an ImportError was raised:
Traceback (most recent call last):
File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
__import__(module_name)
File "/app/api/app.py", line 48, in <module>
app = create_app()
^^^^^^^^^^^^
File "/app/api/app_factory.py", line 75, in create_app
register_blueprints(app)
File "/app/api/app_factory.py", line 140, in register_blueprints
from controllers.console import bp as console_app_bp
File "/app/api/controllers/console/__init__.py", line 5, in <module>
from .app.app_import import AppImportApi, AppImportConfirmApi
File "/app/api/controllers/console/app/app_import.py", line 16, in <module>
from services.app_dsl_service import AppDslService, ImportStatus
ImportError: cannot import name 'ImportStatus' from 'services.app_dsl_service' (/app/api/services/app_dsl_service/__init__.py)
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.
Error: No such command 'upgrade-db'.
```

**Comment by kevinsantiago-mnltechnology** [comment]
Yes, it is defined and i cloned the latest source code

![class](https://github.com/user-attachments/assets/8a0a6cfa-224a-46f9-a0d0-21fda8a907fa)

**Comment by crazywoola** [comment]
Well, I suggest you can use CI to build docker images in case there are problems related to your computer or environment things. And we do not provide guide for building from the source code.  Because you can see the build status in https://github.com/langgenius/dify/actions. So this can not be reproduced in this case.

This should be included in our business license. If you do have problems please contact business@dify.ai.
