### ISSUE TITLE
package.json "start": "next dev"

### ISSUE THREAD

**Issue by xsxs89757** [langgenius/dify#1121]
next build 以后执行next start也报错了
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /data/dify/web/.env.local
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
warn  - "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
Error: Could not find a production build in the '/data/dify/web/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/data/dify/web/node_modules/next/dist/server/next-server.js:352:23)
    at new Server (/data/dify/web/node_modules/next/dist/server/base-server.js:146:29)
    at new NextNodeServer (/data/dify/web/node_modules/next/dist/server/next-server.js:166:9)
    at NextServer.createServer (/data/dify/web/node_modules/next/dist/server/next.js:167:24)
    at async /data/dify/web/node_modules/next/dist/server/next.js:187:31
    at async NextServer.prepare (/data/dify/web/node_modules/next/dist/server/next.js:149:24)
    at async Server.<anonymous> (/data/dify/web/node_modules/next/dist/server/lib/render-server.js:109:17) {
  type: 'Error'
}
error Command failed with exit code 1.

**Comment by xsxs89757** [comment]
手动创建 standalone目录后 重新build 解决
