### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by majestichou** [langgenius/dify#11278]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.12.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Use the dify of 0.12.1 and use Docker for local deployment.
2. ETL_TYPE=Unstructured
3. Create a Knowledge Base
4. Upload a docx document. The link to the document is: https://www.3gpp.org/ftp/specs/archive/38_series/38.899/38899-i00.zip
5. Failed to split the document.
6. Logs of the docker-api-1 container are as follows:
```
2024-12-03 09:48:35.998 INFO [Dummy-1] [_client.py:1038] - HTTP Request: GET http://schemas.openxmlformats.org/officeDocument/2006/relationships/image "HTTP/1.1 404 Not Found"
2024-12-03 09:48:36.008 ERROR [Dummy-1] [app.py:838] - Exception on /console/api/datasets/indexing-estimate [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/datasets.py", line 449, in post
    response = indexing_runner.indexing_estimate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/indexing_runner.py", line 264, in indexing_estimate
    text_docs = index_processor.extract(extract_setting, process_rule_mode=tmp_processing_rule["mode"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 21, in extract
    text_docs = ExtractProcessor.extract(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/rag/extractor/extract_processor.py", line 157, in extract
    return extractor.extract()
           ^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/rag/extractor/word_extractor.py", line 65, in extract
    content = self.parse_docx(self.file_path, "storage")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/rag/extractor/word_extractor.py", line 211, in parse_docx
    image_map = self._extract_images_from_docx(doc, image_folder)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/rag/extractor/word_extractor.py", line 90, in _extract_images_from_docx
    if response.status_code == 200:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'generator' object has no attribute 'status_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/controllers/console/wraps.py", line 142, in decorated
    return view(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/libs/login.py", line 92, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/controllers/console/wraps.py", line 26, in decorated
    return view(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/controllers/console/datasets/datasets.py", line 465, in post
    raise IndexingEstimateError(str(e))
controllers.console.datasets.error.IndexingEstimateError: 500 Internal Server Error: 'generator' object has no attribute 'status_code'
```

Then I changed the document to upload, the document link is: https://www.3gpp.org/ftp/specs/archive/38_series/38.901/38901-i00.zip

The document is split and embedded successfully. Everything is OK!

**_Why https://www.3gpp.org/ftp/specs/archive/38_series/38.899/38899-i00.zip can not be processed correctly?_**

### ✔️ Expected Behavior

No bug report

### ❌ Actual Behavior

AttributeError: 'generator' object has no attribute 'status_code'

**Comment by laipz8200** [comment]
It should be fixed in v0.13.0, please give it a try!
