### ISSUE TITLE
0.3.20 docker compose部署后，无法对话，确定openai 反代地址有效，key有效，好像是在向量化上出现问题了

### ISSUE THREAD

**Issue by leochen-g** [langgenius/dify#1137]
Dify version: Self Host

## Steps To Reproduce

1. 使用接口调用，或者在界面上调试均不通，全部超时

## The current behavior

```
ERROR:root:Unknown Error in completion
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fc8dadd8220>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc8dadd8220>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/services/completion_service.py", line 181, in generate_worker
    Completion.generate(
  File "/app/api/core/completion.py", line 52, in generate
    conversation_message_task = ConversationMessageTask(
  File "/app/api/core/conversation_message_task.py", line 49, in __init__
    self.init()
  File "/app/api/core/conversation_message_task.py", line 86, in init
    system_instruction_tokens = model_instance.get_num_tokens(to_prompt_messages([system_message]))
  File "/app/api/core/model_providers/models/llm/openai_model.py", line 119, in get_num_tokens
    return max(self._client.get_num_tokens_from_messages(prompts) - len(prompts), 0)
  File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 552, in get_num_tokens_from_messages
    model, encoding = self._get_encoding_model()
  File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 530, in _get_encoding_model
    encoding = tiktoken_.encoding_for_model(model)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 67, in encoding_for_model
    return get_encoding(model_encoding_name)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/usr/local/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 114, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 46, in read_file_cached
    contents = read_file(blobpath)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 24, in read_file
    return requests.get(blobpath).content
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc8dadd8220>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
ERROR:root:internal server error.
Traceback (most recent call last):
  File "/app/api/controllers/console/app/completion.py", line 164, in generate
    for chunk in response:
  File "/app/api/services/completion_service.py", line 391, in generate
    cls.handle_error(result)
  File "/app/api/services/completion_service.py", line 495, in handle_error
    raise Exception(description)
Exception: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc8dadd8220>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
ERROR:app:Exception on /console/api/apps/b859395d-4236-45ab-8b7f-2d3de4802d8c/chat-messages [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/app/completion.py", line 164, in generate
    for chunk in response:
  File "/app/api/services/completion_service.py", line 391, in generate
    cls.handle_error(result)
  File "/app/api/services/completion_service.py", line 495, in handle_error
    raise Exception(description)
Exception: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc8dadd8220>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
```

另外一个报错

```
ERROR:root:Unknown Error in completion
Traceback (most recent call last):
  File "/app/api/services/completion_service.py", line 181, in generate_worker
    Completion.generate(
  File "/app/api/core/completion.py", line 52, in generate
    conversation_message_task = ConversationMessageTask(
  File "/app/api/core/conversation_message_task.py", line 49, in __init__
    self.init()
  File "/app/api/core/conversation_message_task.py", line 86, in init
    system_instruction_tokens = model_instance.get_num_tokens(to_prompt_messages([system_message]))
  File "/app/api/core/model_providers/models/llm/openai_model.py", line 119, in get_num_tokens
    return max(self._client.get_num_tokens_from_messages(prompts) - len(prompts), 0)
  File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 552, in get_num_tokens_from_messages
    model, encoding = self._get_encoding_model()
  File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 530, in _get_encoding_model
    encoding = tiktoken_.encoding_for_model(model)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 67, in encoding_for_model
    return get_encoding(model_encoding_name)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/usr/local/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 115, in load_tiktoken_bpe
    return {
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 117, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
ValueError: not enough values to unpack (expected 2, got 1)
ERROR:root:internal server error.
Traceback (most recent call last):
  File "/app/api/controllers/service_api/app/completion.py", line 102, in post
    response = CompletionService.completion(
  File "/app/api/services/completion_service.py", line 156, in completion
    return cls.compact_response(pubsub, streaming)
  File "/app/api/services/completion_service.py", line 369, in compact_response
    cls.handle_error(result)
  File "/app/api/services/completion_service.py", line 495, in handle_error
    raise Exception(description)
Exception: not enough values to unpack (expected 2, got 1)
ERROR:app:Exception on /v1/chat-messages [POST]
Traceback (most recent call last):
  File "/app/api/controllers/service_api/app/completion.py", line 102, in post
    response = CompletionService.completion(
  File "/app/api/services/completion_service.py", line 156, in completion
    return cls.compact_response(pubsub, streaming)
  File "/app/api/services/completion_service.py", line 369, in compact_response
    cls.handle_error(result)
  File "/app/api/services/completion_service.py", line 495, in handle_error
    raise Exception(description)
Exception: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/service_api/wraps.py", line 30, in decorated
    return view(app_model, None, *args, **kwargs)
  File "/app/api/controllers/service_api/app/completion.py", line 131, in post
    raise InternalServerError()
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by leochen-g** [comment]
> The first error seems a general network issue to me. The second one: `ValueError: not enough values to unpack (expected 2, got 1)` Can you provide your curl command. Seems the request is not invalid.

应该也是网络问题导致的，我又重新部署了一遍可以了

**Comment by MichaelPorter0** [comment]
@leochen-g 重新部署一遍就没有网络问题了？
