### ISSUE TITLE
chattts/CosyVoice deployed by xinference bug for dify : TTS is not enabled

### ISSUE THREAD

**Issue by liuhui881125** [langgenius/dify#11631]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Cosyvoice/chattts for tts with xinference in ragflow  ran normally 。。

I was deploying Cosyvoice/chattts for tts with xinference in dify. However, I encountered unexpected errors as followed:

```
2024-12-13 13:46:07,036 xinference.model.audio.chattts 46420 INFO     Speech by voice alloy
2024-12-13 13:46:07,039 xinference.core.model 46420 ERROR    stream encountered an error.
Traceback (most recent call last):
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 533, in _handle_pending_requests
    r = await asyncio.to_thread(_wrapper, gen)
  File "/root/anaconda3/envs/xinference/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/anaconda3/envs/xinference/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 526, in _wrapper
    return next(_gen)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 437, in _to_generator
    for v in gen:
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/audio/chattts.py", line 115, in _generator
    writer = torchaudio.io.StreamWriter(out, format=response_format)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/torio/io/_streaming_media_encoder.py", line 197, in __init__
    self._s = ffmpeg_ext.StreamingMediaEncoderFileObj(dst, format, buffer_size)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/torio/_extension/utils.py", line 25, in __getattr__
    self._import_once()
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/torio/_extension/utils.py", line 39, in _import_once
    self.module = self.import_func()
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/torio/_extension/utils.py", line 143, in _init_ffmpeg
    ext = _find_ffmpeg_extension(ffmpeg_vers)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/torio/_extension/utils.py", line 122, in _find_ffmpeg_extension
    raise ImportError(
ImportError: Failed to intialize FFmpeg extension. Tried versions: ['6', '5', '4', '']. Enable DEBUG logging to see more details about the error.
```

### ✔️ Expected Behavior

fix the bug

**Comment by liuhui881125** [comment]
<img width="547" alt="image" src="https://github.com/user-attachments/assets/b88925c4-d508-4ffc-941d-778fa84616fd" />

env：centos 7.9

**Comment by liuhui881125** [comment]
i am sure cosyVoice and chatTTS deployed by xinference is ok ,they are worked normally in another platform named ragflow（[ragflow](https://demo.ragflow.io/)）

**Comment by liuhui881125** [comment]
![image](https://github.com/user-attachments/assets/2a39fcde-7bbc-4e32-a163-cacc61016287)

**Comment by yihong0618** [comment]
succeed in my env
you need to install ffmpeg in your xinference machine.

**Comment by skytodmoon** [comment]
mark, met the same issue with dify 0.15.3

**Comment by skytodmoon** [comment]
> mark, met the same issue with dify 0.15.3

conda install ffmpeg解决
