### ISSUE TITLE
smtp: No suitable authentication method found.

### ISSUE THREAD

**Issue by doufangyu** [langgenius/dify#11734]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

# ------------------------------
# Mail related configuration
# ------------------------------

# Mail type, support: resend, smtp
MAIL_TYPE=smtp

# Default send from email address, if not specified
MAIL_DEFAULT_SEND_FROM=xxxx@xxxx.cn

# API-Key for the Resend email provider, used when MAIL_TYPE is `resend`.
RESEND_API_KEY=your-resend-api-key

# SMTP server configuration, used when MAIL_TYPE is `smtp`
SMTP_SERVER=smtp.xxxxx.cn
SMTP_PORT=587
SMTP_USERNAME=xxxxx@xxxx.cn
SMTP_PASSWORD=xxxxxxx%xxx%xxx
SMTP_USE_TLS=false
SMTP_OPPORTUNISTIC_TLS=false

### ✔️ Expected Behavior

Normal calling of smtp for password reset

### ❌ Actual Behavior

`
docker-worker-1      | 2024-12-17 05:49:17,340.340 INFO [MainThread] [strategy.py:161] - Task tasks.mail_reset_password_task.send_reset_password_mail_task[a77264e8-10c1-4b54-b72c-eb3ebca957d6] received
docker-worker-1      | 2024-12-17 05:49:17,341.341 INFO [Dummy-2] [mail_reset_password_task.py:22] - Start password reset mail to xxxx@xxxx.cn
docker-worker-1      | 2024-12-17 05:49:17,355.355 ERROR [Dummy-2] [smtp.py:42] - SMTP error occurred
docker-worker-1      | Traceback (most recent call last):
docker-worker-1      |   File "/app/api/libs/smtp.py", line 32, in send
docker-worker-1      |     smtp.login(self.username, self.password)
docker-worker-1      |   File "/usr/local/lib/python3.12/smtplib.py", line 730, in login
docker-worker-1      |     raise SMTPException("No suitable authentication method found.")
docker-worker-1      | smtplib.SMTPException: No suitable authentication method found.
docker-worker-1      | 2024-12-17 05:49:17,358.358 ERROR [Dummy-2] [mail_reset_password_task.py:41] - Send password reset mail to xxxx@xxxx.cn failed
docker-worker-1      | Traceback (most recent call last):
docker-worker-1      |   File "/app/api/tasks/mail_reset_password_task.py", line 29, in send_reset_password_mail_task
docker-worker-1      |     mail.send(to=to, subject="设置您的 Dify 密码", html=html_content)
docker-worker-1      |   File "/app/api/extensions/ext_mail.py", line 79, in send
docker-worker-1      |     self._client.send(
docker-worker-1      |   File "/app/api/libs/smtp.py", line 32, in send
docker-worker-1      |     smtp.login(self.username, self.password)
docker-worker-1      |   File "/usr/local/lib/python3.12/smtplib.py", line 730, in login
docker-worker-1      |     raise SMTPException("No suitable authentication method found.")
docker-worker-1      | smtplib.SMTPException: No suitable authentication method found.
`

**Comment by doufangyu** [comment]
SMTP_USE_TLS=true
SMTP_OPPORTUNISTIC_TLS=true
