### ISSUE TITLE
本地源码启动，创建数据源时，上传excel文件（文件后缀.xlsx）报错

### ISSUE THREAD

**Issue by zmlstc** [langgenius/dify#1180]
### Dify version

0.3.22

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

本地源码启动，创建数据源时，上传excel文件（文件后缀.xlsx）报错

### ✔️ Expected Behavior

正常上传excel文件

### ❌ Actual Behavior

会报服务错误。但是其他类型文件没有问题。
根据报错看，提示有进程使用excel文件，但是检查过后，其实并没有。

ERROR:app:Exception on /console/api/datasets/indexing-estimate [POST]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\dify\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpiidsftp8\\o1od7a83.xlsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\dify\lib\tempfile.py", line 843, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpiidsftp8\\o1od7a83.xlsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\dify\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Anaconda3\envs\dify\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Anaconda3\envs\dify\lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "D:\Anaconda3\envs\dify\lib\site-packages\flask\views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "D:\Anaconda3\envs\dify\lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "E:\dify\api\controllers\console\setup.py", line 83, in decorated
    return view(*args, **kwargs)
  File "E:\dify\api\core\login\login.py", line 95, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\dify\api\controllers\console\wraps.py", line 19, in decorated
    return view(*args, **kwargs)
  File "E:\dify\api\controllers\console\datasets\datasets.py", line 291, in post
    response = indexing_runner.file_indexing_estimate(current_user.current_tenant_id, file_details,
  File "E:\dify\api\core\indexing_runner.py", line 248, in file_indexing_estimate
    text_docs = FileExtractor.load(file_detail)
  File "E:\dify\api\core\data_loader\file_extractor.py", line 24, in load
    with tempfile.TemporaryDirectory() as temp_dir:
  File "D:\Anaconda3\envs\dify\lib\tempfile.py", line 869, in __exit__
    self.cleanup()
  File "D:\Anaconda3\envs\dify\lib\tempfile.py", line 873, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "D:\Anaconda3\envs\dify\lib\tempfile.py", line 855, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "D:\Anaconda3\envs\dify\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\Anaconda3\envs\dify\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "D:\Anaconda3\envs\dify\lib\tempfile.py", line 846, in onerror
    cls._rmtree(path, ignore_errors=ignore_errors)
  File "D:\Anaconda3\envs\dify\lib\tempfile.py", line 855, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "D:\Anaconda3\envs\dify\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\Anaconda3\envs\dify\lib\shutil.py", line 601, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "D:\Anaconda3\envs\dify\lib\shutil.py", line 598, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpiidsftp8\\o1od7a83.xlsx'

**Comment by wzh123-1** [comment]
如何解决的？

**Comment by kiendn1** [comment]
@zmlstc Have you found any solutions? I got same bug
