### ISSUE TITLE
full log and data [Out of range float values are not JSON compliant: nan]

### ISSUE THREAD

**Issue by maogeigei** [langgenius/dify#11975]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

upload the  excel to Knowledge Base , worker contenter report bug log ( Filter out the data that causes bugs )
[错误34122123.xlsx](https://github.com/user-attachments/files/18224010/34122123.xlsx)

2024-12-22 16:36:36.644 ERROR [Dummy-21] [indexing_runner.py:94] - consume document failed
2024-12-23 00:36:36 Traceback (most recent call last):
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/requests/models.py", line 511, in prepare_body
2024-12-23 00:36:36     body = complexjson.dumps(json, allow_nan=False)
2024-12-23 00:36:36            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
2024-12-23 00:36:36     **kw).encode(obj)
2024-12-23 00:36:36           ^^^^^^^^^^^
2024-12-23 00:36:36   File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
2024-12-23 00:36:36     chunks = self.iterencode(o, _one_shot=True)
2024-12-23 00:36:36              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
2024-12-23 00:36:36     return _iterencode(o, 0)
2024-12-23 00:36:36            ^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36 ValueError: Out of range float values are not JSON compliant: nan
2024-12-23 00:36:36 
2024-12-23 00:36:36 During handling of the above exception, another exception occurred:
2024-12-23 00:36:36 
2024-12-23 00:36:36 Traceback (most recent call last):
2024-12-23 00:36:36   File "/app/api/core/indexing_runner.py", line 78, in run
2024-12-23 00:36:36     self._load(
2024-12-23 00:36:36   File "/app/api/core/indexing_runner.py", line 672, in _load
2024-12-23 00:36:36     tokens += future.result()
2024-12-23 00:36:36               ^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
2024-12-23 00:36:36     return self.__get_result()
2024-12-23 00:36:36            ^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
2024-12-23 00:36:36     raise self._exception
2024-12-23 00:36:36   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
2024-12-23 00:36:36     result = self.fn(*self.args, **self.kwargs)
2024-12-23 00:36:36              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/app/api/core/indexing_runner.py", line 729, in _process_chunk
2024-12-23 00:36:36     index_processor.load(dataset, chunk_documents, with_keywords=False)
2024-12-23 00:36:36   File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 57, in load
2024-12-23 00:36:36     vector.create(documents)
2024-12-23 00:36:36   File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 151, in create
2024-12-23 00:36:36     self._vector_processor.create(texts=texts, embeddings=embeddings, **kwargs)
2024-12-23 00:36:36   File "/app/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 85, in create
2024-12-23 00:36:36     self.add_texts(texts, embeddings)
2024-12-23 00:36:36   File "/app/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 106, in add_texts
2024-12-23 00:36:36     with self._client.batch as batch:
2024-12-23 00:36:36          ^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/weaviate/batch/crud_batch.py", line 1534, in __exit__
2024-12-23 00:36:36     self.flush()
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/weaviate/batch/crud_batch.py", line 1152, in flush
2024-12-23 00:36:36     self._send_batch_requests(force_wait=True)
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/weaviate/batch/crud_batch.py", line 1063, in _send_batch_requests
2024-12-23 00:36:36     response_objects, nr_objects = done_future.result()
2024-12-23 00:36:36                                    ^^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
2024-12-23 00:36:36     return self.__get_result()
2024-12-23 00:36:36            ^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
2024-12-23 00:36:36     raise self._exception
2024-12-23 00:36:36   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 59, in run
2024-12-23 00:36:36     result = self.fn(*self.args, **self.kwargs)
2024-12-23 00:36:36              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/weaviate/batch/crud_batch.py", line 1012, in _flush_in_thread
2024-12-23 00:36:36     response = self._create_data(
2024-12-23 00:36:36                ^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/weaviate/batch/crud_batch.py", line 614, in _create_data
2024-12-23 00:36:36     response = self._connection.post(
2024-12-23 00:36:36                ^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/weaviate/connect/connection.py", line 432, in post
2024-12-23 00:36:36     return self._session.post(
2024-12-23 00:36:36            ^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
2024-12-23 00:36:36     return self.request("POST", url, data=data, json=json, **kwargs)
2024-12-23 00:36:36            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
2024-12-23 00:36:36     prep = self.prepare_request(req)
2024-12-23 00:36:36            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/requests/sessions.py", line 486, in prepare_request
2024-12-23 00:36:36     p.prepare(
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/requests/models.py", line 371, in prepare
2024-12-23 00:36:36     self.prepare_body(data, files, json)
2024-12-23 00:36:36   File "/app/api/.venv/lib/python3.12/site-packages/requests/models.py", line 513, in prepare_body
2024-12-23 00:36:36     raise InvalidJSONError(ve, request=self)
2024-12-23 00:36:36 requests.exceptions.InvalidJSONError: Out of range float values are not JSON compliant: nan

**Comment by yihong0618** [comment]
same as 
https://github.com/langgenius/dify/issues/11792

**Comment by maogeigei** [comment]
![image](https://github.com/user-attachments/assets/d972f952-7800-43a9-a2fe-93202455ed94)
