### ISSUE TITLE
tow docker image status always Restarting

### ISSUE THREAD

**Issue by bugrootof** [langgenius/dify#11982]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.8.3-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.api-1 and worker-1 status always is Restarting.
![image](https://github.com/user-attachments/assets/47d294a6-6b82-481e-9bc8-643fd08aa4f3)
2. cat api-1 logs:
2024-12-23 11:03:59 pydantic_core._pydantic_core.ValidationError: 1 validation error for DifyConfig
2024-12-23 11:03:59 CODE_EXECUTION_ENDPOINT
2024-12-23 11:03:59   Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='"http://sandbox:8194"', input_type=str]
2024-12-23 11:03:59     For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
2024-12-23 11:05:00 Traceback (most recent call last):
2024-12-23 11:05:00   File "/app/api/.venv/bin/flask", line 8, in <module>
2024-12-23 11:05:00     sys.exit(main())
2024-12-23 11:05:00              ^^^^^^
2024-12-23 11:05:00   File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 1129, in main
2024-12-23 11:05:00     cli.main()
2024-12-23 11:05:00   File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
2024-12-23 11:05:00     rv = self.invoke(ctx)
2024-12-23 11:05:00          ^^^^^^^^^^^^^^^^
2024-12-23 11:05:00   File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1682, in invoke
2024-12-23 11:05:00     cmd_name, cmd, args = self.resolve_command(ctx, args)
2024-12-23 11:05:00                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 11:05:00   File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1729, in resolve_command
2024-12-23 11:05:00     cmd = self.get_command(ctx, cmd_name)
2024-12-23 11:05:00           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 11:05:00   File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 631, in get_command
2024-12-23 11:05:00     app = info.load_app()
2024-12-23 11:05:00           ^^^^^^^^^^^^^^^
2024-12-23 11:05:00   File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 349, in load_app
2024-12-23 11:05:00     app = locate_app(import_name, name)
2024-12-23 11:05:00           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 11:05:00   File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
2024-12-23 11:05:00     __import__(module_name)
2024-12-23 11:05:00   File "/app/api/app.py", line 21, in <module>
2024-12-23 11:05:00     from app_factory import create_app
2024-12-23 11:05:00   File "/app/api/app_factory.py", line 4, in <module>
2024-12-23 11:05:00     from configs import dify_config
2024-12-23 11:05:00   File "/app/api/configs/__init__.py", line 3, in <module>
2024-12-23 11:05:00     dify_config = DifyConfig()
2024-12-23 11:05:00                   ^^^^^^^^^^^^
2024-12-23 11:05:00   File "/app/api/.venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 167, in __init__
2024-12-23 11:05:00     super().__init__(
2024-12-23 11:05:00   File "/app/api/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
2024-12-23 11:05:00     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
2024-12-23 11:05:00                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 11:05:00 pydantic_core._pydantic_core.ValidationError: 1 validation error for DifyConfig
2024-12-23 11:05:00 CODE_EXECUTION_ENDPOINT
2024-12-23 11:05:00   Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='"http://sandbox:8194"', input_type=str]
2024-12-23 11:05:00     For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
2024-12-23 10:56:51 Running migrations
2024-12-23 10:57:52 Running migrations
4. cat worker-1 logs:
2024-12-23 11:04:59 pydantic_core._pydantic_core.ValidationError: 1 validation error for DifyConfig
2024-12-23 11:04:59 CODE_EXECUTION_ENDPOINT
2024-12-23 11:04:59   Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='"http://sandbox:8194"', input_type=str]
2024-12-23 11:04:59     For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
2024-12-23 11:06:00 Traceback (most recent call last):
2024-12-23 11:06:00   File "/app/api/.venv/bin/flask", line 8, in <module>
2024-12-23 11:06:00     sys.exit(main())
2024-12-23 11:06:00              ^^^^^^
2024-12-23 11:06:00   File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 1129, in main
2024-12-23 11:06:00     cli.main()
2024-12-23 11:06:00   File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
2024-12-23 11:06:00     rv = self.invoke(ctx)
2024-12-23 11:06:00          ^^^^^^^^^^^^^^^^
2024-12-23 11:06:00   File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1682, in invoke
2024-12-23 11:06:00     cmd_name, cmd, args = self.resolve_command(ctx, args)
2024-12-23 11:06:00                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 11:06:00   File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1729, in resolve_command
2024-12-23 11:06:00     cmd = self.get_command(ctx, cmd_name)
2024-12-23 11:06:00           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 11:06:00   File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 631, in get_command
2024-12-23 11:06:00     app = info.load_app()
2024-12-23 11:06:00           ^^^^^^^^^^^^^^^
2024-12-23 11:06:00   File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 349, in load_app
2024-12-23 11:06:00     app = locate_app(import_name, name)
2024-12-23 11:06:00           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 11:06:00   File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
2024-12-23 11:06:00     __import__(module_name)
2024-12-23 11:06:00   File "/app/api/app.py", line 21, in <module>
2024-12-23 11:06:00     from app_factory import create_app
2024-12-23 11:06:00   File "/app/api/app_factory.py", line 4, in <module>
2024-12-23 11:06:00     from configs import dify_config
2024-12-23 11:06:00   File "/app/api/configs/__init__.py", line 3, in <module>
2024-12-23 11:06:00     dify_config = DifyConfig()
2024-12-23 11:06:00                   ^^^^^^^^^^^^
2024-12-23 11:06:00   File "/app/api/.venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 167, in __init__
2024-12-23 11:06:00     super().__init__(
2024-12-23 11:06:00   File "/app/api/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
2024-12-23 11:06:00     validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
2024-12-23 11:06:00                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-23 11:06:00 pydantic_core._pydantic_core.ValidationError: 1 validation error for DifyConfig
2024-12-23 11:06:00 CODE_EXECUTION_ENDPOINT
2024-12-23 11:06:00   Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='"http://sandbox:8194"', input_type=str]
2024-12-23 11:06:00     For further information visit https://errors.pydantic.dev/2.9/v/url_parsing

**Comment by crazywoola** [comment]
Please upgrade to latest version.

**Comment by verigle** [comment]
latest docker image of `langgenius/dify-api:main` also has this problem


CODE_EXECUTION_ENDPOINT has  change to `http://sandbox:8194/` in `.env` file


```
Traceback (most recent call last):
  File "/app/api/.venv/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 1129, in main
    cli.main()
  File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 631, in get_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 349, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/app/api/app.py", line 21, in <module>
    from app_factory import create_app
  File "/app/api/app_factory.py", line 4, in <module>
    from configs import dify_config
  File "/app/api/configs/__init__.py", line 3, in <module>
    dify_config = DifyConfig()
                  ^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 167, in __init__
    super().__init__(
  File "/app/api/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for DifyConfig
CODE_EXECUTION_ENDPOINT
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='"http://sandbox:8194/"', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
Running migrations
Traceback (most recent call last):
  File "/app/api/.venv/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 1129, in main
    cli.main()
  File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 631, in get_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 349, in load_app
    app = locate_app(import_name, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/app/api/app.py", line 21, in <module>
    from app_factory import create_app
  File "/app/api/app_factory.py", line 4, in <module>
    from configs import dify_config
  File "/app/api/configs/__init__.py", line 3, in <module>
    dify_config = DifyConfig()
                  ^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 167, in __init__
    super().__init__(
  File "/app/api/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for DifyConfig
CODE_EXECUTION_ENDPOINT
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='"http://sandbox:8194/"', input_type=str]
```

**Comment by crazywoola** [comment]
https://github.com/langgenius/dify/issues/11788
