### ISSUE TITLE
Server Disconnection Issue During Workflow Execution

### ISSUE THREAD

**Issue by xiandan-erizo** [langgenius/dify#12098]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. The link is an agent calling a tool.
2. The tool then calls my backend service.
3. My backend service attempts to invoke the Dify workflow.
4. At this point, the error "Server disconnected without sending a response" occurs.
5. After the third retry, the error "Reached maximum retries 3" is displayed.

![image](https://github.com/user-attachments/assets/b2afcddf-ade6-4bf3-8ba9-47c3a341265c)

```
024-12-25 12:41:08,319.319 WARNING [ThreadPoolExecutor-87_1] [ssrf_proxy.py:76] - Request to URL https://mywebsite/llmapi/hotel/search failed on attempt 1: Server disconnected without sending a response.  trace_id:466a02059916401aa8facebcd33bebe5
2024-12-25 12:41:08,362.362 DEBUG [ThreadPoolExecutor-86_1] [_trace.py:47] - receive_response_headers.failed exception=RemoteProtocolError('Server disconnected without sending a response.')
2024-12-25 12:41:08,362.362 DEBUG [ThreadPoolExecutor-86_1] [_trace.py:47] - response_closed.started
2024-12-25 12:41:08,362.362 DEBUG [ThreadPoolExecutor-86_1] [_trace.py:47] - response_closed.complete
2024-12-25 12:41:08,362.362 ERROR [ThreadPoolExecutor-86_1] [ssrf_proxy.py:75] - Server disconnected without sending a response.
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/app/api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
    raise exc from None
  File "/app/api/.venv/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpcore/_sync/http_proxy.py", line 343, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 136, in handle_request
    raise exc
  File "/app/api/.venv/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 106, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 177, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpcore/_sync/http11.py", line 231, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/core/helper/ssrf_proxy.py", line 61, in make_request
    response = client.request(method=method, url=url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpx/_client.py", line 837, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/app/api/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.
```

**Comment by xiandan-erizo** [comment]
![image](https://github.com/user-attachments/assets/703f27a4-9437-4be5-9ae1-dd6232c4be4c)
my squid is running

![image](https://github.com/user-attachments/assets/3094800b-eec6-4587-bf73-fda9a113cd4c)

SSRF_PROXY config is here

**Comment by xiandan-erizo** [comment]
I've noticed that the same issue occurs when using an HTTP node to call another workflow within the workflow. Even though the called workflow has returned a result, the calling side still times out.
![image](https://github.com/user-attachments/assets/4fdb19b3-b70f-49e6-b849-b860c4812225)
![image](https://github.com/user-attachments/assets/a55a3555-827b-4b29-9679-2bf679f4fcab)

**Comment by crazywoola** [comment]
I think you are trying to call `workflow/run` in streaming mode instead of blocking right?
The default timeout for a  HTTP node is set to 15s, and duration of a workflow should last more than that number.

**Comment by xiandan-erizo** [comment]
> I think you are trying to call `workflow/run` in streaming mode instead of blocking right? The default timeout for a HTTP node is set to 15s, and duration of a workflow should last more than that number.

After I removed the SSRF configuration, it worked.
```
  #SSRF_PROXY_HTTP_URL: ${SSRF_PROXY_HTTP_URL:-http://ssrf_proxy:3128}
  #SSRF_PROXY_HTTPS_URL: ${SSRF_PROXY_HTTPS_URL:-http://ssrf_proxy:3128}
```
