### ISSUE TITLE
 Issue of not being able to press “like” or "unlike".

### ISSUE THREAD

**Issue by camucamulemon7** [langgenius/dify#12101]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Internal Server Error” occurs when I click ‘Like’ on the chatbot.
![image](https://github.com/user-attachments/assets/c77b27de-ac07-483f-8750-ae27b000f739)

I checked the log with the command “docker compose logs -f” and found the following error.
```
nginx-1       | xxx.xxx.xxx.xxx - - [25/Dec/2024:14:11:55 +0000] "GET /api/site HTTP/1.1" 200 607 "https://xxxxx/chat/yyyyy" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
nginx-1       | xxx.xxx.xxx.xxx - - [25/Dec/2024:14:11:55 +0000] "GET /api/parameters HTTP/1.1" 200 971 "https://xxxxx/chat/yyyyy" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
nginx-1       | xxx.xxx.xxx.xxx - - [25/Dec/2024:14:11:55 +0000] "GET /api/meta HTTP/1.1" 200 19 "https://xxxxx/chat/yyyyy" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
nginx-1       | xxx.xxx.xxx.xxx - - [25/Dec/2024:14:11:55 +0000] "GET /api/conversations?limit=100&pinned=false HTTP/1.1" 200 246 "https://xxxxx/chat/yyyyy" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
nginx-1       | xxx.xxx.xxx.xxx - - [25/Dec/2024:14:11:55 +0000] "GET /api/conversations?limit=100&pinned=true HTTP/1.1" 200 46 "https://xxxxx/chat/yyyyy" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
api-1         | 2024-12-25 14:11:55,303.303 ERROR [Dummy-109] [app.py:875] - Exception on /api/messages/ab3a7d73-1b4e-4346-8565-ad889c0194b5/feedbacks [POST]
api-1         | Traceback (most recent call last):
api-1         |   File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
api-1         |     rv = self.dispatch_request()
api-1         |          ^^^^^^^^^^^^^^^^^^^^^^^
api-1         |   File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
api-1         |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1         |   File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 489, in wrapper
api-1         |     resp = resource(*args, **kwargs)
api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^
api-1         |   File "/app/api/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
api-1         |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1         |   File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api-1         |     resp = meth(*args, **kwargs)
api-1         |            ^^^^^^^^^^^^^^^^^^^^^
api-1         |   File "/app/api/controllers/web/wraps.py", line 21, in decorated
api-1         |     return view(app_model, end_user, *args, **kwargs)
api-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1         |   File "/app/api/controllers/web/message.py", line 111, in post
api-1         |     MessageService.create_feedback(app_model, message_id, end_user, args["rating"], args["content"])
api-1         |                                                                                     ~~~~^^^^^^^^^^^
api-1         | KeyError: 'content
```

On the other hand, when I clicked “Like” from the log & announcement, the process was successfully completed.
![image](https://github.com/user-attachments/assets/d0dc1097-1771-4ec5-a599-970febf83a8a)

**Comment by camucamulemon7** [comment]
@dosu.
Thanks for letting me know!
I did the update and made sure #12058 was reflected and tried it, but it did not fix it.
I thought maybe I was falling into docker compose's cache trap, so I rebuilt with the following command, but it didn't fix it.
```
docker compose build --no-cache
docker compose up --force-recreate --detach
```
Is there any other cause?

**Comment by yihong0618** [comment]
fixed in https://github.com/langgenius/dify/pull/12058

**Comment by hjlarry** [comment]
fixed in https://github.com/langgenius/dify/pull/12077
