### ISSUE TITLE
Workflow trace error

### ISSUE THREAD

**Issue by wy96f** [langgenius/dify#12117]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. configure langfuse
2. execute workflow

### ✔️ Expected Behavior

trace successfully sended to langfuse

### ❌ Actual Behavior
2024-12-26 [2024-12-26 11:54:50,469][ERROR][trace_manager_timer_2024-12-26 03:54:45][ops_trace_manager.py:739] Error processing trace tasks

2024-12-26 Traceback (most recent call last):

2024-12-26   File "/app/api/core/ops/ops_trace_manager.py", line 737, in run

2024-12-26     self.send_to_celery(tasks)

2024-12-26   File "/app/api/core/ops/ops_trace_manager.py", line 753, in send_to_celery

2024-12-26     trace_info = task.execute()

2024-12-26                  ^^^^^^^^^^^^^^

2024-12-26   File "/app/api/core/ops/ops_trace_manager.py", line 330, in execute

2024-12-26     return self.preprocess()

2024-12-26            ^^^^^^^^^^^^^^^^^

2024-12-26   File "/app/api/core/ops/ops_trace_manager.py", line 352, in preprocess

2024-12-26     return preprocess_map.get(self.trace_type, lambda: None)()

2024-12-26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-12-26   File "/app/api/core/ops/ops_trace_manager.py", line 335, in <lambda>

2024-12-26     TraceTaskName.WORKFLOW_TRACE: lambda: self.workflow_trace(

2024-12-26                                           ^^^^^^^^^^^^^^^^^^^^

2024-12-26   File "/app/api/core/ops/ops_trace_manager.py", line 363, in workflow_trace

2024-12-26     db.session.refresh(workflow_run)

2024-12-26   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 1767, in refresh

2024-12-26     return self._proxied.refresh(

2024-12-26            ^^^^^^^^^^^^^^^^^^^^^^

2024-12-26   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3143, in refresh

2024-12-26     self._expire_state(state, attribute_names)

2024-12-26   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3269, in _expire_state

2024-12-26     self._validate_persistent(state)

2024-12-26   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4138, in _validate_persistent

2024-12-26     raise sa_exc.InvalidRequestError(

2024-12-26 sqlalchemy.exc.InvalidRequestError:Instance '<WorkflowRun at 0x7fb237659bb0>' is not persistent within this Session

2024-12-26 [2024-12-26 11:55:08,350][DEBUG][Dummy-40][_trace.py:47] close.started

2024-12-26 [2024-12-26 11:55:08,350][DEBUG][Dummy-40][_trace.py:47] close.complete

2024-12-26 [2024-12-26 11:56:45,503][DEBUG][Dummy-91][_trace.py:47] close.started

2024-12-26 [2024-12-26 11:56:45,503][DEBUG][Dummy-91][_trace.py:47] close.complete

**Comment by laipz8200** [comment]
fixed in #12071

**Comment by laipz8200** [comment]
> Still seeing this issue on main:
> 
> `sqlalchemy.exc.InvalidRequestError: Instance '<WorkflowRun at 0x7fba188049e0>' is not persistent within this Session`

Hi, could you please provide more detailed information, such as the trace log? We want to know where this error happened.

**Comment by laipz8200** [comment]
Hi, @mgmorcos. The logs you prividered seems not belongs to the v0.15.0 version, please check you docker image.
