### ISSUE TITLE
Calling the /v1/chat-messages interface prompts an Internal Server Error, please contact support.

### ISSUE THREAD

**Issue by ouguofeng** [langgenius/dify#12123]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

 0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Using the same application configuration, the application calls the api with an error. I have read the docker log and it is indicated like this. May I ask why this is?

error:
2024-12-26 07:17:28.024 ERROR [Thread-4557 (_generate_worker)] [app_generator.py:232] - Unknown Error when generating
Traceback (most recent call last):
  File "/app/api/core/app/apps/chat/app_generator.py", line 212, in _generate_worker
    runner.run(
  File "/app/api/core/app/apps/chat/app_runner.py", line 159, in run
    context = dataset_retrieval.retrieve(

  File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 136, in retrieve
    all_documents = self.multiple_retrieve(

  File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 418, in multiple_retrieve
    data_post_processor = DataPostProcessor(tenant_id, reranking_mode, reranking_model, weights, False)

  File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 25, in __init__
    self.rerank_runner = self._get_rerank_runner(reranking_mode, tenant_id, reranking_model, weights)

  File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 68, in _get_rerank_runner
    rerank_model_instance = self._get_rerank_model_instance(tenant_id, reranking_model)

  File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 88, in _get_rerank_model_instance
    provider=reranking_model["reranking_provider_name"],

KeyError: 'reranking_provider_name'
2024-12-26 07:17:28.031 ERROR [Dummy-4558] [base_app_generate_response_converter.py:133] - 'reranking_provider_name'
![Uploading 4837d37a622d7ff060d16e005cae8fb.png…]()

### ✔️ Expected Behavior

I hope to solve this problem

**Comment by yihong0618** [comment]
the screen shot is broken

**Comment by ouguofeng** [comment]
![Uploading 4837d37a622d7ff060d16e005cae8fb.png…]()

**Comment by yihong0618** [comment]
still
