### ISSUE TITLE
Long-running workflow (around 1 minute) fails when invoked via the SDK, possibly lazy session related

### ISSUE THREAD

**Issue by why-el** [langgenius/dify#12192]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The steps are too hard to describe. We run a very elaborate workflow, one that takes a bunch of files, then makes a series of LLM calls, chained. This is all I can tell you. Right now, it works from the UI, but it fails using the node SDK. I don't think this matter, but maybe it does. 

Here are some logs I got from the instance: 

```
pi_1                    | 2024-12-29 03:32:07,695.695 INFO [Thread-37 (_generate_worker)] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
api_1                    | 2024-12-29 03:32:15,429.429 INFO [Thread-37 (_generate_worker)] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
api_1                    | 2024-12-29 03:32:37,108.108 INFO [Thread-37 (_generate_worker)] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
api_1                    | 2024-12-29 03:32:47,276.276 INFO [ThreadPoolExecutor-13_0] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
api_1                    | 2024-12-29 03:32:47,320.320 INFO [ThreadPoolExecutor-13_3] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
api_1                    | 2024-12-29 03:32:47,330.330 INFO [ThreadPoolExecutor-13_2] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
api_1                    | 2024-12-29 03:32:47,355.355 INFO [ThreadPoolExecutor-13_1] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
api_1                    | 2024-12-29 03:32:55,359.359 INFO [ThreadPoolExecutor-13_1] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
api_1                    | 2024-12-29 03:32:55,384.384 ERROR [Dummy-38] [workflow.py:100] - internal server error.
api_1                    | Traceback (most recent call last):
api_1                    |   File "/app/api/controllers/service_api/app/workflow.py", line 84, in post
api_1                    |     response = AppGenerateService.generate(
api_1                    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/services/app_generate_service.py", line 93, in generate
api_1                    |     generator = WorkflowAppGenerator().generate(
api_1                    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/app_generator.py", line 129, in generate
api_1                    |     return self._generate(
api_1                    |            ^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/app_generator.py", line 173, in _generate
api_1                    |     response = self._handle_response(
api_1                    |                ^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/app_generator.py", line 310, in _handle_response
api_1                    |     return generate_task_pipeline.process()
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 126, in process
api_1                    |     return self._to_blocking_response(generator)
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 133, in _to_blocking_response
api_1                    |     for stream_response in generator:
api_1                    |                            ^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 197, in _wrapper_process_stream_response
api_1                    |     for response in self._process_stream_response(tts_publisher=tts_publisher, trace_manager=trace_manager):
api_1                    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 414, in _process_stream_response
api_1                    |     self._save_workflow_app_log(workflow_run)
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 455, in _save_workflow_app_log
api_1                    |     workflow_app_log.tenant_id = workflow_run.tenant_id
api_1                    |                                  ^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
api_1                    |     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
api_1                    |     value = self._fire_loader_callables(state, key, passive)
api_1                    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
api_1                    |     return state._load_expired(state, passive)
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 803, in _load_expired
api_1                    |     self.manager.expired_attribute_loader(self, toload, passive)
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 1603, in load_scalar_attributes
api_1                    |     raise orm_exc.DetachedInstanceError(
api_1                    | sqlalchemy.orm.exc.DetachedInstanceError: Instance <WorkflowRun at 0x7396d51f4650> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
api_1                    | 2024-12-29 03:32:55,386.386 ERROR [Dummy-38] [app.py:875] - Exception on /v1/workflows/run [POST]
api_1                    | Traceback (most recent call last):
api_1                    |   File "/app/api/controllers/service_api/app/workflow.py", line 84, in post
api_1                    |     response = AppGenerateService.generate(
api_1                    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/services/app_generate_service.py", line 93, in generate
api_1                    |     generator = WorkflowAppGenerator().generate(
api_1                    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/app_generator.py", line 129, in generate
api_1                    |     return self._generate(
api_1                    |            ^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/app_generator.py", line 173, in _generate
api_1                    |     response = self._handle_response(
api_1                    |                ^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/app_generator.py", line 310, in _handle_response
api_1                    |     return generate_task_pipeline.process()
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 126, in process
api_1                    |     return self._to_blocking_response(generator)
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 133, in _to_blocking_response
api_1                    |     for stream_response in generator:
api_1                    |                            ^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 197, in _wrapper_process_stream_response
api_1                    |     for response in self._process_stream_response(tts_publisher=tts_publisher, trace_manager=trace_manager):
api_1                    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 414, in _process_stream_response
api_1                    |     self._save_workflow_app_log(workflow_run)
api_1                    |   File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 455, in _save_workflow_app_log
api_1                    |     workflow_app_log.tenant_id = workflow_run.tenant_id
api_1                    |                                  ^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
api_1                    |     return self.impl.get(state, dict_)  # type: ignore[no-any-return]
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
api_1                    |     value = self._fire_loader_callables(state, key, passive)
api_1                    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
api_1                    |     return state._load_expired(state, passive)
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 803, in _load_expired
api_1                    |     self.manager.expired_attribute_loader(self, toload, passive)
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 1603, in load_scalar_attributes
api_1                    |     raise orm_exc.DetachedInstanceError(
api_1                    | sqlalchemy.orm.exc.DetachedInstanceError: Instance <WorkflowRun at 0x7396d51f4650> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
api_1                    | 
api_1                    | During handling of the above exception, another exception occurred:
api_1                    | 
api_1                    | Traceback (most recent call last):
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
api_1                    |     rv = self.dispatch_request()
api_1                    |          ^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
api_1                    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 489, in wrapper
api_1                    |     resp = resource(*args, **kwargs)
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
api_1                    |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
api_1                    |     resp = meth(*args, **kwargs)
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/controllers/service_api/wraps.py", line 76, in decorated_view
api_1                    |     return view_func(*args, **kwargs)
api_1                    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
api_1                    |   File "/app/api/controllers/service_api/app/workflow.py", line 101, in post
api_1                    |     raise InternalServerError()
api_1                    | werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
api_1                    | 2024-12-29 03:32:56,874.874 INFO [ThreadPoolExecutor-13_0] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
api_1                    | 2024-12-29 03:32:58,899.899 INFO [ThreadPoolExecutor-13_2] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
api_1                    | 2024-12-29 03:33:01,050.050 INFO [ThreadPoolExecutor-13_3] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
```

### ✔️ Expected Behavior

It works when invoked from the API. 

### ❌ Actual Behavior

This particular workflow does not. I made a smaller workflow, ran it via the API, with no issues. The smaller workflow had file uploads as well. I think this is most likely related to how long the workflow runs for. Somehow, that messes with whatever way the DB session is constructed / kept-alive?

**Comment by why-el** [comment]
Now that I shard my logs, perhaps the problem is simpler, I see some 400 errors from OpenAI, perhaps down the road things fail, but very hard to know why. Specifically, there are no logs of this failed run in the Dify app itself? how else can we monitor this so that we get the same experience one sees when running the workflow manually?

**Comment by why-el** [comment]
@dosu, is this mentioned in the documentation? It sounds like you are asking me to configure _code_ inside the self-hosted instance, which would defeat the purpose of the self-hosted instance because we want to upgrade it regularly. 
 
 If logging of _workflow runs_ is a mere ENV setup, perhaps we can use it. Please clarify. Again, it must log workflow runs, not regular logging which is already properly set up.

**Comment by why-el** [comment]
I need someone from the team to confirm this. So two asks here really: 

1. How do we log workflow runs in the instance. 
2. Why is the workflow run not logged _by default_ in the app (under "Logs" for the workflow) if executed via the API?

**Comment by why-el** [comment]
Closing this is it was mostly user error. Eventually, using an API call to Dify, I was able to run the workflow programmatically and it showed under logs.
