### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

### ISSUE THREAD

**Issue by LiDaiyan** [langgenius/dify#1276]
### Dify version

main

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

when i run `flask db upgrade` i get an error below:
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
even i have run `openssl rand -base64 42` and fill it in the .env file.

### ✔️ Expected Behavior

no error

### ❌ Actual Behavior

AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

**Comment by LiDaiyan** [comment]
the whole info is below 
`Traceback (most recent call last):
  File "/home/lidaiyan/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/flask/cli.py", line 1064, in main
    cli.main()
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/flask/cli.py", line 579, in get_command
    app = info.load_app()
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/flask/cli.py", line 313, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/home/lidaiyan/dify/api/app.py", line 18, in <module>
    from extensions import ext_celery, ext_sentry, ext_redis, ext_login, ext_migrate, \
  File "/home/lidaiyan/dify/api/extensions/ext_storage.py", line 5, in <module>
    import boto3
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/docs/client.py", line 17, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/utils.py", line 37, in <module>
    import botocore.httpsession
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/botocore/httpsession.py", line 45, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/home/lidaiyan/.local/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'`

**Comment by takatost** [comment]
https://stackoverflow.com/questions/74981558/error-updating-python3-pip-attributeerror-module-lib-has-no-attribute-openss
You can check out this link for reference, or you can use Conda to create a clean Python environment and then`pip install -r requirements.txt`.

**Comment by LiDaiyan** [comment]
> https://stackoverflow.com/questions/74981558/error-updating-python3-pip-attributeerror-module-lib-has-no-attribute-openss You can check out this link for reference, or you can use Conda to create a clean Python environment and then`pip install -r requirements.txt`.

thanks, i solved it.
