### ISSUE TITLE
pdf处理状态错误

### ISSUE THREAD

**Issue by DevinFu** [langgenius/dify#13]
![image](https://github.com/langgenius/dify/assets/3973163/c4141102-a1e0-4738-ae89-da13f6305f1e)

导入pdf后，如图，处理状态显示为错误，我该如何进行下一步工作？

**Comment by takatost** [comment]
> ![image](https://user-images.githubusercontent.com/3973163/238269231-c4141102-a1e0-4738-ae89-da13f6305f1e.png)
> 
> 导入pdf后，如图，处理状态显示为错误，我该如何进行下一步工作？

是本地部署的吧？可以看下 /document/:document_id 接口返回中，error 字段返回的是什么，这边错误提示前端最近会加上

**Comment by CaesarC** [comment]
```

Traceback (most recent call last):
  File "/app/api/libs/rsa.py", line 45, in decrypt
    private_key = storage.load(filepath)
  File "/app/api/extensions/ext_storage.py", line 65, in load
    raise FileNotFoundError("File not found")
FileNotFoundError: File not found
```
我也遇到，storage似乎上传不了，权限也改成777了


```

    llm = LLMBuilder.to_llm(
  File "/app/api/core/llm/llm_builder.py", line 43, in to_llm
    model_credentials = cls.get_model_credentials(tenant_id, model_name)
  File "/app/api/core/llm/llm_builder.py", line 103, in get_model_credentials
    return provider_service.get_credentials(model_name)
  File "/app/api/core/llm/provider/llm_provider_service.py", line 32, in get_credentials
    return self.provider.get_credentials(model_id)
  File "/app/api/core/llm/provider/openai_provider.py", line 28, in get_credentials
    'openai_api_key': self.get_provider_api_key(model_id=model_id)
  File "/app/api/core/llm/provider/base.py", line 39, in get_provider_api_key
    return self.get_decrypted_token(provider.encrypted_config)
  File "/app/api/core/llm/provider/base.py", line 100, in get_decrypted_token
    return self.decrypt_token(token)
  File "/app/api/core/llm/provider/base.py", line 108, in decrypt_token
    return rsa.decrypt(base64.b64decode(token), self.tenant_id)
  File "/app/api/libs/rsa.py", line 47, in decrypt
    raise PrivkeyNotFoundError("Private key not found, tenant_id: {tenant_id}".format(tenant_id=tenant_id))
libs.rsa.PrivkeyNotFoundError: Private key not found, tenant_id: 868937c7-dd78-4537-83ed-f86683e263c5
```

**Comment by CaesarC** [comment]
https://github.com/langgenius/dify/pull/21

**Comment by CaesarC** [comment]
已解决
