### ISSUE TITLE
 jinja2.exceptions.templatesyntaxerror 

### ISSUE THREAD

**Issue by Dream97** [langgenius/dify#1441]
### Dify version

0.3.24

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

某些会话会出现这个问题，创建新的就不出现了

### ❌ Actual Behavior

ERROR 2023-11-01 18:14:44,452 [completion.py]: 180 - generate - internal server error.
Traceback (most recent call last):
  File "/data/services/dify/api/controllers/service_api/app/completion.py", line 159, in generate
    for chunk in response:
  File "/data/services/dify/api/services/completion_service.py", line 436, in generate
    cls.handle_error(result)
  File "/data/services/dify/api/services/completion_service.py", line 580, in handle_error
    raise Exception(description)
Exception: expected token 'end of print statement', got ':'
ERROR 2023-11-01 18:14:44,453 [app.py]: 1414 - log_exception - Exception on /v1/chat-messages [POST]
Traceback (most recent call last):
  File "/data/services/dify/api/controllers/service_api/app/completion.py", line 159, in generate
    for chunk in response:
  File "/data/services/dify/api/services/completion_service.py", line 436, in generate
    cls.handle_error(result)
  File "/data/services/dify/api/services/completion_service.py", line 580, in handle_error
    raise Exception(description)
Exception: expected token 'end of print statement', got ':'

**Comment by crazywoola** [comment]
You can upgrade to latest version to see if this error persists.

**Comment by takatost** [comment]
We've removed the dependency on jinja2 template parsing in the latest version.
