### ISSUE TITLE
S3 storage error

### ISSUE THREAD

**Issue by NowakSeweryn** [langgenius/dify#1513]
### Dify version

0.2.29

### Cloud or Self Hosted

Self Hosted

### Steps to reproduce

I set the variables in docker-compose.yaml (example below) 
When I have uploaded file to "dataset" file is saved in "s3" (checked it) but on site I see the error "server error"
The console shows this error

```
ERROR:app:Exception on /console/api/datasets/indexing-estimate [POST]
docker-api-1       | Traceback (most recent call last):
docker-api-1       |   File "/app/api/extensions/ext_storage.py", line 52, in load
docker-api-1       |     data = client.get_object(Bucket=self.bucket_name, Key=filename)['Body'].read()
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
docker-api-1       |     return self._make_api_call(operation_name, kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 980, in _make_api_call
docker-api-1       |     raise error_class(parsed_response, operation_name)
docker-api-1       | botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
docker-api-1       | 
docker-api-1       | During handling of the above exception, another exception occurred:
docker-api-1       | 
docker-api-1       | Traceback (most recent call last):
docker-api-1       |   File "/app/api/libs/rsa.py", line 55, in decrypt
docker-api-1       |     private_key = storage.load(filepath)
docker-api-1       |   File "/app/api/extensions/ext_storage.py", line 55, in load
docker-api-1       |     raise FileNotFoundError("File not found")
docker-api-1       | FileNotFoundError: File not found
docker-api-1       | 
docker-api-1       | During handling of the above exception, another exception occurred:
docker-api-1       | 
docker-api-1       | Traceback (most recent call last):
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
docker-api-1       |     rv = self.dispatch_request()
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
docker-api-1       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
docker-api-1       |     resp = resource(*args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 109, in view
docker-api-1       |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
docker-api-1       |     resp = meth(*args, **kwargs)
docker-api-1       |   File "/app/api/controllers/console/setup.py", line 79, in decorated
docker-api-1       |     return view(*args, **kwargs)
docker-api-1       |   File "/app/api/libs/login.py", line 94, in decorated_view
docker-api-1       |     return current_app.ensure_sync(func)(*args, **kwargs)
docker-api-1       |   File "/app/api/controllers/console/wraps.py", line 19, in decorated
docker-api-1       |     return view(*args, **kwargs)
docker-api-1       |   File "/app/api/controllers/console/datasets/datasets.py", line 268, in post
docker-api-1       |     response = indexing_runner.file_indexing_estimate(current_user.current_tenant_id, file_details,
docker-api-1       |   File "/app/api/core/indexing_runner.py", line 236, in file_indexing_estimate
docker-api-1       |     embedding_model = ModelFactory.get_embedding_model(
docker-api-1       |   File "/app/api/core/model_providers/model_factory.py", line 138, in get_embedding_model
docker-api-1       |     return model_class(
docker-api-1       |   File "/app/api/core/model_providers/models/embedding/openai_embedding.py", line 16, in __init__
docker-api-1       |     credentials = model_provider.get_model_credentials(
docker-api-1       |   File "/app/api/core/model_providers/providers/openai_provider.py", line 306, in get_model_credentials
docker-api-1       |     return self.get_provider_credentials(obfuscated)
docker-api-1       |   File "/app/api/core/model_providers/providers/openai_provider.py", line 210, in get_provider_credentials
docker-api-1       |     credentials['openai_api_key'] = encrypter.decrypt_token(
docker-api-1       |   File "/app/api/core/helper/encrypter.py", line 20, in decrypt_token
docker-api-1       |     return rsa.decrypt(base64.b64decode(token), tenant_id)
docker-api-1       |   File "/app/api/libs/rsa.py", line 57, in decrypt
docker-api-1       |     raise PrivkeyNotFoundError("Private key not found, tenant_id: {tenant_id}".format(tenant_id=tenant_id))
docker-api-1       | libs.rsa.PrivkeyNotFoundError: Private key not found, tenant_id: a41b1ccc-91f5-4301-a48a-2fcc19b41810
```

docker-compose.yaml 
section 'api' and section 'worker' seted as 's3'
```
 STORAGE_TYPE: 's3'
 STORAGE_LOCAL_PATH: storage        
 S3_ENDPOINT: 'https://s3.eu-central-1.amazonaws.com'
 S3_BUCKET_NAME: 'mybucket'
 S3_ACCESS_KEY: 'ak-sdlksdkm'
 S3_SECRET_KEY: 'sk-sdlkmsdlkm'
 S3_REGION: 'eu-central-1'
```

**Comment by crazywoola** [comment]
Can you try ` docker exec -it docker-api-1 flask reset-encrypt-key-pair` to regenerate the encrypt key pair?

**Comment by NowakSeweryn** [comment]
I just checked your solution but still have this same error. File was uploaded to S3 and that's it.

**Comment by waltcow** [comment]
check you file object key first

**Comment by NowakSeweryn** [comment]
If the file exists on S3 and was saved in the bucket then everything is ok in my opinion. 
The error from the logs says that there is a problem finding the file when trying to read it. That is, there is probably an error in the code.

**Comment by JohnJyong** [comment]
It seems that you used local storage at the beginning and later switched to S3 storage, so you need to regenerate the secret key.

**Comment by Srharsha0006** [comment]
I have configured the MinIO details in the Dify docker-compose.yaml file, and the application is running and working fine. I want to see the files in MinIO from Dify. How can I search the files in the MinIO bucket from the Dify web interface?

**Comment by yaohongfenglove** [comment]
I'd like to contribute code by adding Flask commands. This would be helpful for developers who initially use local storage but later want to switch to cloud storage. The code would look something like this:


# code
api/commands.py
```python
@click.command("upload-private-key-file-to-cloud-storage", help="upload private key file to cloud storage")
@click.option("--tenant_id", prompt=False, help="tenant_id")
def upload_private_key_file_cloud_storage(tenant_id: Optional[str] = None):
    """
    upload private.pem to cloud storage
    """
    click.echo(
        click.style(
            "Start upload private.pem to cloud storage",
            fg="green",
        )
    )

    if not tenant_id:
        click.echo(click.style("Warning: did not provide an tenant_id, it will be auto queried in the database", fg="yellow"))
        tenants_list: List[Tenant] = Tenant.query.all()
        tenants = [item.id for item in tenants_list]
    else:
        tenants = [tenant_id, ]

    for tenant_id in tenants:
        click.echo(
            click.style(
                f"Current tenant_id is: {tenant_id}",
                fg="green",
            )
        )

        file_key = f"privkeys/{tenant_id}/private.pem"
        with open(f"{os.environ.get('STORAGE_LOCAL_PATH', 'storage')}/{file_key}", "rb") as f:
            file_content = f.read()
        storage.save(filename=file_key, data=file_content)
        click.echo(
            click.style(
                "Congratulations! file uploaded. link: {}".format(f'https://{os.environ.get("OSS_BUCKET_DOMAIN_NAME", "galaxy-spiders.oss-cn-shenzhen.aliyuncs.com")}/{file_key}'),
                fg="green",
            )
        )


@click.command("upload-local-files-to-cloud-storage", help="upload local files to cloud storage")
def upload_local_files_to_cloud_storage():
    """
    upload local files to cloud storage
    """
    click.echo(
        click.style(
            "Start upload local files to cloud storage",
            fg="green",
        )
    )

    # TODO 2024-10-9 If the amount of data is large, it must be queried in batches
    files: List[UploadFile] = UploadFile.query.filter_by(storage_type="local").all()

    click.echo(
        click.style(
            f"files count: {len(files)}",
            fg="green",
        )
    )

    for file in files:
        target_filepath = f"{os.environ.get('STORAGE_LOCAL_PATH', 'storage')}/{file.key}"

        # if the file exists
        if not os.path.exists(target_filepath):
            click.echo(
                click.style(
                    f"Warning! file not exist. filepath: {target_filepath}, ignore this, continue",
                    fg="yellow",
                )
            )
            continue

        # Upload to cloud storage
        with open(target_filepath, "rb") as f:
            file_content = f.read()
        storage.save(filename=file.key, data=file_content)
        click.echo(
            click.style(
                f"File uploaded. file.key: {file.key}",
                fg="green",
            )
        )

        # Update database record
        file.storage_type = os.environ["STORAGE_TYPE"]
        db.session.commit()
        click.echo(
            click.style(
                f"file.storage_type updated to database. file.key: {file.key}",
                fg="green",
            )
        )

    click.echo(
        click.style(
            "Congratulations! finish files uploaded.",
            fg="green",
        )
    )


def register_commands(app):
    # other code
    app.cli.add_command(upload_private_key_file_cloud_storage)
    app.cli.add_command(upload_local_files_to_cloud_storage)
```


# add to docs 
[Self-Host Related](https://docs.dify.ai/learn-more/faq/install-faq)

**17.1 Migrating from Local Storage to Cloud Storage**

If you want to migrate files from local storage to cloud storage, such as Alibaba Cloud OSS, you need to migrate data from the 'upload_files' and 'privkeys' folders within your local storage directory. Here are the steps:

### Steps:
1. modify environment variables
    If you start from local source code, modify the environment variables in the .env file to the cloud storage you want to migrate to. For example: STORAGE_TYPE=aliyun-oss，then configure the Alibaba Cloud OSS storage settings.

    If you start from docker-compose, modify the environment variables in the docker-compose.yaml file to the cloud storage you want to migrate to, For example: STORAGE_TYPE=aliyun-oss，then configure the Alibaba Cloud OSS storage settings.

2. Execute the following commands:

   For uploading private key files:
   start from local source code：flask upload-private-key-file-to-cloud-storage
   start from docker-compose: docker exec -it docker-api-1 flask upload-private-key-file-to-cloud-storage

   For uploading local files:
   start from local source code：flask upload-local-files-to-cloud-storage
   start from docker-compose: docker exec -it docker-api-1 flask upload-local-files-to-cloud-storage
