### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by mozeqiu123** [langgenius/dify#1783]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.3.30

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Click on an application and this error appears. View logs or prompt word arrangement
![image](https://github.com/langgenius/dify/assets/139750690/ce133a4e-5c14-4e53-8c4b-c7f981fd2e7c)

**Comment by mozeqiu123** [comment]
RangeError: Incorrect locale information provided
    at Intl.getCanonicalLocales (<anonymous>)
    at CanonicalizeLocaleList (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:31779:17)
    at match (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:32039:108)
    at getLocaleOnServer (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/1372.js:4609:63)
    at LocaleLayout (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/1372.js:4529:55)
    at U (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:33704:13)
    at Oa (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:33809:21)
    at Object.toJSON (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:33632:20)
    at stringify (<anonymous>)
    at da (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:33345:9)
RangeError: Incorrect locale information provided
    at Intl.getCanonicalLocales (<anonymous>)
    at CanonicalizeLocaleList (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:31779:17)
    at match (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:32039:108)
    at getLocaleOnServer (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/1372.js:4609:63)
    at LocaleLayout (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/1372.js:4529:55)
    at U (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:33704:13)
    at Oa (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:33809:21)
    at Array.toJSON (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:33632:20)
    at stringify (<anonymous>)
    at da (/home/ecs-user/lilin_test/dify_20231114/dify/web/.next/standalone/.next/server/chunks/5347.js:33345:9)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '2636264908'
}
