### ISSUE TITLE
Error encountered during conversation using Azure gpt-4-vision-preview review model

### ISSUE THREAD

**Issue by yanzu888** [langgenius/dify#1924]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.4.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

model：azure gpt-4-vision-preview
Error messages appear during the chat process
`ERROR:core.application_manager:Validation Error when generating
Traceback (most recent call last):
  File "/app/api/core/application_manager.py", line 163, in _generate_worker
    runner.run(
  File "/app/api/core/app_runner/basic_app_runner.py", line 209, in run
    self._handle_invoke_result(
  File "/app/api/core/app_runner/app_runner.py", line 215, in _handle_invoke_result
    self._handle_invoke_result_stream(
  File "/app/api/core/app_runner/app_runner.py", line 244, in _handle_invoke_result_stream
    for result in invoke_result:
  File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 164, in _invoke_result_generator
    result=LLMResult(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMResult
usage
  none is not an allowed value (type=type_error.none.not_allowed)
`
![error1](https://github.com/langgenius/dify/assets/20461842/b8bc8a11-4b8d-4e35-bb81-07d75392f70a)

![error2](https://github.com/langgenius/dify/assets/20461842/a7b776c7-7bdc-4ef3-a003-f2ebbc868114)

**Comment by yanzu888** [comment]
Dify version
0.4.4

Cloud or Self Hosted
Self Hosted (Docker)

Steps to reproduce
I have updated the latest version of Dify, but the same issue still occurs

![image](https://github.com/langgenius/dify/assets/20461842/615e59ea-c9a7-4de5-ae14-9b695cb81930)
![image](https://github.com/langgenius/dify/assets/20461842/0e31b630-fd89-4970-8b38-a7e999a13349)
![image](https://github.com/langgenius/dify/assets/20461842/e7ed9f3e-4889-4ae4-a1f7-61eee1097e79)
