### ISSUE TITLE
数据集导入时提示：嵌入发生错误

### ISSUE THREAD

**Issue by babyfacehl** [langgenius/dify#194]
Dify version: Self Host

## Steps To Reproduce

1. 这两天开始导入数据集都提示：嵌入发生错误
2.之前没有这个问题

## The expected behavior
<img width="526" alt="image" src="https://github.com/langgenius/dify/assets/107471230/2ccbe6e1-365a-4dec-8706-d6d7152386f4">
<img width="1082" alt="image" src="https://github.com/langgenius/dify/assets/107471230/4817f73b-9922-4597-807d-4accba3dbcf8">

**Comment by babyfacehl** [comment]
docker logs -n 200 docker-worker-1，查看到错误信息如下：
[2023-05-25 03:59:01,071: INFO/MainProcess] Start process document: 88e8b485-07ba-4849-a854-1e156e669faa
[2023-05-25 03:59:09,305: INFO/MainProcess] error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-05-25 03:59:10,351: INFO/MainProcess] error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-05-25 03:59:12,445: INFO/MainProcess] error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-05-25 03:59:14,473: INFO/MainProcess] error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-05-25 03:59:19,289: INFO/MainProcess] error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-05-25 03:59:29,579: INFO/MainProcess] error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-05-25 03:59:29,579: ERROR/MainProcess] consume document failed
Traceback (most recent call last):
  File "/app/api/tasks/document_indexing_task.py", line 41, in document_indexing_task
    indexing_runner.run(document)
  File "/app/api/core/indexing_runner.py", line 68, in run
    self._build_index(
  File "/app/api/core/indexing_runner.py", line 402, in _build_index
    vector_index.add_nodes(chunk_nodes)
  File "/app/api/core/index/vector_index.py", line 52, in add_nodes
    embedding_results = index._get_node_embedding_results(
  File "/usr/local/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py", line 96, in _get_node_embedding_results
    ) = self._service_context.embed_model.get_queued_text_embeddings()
  File "/usr/local/lib/python3.10/site-packages/llama_index/embeddings/base.py", line 155, in get_queued_text_embeddings
    embeddings = self._get_text_embeddings(cur_batch_texts)
  File "/app/api/core/embedding/openai_embedding.py", line 163, in _get_text_embeddings
    embeddings = get_embeddings(texts, engine=engine, openai_api_key=self.openai_api_key)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/app/api/core/embedding/openai_embedding.py", line 70, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, engine=engine, api_key=openai_api_key).data
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

感觉是说 OpenAI API 密钥无效，但是我这个密钥刚刚申请的。不可能无效，而且除了数据集导入这里有问题，其他APP使用是正常的。

**Comment by takatost** [comment]
https://status.openai.com/
目前 OpenAI 不可用，耐心等待一下哈

**Comment by takatost** [comment]
> 这个不影响其他的使用，只是数据集生成吗？

对话和数据集导入请求 OpenAI API 重试次数都是 3 次，只能说数据集导入这块如果分段比较多，就可能不巧超过了 3 次重试，这个只能等 OpenAI 那边稳定
