### ISSUE TITLE
导入文本报错

### ISSUE THREAD

**Issue by chanjetsdp** [langgenius/dify#209]
导入文本文件，报错
docker-worker-1    | [2023-05-25 13:08:12,771: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[d5d942ff-834e-4ae1-a707-fa5e398d97a2] received
docker-worker-1    | [2023-05-25 13:08:12,772: INFO/MainProcess] Start process document: d1a75d51-1024-499f-82c3-7a3f673791a5
docker-worker-1    | [2023-05-25 13:08:12,778: ERROR/MainProcess] consume document failed
docker-worker-1    | Traceback (most recent call last):
docker-worker-1    |   File "/app/api/tasks/document_indexing_task.py", line 41, in document_indexing_task
docker-worker-1    |     indexing_runner.run(document)
docker-worker-1    |   File "/app/api/core/indexing_runner.py", line 48, in run
docker-worker-1    |     text_docs = self._load_data(document)
docker-worker-1    |   File "/app/api/core/indexing_runner.py", line 217, in _load_data
docker-worker-1    |     text_docs = self._load_data_from_file(file_detail)
docker-worker-1    |   File "/app/api/core/indexing_runner.py", line 246, in _load_data_from_file
docker-worker-1    |     self.storage.download(upload_file.key, filepath)
docker-worker-1    |   File "/app/api/extensions/ext_storage.py", line 83, in download
docker-worker-1    |     raise FileNotFoundError("File not found")
docker-worker-1    | FileNotFoundError: File not found

Dify version: Self Host

## Steps To Reproduce

1. 0.2.1 

3. docker-compose ps
docker-compose ps
NAME                IMAGE                              COMMAND                  SERVICE             CREATED             STATUS              PORTS
docker-api-1        langgenius/dify-api:latest         "/entrypoint.sh"         api                 About an hour ago   Up About an hour    80/tcp, 5001/tcp
docker-db-1         postgres:15-alpine                 "docker-entrypoint.s…"   db                  About an hour ago   Up About an hour    0.0.0.0:5432->5432/tcp, :::5432->5432/tcp
docker-nginx-1      nginx:latest                       "/docker-entrypoint.…"   nginx               About an hour ago   Up About an hour    0.0.0.0:80->80/tcp, :::80->80/tcp
docker-redis-1      redis:6-alpine                     "docker-entrypoint.s…"   redis               About an hour ago   Up About an hour    6379/tcp
docker-weaviate-1   semitechnologies/weaviate:1.18.4   "/bin/weaviate --hos…"   weaviate            About an hour ago   Up About an hour    
docker-web-1        langgenius/dify-web:latest         "/entrypoint.sh"         web                 About an hour ago   Up About an hour    80/tcp, 3000/tcp
docker-worker-1     langgenius/dify-api:latest         "/entrypoint.sh"         worker              About an hour ago   Up About an hour    80/tcp, 5001/tcp

## The current behavior
导入文本
![image](https://github.com/langgenius/dify/assets/4714703/de7fb3b0-1a98-47e4-b400-bd342a144743)
![image](https://github.com/langgenius/dify/assets/4714703/b28ce725-3b0d-4f5c-8b8c-e650e8135f21)

**Comment by chanjetsdp** [comment]
> docker-compose.yaml

yes, yesterday I download dify-0.2.1, 
I user the default docker-compose.yaml, and only change *_URL , COOKIE_* , *CORS* envs.

**Comment by chanjetsdp** [comment]
after docker-compose pull 
the error still here
![Uploading image.png…]()

**Comment by chanjetsdp** [comment]
![image](https://github.com/langgenius/dify/assets/4714703/68b22a39-5400-4180-8f87-fe221741691a)

![image](https://github.com/langgenius/dify/assets/4714703/8f541224-ddb7-45e2-abc1-d4105914a59c)

**Comment by chanjetsdp** [comment]
docker-compose.yaml
```
change volumes path
- ./volumes/app/storage:/app/storage

to

- ./volumes/app/storage:/app/api/storage

```
