### ISSUE TITLE
Dataset: Failed to upload xlsx file

### ISSUE THREAD

**Issue by bowenliang123** [langgenius/dify#2172]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When uploading a xlsx to a dataset, the request failed with 500 internal error.

<img width="1016" alt="image" src="https://github.com/langgenius/dify/assets/1935105/b78344cb-5e72-4ec5-af32-1f12ed5b72b8">

<img width="974" alt="image" src="https://github.com/langgenius/dify/assets/1935105/8c62be76-aebc-48ea-ab55-989f42d5b57c">

logs from API  with docker compose:
```
api_1          | [2024-01-24 08:31:07.160][ERROR][app.py][1414] Exception on /console/api/datasets/indexing-estimate [POST]
api_1          | Traceback (most recent call last):
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/descriptors/base.py", line 59, in _convert
api_1          |     value = expected_type(value)
api_1          | TypeError: Fill() takes no arguments
api_1          | 
api_1          | During handling of the above exception, another exception occurred:
api_1          | 
api_1          | Traceback (most recent call last):
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
api_1          |     rv = self.dispatch_request()
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
api_1          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
api_1          |     resp = resource(*args, **kwargs)
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 109, in view
api_1          |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
api_1          |     resp = meth(*args, **kwargs)
api_1          |   File "/app/api/controllers/console/setup.py", line 77, in decorated
api_1          |     return view(*args, **kwargs)
api_1          |   File "/app/api/libs/login.py", line 90, in decorated_view
api_1          |     return current_app.ensure_sync(func)(*args, **kwargs)
api_1          |   File "/app/api/controllers/console/wraps.py", line 19, in decorated
api_1          |     return view(*args, **kwargs)
api_1          |   File "/app/api/controllers/console/datasets/datasets.py", line 284, in post
api_1          |     response = indexing_runner.file_indexing_estimate(current_user.current_tenant_id, file_details,
api_1          |   File "/app/api/core/indexing_runner.py", line 287, in file_indexing_estimate
api_1          |     text_docs = FileExtractor.load(file_detail, is_automatic=processing_rule.mode == 'automatic')
api_1          |   File "/app/api/core/data_loader/file_extractor.py", line 36, in load
api_1          |     return cls.load_from_file(file_path, return_text, upload_file, is_automatic)
api_1          |   File "/app/api/core/data_loader/file_extractor.py", line 106, in load_from_file
api_1          |     return delimiter.join([document.page_content for document in loader.load()]) if return_text else loader.load()
api_1          |   File "/app/api/core/data_loader/loader/excel.py", line 30, in load
api_1          |     wb = load_workbook(filename=self._file_path, read_only=True)
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 346, in load_workbook
api_1          |     reader.read()
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/reader/excel.py", line 299, in read
api_1          |     apply_stylesheet(self.archive, self.wb)
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py", line 198, in apply_stylesheet
api_1          |     stylesheet = Stylesheet.from_tree(node)
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py", line 103, in from_tree
api_1          |     return super(Stylesheet, cls).from_tree(node)
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/descriptors/serialisable.py", line 103, in from_tree
api_1          |     return cls(**attrib)
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py", line 74, in __init__
api_1          |     self.fills = fills
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/descriptors/sequence.py", line 27, in __set__
api_1          |     seq = self.container(_convert(self.expected_type, value) for value in seq)
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/descriptors/sequence.py", line 27, in <genexpr>
api_1          |     seq = self.container(_convert(self.expected_type, value) for value in seq)
api_1          |   File "/usr/local/lib/python3.10/site-packages/openpyxl/descriptors/base.py", line 61, in _convert
api_1          |     raise TypeError('expected ' + str(expected_type))
api_1          | TypeError: expected <class 'openpyxl.styles.fills.Fill'>
```

and
```
api_1          | [2024-01-24 09:09:03.945][ERROR][app.py][1414] Exception on /console/api/datasets/indexing-estimate [POST]
api_1          | Traceback (most recent call last):
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
api_1          |     rv = self.dispatch_request()
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
api_1          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
api_1          |     resp = resource(*args, **kwargs)
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 109, in view
api_1          |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)
api_1          |   File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
api_1          |     resp = meth(*args, **kwargs)
api_1          |   File "/app/api/controllers/console/setup.py", line 77, in decorated
api_1          |     return view(*args, **kwargs)
api_1          |   File "/app/api/libs/login.py", line 90, in decorated_view
api_1          |     return current_app.ensure_sync(func)(*args, **kwargs)
api_1          |   File "/app/api/controllers/console/wraps.py", line 19, in decorated
api_1          |     return view(*args, **kwargs)
api_1          |   File "/app/api/controllers/console/datasets/datasets.py", line 284, in post
api_1          |     response = indexing_runner.file_indexing_estimate(current_user.current_tenant_id, file_details,
api_1          |   File "/app/api/core/indexing_runner.py", line 287, in file_indexing_estimate
api_1          |     text_docs = FileExtractor.load(file_detail, is_automatic=processing_rule.mode == 'automatic')
api_1          |   File "/app/api/core/data_loader/file_extractor.py", line 36, in load
api_1          |     return cls.load_from_file(file_path, return_text, upload_file, is_automatic)
api_1          |   File "/app/api/core/data_loader/file_extractor.py", line 106, in load_from_file
api_1          |     return delimiter.join([document.page_content for document in loader.load()]) if return_text else loader.load()
api_1          |   File "/app/api/core/data_loader/loader/csv_loader.py", line 31, in load
api_1          |     docs = self._read_from_file(csvfile)
api_1          |   File "/app/api/core/data_loader/loader/csv_loader.py", line 52, in _read_from_file
api_1          |     content = "\n".join(f"{k.strip()}: {v.strip()}" for k, v in row.items())
api_1          |   File "/app/api/core/data_loader/loader/csv_loader.py", line 52, in <genexpr>
api_1          |     content = "\n".join(f"{k.strip()}: {v.strip()}" for k, v in row.items())
api_1          | AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by zhangyangeng** [comment]
分享个排查路径：
检测一下文档是不是从企业微信或者其他共享文档里导出的，这个直接导出的文件大概率样式是有些不兼容的
用本地的Excel打开另存为一下再导入就没有问题了，如图：

<img width="748" height="86" alt="Image" src="https://github.com/user-attachments/assets/af0c9998-7c19-42ce-a34a-90a8214d83f8" />

下面是直接导出的文件
上面是另存为的文件，大小增加了12kb，导入就没有问题了
怀疑共享文档里用的样式是Excel文件不支持的格式，重新保存后会自动去除或者修正这些格式，所以上传就没有问题了
