### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by perzeuss** [langgenius/dify#2188]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Prerequisites
- Deploy Dify 0.5.0 image using the k8s helm chart from https://github.com/BorisPolonsky/dify-helm
- Set up the instance

Reproduce
- Create a new chat app (Basic Assistant)
- Visit Overview Page
- Click on the preview button
- Get navigated to e.g. `/chat/X4sOQQS07aONzXfL`

### ✔️ Expected Behavior

I see the builtin dify chat

### ❌ Actual Behavior

I see an error page for status code 500
Frontend logs:

```
ReferenceError: window is not defined
    at 3687 (/app/web/.next/server/chunks/6097.js:1:27551)
    at t (/app/web/.next/server/webpack-runtime.js:1:143)
    at 67160 (/app/web/.next/server/chunks/7160.js:1:10468)
    at t (/app/web/.next/server/webpack-runtime.js:1:143)
    at F (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:91937)
    at $ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:90488)
    at rC (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:33840)
    at n$ (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59861)
    at nj (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64628)
    at nO (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64035)
```

**Comment by crazywoola** [comment]
Let me check.

**Comment by zxhlyh** [comment]
#2201 fixed
