### ISSUE TITLE
ERROR: Settings - Model Provider - Setup Baichuan - Save

### ISSUE THREAD

**Issue by JiakunXu** [langgenius/dify#2442]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```
ERROR:core.model_runtime.model_providers.baichuan.baichuan:baichuan credentials validate failed
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/baichuan/llm/baichuan_turbo.py", line 167, in generate
    data = self._build_parameters(model, stream, messages, parameters)
  File "/app/api/core/model_runtime/model_providers/baichuan/llm/baichuan_turbo.py", line 131, in _build_parameters
    if parameters['frequency_penalty'] < 1 or parameters['frequency_penalty'] > 2:
KeyError: 'frequency_penalty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/baichuan/baichuan.py", line 22, in validate_provider_credentials
    model_instance.validate_credentials(
  File "/app/api/core/model_runtime/model_providers/baichuan/llm/llm.py", line 101, in validate_credentials
    instance.generate(model=model, stream=False, messages=[
  File "/app/api/core/model_runtime/model_providers/baichuan/llm/baichuan_turbo.py", line 170, in generate
    raise InternalServerError(f"Failed to build parameters for model: {model}")
core.model_runtime.model_providers.baichuan.llm.baichuan_turbo_errors.InternalServerError: Failed to build parameters for model: baichuan2-turbo
ERROR:app:Exception on /console/api/workspaces/current/model-providers/baichuan [POST]
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/baichuan/llm/baichuan_turbo.py", line 167, in generate
    data = self._build_parameters(model, stream, messages, parameters)
  File "/app/api/core/model_runtime/model_providers/baichuan/llm/baichuan_turbo.py", line 131, in _build_parameters
    if parameters['frequency_penalty'] < 1 or parameters['frequency_penalty'] > 2:
KeyError: 'frequency_penalty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 84, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/workspace/model_providers.py", line 112, in post
    model_provider_service.save_provider_credentials(
  File "/app/api/services/model_provider_service.py", line 157, in save_provider_credentials
    provider_configuration.add_or_update_custom_credentials(credentials)
  File "/app/api/core/entities/provider_configuration.py", line 199, in add_or_update_custom_credentials
    provider_record, credentials = self.custom_credentials_validate(credentials)
  File "/app/api/core/entities/provider_configuration.py", line 181, in custom_credentials_validate
    credentials = model_provider_factory.provider_credentials_validate(
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 87, in provider_credentials_validate
    model_provider_instance.validate_provider_credentials(filtered_credentials)
  File "/app/api/core/model_runtime/model_providers/baichuan/baichuan.py", line 30, in validate_provider_credentials
    raise ex
  File "/app/api/core/model_runtime/model_providers/baichuan/baichuan.py", line 22, in validate_provider_credentials
    model_instance.validate_credentials(
  File "/app/api/core/model_runtime/model_providers/baichuan/llm/llm.py", line 101, in validate_credentials
    instance.generate(model=model, stream=False, messages=[
  File "/app/api/core/model_runtime/model_providers/baichuan/llm/baichuan_turbo.py", line 170, in generate
    raise InternalServerError(f"Failed to build parameters for model: {model}")
core.model_runtime.model_providers.baichuan.llm.baichuan_turbo_errors.InternalServerError: Failed to build parameters for model: baichuan2-turbo
```

**Comment by takatost** [comment]
@Yeuoly help take a look?

**Comment by crazywoola** [comment]
#2446
