### ISSUE TITLE
failed to add cohere key

### ISSUE THREAD

**Issue by Magein** [langgenius/dify#2506]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to file this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![version](https://github.com/langgenius/dify/assets/16146901/6c25b0f6-621a-4830-8da7-658096d92e04)
![403](https://github.com/langgenius/dify/assets/16146901/c851294d-fc0c-42b0-9d16-ffa9eeaca6c3)
添加从cohere中获取的key点击确定出现403的错误。
key是Trial keys（free）类型的，是不是只能添加Production 类型的key

**Comment by crazywoola** [comment]
Try to remove all the old keys and use this command `flask reset-encrypt-key-pair` to reset all encryption keys.

https://docs.dify.ai/getting-started/install-self-hosted/install-faq#id-1.-how-to-reset-the-password-if-the-local-deployment-initialization-fails-with-an-incorrect-password

**Comment by Magein** [comment]
重置后添加 cohere中的key还是出现403的错误
![添加key失败](https://github.com/langgenius/dify/assets/16146901/daff4d53-2947-4c80-90e7-25c90718a87c)

**Comment by zhanaali** [comment]
貌似是国内ip被拦截了

**Comment by mylxsw** [comment]
我这边也遇到了同样的问题

**Comment by Magein** [comment]
国内ip的问题。被封禁了



---Original---
From: ***@***.***&gt;
Date: Thu, Feb 29, 2024 01:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [langgenius/dify] failed to add cohere key (Issue #2506)




 
我这边也遇到了同样的问题

**Comment by m5314** [comment]
> 国内ip的问题。被封禁了
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Feb 29, 2024 01:53 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [langgenius/dify] failed to add cohere key (Issue #2506) 我这边也遇到了同样的问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

你好，我也遇到这个问题，请问有解决办法吗？

**Comment by jay-jjwu** [comment]
我也遇到了相同的问题，用了代理也不行，有人解决了吗？

**Comment by jay-jjwu** [comment]
在dify-api容器中，添加代理服务器，可以解决

**Comment by marioalexandreantunes** [comment]
Got same error in v0.10.1

```
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 42, in invoke
    return self._invoke(model, credentials, query, docs, score_threshold, top_n, user)
  File "/app/api/core/model_runtime/model_providers/cohere/rerank/rerank.py", line 51, in _invoke
    response = client.rerank(
  File "/app/api/.venv/lib/python3.10/site-packages/cohere/base_client.py", line 1259, in rerank
    raise ApiError(status_code=_response.status_code, body=_response.text)
cohere.core.api_error.ApiError: status_code: 403, body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 496, in _retriever
    documents = RetrievalService.retrieve(
  File "/app/api/core/rag/datasource/retrieval_service.py", line 110, in retrieve
    all_documents = data_post_processor.invoke(
  File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 37, in invoke
    documents = self.rerank_runner.run(query, documents, score_threshold, top_n, user)
  File "/app/api/core/rag/rerank/rerank_model.py", line 45, in run
    rerank_result = self.rerank_model_instance.invoke_rerank(
  File "/app/api/core/model_manager.py", line 226, in invoke_rerank
    return self._round_robin_invoke(
  File "/app/api/core/model_manager.py", line 310, in _round_robin_invoke
    return function(*args, **kwargs)
  File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 44, in invoke
    raise self._transform_invoke_error(e)
core.model_runtime.errors.invoke.InvokeBadRequestError: [cohere] Bad Request Error, status_code: 403, body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py:1107: ResourceWarning: unclosed <socket object, fd=16, family=2, type=1, proto=6>
  if is_not_primary_key(identitykey[1]):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2024-11-02 10:48:36,397.397 INFO [Thread-13 (_generate_worker)] [_client.py:1038] - HTTP Request: POST https://api.cohere.com/v2/rerank "HTTP/1.1 403 Forbidden"
2024-11-02 10:48:36,399.399 ERROR [Thread-13 (_generate_worker)] [knowledge_retrieval_node.py:65] - Error when running knowledge retrieval node
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/cohere/base_client.py", line 1257, in rerank
    _response_json = _response.json()
  File "/app/api/.venv/lib/python3.10/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 42, in invoke
    return self._invoke(model, credentials, query, docs, score_threshold, top_n, user)
  File "/app/api/core/model_runtime/model_providers/cohere/rerank/rerank.py", line 51, in _invoke
    response = client.rerank(
  File "/app/api/.venv/lib/python3.10/site-packages/cohere/base_client.py", line 1259, in rerank
    raise ApiError(status_code=_response.status_code, body=_response.text)
cohere.core.api_error.ApiError: status_code: 403, body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/api/core/workflow/nodes/knowledge_retrieval/knowledge_retrieval_node.py", line 58, in _run
    results = self._fetch_dataset_retriever(node_data=self.node_data, query=query)
  File "/app/api/core/workflow/nodes/knowledge_retrieval/knowledge_retrieval_node.py", line 155, in _fetch_dataset_retriever
    all_documents = dataset_retrieval.multiple_retrieve(
  File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 390, in multiple_retrieve
    all_documents = data_post_processor.invoke(
  File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 37, in invoke
    documents = self.rerank_runner.run(query, documents, score_threshold, top_n, user)
  File "/app/api/core/rag/rerank/rerank_model.py", line 45, in run
    rerank_result = self.rerank_model_instance.invoke_rerank(
  File "/app/api/core/model_manager.py", line 226, in invoke_rerank
    return self._round_robin_invoke(
  File "/app/api/core/model_manager.py", line 310, in _round_robin_invoke
    return function(*args, **kwargs)
  File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 44, in invoke
    raise self._transform_invoke_error(e)
core.model_runtime.errors.invoke.InvokeBadRequestError: [cohere] Bad Request Error, status_code: 403, body: <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:1312: ResourceWarning: unclosed <socket object, fd=16, family=2, type=1, proto=6>
  fn = getattr(self, f"_memoized_method_{key}")
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2024-11-02 10:54:17,113.113 INFO [Dummy-22] [_client.py:1038] - HTTP Request: POST https://api.cohere.ai/v1/rerank "HTTP/1.1 403 Forbidden"
/usr/local/lib/python3.10/json/decoder.py:353: ResourceWarning: unclosed <socket object, fd=16, family=2, type=1, proto=6>
  obj, end = self.scan_once(s, idx)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2024-11-02 10:55:43,784.784 INFO [Dummy-23] [_client.py:1038] - HTTP Request: POST https://api.cohere.com/v2/rerank"HTTP/1.1 403 Forbidden"
/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py:1340: ResourceWarning: unclosed <socket object, fd=16, family=2, type=1, proto=6>
  for key, getter in populators["quick"]:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2024-11-02 10:55:51,036.036 INFO [Dummy-24] [_client.py:1038] - HTTP Request: POST https://api.cohere.com/v2/rerank "HTTP/1.1 403 Forbidden"
```

Deleted the Account a trying to add again and now i got :
```
2024-11-02 11:01:40,144.144 INFO [Dummy-25] [_client.py:1038] - HTTP Request: POST https://api.cohere.com/v2/rerank "HTTP/1.1 403 Forbidden"
 ```

**Comment by RamyHuang** [comment]
有可以解决的么，我这边遇到了同样的问题

**Comment by RamyHuang** [comment]
![image](https://github.com/user-attachments/assets/834beab8-1930-4e29-a747-b5a0373ab80a)
一直报403

**Comment by RamyHuang** [comment]
![image](https://github.com/user-attachments/assets/178ece39-4b52-486d-ae6c-ff8b9075c733)
一直报403异常。我在api了加了http_proxy的代理，还是不行

**Comment by 159753Fetter** [comment]
> 在dify-api容器中，添加代理服务器，可以解决

您好，请问具体怎么加呢？
