### ISSUE TITLE
Can not use STT service

### ISSUE THREAD

**Issue by KnaveM** [langgenius/dify#2514]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create an app with Speech to Text feature enabled.
2. Can use the TTS service in Studio
3. Publish the app and open another conversation, record a message, the server response with: "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

### ❌ Actual Behavior

<img width="1063" alt="image" src="https://github.com/langgenius/dify/assets/33738071/5867e379-19ff-4f2c-b8e5-daaed72381d8">

```json
{
    "code": "internal_server_error",
    "message": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
    "status": 500
}
```

API server logs:
```log
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
ERROR:root:internal server error.
Traceback (most recent call last):
  File "/app/api/controllers/console/explore/audio.py", line 43, in post
    response = AudioService.transcript_asr(
TypeError: AudioService.transcript_asr() missing 1 required positional argument: 'promot'
ERROR:app:Exception on /console/api/installed-apps/66cb0253-fb93-4cad-82f5-0920951f11df/audio-to-text [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/explore/audio.py", line 43, in post
    response = AudioService.transcript_asr(
TypeError: AudioService.transcript_asr() missing 1 required positional argument: 'promot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/explore/wraps.py", line 39, in decorated
    return view(installed_app, *args, **kwargs)
  File "/app/api/controllers/console/explore/audio.py", line 73, in post
    raise InternalServerError()
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by crazywoola** [comment]
Fixed in this pr https://github.com/langgenius/dify/pull/2493, will release in v0.5.7
