### ISSUE TITLE
the auto-created index on Milvus is not working

### ISSUE THREAD

**Issue by bowenliang123** [langgenius/dify#2569]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

main/0.5.6

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

- use milvus 2.3.9 as vector backend
- upload document to knowledge library

### ❌ Actual Behavior

- it's not able to be queried on or used
![image](https://github.com/langgenius/dify/assets/1935105/14cec1de-c772-4f30-b578-aee8f327feb8)

- it's not working when deleting docs from index , when disabling docs. logs from the worker.
```
[2024-02-27 02:49:45,540: ERROR/MainProcess] Cleaned document when document deleted failed
Traceback (most recent call last):
  File "/Users/bw/dev/dify/api/tasks/clean_document_task.py", line 36, in clean_document_task
    index_processor.clean(dataset, index_node_ids)
  File "/Users/bw/dev/dify/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 68, in clean
    vector.delete_by_ids(node_ids)
  File "/Users/bw/dev/dify/api/core/rag/datasource/vdb/vector_factory.py", line 141, in delete_by_ids
    self._vector_processor.delete_by_ids(ids)
  File "/Users/bw/dev/dify/api/core/rag/datasource/vdb/milvus/milvus_vector.py", line 127, in delete_by_ids
    self._client.delete(collection_name=self._collection_name, pks=doc_ids)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dify/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 413, in delete
    raise ex from ex
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dify/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 409, in delete
    res = conn.delete(collection_name, expr, timeout=timeout, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dify/lib/python3.10/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dify/lib/python3.10/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dify/lib/python3.10/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dify/lib/python3.10/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dify/lib/python3.10/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dify/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 604, in delete
    raise err from err
  File "/opt/homebrew/Caskroom/miniforge/base/envs/dify/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 600, in delete
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=failed to create expr plan, expr =  id in [47102f94-24ed-40bb-a443-4501c256007f,42cec4f7-431f-4653-8bc9-f575219fa1c1,46d7afe5-1590-45df-9460-376a1f454e32])>
```

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/2573
