### ISSUE TITLE
Question: After integrating Dify with WeChat Work, I'm not receiving any replies to my inquiries.

### ISSUE THREAD

**Issue by Aa242615** [langgenius/dify#2701]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

      at listOnTimeout (node:internal/timers:575:11)
      at processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [Array]
  }
}
2024-03-05 22:29:00.108 ERROR [#] e1469a49-0c60-4240-8768-ec54f175c900 failed to get package typings Error: entry file or path not exists
    at PackageDeclaration.parsePackageEntry (/app/node_modules/node-modules-utils/dist/package.js:72:19)
    at PackageDeclaration.parse (/app/node_modules/node-modules-utils/dist/package.js:41:13)
    at PackageDeclaration.load (/app/node_modules/node-modules-utils/dist/declaration.js:17:9)
    at getThreePartyPackageTypings (/app/dist/handler/typings.js:87:9)
2024-03-05 22:29:14.942 ERROR [#] e37b93e2-0120-4cf4-ab39-aa908c5d9859 failed to get package typings Error: entry file or path not exists
    at PackageDeclaration.parsePackageEntry (/app/node_modules/node-modules-utils/dist/package.js:72:19)
    at PackageDeclaration.parse (/app/node_modules/node-modules-utils/dist/package.js:41:13)
    at PackageDeclaration.load (/app/node_modules/node-modules-utils/dist/declaration.js:17:9)
    at getThreePartyPackageTypings (/app/dist/handler/typings.js:87:9)
    at PackageDeclaration.parsePackageEntry (/app/node_modules/node-modules-utils/dist/package.js:72:19)
2024-03-05 22:29:17.564 ERROR [#] 08ed5712-4c4e-4308-a8f7-65e296db7557 failed to get package typings Error: entry file or path not exists
    at PackageDeclaration.parse (/app/node_modules/node-modules-utils/dist/package.js:41:13)
    at PackageDeclaration.load (/app/node_modules/node-modules-utils/dist/declaration.js:17:9)
    at getThreePartyPackageTypings (/app/dist/handler/typings.js:87:9)
2024-03-05 22:29:18.227 ERROR [#] 6d4c41d6-b0b3-4663-949c-e3823c0cb4f0 failed to get package typings Error: entry file or path not exists
    at PackageDeclaration.parsePackageEntry (/app/node_modules/node-modules-utils/dist/package.js:72:19)
    at PackageDeclaration.parse (/app/node_modules/node-modules-utils/dist/package.js:41:13)
    at PackageDeclaration.load (/app/node_modules/node-modules-utils/dist/declaration.js:17:9)
    at getThreePartyPackageTypings (/app/dist/handler/typings.js:87:9)
2024-03-05 22:29:18.883 ERROR [#] d759f9da-7a41-4364-a8cf-9f91f1f1ff9c failed to get package typings Error: entry file or path not exists
    at PackageDeclaration.parsePackageEntry (/app/node_modules/node-modules-utils/dist/package.js:72:19)
    at PackageDeclaration.parse (/app/node_modules/node-modules-utils/dist/package.js:41:13)
    at PackageDeclaration.load (/app/node_modules/node-modules-utils/dist/declaration.js:17:9)
    at getThreePartyPackageTypings (/app/dist/handler/typings.js:87:9)
2024-03-05 22:29:32.305  INFO [attap] [main] called GET /attap
2024-03-05 22:29:36.832  INFO [attap] [main] called GET /attap
2024-03-05 22:29:37.409  INFO [attap] [main] called GET /attap

### ✔️ Expected Behavior

Is there anyone who can help me answer this question?

**Comment by moyudaduizhang** [comment]
![Uploading QQ截图20240305230221.png…]()

**Comment by crazywoola** [comment]
You can read the description in this pr  https://github.com/langgenius/dify/pull/2638 . And the logs you provide seems not related to our side.

**Comment by yshaoliang** [comment]
Thanks for your help!
I have configured YAML according to your instructions and ensured that DIFY1 API-BASE and DIFY1 API_KEY are correct:
DIFY_API_BASE: ' http://localhost/v1 '
DIFY_API_KEY: 'app-r5WC7hymNwOYuMH8plvfAbA6'

And I also ensure that this UUID is copied from the wecom group chat robot app:
https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=27ff0100 -1d2a-4293-****-3b9b44477a68

Restart Docker, log in to dify again, but still return an invalid UUID

![11](https://github.com/user-attachments/assets/fd67a238-fae3-4fac-8204-b3f3cb536098)
