### ISSUE TITLE
Cohere embedding model not working

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#2703]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.8

### Cloud or Self Hosted

Cloud, Self Hosted (Source)

### Steps to reproduce

![CleanShot 2024-03-05 at 21 03 24@2x](https://github.com/langgenius/dify/assets/119136210/31370b5e-717f-41c6-831d-dc9565de3f04)
Using Cohere embedding models does not work in Dify cloud or local. Tested with multiple fresh API keys. 

### ✔️ Expected Behavior

Normal embedding process that works like OpenAI embedding models

### ❌ Actual Behavior

Nothing, no text preview or indexing happending

**Comment by JohnJyong** [comment]
Are you using a Trial key?
The cohere trial key which is limited to 10 API calls / minute.

**Comment by AndyMik90** [comment]
@JohnJyong no I'm using production key.

**Comment by JohnJyong** [comment]
it works fine with the model 'embed-multilingual-v2.0' in my side. 
pls provide your embedding model name, thanks @AndyMik90

**Comment by AndyMik90** [comment]
> it works fine with the model 'embed-multilingual-v2.0' in my side. pls provide your embedding model name, thanks @AndyMik90

I tried with 'embed-multilingual-v3.0' and v2.0 but it does nothing. Tried with multiple fresh production keys, also multiple documents to test with, they work fine with OpenAI embedding models.

**Comment by AndyMik90** [comment]
I can confirm that the issue is still in place.

Here is how to reproduce:

- Add cohere API to Dify Cloud in the model providers.
- Use any cohere model, I tested "embed-english-v2.0", "embed-english-v3.0" and "embed-multilingual-v3.0" as system embedding model.
- Upload a PDF and try to auto chunk it (tested also manual).
- The indexing process never gets beyond 0%.

They all just stop on the indexing step:
![CleanShot 2024-03-29 at 21 47 57@2x](https://github.com/langgenius/dify/assets/119136210/219b8d34-92dd-4de5-9370-81624f5ae218)


I double-checked that the API is working ,but using OpenAI embedding model, but using Cohere for reranking:

rerank-english:
![CleanShot 2024-03-29 at 21 43 12@2x](https://github.com/langgenius/dify/assets/119136210/daeac2c6-01d2-4d08-afd6-b898daa7740a)

rerank-multilingual:
![CleanShot 2024-03-29 at 21 45 11@2x](https://github.com/langgenius/dify/assets/119136210/3dd051c6-ef92-46ed-bf58-428375a9b6a6)

**Comment by AppendinoCom** [comment]
I see this issue closed, but it has not been fixed.

**Comment by Lalusch** [comment]
I wonder why on the cloud.dify it works but not on the local

**Comment by AndyMik90** [comment]
@JohnJyong I tried to revisit this on 0.6.6 with the change to add API Base for cohere (API base: https://api.cohere.ai/v1)

Error using Cohere-multilingual-v.3.0
```python
 2024-05-08 11:04:14.859 ERROR [Thread-209 (process_request_thread)] [app.py:838] - Exception on /console/api/datasets/indexing-estimate [POST]
Traceback (most recent call last):
  File "/.../flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/.../flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/.../flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/.../flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/.../flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/.../api/controllers/console/setup.py", line 86, in decorated
    return view(*args, **kwargs)
  File "/.../api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/.../api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/.../api/controllers/console/datasets/datasets.py", line 332, in post
    response = indexing_runner.indexing_estimate(current_user.current_tenant_id, extract_settings,
  File "/.../api/core/indexing_runner.py", line 264, in indexing_estimate
    text_docs = index_processor.extract(extract_setting, process_rule_mode=tmp_processing_rule["mode"])
  File "/.../api/core/rag/index_processor/processor/paragraph_index_processor.py", line 21, in extract
    text_docs = ExtractProcessor.extract(extract_setting=extract_setting,
  File "/.../api/core/rag/extractor/extract_processor.py", line 135, in extract
    return extractor.extract()
  File "/.../api/core/rag/extractor/pdf_extractor.py", line 38, in extract
    documents = list(self.load())
  File "/.../api/core/rag/extractor/pdf_extractor.py", line 55, in load
    yield from self.parse(blob)
  File "/.../api/core/rag/extractor/pdf_extractor.py", line 64, in parse
    for page_number, page in enumerate(pdf_reader):
  File "/.../pypdfium2/_helpers/document.py", line 121, in __iter__
    yield self[i]
  File "/.../pypdfium2/_helpers/document.py", line 124, in __getitem__
    return self.get_page(i)
  File "/.../pypdfium2/_helpers/document.py", line 368, in get_page
    raise PdfiumError("Failed to load page.")
pypdfium2._helpers.misc.PdfiumError: Failed to load page.
```

Error using cohere-multilingual-v2.0:

```python
Unhandled Runtime Error
TypeError: Failed to fetch

Source
service/base.ts (299:17) @ fetch

  297 | }),
  298 | new Promise((resolve, reject) => {
> 299 |   globalThis.fetch(urlWithPrefix, options as RequestInit)
      |             ^
  300 |     .then((res) => {
  301 |       const resClone = res.clone()
  302 |       // Error handler
```
  
Can you try reproducing using local code startup, with Qdrant (v.1.7.3 as the docker is set)? You see that others are having the same issue.
