### ISSUE TITLE
When i start with source code , error occurs

### ISSUE THREAD

**Issue by ZJ-CAI** [langgenius/dify#2720]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

**### When i try "flask db upgrade" the error occurs:**

Traceback (most recent call last):
  File "/root/miniconda3/envs/langchain_czj/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/flask/cli.py", line 1107, in main
    cli.main()
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/flask/cli.py", line 388, in decorator
    return ctx.invoke(f, *args, **kwargs)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/flask_migrate/cli.py", line 150, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/16T/czj/dify/api/migrations/env.py", line 114, in <module>
    run_migrations_online()
  File "/home/ubuntu/16T/czj/dify/api/migrations/env.py", line 98, in run_migrations_online
    with connectable.connect() as connection:
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/root/miniconda3/envs/langchain_czj/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by crazywoola** [comment]
Please use the right template for reporting bugs. And do notice the format of error message.

**Comment by aspack00** [comment]
I encountered a similar issue, but after exposing the port, I could connect to the database using pgAdmin. Finally, I changed 127.0.0.1 to a non-local IP, such as 192.168.1.130, and it worked fine. Strangely, only the DB_HOST of the api container needed to be set this way, but the worker container didn't. I don't care anymore, as long as it runs.

我遇到类似的问题，我将127.0.0.1改成非本地ip，比如192.168.1.130就好了，奇怪的是只有api这个容器的DB_HOST需要这样设置，worker这个容器就不用。我也不管了，反正他能跑就行。

![image](https://github.com/langgenius/dify/assets/3943619/3720a5c6-fa5f-4d7f-b89b-75dbb673c1e2)

![image](https://github.com/langgenius/dify/assets/3943619/cbf0caa9-5aad-493d-ad43-fcc7a6739bdd)
