### ISSUE TITLE
celery无法启动

### ISSUE THREAD

**Issue by AtmosphereMao** [langgenius/dify#275]
celery无法启动，发生以下错误。
```shell
Administrator@DESKTOP-5DPNN43 MINGW64 /e/dify/api (develop)
$ celery -A app.celery worker  -l info
[2023-05-31 17:53:05,612: WARNING/MainProcess] C:\Python311\Lib\site-packages\kombu\utils\compat.py:82: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for ep in importlib_metadata.entry_points().get(namespace, [])

[2023-05-31 17:53:05,630: WARNING/MainProcess] C:\Python311\Lib\site-packages\celery\utils\imports.py:145: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for ep in entry_points().get(namespace, []):


 -------------- celery@DESKTOP-5DPNN43 v5.2.7 (dawn-chorus)
--- ***** -----
-- ******* ---- Windows-10-10.0.19043-SP0 2023-05-31 17:53:05
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         app:0x219cfb2b350
- ** ---------- .> transport:   redis://:**@localhost:6379/1
- ** ---------- .> results:     postgresql://postgres:**@localhost:5432/dify
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . tasks.add_document_to_index_task.add_document_to_index_task
  . tasks.add_segment_to_index_task.add_segment_to_index_task
  . tasks.clean_dataset_task.clean_dataset_task
  . tasks.clean_document_task.clean_document_task
  . tasks.deal_dataset_vector_index_task.deal_dataset_vector_index_task
  . tasks.document_indexing_task.document_indexing_task
  . tasks.generate_conversation_summary_task.generate_conversation_summary_task
  . tasks.remove_document_from_index_task.remove_document_from_index_task
  . tasks.remove_segment_from_index_task.remove_segment_from_index_task

[2023-05-31 17:53:05,690: CRITICAL/MainProcess] Unrecoverable error: AttributeError("Can't pickle local object 'init_app.<locals>.FlaskTask'")
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\celery\worker\worker.py", line 203, in start
    self.blueprint.start(self)
  File "C:\Python311\Lib\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "C:\Python311\Lib\site-packages\celery\bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\celery\concurrency\base.py", line 129, in start
    self.on_start()
  File "C:\Python311\Lib\site-packages\celery\concurrency\prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\billiard\pool.py", line 1046, in __init__
    self._create_worker_process(i)
  File "C:\Python311\Lib\site-packages\billiard\pool.py", line 1158, in _create_worker_process
    w.start()
  File "C:\Python311\Lib\site-packages\billiard\process.py", line 124, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\billiard\popen_spawn_win32.py", line 83, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python311\Lib\site-packages\billiard\reduction.py", line 99, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'init_app.<locals>.FlaskTask'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\billiard\spawn.py", line 165, in spawn_main
    exitcode = _main(fd)
               ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\billiard\spawn.py", line 207, in _main
    self = pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input

```
没有修改过tasks的内容。

**Comment by AtmosphereMao** [comment]
已解决，windows需使用`solo`并发池
```
celery -A app.celery worker -l info --pool=solo
```
