### ISSUE TITLE
工作流中的知识检索不配置系统rerank模型情况下不可用

### ISSUE THREAD

**Issue by FFinchR** [langgenius/dify#2954]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

工作流中配置了【知识检索节点】后，调试时没有输出，查看docker-api日志后报错如下：
```
Exception in thread Thread-78 (embedding_search):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/api/core/rag/datasource/retrieval_service.py", line 133, in embedding_search
    data_post_processor = DataPostProcessor(str(dataset.tenant_id), reranking_model, False)
  File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 16, in __init__
    self.rerank_runner = self._get_rerank_runner(reranking_model, tenant_id)
  File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 33, in _get_rerank_runner
    rerank_model_instance = model_manager.get_model_instance(
  File "/app/api/core/model_manager.py", line 228, in get_model_instance
    return self.get_default_model_instance(tenant_id, model_type)
  File "/app/api/core/model_manager.py", line 250, in get_default_model_instance
    raise ProviderTokenNotInitError(f"Default model not found for {model_type}")
core.errors.error.ProviderTokenNotInitError: Default model not found for ModelType.RERANK
```
然后在系统配置中添加了rerank模型后就可用了。
但是页面上提供了Rerank模型的开关，是否应该在关闭时不去初始化Rerank模型？

**Comment by crazywoola** [comment]
Close due to #1542
