### ISSUE TITLE
dify can't use ollama nomic-embed-text model in [Embedding] index document 

### ISSUE THREAD

**Issue by AdamYLK** [langgenius/dify#2958]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

i'm make sure that ollama can be use in 0.0.0.0，and can be use in dify hosted server
![image](https://github.com/langgenius/dify/assets/13025698/21fa1995-e775-4b8f-9638-17373e51745b)

when i config add model,it's success
![image](https://github.com/langgenius/dify/assets/13025698/c77b9d5e-dccb-4580-9f44-ec1027ee1ef4)

when i config global model config,it's success
![image](https://github.com/langgenius/dify/assets/13025698/cbc4d10f-59f7-4a88-8a81-2afd71942832)

but when i add file to dataset (a simple file like 1.txt only few sentents in) and confirm to index，web alert error
![image](https://github.com/langgenius/dify/assets/13025698/c4c852d7-522d-45b0-9811-79940244fb52)

and server error info follow (worker logs)

```
[2024-03-25 04:19:30,042: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[c3686f4a-d3a8-425b-8e64-d7e035d8a4ff] received
[2024-03-25 04:19:30,053: INFO/MainProcess] Start process document: 7f9548e4-fb63-4271-928e-0a8a204b919f
[2024-03-25 04:19:31,486: ERROR/MainProcess] consume document failed
Traceback (most recent call last):
  File "/app/api/core/indexing_runner.py", line 71, in run
    self._load(
  File "/app/api/core/indexing_runner.py", line 674, in _load
    index_processor.load(dataset, chunk_documents)
  File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 59, in load
    vector = Vector(dataset)
  File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 23, in __init__
    self._vector_processor = self._init_vector()
  File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 48, in _init_vector
    return WeaviateVector(
  File "/app/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 30, in __init__
    self._client = self._init_client(config)
  File "/app/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 39, in _init_client
    client = weaviate.Client(
  File "/usr/local/lib/python3.10/site-packages/weaviate/client.py", line 150, in __init__
    self._connection = Connection(
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 654, in __init__
    self._server_version = self.get_meta()["version"]
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 678, in get_meta
    raise UnexpectedStatusCodeException("Meta endpoint", response)
weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 502, with response body: None.
[2024-03-25 04:19:31,495: INFO/MainProcess] Processed dataset: ace11a14-86f2-4a17-a301-1d637d9c0e0f latency: 1.4506416786462069
```

### ✔️ Expected Behavior

how can i use nomic-embed-text or this is a bug need fix

**Comment by AdamYLK** [comment]
i make sure that in ollama server logs didn't receive interface request from dify, when i index document
but，when save model config there have logs from dify

**Comment by crazywoola** [comment]
It's not the problem with ollama, it's the problem with weaviate. You should check the configuration of weaviate and check the container's status.

**Comment by AdamYLK** [comment]
i change yaml config，open 8080 for weaviate (default yaml didn't need must open 8080 port for host)
and check it's can be used
![image](https://github.com/langgenius/dify/assets/13025698/1b4996a2-7eaf-470a-9814-7af417591fba)

then down and up container
and upload file to dataset ... it's work

so maybe change default yaml config?

----
and another suggestion
open  read time out config for dify
like chat or embedding config:
core.model_runtime.errors.invoke.InvokeConnectionError: [ollama] Connection Error, HTTPConnectionPool(host='ollama host', port=11434): Read timed out. (read timeout=60)
core.model_runtime.errors.invoke.InvokeConnectionError: [ollama] Connection Error, HTTPConnectionPool(host='ollama host', port=11434): Read timed out. (read timeout=300)

**Comment by crazywoola** [comment]
> and another suggestion
> open read time out config for dify

This config is in our roadmap. we are doing refinement on RAG these days.

**Comment by crazywoola** [comment]
> then down and up container
> and upload file to dataset ... it's work
> so maybe change default yaml config?

We have tested the installation steps for many times. so typically it is the problem of port conflict.

**Comment by AdamYLK** [comment]
impossible, this server only have dify container
if i didn't <uncomment to expose weaviate port to host> ，they dosn't work
