### ISSUE TITLE
local embedding model 500 error 

### ISSUE THREAD

**Issue by Frank-Zeng** [langgenius/dify#3020]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

add local embedding m3e model. occur 500 error, how to resolve this issue?![img_v3_029d_ff2838be-c178-43ff-ba1a-194be0538f3g](https://github.com/langgenius/dify/assets/17022654/c67f316d-f6b0-4bbd-ac7b-ed607925719b)

### ✔️ Expected Behavior

1

### ❌ Actual Behavior

add local embedding success.

**Comment by crazywoola** [comment]
Please provide the container's log.

**Comment by Frank-Zeng** [comment]
> Please provide the container's log.

[2024-03-28 06:29:44,868: WARNING/MainProcess] --- Logging error ---
[2024-03-28 06:29:44,871: WARNING/MainProcess] Traceback (most recent call last):
[2024-03-28 06:29:44,871: WARNING/MainProcess]   File "/app/api/core/model_runtime/model_providers/__base/text_embedding_model.py", line 31, in invoke
    return self._invoke(model, credentials, texts, user)
[2024-03-28 06:29:44,871: WARNING/MainProcess]   File "/app/api/core/model_runtime/model_providers/nvidia/text_embedding/text_embedding.py", line 73, in _invoke
    raise InvokeError(msg)
[2024-03-28 06:29:44,871: WARNING/MainProcess] core.model_runtime.errors.invoke.InvokeError: Inference error
[2024-03-28 06:29:44,871: WARNING/MainProcess]
During handling of the above exception, another exception occurred:
[2024-03-28 06:29:44,872: WARNING/MainProcess] Traceback (most recent call last):
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/app/api/core/embedding/cached_embedding.py", line 35, in embed_documents
    embedding_result = self._model_instance.invoke_text_embedding(
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/app/api/core/model_manager.py", line 95, in invoke_text_embedding
    return self.model_type_instance.invoke(
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/app/api/core/model_runtime/model_providers/__base/text_embedding_model.py", line 33, in invoke
    raise self._transform_invoke_error(e)
[2024-03-28 06:29:44,872: WARNING/MainProcess] core.model_runtime.errors.invoke.InvokeError: [nvidia] Error: Inference error
[2024-03-28 06:29:44,872: WARNING/MainProcess]
During handling of the above exception, another exception occurred:
[2024-03-28 06:29:44,872: WARNING/MainProcess] Traceback (most recent call last):
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/utils/log.py", line 146, in format
    msg = super().format(record)
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2024-03-28 06:29:44,873: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2024-03-28 06:29:44,873: WARNING/MainProcess] TypeError: not all arguments converted during string formatting
[2024-03-28 06:29:44,873: WARNING/MainProcess] Call stack:
[2024-03-28 06:29:44,874: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/concurrency/base.py", line 29, in apply_target
    ret = target(*args, **kwargs)
[2024-03-28 06:29:44,874: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 649, in fast_trace_task

**Comment by crazywoola** [comment]
@dosu-bot

```
[2024-03-28 06:29:44,868: WARNING/MainProcess] --- Logging error ---
[2024-03-28 06:29:44,871: WARNING/MainProcess] Traceback (most recent call last):
[2024-03-28 06:29:44,871: WARNING/MainProcess]   File "/app/api/core/model_runtime/model_providers/__base/text_embedding_model.py", line 31, in invoke
    return self._invoke(model, credentials, texts, user)
[2024-03-28 06:29:44,871: WARNING/MainProcess]   File "/app/api/core/model_runtime/model_providers/nvidia/text_embedding/text_embedding.py", line 73, in _invoke
    raise InvokeError(msg)
[2024-03-28 06:29:44,871: WARNING/MainProcess] core.model_runtime.errors.invoke.InvokeError: Inference error
[2024-03-28 06:29:44,871: WARNING/MainProcess]
During handling of the above exception, another exception occurred:
[2024-03-28 06:29:44,872: WARNING/MainProcess] Traceback (most recent call last):
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/app/api/core/embedding/cached_embedding.py", line 35, in embed_documents
    embedding_result = self._model_instance.invoke_text_embedding(
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/app/api/core/model_manager.py", line 95, in invoke_text_embedding
    return self.model_type_instance.invoke(
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/app/api/core/model_runtime/model_providers/__base/text_embedding_model.py", line 33, in invoke
    raise self._transform_invoke_error(e)
[2024-03-28 06:29:44,872: WARNING/MainProcess] core.model_runtime.errors.invoke.InvokeError: [nvidia] Error: Inference error
[2024-03-28 06:29:44,872: WARNING/MainProcess]
During handling of the above exception, another exception occurred:
[2024-03-28 06:29:44,872: WARNING/MainProcess] Traceback (most recent call last):
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/utils/log.py", line 146, in format
    msg = super().format(record)
[2024-03-28 06:29:44,872: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2024-03-28 06:29:44,873: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2024-03-28 06:29:44,873: WARNING/MainProcess] TypeError: not all arguments converted during string formatting
[2024-03-28 06:29:44,873: WARNING/MainProcess] Call stack:
[2024-03-28 06:29:44,874: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/concurrency/base.py", line 29, in apply_target
    ret = target(*args, **kwargs)
[2024-03-28 06:29:44,874: WARNING/MainProcess]   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 649, in fast_trace_task
```
