### ISSUE TITLE
API unable to connect to PostgreSQL database

### ISSUE THREAD

**Issue by yang208115** [langgenius/dify#3047]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

I executed "Docker Compose - f Docker Compose. yaml - p dify up - d" in the Docker directory based on the document. I accessed“ http://localhost/install ”The webpage was constantly loading, and when I opened Dockers Desktop, I saw that db-1 was repeatedly rebooting, and the backend of api-1 was constantly reporting
2024-03-30 23:41:02 Traceback (most recent call last):
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
2024-03-30 23:41:02     return fn()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
2024-03-30 23:41:02     return _ConnectionFairy._checkout(self)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
2024-03-30 23:41:02     fairy = _ConnectionRecord.checkout(pool)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
2024-03-30 23:41:02     rec = pool._do_get()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
2024-03-30 23:41:02     with util.safe_reraise():
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2024-03-30 23:41:02     compat.raise_(
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2024-03-30 23:41:02     raise exception
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
2024-03-30 23:41:02     return self._create_connection()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
2024-03-30 23:41:02     return _ConnectionRecord(self)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
2024-03-30 23:41:02     self.__connect()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
2024-03-30 23:41:02     with util.safe_reraise():
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2024-03-30 23:41:02     compat.raise_(
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2024-03-30 23:41:02     raise exception
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
2024-03-30 23:41:02     self.dbapi_connection = connection = pool._invoke_creator(self)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
2024-03-30 23:41:02     return dialect.connect(*cargs, **cparams)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
2024-03-30 23:41:02     return self.dbapi.connect(*cargs, **cparams)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
2024-03-30 23:41:02     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2024-03-30 23:41:02 psycopg2.OperationalError: could not translate host name "db" to address: Temporary failure in name resolution
2024-03-30 23:41:02 
2024-03-30 23:41:02 
2024-03-30 23:41:02 The above exception was the direct cause of the following exception:
2024-03-30 23:41:02 
2024-03-30 23:41:02 Traceback (most recent call last):
2024-03-30 23:41:02   File "/usr/local/bin/flask", line 8, in <module>
2024-03-30 23:41:02     sys.exit(main())
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1107, in main
2024-03-30 23:41:02     cli.main()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
2024-03-30 23:41:02     rv = self.invoke(ctx)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
2024-03-30 23:41:02     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
2024-03-30 23:41:02     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
2024-03-30 23:41:02     return ctx.invoke(self.callback, **ctx.params)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-03-30 23:41:02     return __callback(*args, **kwargs)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
2024-03-30 23:41:02     return f(get_current_context(), *args, **kwargs)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 388, in decorator
2024-03-30 23:41:02     return ctx.invoke(f, *args, **kwargs)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-03-30 23:41:02     return __callback(*args, **kwargs)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/flask_migrate/cli.py", line 154, in upgrade
2024-03-30 23:41:02     _upgrade(directory, revision, sql, tag, x_arg)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 111, in wrapped
2024-03-30 23:41:02     f(*args, **kwargs)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 200, in upgrade
2024-03-30 23:41:02     command.upgrade(config, revision, sql=sql, tag=tag)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
2024-03-30 23:41:02     script.run_env()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
2024-03-30 23:41:02     util.load_python_file(self.dir, "env.py")
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
2024-03-30 23:41:02     module = load_module_py(module_id, path)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
2024-03-30 23:41:02     spec.loader.exec_module(module)  # type: ignore
2024-03-30 23:41:02   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-03-30 23:41:02   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-03-30 23:41:02   File "/app/api/migrations/env.py", line 112, in <module>
2024-03-30 23:41:02     run_migrations_online()
2024-03-30 23:41:02   File "/app/api/migrations/env.py", line 96, in run_migrations_online
2024-03-30 23:41:02     with connectable.connect() as connection:
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
2024-03-30 23:41:02     return self._connection_cls(self, close_with_result=close_with_result)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
2024-03-30 23:41:02     else engine.raw_connection()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
2024-03-30 23:41:02     return self._wrap_pool_connect(self.pool.connect, _connection)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
2024-03-30 23:41:02     Connection._handle_dbapi_exception_noconnection(
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
2024-03-30 23:41:02     util.raise_(
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2024-03-30 23:41:02     raise exception
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
2024-03-30 23:41:02     return fn()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
2024-03-30 23:41:02     return _ConnectionFairy._checkout(self)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
2024-03-30 23:41:02     fairy = _ConnectionRecord.checkout(pool)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
2024-03-30 23:41:02     rec = pool._do_get()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
2024-03-30 23:41:02     with util.safe_reraise():
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2024-03-30 23:41:02     compat.raise_(
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2024-03-30 23:41:02     raise exception
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
2024-03-30 23:41:02     return self._create_connection()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
2024-03-30 23:41:02     return _ConnectionRecord(self)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
2024-03-30 23:41:02     self.__connect()
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
2024-03-30 23:41:02     with util.safe_reraise():
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2024-03-30 23:41:02     compat.raise_(
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2024-03-30 23:41:02     raise exception
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
2024-03-30 23:41:02     self.dbapi_connection = connection = pool._invoke_creator(self)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
2024-03-30 23:41:02     return dialect.connect(*cargs, **cparams)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
2024-03-30 23:41:02     return self.dbapi.connect(*cargs, **cparams)
2024-03-30 23:41:02   File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
2024-03-30 23:41:02     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2024-03-30 23:41:02 sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "db" to address: Temporary failure in name resolution
2024-03-30 23:41:02 
2024-03-30 23:41:02 (Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by crazywoola** [comment]
Please check you command and configure the docker network according to your needs. This error typically means the `api-1` can not reach to the `db` in same network. So you need to create a network bridge I think.
