### ISSUE TITLE
[chatglm] Server Unavailable Error, Internal Server Error

### ISSUE THREAD

**Issue by zps-509** [langgenius/dify#3066]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1.  DIFY 接入  chatglm3 , 基础助手，可以正常对话。
2.   搭建 stable diffusion ，可以正常出图
3.  DIFY 智能助手 接入 stable diffuion ，可以正常出图，但是出图后，马上图片消失，且报错[chatglm] Server Unavailable Error, Internal Server Error
![chatglm 报错](https://github.com/langgenius/dify/assets/109783453/fd93d685-5bb6-4691-ad05-67fe5a96b3f7)

**Comment by zps-509** [comment]
我刚刚在  https://udify.app/chat/VfbjY8kvFH76I3CA  配置同一个 chatglm 和同一个 stable diffusion成功了。可以生成图片，没有报错。。
但是在私有化 docker 部署的里面还是一样，使用的同样的方法。会生成图片，但是一下就会报错，图片没了。

**Comment by zps-509** [comment]
INFO:httpx:HTTP Request: GET http://192.168.133.98:20009/sdapi/v1/sd-models "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://192.168.133.98:55555/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET http://192.168.133.98:20009/sdapi/v1/sd-models "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://192.168.133.98:55555/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 0.957732 seconds
INFO:httpx:HTTP Request: POST http://192.168.133.98:55555/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 1.993984 seconds
INFO:httpx:HTTP Request: POST http://192.168.133.98:55555/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
ERROR:core.application_manager:Unknown Error when generating
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 96, in invoke
    result = self._invoke(model, credentials, prompt_messages, model_parameters, tools, stop, stream, user)
  File "/app/api/core/model_runtime/model_providers/chatglm/llm/llm.py", line 66, in _invoke
    return self._generate(
  File "/app/api/core/model_runtime/model_providers/chatglm/llm/llm.py", line 176, in _generate
    result = client.chat.completions.create(
  File "/usr/local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 897, in request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/core/application_manager.py", line 173, in _generate_worker
    runner.run(
  File "/app/api/core/app_runner/assistant_app_runner.py", line 248, in run
    self._handle_invoke_result(
  File "/app/api/core/app_runner/app_runner.py", line 230, in _handle_invoke_result
    self._handle_invoke_result_stream(
  File "/app/api/core/app_runner/app_runner.py", line 263, in _handle_invoke_result_stream
    for result in invoke_result:
  File "/app/api/core/features/assistant_fc_runner.py", line 111, in run
    chunks: Union[Generator[LLMResultChunk, None, None], LLMResult] = model_instance.invoke_llm(
  File "/app/api/core/model_manager.py", line 70, in invoke_llm
    return self.model_type_instance.invoke(
  File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 111, in invoke
    raise self._transform_invoke_error(e)
core.model_runtime.errors.invoke.InvokeServerUnavailableError: [chatglm] Server Unavailable Error, Internal Server Error


这个是 docker_api  的日志，请帮忙看下怎么处理

**Comment by zps-509** [comment]
[root@localhost docker]$ curl -X POST "http://192.168.133.98:55555/v1/chat/completions" -H "Content-Type: application/json" -d "{\"model\": \"chatglm3-6b\", \"messages\": [{\"role\": \"system\", \"content\": \"\"}, {\"role\": \"user\", \"content\": \"hello Word\"}], \"stream\": false, \"max_tokens\": 100, \"temperature\": 0.8, \"top_p\": 0.8}"
 
{"model":"chatglm3-6b","object":"chat.completion","choices":[{"index":0,"message":{"role":"assistant","content":"Hello! How can I assist you today?","name":null,"function_call":null},"finish_reason":"stop"}],"created":1711979906,"usage":{"prompt_tokens":11,"total_tokens":23,"completion_tokens":12}}

**Comment by zps-509** [comment]
我切换成   XInference   ，可以正常调取tools，没有报错。
但是我的 “提示词”，感觉失效了。
请问这个是什么回事呢 ？

**Comment by zps-509** [comment]
1. 我使用 chatglm3作为LLM，提示词里面说“你是一个客服，你叫XX”，然后跟他对话，问他‘你是谁’，他回复我“我是XX客服，有什么可以帮助你的”
2. 我使用  XInference 里面的chatglm3作为LLM, 提示词一样，然后跟他对话，问他‘你是谁’，他回答我 ‘我是一个名为 ChatGLM3-6B 的人工智能助手’

以上操作对比，感觉使用  XInference之后，提示词失效了。

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
