### ISSUE TITLE
An error message is displayed after the knowledge base file is uploaded

### ISSUE THREAD

**Issue by JackHu1120** [langgenius/dify#3145]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

 consume document failed
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/gevent/_socketcommon.py", line 590, in connect
    self._internal_connect(address)
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/gevent/_socketcommon.py", line 634, in _internal_connect
    raise _SocketError(err, strerror(err))
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3d47c11550>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/meta (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3d47c11550>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/headless/Desktop/dify/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 40, in _init_client
    client = weaviate.Client(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/weaviate/client.py", line 150, in __init__
    self._connection = Connection(
                       ^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/weaviate/connect/connection.py", line 654, in __init__
    self._server_version = self.get_meta()["version"]
                           ^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/weaviate/connect/connection.py", line 675, in get_meta
    response = self.get(path="/meta")
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/weaviate/connect/connection.py", line 516, in get
    return self._session.get(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/meta (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3d47c11550>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/headless/Desktop/dify/api/core/indexing_runner.py", line 72, in run
    self._load(
  File "/headless/Desktop/dify/api/core/indexing_runner.py", line 670, in _load
    tokens += future.result()
              ^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/anaconda3/envs/dify/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/Desktop/dify/api/core/indexing_runner.py", line 703, in _process_chunk
    index_processor.load(dataset, chunk_documents)
  File "/headless/Desktop/dify/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 59, in load
    vector = Vector(dataset)
             ^^^^^^^^^^^^^^^
  File "/headless/Desktop/dify/api/core/rag/datasource/vdb/vector_factory.py", line 23, in __init__
    self._vector_processor = self._init_vector()
                             ^^^^^^^^^^^^^^^^^^^
  File "/headless/Desktop/dify/api/core/rag/datasource/vdb/vector_factory.py", line 48, in _init_vector
    return WeaviateVector(
           ^^^^^^^^^^^^^^^
  File "/headless/Desktop/dify/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 31, in __init__
    self._client = self._init_client(config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/headless/Desktop/dify/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 47, in _init_client
    raise ConnectionError("Vector database connection error")
ConnectionError: Vector database connection error
![image](https://github.com/langgenius/dify/assets/129717356/03ebc7b6-d862-4cbe-a41e-cc5abea572d5)

**Comment by crazywoola** [comment]
This is a general network question.

>  HTTPConnectionPool(host='localhost', port=8080)

Please check your api and worker process can access this location as expected.
