### ISSUE TITLE
when run 'flask db upgrade', but get an error: ModuleNotFoundError: No module named 'gevent'

### ISSUE THREAD

**Issue by chenj-freedom** [langgenius/dify#3162]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

main

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

`
> flask db upgrade
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/Users/andrew.chen/Documents/workspaces/others/dify/api/app.py", line 6, in <module>
    from gevent import monkey
ModuleNotFoundError: No module named 'gevent'
`

I have installed gevent as follows:
`
pip list | grep gevent
gevent 23.9.1
`

And I directly executed 'import gevent' in the Python interactive command line without any error. However, I'm not sure why executing 'flask db upgrade' is causing an error.

**Comment by chenj-freedom** [comment]
![image](https://github.com/langgenius/dify/assets/16769793/1f6d75ff-7d1a-44b6-824f-94afcd6ffdbe)
I try the command pip install -r requirements.txt --upgrade, and then run 'flask db upgrade', still have this issue.

**Comment by chenj-freedom** [comment]
If I use Python version 3.10, I encounter the following error when executing `pip install -r requirements.txt --upgrade`, but if I switch to Python version 3.11.7, the problem disappears.

<img width="1768" alt="image" src="https://github.com/langgenius/dify/assets/16769793/18e24e8c-fdbe-4eb2-811c-9155932b742c">

By the way, I'm using macOS environment, not sure if this is a macOS-specific issue.

**Comment by crazywoola** [comment]
I am use MacOS as well. It seems your deps is broken while install the required package such as protobuf.  I think you can reinstall this one.

<img width="728" alt="image" src="https://github.com/langgenius/dify/assets/100913391/d46def2e-dbbd-47b2-a1a1-9f205d41d964">

**Comment by chenj-freedom** [comment]
> ![image](https://private-user-images.githubusercontent.com/16769793/320442867-1f6d75ff-7d1a-44b6-824f-94afcd6ffdbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDE2MzIsIm5iZiI6MTcxMjY0MTMzMiwicGF0aCI6Ii8xNjc2OTc5My8zMjA0NDI4NjctMWY2ZDc1ZmYtN2QxYS00NGI2LTgyNGYtOTRhZmNkNmZmZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA1NDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZTI3ODdlMjc0ZDliNzA5NjU4ZjVkNWVhNmRiMGI2MDUzZmE2ZjJiODgyMGFhMjU2MzU5Njc3ZTBkZTJlM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BwA5iB-wxj_Qa5L2z86K-jXpTQH_DFvjcfh_0Ks6kS0) I try the command pip install -r requirements.txt --upgrade, and then run 'flask db upgrade', still have this issue.

For this error with `flask db upgrade`, I have found a solution. It seems that the system environment variable PATH wasn't being found.
You can configure the env variable PATH for a specific conda env using the command:
`conda env config vars set PATH=/opt/anaconda3/envs/dify/lib/python3.11/site-packages:$PATH
`
Then please exit and re-enter the conda environment to make the changes permanent.
You can verify the changes using the command:
`conda env config vars list
`

**Comment by tobiasoberrauch** [comment]
The problem solved by deactivating and activating the env like this
`
conda deactivate 
conda activate dify 
`
