### ISSUE TITLE
got invalid_request_error  when use   gpt-4-vision-preview 

### ISSUE THREAD

**Issue by infometa** [langgenius/dify#3165]
### Self Checks

- [x] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Create an  Assistant with  gpt-4-vision-preview model  and knowledgebase . after upload the image got and send the message  got the error message
{'error': {'message': 'Invalid chat format. Unexpected keys in messages.', 'type': 'invalid_request_error', 'param': None, 'code': None}\

```docker logs
api-1       | INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 400 Bad Request"
api-1       | ERROR:core.application_manager:Unknown Error when generating
api-1       | Traceback (most recent call last):
api-1       |   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 96, in invoke
api-1       |     result = self._invoke(model, credentials, prompt_messages, model_parameters, tools, stop, stream, user)
api-1       |   File "/app/api/core/model_runtime/model_providers/openai/llm/llm.py", line 74, in _invoke
api-1       |     return self._chat_generate(
api-1       |   File "/app/api/core/model_runtime/model_providers/openai/llm/llm.py", line 551, in _chat_generate
api-1       |     response = client.chat.completions.create(
api-1       |   File "/usr/local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
api-1       |     return func(*args, **kwargs)
api-1       |   File "/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 667, in create
api-1       |     return self._post(
api-1       |   File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1208, in post
api-1       |     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
api-1       |   File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 897, in request
api-1       |     return self._request(
api-1       |   File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 988, in _request
api-1       |     raise self._make_status_error_from_response(err.response) from None
api-1       | openai.BadRequestError: Error code: 400 - {'error': {'message': 'Invalid chat format. Unexpected keys in messages.', 'type': 'invalid_request_error', 'param': None, 'code': None}}
api-1       | 
api-1       | During handling of the above exception, another exception occurred:
api-1       | 
api-1       | Traceback (most recent call last):
api-1       |   File "/app/api/core/application_manager.py", line 173, in _generate_worker
api-1       |     runner.run(
api-1       |   File "/app/api/core/app_runner/assistant_app_runner.py", line 248, in run
api-1       |     self._handle_invoke_result(
api-1       |   File "/app/api/core/app_runner/app_runner.py", line 230, in _handle_invoke_result
api-1       |     self._handle_invoke_result_stream(
api-1       |   File "/app/api/core/app_runner/app_runner.py", line 263, in _handle_invoke_result_stream
api-1       |     for result in invoke_result:
api-1       |   File "/app/api/core/features/assistant_cot_runner.py", line 137, in run
api-1       |     chunks: Generator[LLMResultChunk, None, None] = model_instance.invoke_llm(
api-1       |   File "/app/api/core/model_manager.py", line 70, in invoke_llm
api-1       |     return self.model_type_instance.invoke(
api-1       |   File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 111, in invoke
api-1       |     raise self._transform_invoke_error(e)
api-1       | core.model_runtime.errors.invoke.InvokeBadRequestError: [openai] Bad Request Error, Error code: 400 - {'error': {'message': 'Invalid chat format. Unexpected keys in messages.', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)

**Comment by songst** [comment]
I also encountered this issue. How was it resolved? Need help.

---------------------------------
Run failed: [models] Bad Request Error, Error code: 400 - {'error': {'message': 'Invalid chat format. Content blocks are expected to be either text or image_url type.', 'type': 'invalid_request_error', 'param': None, 'code': None}}
