### ISSUE TITLE
0.6.0 version not work.

### ISSUE THREAD

**Issue by jtsang4** [langgenius/dify#3175]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

It can be reproduced by starting with the `docker-compose.yaml` file provided in the repo.

### ✔️ Expected Behavior

Start app.

### ❌ Actual Behavior

```
docker-api-1       | Traceback (most recent call last):
docker-api-1       |   File "/usr/local/bin/flask", line 8, in <module>
docker-api-1       |     sys.exit(main())
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1105, in main
docker-api-1       |     cli.main()
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
docker-api-1       |     rv = self.invoke(ctx)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1682, in invoke
docker-api-1       |     cmd_name, cmd, args = self.resolve_command(ctx, args)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1729, in resolve_command
docker-api-1       |     cmd = self.get_command(ctx, cmd_name)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 611, in get_command
docker-api-1       |     app = info.load_app()
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 335, in load_app
docker-api-1       |     app = locate_app(import_name, name)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
docker-api-1       |     __import__(module_name)
docker-api-1       |   File "/app/api/app.py", line 192, in <module>
docker-api-1       |     app = create_app()
docker-api-1       |   File "/app/api/app.py", line 91, in create_app
docker-api-1       |     register_blueprints(app)
docker-api-1       |   File "/app/api/app.py", line 151, in register_blueprints
docker-api-1       |     from controllers.console import bp as console_app_bp
docker-api-1       |   File "/app/api/controllers/console/__init__.py", line 10, in <module>
docker-api-1       |     from .app import (advanced_prompt_template, annotation, app, audio, completion, conversation, generator, message,
docker-api-1       |   File "/app/api/controllers/console/app/app.py", line 19, in <module>
docker-api-1       |     from services.app_service import AppService
docker-api-1       |   File "/app/api/services/app_service.py", line 20, in <module>
docker-api-1       |     from services.workflow_service import WorkflowService
docker-api-1       |   File "/app/api/services/workflow_service.py", line 11, in <module>
docker-api-1       |     from core.workflow.workflow_engine_manager import WorkflowEngineManager
docker-api-1       |   File "/app/api/core/workflow/workflow_engine_manager.py", line 14, in <module>
docker-api-1       |     from core.workflow.nodes.code.code_node import CodeNode
docker-api-1       |   File "/app/api/core/workflow/nodes/code/code_node.py", line 12, in <module>
docker-api-1       |     MIN_NUMBER = int(os.environ.get('CODE_MIN_NUMBER', '-9223372036854775808'))
docker-api-1       | ValueError: invalid literal for int() with base 10: '-9.223372036854776e+18'
docker-api-1       | Running migrations
docker-api-1       | None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
```

**Comment by jtsang4** [comment]
Maybe because I'm upgrading to 0.6.0 from 0.5.11-fix1 so I meet this problem? Do I need to provide any info else to make the reproduction?

**Comment by jtsang4** [comment]
Sorry for disturbing you guys, according to your response `cant-repdocuce`, I find out it is because my VSCode formatter automatically update the `CODE_MAX_NUMBER` enviromment variable from `9223372036854775807` to `9223372036854776000` just like [this problem](https://stackoverflow.com/questions/8104391/why-do-javascript-converts-some-number-values-automatically), after I revert this value it works now.

**Comment by wencan** [comment]
我也遇到了这问题
重新格式化一下，值就变了
