### ISSUE TITLE
RangeError: Incorrect locale information provided

### ISSUE THREAD

**Issue by amizzo87** [langgenius/dify#3210]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.0-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Update from 0.5.11-fx1 to 0.6.0.

### ✔️ Expected Behavior

Dify to start seccessfully.

### ❌ Actual Behavior

Could this be a regression / similar problem to [this issue](https://github.com/langgenius/dify/issues/1396)?

```
2024-04-09T05:08:33.550860944Z 05:08:33 1|dify-web  | RangeError: Incorrect locale information provided
2024-04-09T05:08:33.551848751Z 05:08:33 1|dify-web  |     at Intl.getCanonicalLocales (<anonymous>)
2024-04-09T05:08:33.552301402Z 05:08:33 1|dify-web  |     at o (/app/web/.next/server/chunks/3384.js:43:7624)
2024-04-09T05:08:33.552745046Z 05:08:33 1|dify-web  |     at y (/app/web/.next/server/chunks/2518.js:104:49578)
2024-04-09T05:08:33.553150348Z 05:08:33 1|dify-web  |     at u (/app/web/.next/server/app/(commonLayout)/apps/page.js:1:19386)
2024-04-09T05:08:33.553530563Z 05:08:33 1|dify-web  |     at em (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:128334)
2024-04-09T05:08:33.554158964Z 05:08:33 1|dify-web  |     at /app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140034
2024-04-09T05:08:33.554725429Z 05:08:33 1|dify-web  |     at Array.toJSON (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143612)
2024-04-09T05:08:33.555084925Z 05:08:33 1|dify-web  |     at stringify (<anonymous>)
2024-04-09T05:08:33.555868247Z 05:08:33 1|dify-web  |     at eE (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131997)
2024-04-09T05:08:33.556975769Z 05:08:33 1|dify-web  |     at eR (/app/web/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132440)
2024-04-09T05:08:33.562960972Z 05:08:33 1|dify-web  | [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.]
```

**Comment by crazywoola** [comment]
Please clear browser cache and switch to English and switch it back to see if this error persists.

**Comment by amizzo87** [comment]
Ah my bad - it was the cache, d'oh! Thanks for the help :)
