### ISSUE TITLE
When using qwen-14b and chatglm3-6b for multi-model debugging, an error occurred with chatglm3-6b. 

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#3267]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.5.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

qwen-14b and chatglm3-6b are custom large models managed by xinference.

- 截图
![112](https://github.com/langgenius/dify/assets/21255047/da678490-d629-4652-98f4-90ddc5f1ae66)

- 错误日志
```
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:openai._base_client:HTTP Request: POST http://127.0.0.1:59997/v1/chat/completions "500 Internal Server Error"
DEBUG:openai._base_client:Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://127.0.0.1:59997/v1/chat/completions'
For more information check: https://httpstatuses.com/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://127.0.0.1:59997/v1/chat/completions'
For more information check: https://httpstatuses.com/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://127.0.0.1:59997/v1/chat/completions'
For more information check: https://httpstatuses.com/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://127.0.0.1:59997/v1/chat/completions'
For more information check: https://httpstatuses.com/500
DEBUG:openai._base_client:Re-raising status error
ERROR:core.application_manager:Unknown Error when generating
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 96, in invoke
    result = self._invoke(model, credentials, prompt_messages, model_parameters, tools, stop, stream, user)
  File "/app/api/core/model_runtime/model_providers/xinference/llm/llm.py", line 79, in _invoke
    return self._generate(
  File "/app/api/core/model_runtime/model_providers/xinference/llm/llm.py", line 413, in _generate
    resp = client.chat.completions.create(
  File "/usr/local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 897, in request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'detail': '[address=127.0.0.1:34773, pid=24418] 0'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/core/application_manager.py", line 173, in _generate_worker
    runner.run(
  File "/app/api/core/app_runner/assistant_app_runner.py", line 248, in run
    self._handle_invoke_result(
  File "/app/api/core/app_runner/app_runner.py", line 230, in _handle_invoke_result
    self._handle_invoke_result_stream(
  File "/app/api/core/app_runner/app_runner.py", line 263, in _handle_invoke_result_stream
    for result in invoke_result:
  File "/app/api/core/features/assistant_fc_runner.py", line 111, in run
    chunks: Union[Generator[LLMResultChunk, None, None], LLMResult] = model_instance.invoke_llm(
  File "/app/api/core/model_manager.py", line 70, in invoke_llm
    return self.model_type_instance.invoke(
  File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 111, in invoke
    raise self._transform_invoke_error(e)
core.model_runtime.errors.invoke.InvokeServerUnavailableError: [xinference] Server Unavailable Error, Error code: 500 - {'detail': '[address=127.0.0.1:34773, pid=24418] 0'}
DEBUG:core.app_runner.generate_task_pipeline:error: [xinference] Server Unavailable Error, Error code: 500 - {'detail': '[address=127.0.0.1:34773, pid=24418] 0'}
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
```

**Comment by andylzming** [comment]
> This issue is caused by xinference returning a `Server Unavailable Error` exception.

- xinference 错误日志

```
 技能2：使用 ‘GetFreeDayData’ 召测用户电表日冻结数据\n\n## 工作流程\n- 根据用户输入的用户户号和数据项ID作为条件，召测相关数据。若用户未提供相关信息，请询问用户提供。\n<|user|>\n 你好。\n<|assistant|>', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.01, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|user|>', '<|observation|>'], stop_token_ids=[64795, 64797, 2], include_stop_str_in_output=False, ignore_eos=False, max_tokens=512, logprobs=None, prompt_logprobs=None, skip_special_t
```

**Comment by takatost** [comment]
I've already talked to the xorbits team, they will fix it soon.

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
