### ISSUE TITLE
local variable 'docs' referenced before assignment

### ISSUE THREAD

**Issue by liuzhenghua** [langgenius/dify#3312]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

upload some csv file when create a knowleage

### ✔️ Expected Behavior

Document status is Available

### ❌ Actual Behavior

Document status is Error

**Comment by liuzhenghua** [comment]
[2024-04-10 08:36:58,393: ERROR/MainProcess] consume document failed
Traceback (most recent call last):
  File "/app/api/core/indexing_runner.py", line 64, in run
    text_docs = self._extract(index_processor, dataset_document, processing_rule.to_dict())
  File "/app/api/core/indexing_runner.py", line 362, in _extract
    text_docs = index_processor.extract(extract_setting, process_rule_mode=process_rule['mode'])
  File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 21, in extract
    text_docs = ExtractProcessor.extract(extract_setting=extract_setting,
  File "/app/api/core/rag/extractor/extract_processor.py", line 129, in extract
    return extractor.extract()
  File "/app/api/core/rag/extractor/csv_extractor.py", line 53, in extract
    return docs
UnboundLocalError: local variable 'docs' referenced before assignment
