### ISSUE TITLE
"[xinference] Server Unavailable Error, Internal Server Error" in workflow

### ISSUE THREAD

**Issue by liuzhenghua** [langgenius/dify#3315]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. create a workflow from template "三步翻译工作流"
2. change the llm provider to qwen1.5-chat which provided by xinference.
3. click the run button

the model is ok in chat bot.
![Uploading image.png…]()

### ✔️ Expected Behavior

execute success.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/11787325/a7cddc14-43af-4468-8740-06b9dcf934fd)

**Comment by liuzhenghua** [comment]
Internal Server Error
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 96, in invoke
    result = self._invoke(model, credentials, prompt_messages, model_parameters, tools, stop, stream, user)
  File "/app/api/core/model_runtime/model_providers/xinference/llm/llm.py", line 79, in _invoke
    return self._generate(
  File "/app/api/core/model_runtime/model_providers/xinference/llm/llm.py", line 413, in _generate
    resp = client.chat.completions.create(
  File "/usr/local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 897, in request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None

**Comment by liuzhenghua** [comment]
but no logs in xinference

**Comment by andylzming** [comment]
The same problem。

![112](https://github.com/langgenius/dify/assets/21255047/e612ff70-d6a8-4a51-9345-acb5814b1fb5)


- dify logs

```
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 500, b'Internal Server Error', [(b'date', b'Thu, 11 Apr 2024 20:12:17 GMT'), (b'server', b'uvicorn'), (b'content-length', b'21'), (b'content-type', b'text/plain; charset=utf-8')])
INFO:httpx:HTTP Request: POST http://127.0.0.1:59997/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
DEBUG:openai._base_client:HTTP Request: POST http://127.0.0.1:59997/v1/chat/completions "500 Internal Server Error"
DEBUG:openai._base_client:Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://127.0.0.1:59997/v1/chat/completions'
For more information check: https://httpstatuses.com/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://127.0.0.1:59997/v1/chat/completions'
For more information check: https://httpstatuses.com/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://127.0.0.1:59997/v1/chat/completions'
For more information check: https://httpstatuses.com/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 967, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://127.0.0.1:59997/v1/chat/completions'
For more information check: https://httpstatuses.com/500
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:openai._base_client:Re-raising status error
DEBUG:core.app.task_pipeline.based_generate_task_pipeline:error: Run failed: Node LLM run failed: [xinference] Server Unavailable Error, Internal Server Error

```

- xinference logs

```
INFO 04-11 16:12:11 async_llm_engine.py:379] Received request c7c6bb42-f83f-11ee-8eb7-80615f20f615: prompt: '<|im_start|>system\n\n    ### Job Description\',\n    You are a text classification engine that analyzes text data and assigns categories based on user input or automatically determined categories.\n    ### Task\n    Your task is to assign one categories ONLY to the input text and only one category may be assigned returned in the output.Additionally, you need to extract the key words from the text that are related to the classification.\n    ### Format\n    The input text is in the variable text_field.Categories are specified as a comma-separated list in the variable categories or left empty for automatic determination.Classification instructions may be included to improve the classification accuracy.\n    ### Constraint\n    DO NOT include anything other than the JSON array in your response.\n    ### Memory\n    Here is the chat histories between human and assistant, inside <histories></histories> XML tags.\n    <histories>\n    \n    </histories>\n<|im_end|>\n<|im_start|>user\n    { "input_text": ["I recently had a great experience with your company. The service was prompt and the staff was very friendly."],\n    "categories": ["Customer Service, Satisfaction, Sales, Product"],\n    "classification_instructions": ["classify the text based on the feedback provided by customer"]}```JSON<|im_end|>\n<|im_start|>assistant\n    {"keywords": ["recently", "great experience", "company", "service", "prompt", "staff", "friendly"],\n    "categories": ["Customer Service"]}```<|im_end|>\n<|im_start|>user\n    {"input_text": ["bad service, slow to bring the food"],\n    "categories": ["Food Quality, Experience, Price" ], \n    "classification_instructions": []}```JSON<|im_end|>\n<|im_start|>assistant\n    {"keywords": ["bad service", "slow", "food", "tip", "terrible", "waitresses"],\n    "categories": ["Experience""]}```<|im_end|>\n<|im_start|>user\n    \'{"input_text": ["电量计算"],\',\n    \'"categories": ["电量计算,其他" ], \',\n    \'"classification_instructions": [""]}```JSON\'<|im_end|>\n<|im_start|>assistant\n', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.5, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|endoftext|>', '<|im_start|>', '<|im_end|>'], stop_token_ids=[151643, 151644, 151645], include_stop_str_in_output=False, ignore_eos=False, max_tokens=6801, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: None.
INFO 04-11 16:12:11 llm_engine.py:653] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%
INFO 04-11 16:12:11 async_llm_engine.py:111] Finished request c7c6bb42-f83f-11ee-8eb7-80615f20f615.
```

**Comment by hunterhome** [comment]
Traceback (most recent call last):
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
    await self.asgi_callable(scope, receive, wrapped_send)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/rjsoft/anaconda3/envs/xinference/lib/python3.9/site-packages/xinference/api/restful_api.py", line 1285, in create_chat_completion
    assert non_system_messages
AssertionError

**Comment by liuzhenghua** [comment]
while no 'user' role input, xinference returns 500
![image](https://github.com/langgenius/dify/assets/11787325/4ba0e8e7-cdc8-4838-825e-0cb940f373d4)

**Comment by liuzhenghua** [comment]
![image](https://github.com/langgenius/dify/assets/11787325/c8a85450-fcbc-4e42-bd84-c3a638658c22)

**Comment by liuzhenghua** [comment]
If I add USER msg in wokflow node, it works.
![image](https://github.com/langgenius/dify/assets/11787325/c4124099-81ab-41fe-bf01-f756f972da9a)
![image](https://github.com/langgenius/dify/assets/11787325/f8c32fc7-1730-4ff2-aa48-5df6124d7103)

**Comment by liuzhenghua** [comment]
It would be fixed by xinference

**Comment by JokerQyou** [comment]
Just figured out myself, at least a single message of `user` role is required to call a `chat` model (tested with Qwen series). If using text generation model this would not be necessary.
