### ISSUE TITLE
An error occurred during login to the console

### ISSUE THREAD

**Issue by puleiC** [langgenius/dify#3359]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.1

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

INFO:root:Account 70ac5238-d66a-4c05-8c4c-0eaf5132379c logged in successfully.
ERROR:app:Exception on /console/api/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 84, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/auth/login.py", line 37, in post
    token = AccountService.get_account_jwt_token(account)
  File "/app/api/services/account_service.py", line 78, in get_account_jwt_token
    token = PassportService().issue(payload)
  File "/app/api/libs/passport.py", line 11, in issue
    return jwt.encode(payload, self.sk, algorithm='HS256')
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 73, in encode
    return api_jws.encode(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 160, in encode
    key = alg_obj.prepare_key(key)
  File "/usr/local/lib/python3.10/site-packages/jwt/algorithms.py", line 265, in prepare_key
    key_bytes = force_bytes(key)
  File "/usr/local/lib/python3.10/site-packages/jwt/utils.py", line 22, in force_bytes
    raise TypeError("Expected a string value")
TypeError: Expected a string value
INFO:root:Account 70ac5238-d66a-4c05-8c4c-0eaf5132379c logged in successfully.
ERROR:app:Exception on /console/api/login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 84, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/auth/login.py", line 37, in post
    token = AccountService.get_account_jwt_token(account)
  File "/app/api/services/account_service.py", line 78, in get_account_jwt_token
    token = PassportService().issue(payload)
  File "/app/api/libs/passport.py", line 11, in issue
    return jwt.encode(payload, self.sk, algorithm='HS256')
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 73, in encode
    return api_jws.encode(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 160, in encode
    key = alg_obj.prepare_key(key)
  File "/usr/local/lib/python3.10/site-packages/jwt/algorithms.py", line 265, in prepare_key
    key_bytes = force_bytes(key)
  File "/usr/local/lib/python3.10/site-packages/jwt/utils.py", line 22, in force_bytes
    raise TypeError("Expected a string value")
TypeError: Expected a string value

**Comment by puleiC** [comment]
> 嘿，@puleiC！ 🚀 我是 Dosu，您友好的机器人，可以帮助您解决错误、回答问题并进入贡献的世界！当我们等待人类维护人员时，我会为您提供支持。 😎 让我们深入研究这个问题，看看发生了什么。我会立即回来为您提供完整的答案！

I used the douban/dify helm for deployment

**Comment by puleiC** [comment]
It has nothing to do with my configuration is it a code level problem?

**Comment by crazywoola** [comment]
@LeoQuote Please take a look at this one :)

**Comment by puleiC** [comment]
Is this because the following code is missing?  extraBackendEnvs: []  
  # - name: SECRET_KEY  
  #   value: xxx   

> @LeoQuote Please take a look at this one :)

**Comment by LeoQuote** [comment]
There's **nothing** I can do to help you, the helm chart is only providing a way to render yaml file, I see no clue about incorrect yaml render, please read the `Readme` or the helm chart code if you have any question.

an issue was also raised issue on https://github.com/douban/charts/issues/70 , but I think it's not the issue of helm chart.

**Comment by puleiC** [comment]
> There's **nothing** I can do to help you, the helm chart is only providing a way to render yaml file, I see no clue about incorrect yaml render, please read the `Readme` or the helm chart code if you have any question.
> 
> an issue was also raised issue on [douban/charts#70](https://github.com/douban/charts/issues/70) , but I think it's not the issue of helm chart.

The problem has been solved without this code values.yaml:
- name: SECRET_KEY
value: "***"
I hope you can comment this configuration as a must in a later version and add mail configuration

**Comment by crazywoola** [comment]
As the bot suggests, I think you need to check whether you have setup the `SECRET_KEY` correctly in `.env` file.

```
self.sk = current_app.config.get('SECRET_KEY')
```

**Comment by LeoQuote** [comment]
It is clearly stated in readme https://github.com/douban/charts/tree/master/charts/dify#install , pr are welcomed.

the minimal config I provided is 
```
global:
  host: "mydify.example.com"
  enableTLS: false

extraEnvs:
- name: SECRET_KEY
  value: "generate your own one"
- name: LOG_LEVEL
  value: "DEBUG"
- name: VECTOR_STORE
  value: "milvus"

ingress:
  enabled: true
  className: "nginx"

minio:
  embedded: true
```

**Comment by LeoQuote** [comment]
I updated the default value for SECRET_KEY 👆

Thanks for your feedback, I advice you first check the dify configure manul as I mentioned in the bottom of the readme, and prefer to consult to dify first, like the bot suggested, it found your configuration problem instantly while I have zero clue about it.

I also advice you read through the chart readme and apply changes for production use. The default configuration is suitable for experimentation but is a disaster for production.

**Comment by LeoQuote** [comment]
Also, maybe there should be a checker for the critical environment variable?  You can submit a pr for that check.
