### ISSUE TITLE
No answer responded and "ResourceWarning: Enable tracemalloc to get the object allocation traceback"

### ISSUE THREAD

**Issue by bowenliang123** [langgenius/dify#3487]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

main/0.6.2

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

vdb: weaviate

Updated to latest commit on main branch.

Query and no answer responded.

<img width="1246" alt="image" src="https://github.com/langgenius/dify/assets/1935105/1c371a7c-938a-4f30-98d7-9a89c51bbf5e">

### ❌ Actual Behavior

<img width="1203" alt="image" src="https://github.com/langgenius/dify/assets/1935105/3cb5acde-db0a-4705-9aa0-387f1f67a3c9">

error message
```
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=34, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=77, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=39, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=84, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=58, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ERROR:core.app.apps.chat.app_generator:Unknown Error when generating
Traceback (most recent call last):
  File "/app/api/core/app/apps/chat/app_generator.py", line 181, in _generate_worker
    runner.run(
  File "/app/api/core/app/apps/chat/app_runner.py", line 215, in run
    app_id=app_record.id,
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 487, in __get__
    return self.impl.get(state, dict_)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 959, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 990, in _fire_loader_callables
    return state._load_expired(state, passive)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/state.py", line 712, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 1369, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <App at 0x7f193911f280> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)
ERROR:root:Instance <App at 0x7f193911f280> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)
/app/api/core/provider_manager.py:612: ResourceWarning: unclosed <socket object, fd=30, family=2, type=1, proto=6>
  return SystemConfiguration(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/provider_manager.py:612: ResourceWarning: unclosed <socket object, fd=39, family=2, type=1, proto=6>
  return SystemConfiguration(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/provider_manager.py:612: ResourceWarning: unclosed <socket object, fd=34, family=2, type=1, proto=6>
  return SystemConfiguration(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/provider_manager.py:612: ResourceWarning: unclosed <socket object, fd=58, family=2, type=1, proto=6>
  return SystemConfiguration(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/provider_manager.py:612: ResourceWarning: unclosed <socket object, fd=36, family=2, type=1, proto=6>
  return SystemConfiguration(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=110, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=124, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=105, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=127, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=103, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/app/api/core/entities/provider_configuration.py:44: ResourceWarning: unclosed <socket object, fd=145, family=2, type=1, proto=6>
  super().__init__(**data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by crazywoola** [comment]
@dosu-bot give me a fix to this.

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)
