### ISSUE TITLE
Celery won't start on MacOs

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#3527]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Start Celery with "celery -A app.celery worker -P gevent -c 1 -Q dataset,generation,mail --loglevel INFO" on latest version

### ✔️ Expected Behavior

Celery has worked just fine up until now, don't know if its something I've done? Tried with fresh Enviroment in python aswell

### ❌ Actual Behavior

`Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app': 
Unable to load celery application.
While trying to load the module app.celery the following error occurred:
Traceback (most recent call last):
  File ".../site-packages/celery/bin/celery.py", line 58, in convert
    return find_app(value)
  File ".../site-packages/celery/app/utils.py", line 383, in find_app
    sym = symbol_by_name(app, imp=imp)
  File ".../site-packages/kombu/utils/imports.py", line 59, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File ".../site-packages/celery/utils/imports.py", line 109, in import_from_cwd
    return imp(module, package=package)
  File ".../importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File ".../api/app.py", line 8, in <module>
    import grpc.experimental.gevent
  File ".../site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File ".../site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(.../site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_CFDataGetBytes'
`

**Comment by takatost** [comment]
trying `pip install --upgrade -r requirements.txt`?

**Comment by AndyMik90** [comment]
> trying `pip install --upgrade -r requirements.txt`?

Yes, still same error.

Also tried with clean conda enviroment.

**Comment by AndyMik90** [comment]
Works after installing grpcio

**Comment by AndyMik90** [comment]
pip install --upgrade grpcio
