### ISSUE TITLE
Error uploading PDFs

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#3662]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When uploading PDFs I'm encountering internal server error

### ✔️ Expected Behavior

Has worked normally before with the same PDFs.

### ❌ Actual Behavior

The PDF gives error on both index estimate and the other steps, but when viewing the chunks it's actually indexed the PDF. But giving a whole lot of errors. Also the indexing status bar shows 0%, but going to the next it says "available" on the document.

Errors:

`2024-04-21 12:45:08.127 ERROR [Thread-68 (process_request_thread)] [app.py:838] - Exception on /console/api/datasets/3b43a5b7-96ce-4489-b16d-bf4cfdd88e86/batch/20240421124507938890/indexing-estimate [GET] Traceback (most recent call last): File "...lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request rv = self.dispatch_request() File "...lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return] File "...lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper resp = resource(*args, **kwargs) File "...lib/python3.10/site-packages/flask/views.py", line 110, in view return current_app.ensure_sync(self.dispatch_request)(**kwargs) # type: ignore[no-any-return] File "...lib/python3.10/site-packages/.../api/controllers/console/setup.py", line 86, in decorated return view(*args, **kwargs) File "...lib/python3.10/site-packages/.../api/libs/login.py", line 91, in decorated_view return current_app.ensure_sync(func)(*args, **kwargs) File "...lib/python3.10/site-packages/.../api/controllers/console/wraps.py", line 21, in decorated return view(*args, **kwargs) File "...lib/python3.10/site-packages/.../api/controllers/console/datasets/datasets_document.py", line 493, in get response = indexing_runner.indexing_estimate(current_user.current_tenant_id, extract_settings, File "...lib/python3.10/site-packages/.../api/core/indexing_runner.py", line 264, in indexing_estimate text_docs = index_processor.extract(extract_setting, process_rule_mode=tmp_processing_rule["mode"]) File "...lib/python3.10/site-packages/.../api/core/rag/index_processor/processor/paragraph_index_processor.py", line 21, in extract text_docs = ExtractProcessor.extract(extract_setting=extract_setting, File "...lib/python3.10/site-packages/.../api/core/rag/extractor/extract_processor.py", line 135, in extract return extractor.extract() File "...lib/python3.10/site-packages/.../api/core/rag/extractor/pdf_extractor.py", line 38, in extract documents = list(self.load()) File ".../api/core/rag/extractor/pdf_extractor.py", line 55, in load yield from self.parse(blob) File ".../api/core/rag/extractor/pdf_extractor.py", line 62, in parse pdf_reader = pypdfium2.PdfDocument(file_path, autoclose=True) File "...lib/python3.10/site-packages/pypdfium2/_helpers/document.py", line 81, in __init__ self.raw, to_hold, to_close = _open_pdf(self._input, self._password, self._autoclose) File "...lib/python3.10/site-packages/pypdfium2/_helpers/document.py", line 733, in _open_pdf raise PdfiumError(f"Failed to load document (PDFium: {pdfium_i.ErrorToStr.get(err_code)}).") pypdfium2._helpers.misc.PdfiumError: Failed to load document (PDFium: Data format error). 2024-04-21 12:45:08.128 INFO [Thread-68 (process_request_thread)] [_internal.py:96] - 127.0.0.1 - - [21/Apr/2024 12:45:08] "GET /console/api/datasets/3b43a5b7-96ce-4489-b16d-bf4cfdd88e86/batch/20240421124507938890/indexing-estimate HTTP/1.1" 500 -
`

**Comment by AndyMik90** [comment]
The problem is only happening using cohere embedding v.3.0
no problem with v.2.0

**Comment by AndyMik90** [comment]
This issue seems to be related to the latest MacOS version and not the Dify code, and will close it.
