### ISSUE TITLE
RangeError: Incorrect locale information provided

### ISSUE THREAD

**Issue by ppxiagogo** [langgenius/dify#3830]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.4

### Cloud or Self Hosted

Cloud, Self Hosted (Source)

### Steps to reproduce

RangeError: Incorrect locale information provided
    at Intl.getCanonicalLocales (<anonymous>)
    at p (/usr/local/ai/web/.next/standalone/.next/server/chunks/4599.js:43:35370)
    at b (/usr/local/ai/web/.next/standalone/.next/server/chunks/9734.js:107:49277)
    at M (/usr/local/ai/web/.next/standalone/.next/server/chunks/9734.js:107:44845)
    at eh (/usr/local/ai/web/.next/standalone/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134786)
    at e (/usr/local/ai/web/.next/standalone/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137671)
    at ek (/usr/local/ai/web/.next/standalone/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:138145)
    at Array.toJSON (/usr/local/ai/web/.next/standalone/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135755)
    at stringify (<anonymous>)
    at eR (/usr/local/ai/web/.next/standalone/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142219) {
  digest: '694571780'
}
<img width="452" alt="image" src="https://github.com/langgenius/dify/assets/37864392/4804c078-ccce-4ceb-9145-c5d623242e29">

I updated the dependency package。After deployment on the server, this error will be reported and crash in less than half an hour。

**Comment by crazywoola** [comment]
Duplicated #3726 Should be released soon.
