### ISSUE TITLE
PackageNotFoundError: Package not found at '/tmp/tmpob0j9912/ou_di5g8.docx

### ISSUE THREAD

**Issue by ryanwong2023** [langgenius/dify#3888]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.5

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After uploading the file and clicking the save&process button, an internal error occurred. The specific error message is: PackageNotFoundError: Package not found at '/tmp/tmpob0j9912/ou_di5g8.docx

**Comment by ryanwong2023** [comment]
2024-04-26 16:38:56 [2024-04-26 08:38:56,221: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[e711ba73-4465-45ec-8cb3-227bf573e700] received
2024-04-26 16:38:56 [2024-04-26 08:38:56,224: INFO/MainProcess] Start process document: 234cd502-f381-4be9-a65e-c035c6721dd5
2024-04-26 16:38:56 [2024-04-26 08:38:56,293: ERROR/MainProcess] consume document failed
2024-04-26 16:38:56 Traceback (most recent call last):
2024-04-26 16:38:56   File "/app/api/core/indexing_runner.py", line 64, in run
2024-04-26 16:38:56     text_docs = self._extract(index_processor, dataset_document, processing_rule.to_dict())
2024-04-26 16:38:56   File "/app/api/core/indexing_runner.py", line 362, in _extract
2024-04-26 16:38:56     text_docs = index_processor.extract(extract_setting, process_rule_mode=process_rule['mode'])
2024-04-26 16:38:56   File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 21, in extract
2024-04-26 16:38:56     text_docs = ExtractProcessor.extract(extract_setting=extract_setting,
2024-04-26 16:38:56   File "/app/api/core/rag/extractor/extract_processor.py", line 134, in extract
2024-04-26 16:38:56     return extractor.extract()
2024-04-26 16:38:56   File "/app/api/core/rag/extractor/word_extractor.py", line 51, in extract
2024-04-26 16:38:56     document = docx_Document(self.file_path)
2024-04-26 16:38:56   File "/usr/local/lib/python3.10/site-packages/docx/api.py", line 23, in Document
2024-04-26 16:38:56     document_part = Package.open(docx).main_document_part
2024-04-26 16:38:56   File "/usr/local/lib/python3.10/site-packages/docx/opc/package.py", line 116, in open
2024-04-26 16:38:56     pkg_reader = PackageReader.from_file(pkg_file)
2024-04-26 16:38:56   File "/usr/local/lib/python3.10/site-packages/docx/opc/pkgreader.py", line 22, in from_file
2024-04-26 16:38:56     phys_reader = PhysPkgReader(pkg_file)
2024-04-26 16:38:56   File "/usr/local/lib/python3.10/site-packages/docx/opc/phys_pkg.py", line 21, in __new__
2024-04-26 16:38:56     raise PackageNotFoundError("Package not found at '%s'" % pkg_file)
2024-04-26 16:38:56 docx.opc.exceptions.PackageNotFoundError: Package not found at '/tmp/tmpa9pd91rr/mwu5dks5.docx'
2024-04-26 16:38:56 [2024-04-26 08:38:56,297: INFO/MainProcess] Processed dataset: 1f79150d-e1de-438b-9ecc-8c2b493470b2 latency: 0.07531608099816367
2024-04-26 16:38:56 [2024-04-26 08:38:56,307: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[e711ba73-4465-45ec-8cb3-227bf573e700] succeeded in 0.0847187830004259

**Comment by crazywoola** [comment]
Please upgrade to latest version to see if this issue persists. :)

**Comment by TotalDom1Nation** [comment]
i have the same problem 
by using the latest version 
what should i do @crazywoola

**Comment by chinchilla-forest** [comment]
> i have the same problem by using the latest version what should i do [@crazywoola](https://github.com/crazywoola)

I am the same problem,and i have solve it. the reason is my file is docx ,but actually it's doc. dify doesn't support doc.You can use office or wps open file,and save to another docx file.

**Comment by ifun248** [comment]
Another solve solution: add a special handle at the ExtractProcessor.extract() for the docx file but actually being doc. Key codes are below:
```
if etl_type == "Unstructured":
    unstructured_api_url = dify_config.UNSTRUCTURED_API_URL or ""
    unstructured_api_key = dify_config.UNSTRUCTURED_API_KEY or ""

    if file_extension in {".xlsx", ".xls"}:
        extractor = ExcelExtractor(file_path)
    elif file_extension == ".pdf":
        extractor = PdfExtractor(file_path)
    elif file_extension in {".md", ".markdown", ".mdx"}:
        extractor = (
            UnstructuredMarkdownExtractor(file_path, unstructured_api_url, unstructured_api_key)
            if is_automatic
            else MarkdownExtractor(file_path, autodetect_encoding=True)
        )
    elif file_extension in {".htm", ".html"}:
        extractor = HtmlExtractor(file_path)
    elif file_extension == ".docx":
        extractor = WordExtractor(file_path, upload_file.tenant_id, upload_file.created_by)

        ### add a special handle here ###
        import os
        if os.path.isfile(file_path):
            extractor = UnstructuredWordExtractor(file_path, unstructured_api_url, unstructured_api_key)
```
Hope helps.
