### ISSUE TITLE
raise private key not found when set llm key

### ISSUE THREAD

**Issue by cjdxhjj** [langgenius/dify#4258]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.7

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

when i set the llm secret it report an error

### ❌ Actual Behavior

the docker report error
![image](https://github.com/langgenius/dify/assets/5616997/85089ecf-d5cf-44cc-9d57-a9685e001620)
![image](https://github.com/langgenius/dify/assets/5616997/1da98a51-ef10-4c7e-b6a0-a857d04d71dd)
![image](https://github.com/langgenius/dify/assets/5616997/66c05973-f275-4b5b-a87e-11841cad906b)
self host
![image](https://github.com/langgenius/dify/assets/5616997/01cd2872-52d5-4dc7-ae80-602697c7ef4e)

**Comment by cjdxhjj** [comment]
the dify 0.6.6 also report that error

**Comment by btnkr** [comment]
我有同样的问题
我发现在设置API Key后就会一直有这个问题
![image](https://github.com/langgenius/dify/assets/46664126/3d70888c-efca-4faf-8555-83966edfbb48)
```bash
2024-05-11 07:07:16.629 INFO [Thread-169 (process_request_thread)] [_internal.py:97] - 127.0.0.1 - - [11/May/2024 07:07:16] "OPTIONS /console/api/workspaces/current/model-providers HTTP/1.1" 200 -
2024-05-11 07:07:16.772 ERROR [Thread-171 (process_request_thread)] [app.py:838] - Exception on /console/api/workspaces/current/model-providers [GET]
Traceback (most recent call last):
  File "/home/anhao/project/dify/api/libs/rsa.py", line 55, in get_decrypt_decoding
    private_key = storage.load(filepath)
  File "/home/anhao/project/dify/api/extensions/ext_storage.py", line 45, in load
    return self.load_once(filename)
  File "/home/anhao/project/dify/api/extensions/ext_storage.py", line 48, in load_once
    return self.storage_runner.load_once(filename)
  File "/home/anhao/project/dify/api/extensions/storage/local_storage.py", line 40, in load_once
    raise FileNotFoundError("File not found")
FileNotFoundError: File not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/anhao/project/dify/api/controllers/console/setup.py", line 86, in decorated
    return view(*args, **kwargs)
  File "/home/anhao/project/dify/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/anhao/project/dify/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/home/anhao/project/dify/api/controllers/console/workspace/model_providers.py", line 33, in get
    provider_list = model_provider_service.get_provider_list(
  File "/home/anhao/project/dify/api/services/model_provider_service.py", line 46, in get_provider_list
    provider_configurations = self.provider_manager.get_configurations(tenant_id)
  File "/home/anhao/project/dify/api/core/provider_manager.py", line 118, in get_configurations
    custom_configuration = self._to_custom_configuration(
  File "/home/anhao/project/dify/api/core/provider_manager.py", line 509, in _to_custom_configuration
    self.decoding_rsa_key, self.decoding_cipher_rsa = encrypter.get_decrypt_decoding(tenant_id)
  File "/home/anhao/project/dify/api/core/helper/encrypter.py", line 29, in get_decrypt_decoding
    return rsa.get_decrypt_decoding(tenant_id)
  File "/home/anhao/project/dify/api/libs/rsa.py", line 57, in get_decrypt_decoding
    raise PrivkeyNotFoundError("Private key not found, tenant_id: {tenant_id}".format(tenant_id=tenant_id))
libs.rsa.PrivkeyNotFoundError: Private key not found, tenant_id: ea69b0eb-d3a8-421e-85c2-4310c3ee5c63
2024-05-11 07:07:16.804 INFO [Thread-171 (process_request_thread)] [_internal.py:97] - 127.0.0.1 - - [11/May/2024 07:07:16] "GET /console/api/workspaces/current/model-providers HTTP/1.1" 500 -
```
```bash
2024-05-11 07:07:16.936 INFO [Thread-172 (process_request_thread)] [_internal.py:97] - 127.0.0.1 - - [11/May/2024 07:07:16] "OPTIONS /console/api/workspaces/current/models/model-types/llm HTTP/1.1" 200 -
2024-05-11 07:07:17.002 ERROR [Thread-173 (process_request_thread)] [app.py:838] - Exception on /console/api/workspaces/current/models/model-types/llm [GET]
Traceback (most recent call last):
  File "/home/anhao/project/dify/api/libs/rsa.py", line 55, in get_decrypt_decoding
    private_key = storage.load(filepath)
  File "/home/anhao/project/dify/api/extensions/ext_storage.py", line 45, in load
    return self.load_once(filename)
  File "/home/anhao/project/dify/api/extensions/ext_storage.py", line 48, in load_once
    return self.storage_runner.load_once(filename)
  File "/home/anhao/project/dify/api/extensions/storage/local_storage.py", line 40, in load_once
    raise FileNotFoundError("File not found")
FileNotFoundError: File not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/anhao/app/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/anhao/project/dify/api/controllers/console/setup.py", line 86, in decorated
    return view(*args, **kwargs)
  File "/home/anhao/project/dify/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/anhao/project/dify/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/home/anhao/project/dify/api/controllers/console/workspace/models.py", line 251, in get
    models = model_provider_service.get_models_by_model_type(
  File "/home/anhao/project/dify/api/services/model_provider_service.py", line 290, in get_models_by_model_type
    provider_configurations = self.provider_manager.get_configurations(tenant_id)
  File "/home/anhao/project/dify/api/core/provider_manager.py", line 118, in get_configurations
    custom_configuration = self._to_custom_configuration(
  File "/home/anhao/project/dify/api/core/provider_manager.py", line 509, in _to_custom_configuration
    self.decoding_rsa_key, self.decoding_cipher_rsa = encrypter.get_decrypt_decoding(tenant_id)
  File "/home/anhao/project/dify/api/core/helper/encrypter.py", line 29, in get_decrypt_decoding
    return rsa.get_decrypt_decoding(tenant_id)
  File "/home/anhao/project/dify/api/libs/rsa.py", line 57, in get_decrypt_decoding
    raise PrivkeyNotFoundError("Private key not found, tenant_id: {tenant_id}".format(tenant_id=tenant_id))
libs.rsa.PrivkeyNotFoundError: Private key not found, tenant_id: ea69b0eb-d3a8-421e-85c2-4310c3ee5c63
2024-05-11 07:07:17.008 INFO [Thread-173 (process_request_thread)] [_internal.py:97] - 127.0.0.1 - - [11/May/2024 07:07:17] "GET /console/api/workspaces/current/models/model-types/llm HTTP/1.1" 500 -
```

在开发环境中存在这个问题，启动生产环境的时候不会有这个问题
我在生产环境中，把api key删掉，再启动调试环境，这个问题也会消失，但是再设置api key还是会复现

**Comment by steven-yan** [comment]
the dify 0.6.14 also report that error
