### ISSUE TITLE
not be able to deploy it on coolify

### ISSUE THREAD

**Issue by muskdevops** [langgenius/dify#4267]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

2024-05-10T09:00:43.313361428Z None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

2024-05-10T09:00:47.098335721Z Traceback (most recent call last):

2024-05-10T09:00:47.098348680Z File "/usr/local/bin/gunicorn", line 8, in <module>

2024-05-10T09:00:47.098351327Z sys.exit(run())

2024-05-10T09:00:47.098353069Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run

2024-05-10T09:00:47.098354740Z WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()

2024-05-10T09:00:47.098356294Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 236, in run

2024-05-10T09:00:47.098357792Z super().run()

2024-05-10T09:00:47.098359182Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run

2024-05-10T09:00:47.098360636Z Arbiter(self).run()

2024-05-10T09:00:47.098362031Z File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__

2024-05-10T09:00:47.098363528Z self.setup(app)

2024-05-10T09:00:47.098365026Z File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup

2024-05-10T09:00:47.098366541Z self.app.wsgi()

2024-05-10T09:00:47.098367975Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi

2024-05-10T09:00:47.098369479Z self.callable = self.load()

2024-05-10T09:00:47.098370867Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load

2024-05-10T09:00:47.098372338Z return self.load_wsgiapp()

2024-05-10T09:00:47.098373722Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp

2024-05-10T09:00:47.098375232Z return util.import_app(self.app_uri)

2024-05-10T09:00:47.098376737Z File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app

2024-05-10T09:00:47.098378253Z mod = importlib.import_module(module)

2024-05-10T09:00:47.098379666Z File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module

2024-05-10T09:00:47.098381176Z return _bootstrap._gcd_import(name[level:], package, level)

2024-05-10T09:00:47.098382584Z File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

2024-05-10T09:00:47.098384364Z File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

2024-05-10T09:00:47.098385864Z File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

2024-05-10T09:00:47.098387367Z File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

2024-05-10T09:00:47.098388928Z File "<frozen importlib._bootstrap_external>", line 883, in exec_module

2024-05-10T09:00:47.098390462Z File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

2024-05-10T09:00:47.098397864Z File "/app/api/app.py", line 210, in <module>

2024-05-10T09:00:47.098399796Z app = create_app()

2024-05-10T09:00:47.098401191Z File "/app/api/app.py", line 80, in create_app

2024-05-10T09:00:47.098402603Z app.config.from_object(Config())

2024-05-10T09:00:47.098403996Z File "/app/api/config.py", line 197, in __init__

2024-05-10T09:00:47.098406008Z self.BROKER_USE_SSL = self.CELERY_BROKER_URL.startswith('rediss://')

2024-05-10T09:00:47.098407561Z AttributeError: 'NoneType' object has no attribute 'startswith'

2024-05-10T09:00:49.453732971Z None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

2024-05-10T09:00:52.763687871Z Traceback (most recent call last):

2024-05-10T09:00:52.763730592Z File "/usr/local/bin/gunicorn", line 8, in <module>

2024-05-10T09:00:52.763733009Z sys.exit(run())

2024-05-10T09:00:52.763734581Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run

2024-05-10T09:00:52.763736287Z WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()

2024-05-10T09:00:52.763737891Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 236, in run

2024-05-10T09:00:52.763739539Z super().run()

2024-05-10T09:00:52.763756152Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run

2024-05-10T09:00:52.763757628Z Arbiter(self).run()

2024-05-10T09:00:52.763759010Z File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__

2024-05-10T09:00:52.763760502Z self.setup(app)

2024-05-10T09:00:52.763761857Z File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup

2024-05-10T09:00:52.763763320Z self.app.wsgi()

2024-05-10T09:00:52.763764759Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi

2024-05-10T09:00:52.763766225Z self.callable = self.load()

2024-05-10T09:00:52.763767576Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load

2024-05-10T09:00:52.763769044Z return self.load_wsgiapp()

2024-05-10T09:00:52.763770398Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp

2024-05-10T09:00:52.763771867Z return util.import_app(self.app_uri)

2024-05-10T09:00:52.763773234Z File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app

2024-05-10T09:00:52.763774711Z mod = importlib.import_module(module)

2024-05-10T09:00:52.763776146Z File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module

2024-05-10T09:00:52.763777617Z return _bootstrap._gcd_import(name[level:], package, level)

2024-05-10T09:00:52.763786251Z File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

2024-05-10T09:00:52.763788071Z File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

2024-05-10T09:00:52.763789490Z File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked

2024-05-10T09:00:52.763790929Z File "<frozen importlib._bootstrap>", line 688, in _load_unlocked

2024-05-10T09:00:52.763792340Z File "<frozen importlib._bootstrap_external>", line 883, in exec_module

2024-05-10T09:00:52.763793832Z File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

2024-05-10T09:00:52.763795370Z File "/app/api/app.py", line 210, in <module>

2024-05-10T09:00:52.763796860Z app = create_app()

2024-05-10T09:00:52.763798240Z File "/app/api/app.py", line 80, in create_app

2024-05-10T09:00:52.763799670Z app.config.from_object(Config())

2024-05-10T09:00:52.763800992Z File "/app/api/config.py", line 197, in __init__

2024-05-10T09:00:52.763802964Z self.BROKER_USE_SSL = self.CELERY_BROKER_URL.startswith('rediss://')

2024-05-10T09:00:52.763804402Z AttributeError: 'NoneType' object has no attribute 'startswith'

2024-05-10T09:00:55.256429308Z None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

2024-05-10T09:00:58.443578769Z Traceback (most recent call last):

2024-05-10T09:00:58.443619530Z File "/usr/local/bin/gunicorn", line 8, in <module>

2024-05-10T09:00:58.443622387Z sys.exit(run())

2024-05-10T09:00:58.443624073Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run

2024-05-10T09:00:58.443625799Z WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()

2024-05-10T09:00:58.443627553Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 236, in run

2024-05-10T09:00:58.443629103Z super().run()

2024-05-10T09:00:58.443630603Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run

2024-05-10T09:00:58.443632101Z Arbiter(self).run()

2024-05-10T09:00:58.443633541Z File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__

2024-05-10T09:00:58.443635033Z self.setup(app)

2024-05-10T09:00:58.443636516Z File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup

2024-05-10T09:00:58.443638046Z self.app.wsgi()

2024-05-10T09:00:58.443639569Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi

2024-05-10T09:00:58.443641088Z self.callable = self.load()

2024-05-10T09:00:58.443642486Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load

2024-05-10T09:00:58.443652591Z return self.load_wsgiapp()

2024-05-10T09:00:58.443654357Z File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp

### 2. Describe the feature you'd like to see

deployment on coolify

### 3. How will this feature improve your workflow or experience?

include node command only to run this applciation, it would be optional if we can run though docker compose or node

### 4. Additional context or comments

Kindly can we use yarn install , yarn build, yarn start to run this applciation.
It would help us alot

### 5. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by muskdevops** [comment]
CELERY_BROKER_URL: redis://:redis@***.**.**.**:9026/0

**Comment by muskdevops** [comment]
same isuue

**Comment by lvjiajjjlzy** [comment]
Using Docker can save a lot of trouble

**Comment by syedmusaali359** [comment]
> Using Docker can save a lot of trouble

I am using docker compose to run this application, still getting these issue.

**Comment by taowang1993** [comment]
Anyone succeeded deploying Dify with Coolify yet?

**Comment by imankeeth** [comment]
This is the video I referred to for deploying: https://youtu.be/vyDiLwlRFfk?si=CDv9AkDq6xweg8o4

Hope this helps!
