### ISSUE TITLE
bge-reranker-v2-minicpm-layerwise from Xinference mount error

### ISSUE THREAD

**Issue by lk1983823** [langgenius/dify#4373]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I want to mount bge-reranker-v2-minicpm-layerwise from Xinference to Dify as follows:
![rerank_error](https://github.com/langgenius/dify/assets/20237650/2634ddd5-cfa7-4939-bc0f-7c26ca7fa3c5)

### ❌ Actual Behavior

But it failed, the docker log shows:
```
Exception in thread Thread-1 (embedding_search):
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 35, in invoke
    return self._invoke(model, credentials, query, docs, score_threshold, top_n, user)
  File "/app/api/core/model_runtime/model_providers/xinference/rerank/rerank.py", line 51, in _invoke
    response = handle.rerank(
  File "/usr/local/lib/python3.10/site-packages/xinference_client/client/restful/restful_client.py", line 161, in rerank
    raise RuntimeError(
RuntimeError: Failed to rerank documents, detail: [address=0.0.0.0:56051, pid=1240943] Model not found in the model list, uid: bge-reranker-v2-minicpm-layerwise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/api/core/rag/datasource/retrieval_service.py", line 134, in embedding_search
    all_documents.extend(data_post_processor.invoke(
  File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 22, in invoke
    documents = self.rerank_runner.run(query, documents, score_threshold, top_n, user)
  File "/app/api/core/rerank/rerank.py", line 33, in run
    rerank_result = self.rerank_model_instance.invoke_rerank(
  File "/app/api/core/model_manager.py", line 120, in invoke_rerank
    return self.model_type_instance.invoke(
  File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 37, in invoke
    raise self._transform_invoke_error(e)
core.model_runtime.errors.invoke.InvokeError: [xinference] Error: Failed to rerank documents, detail: [address=0.0.0.0:56051, pid=1240943] Model not found in the model list, uid: bge-reranker-v2-minicpm-layerwise
Building prefix dict from the default dictionary ...
2024-05-14 06:55:52.610 DEBUG [Thread-3 (keyword_search)] [__init__.py:113] - Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
2024-05-14 06:55:53.307 DEBUG [Thread-3 (keyword_search)] [__init__.py:146] - Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.784 seconds.
2024-05-14 06:55:53.394 DEBUG [Thread-3 (keyword_search)] [__init__.py:164] - Loading model cost 0.784 seconds.
Prefix dict has been built successfully.
2024-05-14 06:55:53.394 DEBUG [Thread-3 (keyword_search)] [__init__.py:166] - Prefix dict has been built successfully.
/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/model.py:120: SAWarning: This declarative base already contains a class with the same class name and module name as services.app_service.ModifiedApp, and will be replaced in the string-lookup table.
```

**Comment by lk1983823** [comment]
Check Model Compatibility: Ensure the bge-reranker-v2-minicpm-layerwise model is compatible with the ggml format, as required by LocalAI. Compatibility details can be found in the LocalAI documentation.

How to check this compatibility ? I download the model from huggingface. https://huggingface.co/BAAI/bge-reranker-v2-minicpm-layerwise

**Comment by BradKML** [comment]
Seconding this but also @lk1983823 LocalAI has their own Web UX downloader, so could you note down possible ways to get around this? Maybe get FlashRank in on the action?
Also relevant ideas https://github.com/langgenius/dify/issues/4377 https://github.com/langgenius/dify/discussions/3779
