### ISSUE TITLE
启动的时候报错：flask run --host 0.0.0.0 --port=5001 --debug

### ISSUE THREAD

**Issue by lixiaodong** [langgenius/dify#44]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/cli.py", line 312, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/Users/jetty/workspace/dify/api/app.py", line 22, in <module>
    from events import event_handlers
  File "/Users/jetty/workspace/dify/api/events/event_handlers/__init__.py", line 3, in <module>
    from .create_provider_when_tenant_created import handle
  File "/Users/jetty/workspace/dify/api/events/event_handlers/create_provider_when_tenant_created.py", line 2, in <module>
    from services.provider_service import ProviderService
  File "/Users/jetty/workspace/dify/api/services/provider_service.py", line 5, in <module>
    from core.llm.provider.llm_provider_service import LLMProviderService
  File "/Users/jetty/workspace/dify/api/core/llm/provider/llm_provider_service.py", line 3, in <module>
    from core.llm.provider.anthropic_provider import AnthropicProvider
  File "/Users/jetty/workspace/dify/api/core/llm/provider/anthropic_provider.py", line 3, in <module>
    from core.llm.provider.base import BaseProvider
  File "/Users/jetty/workspace/dify/api/core/llm/provider/base.py", line 13, in <module>
    class BaseProvider(ABC):
  File "/Users/jetty/workspace/dify/api/core/llm/provider/base.py", line 76, in BaseProvider
    def get_provider_configs(self, obfuscated: bool = False) -> Union[str | dict]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by takatost** [comment]
你好，需要 python 3.10 以上支持
https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md#install-dependencies
