### ISSUE TITLE
局域网如何连接openaipublic.blob.core.windows.net？

### ISSUE THREAD

**Issue by immno** [langgenius/dify#447]
为什么会请求这个地址？在局域网中如何破解？
```
dify-api-1       | During handling of the above exception, another exception occurred:
dify-api-1       |
dify-api-1       | Traceback (most recent call last):
dify-api-1       |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
dify-api-1       |     resp = conn.urlopen(
dify-api-1       |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
dify-api-1       |     retries = retries.increment(
dify-api-1       |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
dify-api-1       |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
dify-api-1       | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6c2485b8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by immno** [comment]
好像有相关的修复提交：
https://github.com/openai/whisper/discussions/1121
https://github.com/openai/whisper/commit/b5851c6c40e753606765ac45b85b298e3ae9e00d

**Comment by zdm0100** [comment]
遇到了跟你一样的问题，如何解决呢？

**Comment by lifeofbow** [comment]
解决了吗大佬们
