### ISSUE TITLE
检查版本接口超时

### ISSUE THREAD

**Issue by geezerrrr** [langgenius/dify#458]
Dify version: Self Host 0.3.3

每次刷新页面都调用接口检查版本：
`/console/api/version?current_version=0.3.3`

接口返回500，看日志是 updates.dify.ai 连接超时。
有没有办法关掉自动检查更新？

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f669c730cd0>, 'Connection to updates.dify.ai timed out. (connect timeout=None)')
```

**Comment by crazywoola** [comment]
Duplicate #436
