### ISSUE TITLE
psycopg2.errors.UndefinedTable: relation "embedding_vector_index_0799a0c6_ca9a_418e_9e33_900236a74af4_nod" does not exist

### ISSUE THREAD

**Issue by wencan** [langgenius/dify#4696]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1. docker compose 在本地运行dify。vector数据库选pgvector。
2. 知识库上传一个txt文件，可以用下面附件中的。自定义分割，分割标记为\n\n。embedding和rerank我选择了bce的，都是运行在xinference上。高精度-混合搜索。这时topk保持默认的3。
3. 在chatbot中添加知识库。最重要一步来了，chatbot页面，修改知识库，topk改为1。
4. 回到知识库，测试页面。随便输点什么，点测试，右边会闪下，下面recents会新增一条，还有日志：
```
pgvector-1    | 2024-05-27 16:02:11.622 UTC [15031] ERROR:  relation "embedding_vector_index_19b3d0de_5efd_46d0_a74e_9f19b6bd951b_nod" does not exist at character 17053
pgvector-1    | 2024-05-27 16:02:11.622 UTC [15031] STATEMENT:  SELECT meta, text, embedding <=> '[0.01672604118639007, 0.014439345314756559, 0.01530501150914625, 0.02549769352839403, -0.06947399664927052, -0.030314819839635448, 0.00847174039641705, -0.0252105649164462, 0.09150560185832687, 0.06796652067946418, 0.003746830852401398, 0.0225697420182749, 0.11625115555135326, -0.008024675758981872, -0.011151345429179537, 0.04210279502807976, -0.013978434704626334, -0.024566402620209773, 0.023689674176296187, 0.04349188872296763, -0.006467775897202232, 0.04668087132388973, 0.031365521202858924, 0.01361495440548638, 0.04893135644255653, -0.007923617015246603, -0.005683782035865083, 0.04474582143545914, 0.01860995960290949, -0.00036008280528926687, -0.03489530453561959, -0.01380581779098295, 0.02980687837088363, 0.015871826534359854, -0.01881160584115801, 0.041841827267211765, 0.009256710283810862, -0.004263120231037658, 0.0024838147180232997, -0.031582947770786934, -0.02212635610500367, 0.017808815436387748, 0.039731834021350054, -0.015314863970647623, -0.004288427524979197, -0.005961535489130279, 0.033386211789826266, 0.023310020529350876, 0.01414204572898734, -0.017377885031209853, -0.015065596415266131, 0.0402244142555803, -0.004921773906512327, -0.05098027727936125, -0.018501797661908792, 0.017310366007301497, -0.017873123260063878, -0.003085268656530777, 0.050383586357323505, -0.04010354721203667, 0.03608098992995054, 0.01004940921723926, 0.035187117700110376, -0.03835339093140874, 0.0595891474740943, -0.018425086484203428, 0.05187802753639601, -0.016556236866917606, -0.003856197226319824, -0.006785703346644189, 0.0045076236057961915, -0.027905393347989426, 0.011118304898251833, 0.03104590060897898, -0.07330790150564874, 0.017700647907451614, 0.014081101842445437, 0.005311514242586154, -0.008527623476096447, -0.06102064614838292, -0.0070375660323757664, -0.021658765118056228, 0.010797321779447365, -0.030067909461686602, -0.03960010030602289, 0.016883579987574126, -0.018834177375040916, 0.010785091651416737, -0.01454533354887152, 0.03033366794587089, 0.018562655866773962, -0.0007617428770423902, 0.019386578320789848, -0.02801242280074117, 0.026565490248770283, -0.013040992410846412, 0.001991861962376711, 0.007754345877947268, -0.00042878099999055366, -0.02465863149462899, 0.0031323798417243016, -0.13879854955316281, 0.062519639632193, 0.016129491825383452, -0.006594012946702658, -0.036208677980019935, -0.0072004785648069084, -0.057199209838614054, 0.014246322192212849, -0.004714839618693448, 0.015257813943784067, 0.030102102038637297, 0.022242780739873368, 0.04088887193333085, -0.022295812109833776, 0.02794156591673064, 0.05447702846309736, 0.04984397805843939, 0.028760781466461816, 0.029727922705776972, 0.06208565821426545, -0.026639312463853728, -0.05287077642118255, 0.008285813951880756, 0.017146244618170405, -0.023425267972488114, 0.02615380655588914, -0.06595267345076436, 0.010624209402195066, -0.13044197836878685, 0.031640209207874595, -0.018623327807124508, 0.002133320315182086, -0.02972041065790193, 0.04684315614490657, -0.03290346632196849, 0.0023247266617388053, -0.011013805848931342, -0.013342990518997181, -0.04794234402393348, -0.02000522610381221, -0.01905179579541899, 0.014959027035865524, -0.015719145511717356, -0.005544556296098195, 0.015870409061403516, 0.012288294713257453, -0.09377433344884686, 0.0011912387544193292, 0.013684232697735419, -0.008654590682494225, -0.010437344184505034, 0.07374879706235936, 0.02405535239670878, -0.003849390422463301, 0.005408656309240033, -0.049910806040998464, 0.028724040790950978, -0.0585404484544031, -0.03618256369506876, -0.04664772741615641, 0.02622120637050813, -0.0058121173551228195, -0.03607507416896588, 0.046868529097089516, -0.002391007259455512, 0.08425836251844458, 0.02330175038490129, -0.025557124947077133, -0.030386920970603706, -0.04133950912415664, 0.03971830004171701, -0.019274087592469142, -0.004803572308173054, -0.03094600881242787, -0.039674516704908, 0.009659627437310928, 0.039777152177759616, -0.009052143417972936, -0.06126002957729555, -0.0160463005052141, -0.042936667732467196, 0.024677015802223007, -0.0017427460961593224, 0.02747768159362434, 0.02167192098072457, 0.06098696579884746, -0.02563548642838212, -0.04688949503085631, 0.010345271772278106, 0.024529833308052397, -0.016736609834950195, 0.036931786628137286, 0.02784322942887669, -0.03157760942979763, 6.638259209038185e-05, 0.07929670798236604, -0.014936788915463807, -0.023063294553271517, -0.001332679528511136, 0.03172557423492968, 0.0038770446492891824, 0.016501076493554975, -0.07945710408120453, 0.049288045537493066, -0.020146585969255473, 0.011744403261859408, 0.04289456077628986, 0.005666684816067163, -0.040232952620930955, 0.01925777268363267, -0.010603412969136587, 0.01264068296055117, 0.060313701534845186, -0.06168647845825144, -0.014022694878592798, -0.016845753389942996, -0.08192260550498001, -0.001703469312866472, -0.020493162763692726, 0.029943114099529416, 0.03839235374257912, 0.03244801978137495, 0.01636590992322317, -0.005988872134958716, -0.019169200181635645, 0.02438283707839642, -0.015214198245038224, 0.02126442823942261, -0.009043151498529155, 0.0004202789562202514, -0.009725772760423884, -0.022592000627773223, -0.04498960070691704, -0.009462074361771407, 0.013982645213979553, 0.05619017398466824, -0.008655101978586884, -0.03384568909451641, -0.02690724092963346, -0.008766574771335136, -0.029004549562048846, 0.001786689387620271, -0.028840884520978594, 0.020286908341352248, 0.011122649518055586, 0.01455507890827698, -0.02228564206733496, 0.0026574111501829947, 0.1403154281556677, -0.012231782990841178, 0.013100460151109869, -0.005121015469876971, 0.00275255459859489, 0.02698237072160961, -0.033207334525846156, 0.022377258131501043, 0.03366119781806534, -0.003031758819598414, -0.01725899797945674, 0.033799227273987015, -0.04979940496008835, -0.009140638620196387, -0.009575661256760713, -0.014311223268368074, 0.012957771288354718, 0.019405687197345776, 0.0070777721591813005, -0.06299887587659513, -0.0170684214413127, 0.023363664709564417, -0.04280238219328959, 0.0165764707811419, 0.00934127716742076, -0.021160377156259805, -0.02249494191448964, 0.0189630314409719, 0.09791453912366381, 0.04955459750850968, 0.047838788404379586, 0.026237357366571727, -0.02406005930099349, -0.005960509171654666, 0.02932719509164639, -0.011139542778209985, 0.02082866240744491, -0.09285502866217907, -0.0460144392422841, -0.0727587266612932, -0.062009643665844806, -0.04202111058783377, 0.009635083362218086, -0.021773677285067128, 0.027563113675904697, -0.018511459202282667, -0.013258155414486215, -0.005057399153211409, 0.01878024821011999, 0.014554276108218923, -0.036972396017616996, -0.016731001410414677, -0.001922460153471408, -0.013500286244989645, -0.007510458107409588, -0.025367656682795142, 0.04371777169985985, 0.0630221142374404, 0.0006141908224332227, -0.04371131949707306, -0.025563046295997233, -0.018610076949553706, -0.011142674816023494, -0.02951868246326697, 0.04608590521125747, 0.02351382929861426, -0.003667662380086775, 0.1081979794589878, 0.0018512236390969962, 0.036891315074398405, 0.018009962485737063, 0.006365375583300338, 0.04324891038892263, -0.016127128128692794, -0.006442125876553773, 0.04810079552123922, 0.03750718751615278, 0.002389480588927473, -0.0052045471884468114, 0.07271853077903598, -0.012885216603293332, 0.005601607254284325, -0.024481592661408282, 0.004208322142155983, -0.00788935086381263, -0.04062814259104158, 0.05824233582402752, 0.050889637241251826, -0.01395414674324111, 0.05486444375236732, 0.04533636562851407, -0.10585023446136162, 0.050651777456068865, 0.01995186504566091, 0.046615995393443986, -0.00026614736956624046, -0.03608765074899372, 0.01155648378701657, -0.04833868510874452, -0.03771174693141012, 0.036724783422448, 0.04353254281593085, -0.036953039409256615, -0.001550107027761715, 0.055618546815719164, -0.003142796219043717, -0.021248685162646053, 0.033679813093657494, 0.008119201274866482, -0.019148012593096442, -0.06603669364802382, 0.01016311252755021, 0.03530449042135954, 0.02122006003203766, -0.028260996520805663, -0.021166307818405634, 0.036248862686406286, 0.014337218344029885, 0.011105637979934396, -0.0068287798096201766, 0.027354121165199155, 0.01137680558562355, 0.027149153830654773, -0.013049648122841285, -0.019418491020081467, -0.04302190237436204, -0.0495849176462012, -0.06100594987817859, 0.03592311212734985, 0.05612970507263864, 0.08071696745584186, -0.0045178709480685805, 0.0075898859530608345, 0.002427047580391338, 5.92502582527333e-05, 0.017859194399659818, 0.03286802763541492, -0.06895798433909976, -0.08058705168217749, 0.06037728106426911, 0.01377232929389756, -0.076736554382836, 0.04827431954306886, 0.03259475524071045, -0.0007498870824785077, 0.021831169690152932, -0.03384462738678301, -0.03672424325535557, 0.02298557382189686, -0.01002816016141023, -0.01020102108156778, -0.008398719118746515, 0.01091815715802351, -0.07399087387615354, 0.056394994170246064, 0.021673455800325123, -0.0009112784159017278, -0.025882916484326786, 0.008999539525073605, -0.03688380116387822, -0.04911809779434433, 0.010889556241802021, 0.03501709917644608, -0.03346195811734584, 0.01645240185059177, -0.0011006128025638278, -0.03114466364257143, 0.010799548571719771, 0.003610731795343225, 0.053246356463192895, 0.05367464936284363, 0.044032003661331545, -0.03800803416954232, 0.012033622692983963, 0.007938653218190138, 0.0038263918771806057, 0.06781508017848913, 0.030389698174516845, 0.01965582181404287, 0.00393545440710954, -0.027156284036274823, -0.005657329215158567, 0.015375526597772434, 0.032624341496214335, 0.05293485513950569, 0.06379555900799147, -0.06998831022706783, 0.052795819855205005, 0.010562430119305044, 0.07029234606900867, -0.055578622879653296, 0.011710694972646754, -0.07543275493448766, -0.015450284792041897, 0.021532053094043494, 0.07376144814819305, 0.008939802632586506, -0.015300872711631164, -0.013838633873170527, -0.01616963741622173, -0.00604555382374459, 0.04211284586128921, 0.02095560726210093, 0.036486566009396953, 0.005930352946736012, 0.009843517079379738, -0.005906198630140035, 0.04714394725900253, 0.013077552409778056, -0.05199004701549471, -0.03581887477967242, -0.004343875677016933, 0.04416839026423418, -0.1110805941862459, 0.018824059486606197, 0.004613504272153953, 0.0572862624221717, 0.014716668031331672, -0.0009332660105312674, 0.10054165854149376, 0.01700832692095751, -0.04317250095973097, 0.007737546681372757, -0.009164117262265542, -0.0002694739664860472, 0.015447275688808045, 0.0028854061338404835, 0.0014311126410820466, -0.018765356362175294, 0.012497274185446973, 0.04229817905334641, -0.017749005900739943, 0.03384380782291864, -0.04699761040572835, -0.057386614292073944, 0.07900840776662119, -0.010313908553304649, -0.09799769505357539, 0.024472288748902497, -0.0015508152985785968, 0.02593429568804242, 0.04124869027211318, 0.01307197751285517, 0.04146530472675739, 0.037810210079134016, -0.03432133043378617, 0.002963741538113423, -0.08768156902122407, 0.021630812402345653, 0.013813389443502674, -0.024895658677431546, 0.015947764714329498, -0.016579519931246397, 0.014497178583904136, -0.0022832292561855965, 0.018367597804407918, 0.027764363170737057, -0.040449026908482746, -0.07502809900174352, 0.04485546045406085, 0.01479694431184706, 0.10143577291520295, 0.006292643481288766, 0.004755714900767791, 0.014453250892096288, -0.028687655880663087, -0.03070219601335733, 0.004917439996918165, 0.025697927881621653, 0.04312304773109662, -0.013401378856398357, -0.06183070679722001, 0.006050406945673284, -0.01574528587370058, 0.0016026403729761285, -0.05207709214847176, -0.014661216154003644, -0.0019308275047145683, -0.04449306421439605, -0.042346976630889266, 0.04335730516056662, 0.08605678366010353, -0.035894632283062874, -0.026587855029041946, -0.06584103395127551, -0.03840885305328508, 0.018934458464427602, 0.001517739610223756, 0.019451830505555153, 0.045343767780325485, -0.020308803735047044, 0.008141172105689704, -0.015249067893499599, 0.013526685514648204, 0.013887758344936562, -0.018269168184296657, 0.0850645302389259, 0.006179599081698321, -0.006901843928129077, -0.016617465738166894, 0.029865585220604826, -0.008461657898240108, 0.003076407587908525, 0.04734973974534673, 0.026375379371912817, 0.0035413368549418994, 0.033671043760308696, -0.018488213390856798, 0.026499932590200986, -0.054780241015883524, 0.020990801942140334, 0.045329179543539634, -0.0014780843607202414, 0.018799746379511494, 0.027137745129133663, -0.0007159784424973044, 0.007232310704695949, 0.007497829838978938, -0.00044798888777753933, 0.014713622606517467, 0.0990053711765644, -0.021879265050475636, 0.025603655685476942, 0.004439529024537628, 0.023738911338093572, -0.009597182258781103, -0.03343112016430364, 0.0036783933116052723, -0.017473617541149265, -0.07479436683820477, -0.017960987956905306, 0.046125490145906715, -0.014244183875584892, 0.0050050937491967745, -0.007043405424909428, 0.033128272689966154, 0.014598294138316367, 0.0066155469872390725, 0.006128068072403262, -0.1587923911698408, -0.0018310910062025317, -0.02329782020364259, 0.007635532866338721, 0.004273340099294139, 0.00431011011146603, -0.0030455486801084287, -0.02240298684890693, -0.009222567998279118, 0.005090401034252327, 0.004238017362400926, -0.08131450401877603, -0.03866500773909502, -0.028481041967809373, -0.010319657607548714, -0.011811044048581281, 0.007890348310288477, 0.016459690381049257, 0.02452772479374678, -0.006193480910312434, -0.006145827462550693, -0.0066802101104768575, -0.05961135765481883, -0.0017268789206498927, -0.030352471348622824, -0.0941588281105274, -0.04851821057323554, -0.051621578552652946, 0.0019148609105204548, 0.035436835084294696, -0.04939830295428335, -0.042462315343638674, 0.0019375269736445354, -0.004730325184778529, -0.01774422449064938, 0.0032295542718375975, -0.021764121915466592, -0.02501383419873877, -0.03048807005262857, 0.05925274258480102, 0.006382087701214259, -0.02486152384248039, 0.031644873271320935, -0.010874575918212875, 0.028331400782045643, 0.012384507785644613, -0.07653851795088101, -0.007186584163338058, 0.028092464387968124, -0.01631977220294923, 0.0062946765584659566, 0.009906326405035666, -0.000625376705028705, 0.014274273045278278, 0.027383271561738802, 0.017882309825925445, 0.017389735179630637, 0.0018751869181501553, -0.029138773633936618, -0.0934464333972916, -0.015334449684361004, 0.0030996801748583705, -0.02074029852170427, 0.010423949903257965, 0.06819436688434061, -0.005897239306986316, -0.033467784471363476, 0.025651361752964067, -0.0011718829609661948, 0.006168999699493281, -0.03108874144734396, 0.01852540482649304, -0.00023496003959187116, -0.02081818502849695, 0.00821911076654648, -0.014446835942212419, 0.03295588115638547, -0.07075557846631375, 0.003150089638944712, 0.009934155254844012, -0.03212582687454796, -0.0026883545755066046, -0.04045527049501316, 0.05384249976755762, -0.051045726904512055, -0.07146505255196016, -0.00854224244652721, 0.014620332024364857, 0.0029192219908103366, -0.009394057080286415, -0.03425784031132927, 0.012123171221037649, -0.026773808481932865, -0.011100254935461578, 0.033816438115138854, 0.027010017963516195, -0.0397544837863291, 0.05159588522550484, 0.002860715375442371, -0.0212062839085356, -0.0058541963716229614, -0.014046295523919037, -0.0035952185224115934, 0.025872373912798705, 0.02708305786763819, -0.034077223336782515, -0.1016004679990391, -0.027451703281768845, -0.02415157478232167, 0.05897803595333388, 0.018560549215113496, -0.01523402796526577, -0.01325736192765389, 0.012490114177504582, 0.003915585571333921, -0.02296165745821832, -0.008856420391289657, -0.03612650180145532, -0.08082445698194475, 0.01872359585799517, 0.02777594137296648, -0.031196001868093844, 0.0382691621178929, -0.0003585712105453808, 0.06845739473074042, 0.00418510287342345, -0.0006803103595524348, 0.0868100150055269, 0.07608313101493215, 0.016049396221447257, 0.013982861280816525, 0.026417935225570413, 0.07306909549673146, 0.003830084571183152, -0.042514443330703124, -0.03640756750345193, 0.05295805624744804, -0.025940023321867303, 0.010954829846986508, -0.018635980755603347, -0.009226414360506236, -0.0058684484009599025, -0.03048957134461649, -0.03754629933893486, 0.06516747911463042, 0.02418550845159703, 0.0042480695925942395, -0.032585263201044885, 0.017266286509914224, 0.01825560626498642, 0.030271535691725644, -0.014502068027413183, 0.020351817799410633, -0.027956761375834183, 0.04116894298281933, -0.030465686645905442, 0.004221245174181036, 0.023719701878699744, 0.04711470373020557, -0.02865325468745601, 0.0013965250669450155, 0.056893825441587303, -0.005566579746646801, -0.022746659779561095, -0.017679315032591, -0.030266040888544052, -0.031529646317280315, -0.03509819874611614, -0.017571978243390116, -0.029197266279465988, 0.006636753667891024, -0.04661148406689963, -0.000872647970474645, -0.04591032855447662, -0.001210926913615757, 0.013546456561553642, 0.06921698887198356, 0.031781181643127425, 0.0183652117559755, -0.01378934362598647]' AS distance FROM embedding_Vector_index_19b3d0de_5efd_46d0_a74e_9f19b6bd951b_Node ORDER BY distance LIMIT 1
api-1         | Exception in thread Thread-45 (embedding_search):
api-1         | Traceback (most recent call last):
api-1         |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
api-1         |     self.run()
api-1         |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
api-1         |     self._target(*self._args, **self._kwargs)
api-1         |   File "/app/api/core/rag/datasource/retrieval_service.py", line 121, in embedding_search
api-1         |     documents = vector.search_by_vector(
api-1         |   File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 226, in search_by_vector
api-1         |     return self._vector_processor.search_by_vector(query_vector, **kwargs)
api-1         |   File "/app/api/core/rag/datasource/vdb/pgvector/pgvector.py", line 135, in search_by_vector
api-1         |     cur.execute(
api-1         | psycopg2.errors.UndefinedTable: relation "embedding_vector_index_19b3d0de_5efd_46d0_a74e_9f19b6bd951b_nod" does not exist
api-1         | LINE 1: ...17559755, -0.01378934362598647]' AS distance FROM embedding_...
api-1         |                                                              ^
api-1         | 

```
[fh21_ask_test.txt](https://github.com/langgenius/dify/files/15458028/fh21_ask_test.txt)

### ✔️ Expected Behavior

期望正常检索知识库

### ❌ Actual Behavior

异常了

**Comment by wencan** [comment]
MIGRATION_ENABLED一直是true
dify库存在
表embedding_vector_index_0799a0c6_ca9a_418e_9e33_900236a74af4_nod不存在
为什么会出现需要用户手工创建表这种情况？
pgvector镜像我用的是pgvector/pgvector:pg16

问题没解决，为啥关闭了这个issue？ @crazywoola
