### ISSUE TITLE
Failed to call xinference and azure openai text embedding models

### ISSUE THREAD

**Issue by Starlento** [langgenius/dify#4736]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Add xinference text embedding model.
Drag a pdf to knowledge base.

I also tried azure openai service text-embedding. Failed as well, but the gpt-4o API works.
Logically since I add the url successfully, the service should be valid.

![image](https://github.com/langgenius/dify/assets/33574105/7eb10730-833a-4eb2-bee2-d1cf5671e965)

### ✔️ Expected Behavior

successfully call the api and create vector db.

### ❌ Actual Behavior

![image](https://github.com/langgenius/dify/assets/33574105/eaac6323-1b9c-4916-a33c-4814cd261b4f)
![image](https://github.com/langgenius/dify/assets/33574105/9441f8bc-6b71-41f0-9b66-5ae8c83f92f2)

``` python

[2024-05-28 12:28:46,829: ERROR/MainProcess] consume document failed
Traceback (most recent call last):
  File "/app/api/core/indexing_runner.py", line 73, in run
    self._load(
  File "/app/api/core/indexing_runner.py", line 678, in _load
    tokens += future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/api/core/indexing_runner.py", line 733, in _process_chunk
    index_processor.load(dataset, chunk_documents, with_keywords=False)
  File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 59, in load
    vector = Vector(dataset)
  File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 23, in __init__
    self._vector_processor = self._init_vector()
  File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 48, in _init_vector
    return WeaviateVector(
  File "/app/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 31, in __init__
    self._client = self._init_client(config)
  File "/app/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 40, in _init_client
    client = weaviate.Client(
  File "/usr/local/lib/python3.10/site-packages/weaviate/client.py", line 150, in __init__
    self._connection = Connection(
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 654, in __init__
    self._server_version = self.get_meta()["version"]
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 678, in get_meta
    raise UnexpectedStatusCodeException("Meta endpoint", response)
weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 503, with response body: None.
```

**Comment by Starlento** [comment]
[Solved by https://github.com/langgenius/dify/issues/734](https://github.com/langgenius/dify/issues/734#issuecomment-1925580564)
