### ISSUE TITLE
An error occurs when starting the api server on MacOS

### ISSUE THREAD

**Issue by buddypia** [langgenius/dify#4738]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Run flask run --host 0.0.0.0 --port=5001 --debug from the link below
https://github.com/langgenius/dify/blob/main/api/README.md

The following error occurs in MacOS environment
Is development not supported on MacOS?
```
/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
ERROR:root:Failed to load module core.model_runtime.model_providers.openai.llm.llm from /Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/openai/llm/llm.py: unsupported platform
Traceback (most recent call last):
  File "/Users/a13973/dev/buddypia/dify/api/core/utils/module_import_helper.py", line 29, in import_module_from_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/openai/llm/llm.py", line 6, in <module>
    from openai import OpenAI, Stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/types/__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/types/batch.py", line 7, in <module>
    from .._models import BaseModel
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/_models.py", line 24, in <module>
    from ._types import (
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/_types.py", line 21, in <module>
    import httpx
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 12, in <module>
    from .._synchronization import Lock
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_synchronization.py", line 13, in <module>
    import trio
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/__init__.py", line 23, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: split
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar, RunVarToken
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/_local.py", line 9, in <module>
    from . import _run
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/_run.py", line 2822, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform
Traceback (most recent call last):
  File "/Users/a13973/.asdf/installs/python/3.11.5/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 1107, in main
    cli.main()
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 955, in run_command
    raise e from None
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 939, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 341, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 247, in locate_app
    __import__(module_name)
  File "/Users/a13973/dev/buddypia/dify/api/app.py", line 24, in <module>
    from commands import register_commands
  File "/Users/a13973/dev/buddypia/dify/api/commands.py", line 9, in <module>
    from core.rag.datasource.vdb.vector_factory import Vector
  File "/Users/a13973/dev/buddypia/dify/api/core/rag/datasource/vdb/vector_factory.py", line 6, in <module>
    from core.embedding.cached_embedding import CacheEmbedding
  File "/Users/a13973/dev/buddypia/dify/api/core/embedding/cached_embedding.py", line 8, in <module>
    from core.model_manager import ModelInstance
  File "/Users/a13973/dev/buddypia/dify/api/core/model_manager.py", line 4, in <module>
    from core.entities.provider_configuration import ProviderModelBundle
  File "/Users/a13973/dev/buddypia/dify/api/core/entities/provider_configuration.py", line 21, in <module>
    from core.model_runtime.model_providers import model_provider_factory
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/__init__.py", line 3, in <module>
    model_provider_factory = ModelProviderFactory()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/model_provider_factory.py", line 34, in __init__
    self.get_providers()
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/model_provider_factory.py", line 55, in get_providers
    models = model_provider_instance.models(model_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/__base/model_provider.py", line 71, in models
    model_instance = self.get_model_instance(model_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/__base/model_provider.py", line 103, in get_model_instance
    mod = import_module_from_source(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/dev/buddypia/dify/api/core/utils/module_import_helper.py", line 33, in import_module_from_source
    raise e
  File "/Users/a13973/dev/buddypia/dify/api/core/utils/module_import_helper.py", line 29, in import_module_from_source
    spec.loader.exec_module(module)
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/openai/llm/llm.py", line 6, in <module>
    from openai import OpenAI, Stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/types/__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/types/batch.py", line 7, in <module>
    from .._models import BaseModel
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/_models.py", line 24, in <module>
    from ._types import (
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/_types.py", line 21, in <module>
    import httpx
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 12, in <module>
    from .._synchronization import Lock
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_synchronization.py", line 13, in <module>
    import trio
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/__init__.py", line 23, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: split
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar, RunVarToken
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/_local.py", line 9, in <module>
    from . import _run
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/_run.py", line 2822, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform
```

### ✔️ Expected Behavior

No Error

### ❌ Actual Behavior

/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
ERROR:root:Failed to load module core.model_runtime.model_providers.openai.llm.llm from /Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/openai/llm/llm.py: unsupported platform
Traceback (most recent call last):
  File "/Users/a13973/dev/buddypia/dify/api/core/utils/module_import_helper.py", line 29, in import_module_from_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/openai/llm/llm.py", line 6, in <module>
    from openai import OpenAI, Stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/types/__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/types/batch.py", line 7, in <module>
    from .._models import BaseModel
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/_models.py", line 24, in <module>
    from ._types import (
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/_types.py", line 21, in <module>
    import httpx
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 12, in <module>
    from .._synchronization import Lock
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_synchronization.py", line 13, in <module>
    import trio
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/__init__.py", line 23, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: split
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar, RunVarToken
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/_local.py", line 9, in <module>
    from . import _run
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/_run.py", line 2822, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform
Traceback (most recent call last):
  File "/Users/a13973/.asdf/installs/python/3.11.5/bin/flask", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 1107, in main
    cli.main()
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 955, in run_command
    raise e from None
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 939, in run_command
    app: WSGIApplication = info.load_app()
                           ^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 341, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/flask/cli.py", line 247, in locate_app
    __import__(module_name)
  File "/Users/a13973/dev/buddypia/dify/api/app.py", line 24, in <module>
    from commands import register_commands
  File "/Users/a13973/dev/buddypia/dify/api/commands.py", line 9, in <module>
    from core.rag.datasource.vdb.vector_factory import Vector
  File "/Users/a13973/dev/buddypia/dify/api/core/rag/datasource/vdb/vector_factory.py", line 6, in <module>
    from core.embedding.cached_embedding import CacheEmbedding
  File "/Users/a13973/dev/buddypia/dify/api/core/embedding/cached_embedding.py", line 8, in <module>
    from core.model_manager import ModelInstance
  File "/Users/a13973/dev/buddypia/dify/api/core/model_manager.py", line 4, in <module>
    from core.entities.provider_configuration import ProviderModelBundle
  File "/Users/a13973/dev/buddypia/dify/api/core/entities/provider_configuration.py", line 21, in <module>
    from core.model_runtime.model_providers import model_provider_factory
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/__init__.py", line 3, in <module>
    model_provider_factory = ModelProviderFactory()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/model_provider_factory.py", line 34, in __init__
    self.get_providers()
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/model_provider_factory.py", line 55, in get_providers
    models = model_provider_instance.models(model_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/__base/model_provider.py", line 71, in models
    model_instance = self.get_model_instance(model_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/__base/model_provider.py", line 103, in get_model_instance
    mod = import_module_from_source(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/dev/buddypia/dify/api/core/utils/module_import_helper.py", line 33, in import_module_from_source
    raise e
  File "/Users/a13973/dev/buddypia/dify/api/core/utils/module_import_helper.py", line 29, in import_module_from_source
    spec.loader.exec_module(module)
  File "/Users/a13973/dev/buddypia/dify/api/core/model_runtime/model_providers/openai/llm/llm.py", line 6, in <module>
    from openai import OpenAI, Stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/types/__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/types/batch.py", line 7, in <module>
    from .._models import BaseModel
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/_models.py", line 24, in <module>
    from ._types import (
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/openai/_types.py", line 21, in <module>
    import httpx
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 12, in <module>
    from .._synchronization import Lock
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/httpcore/_synchronization.py", line 13, in <module>
    import trio
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/__init__.py", line 23, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: split
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar, RunVarToken
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/_local.py", line 9, in <module>
    from . import _run
  File "/Users/a13973/.asdf/installs/python/3.11.5/lib/python3.11/site-packages/trio/_core/_run.py", line 2822, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform

**Comment by buddypia** [comment]
@crazywoola  Thanks. close issue
