### ISSUE TITLE
File Segmentation Failed: target_part property on _Realationship is undefined when target model is External

### ISSUE THREAD

**Issue by majestichou** [langgenius/dify#5018]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1 Download a file from the website: https://www.3gpp.org/ftp/specs/archive/38_series/38.174/38174-i40.zip, decompress the compressed package and get the file 38174-i40.docx
2 Click the Create Knowledge button of Dify, Browse, choose 38174-i40.docx and click "next" button.
3 Dify's UI shows an error message in the upper right corner: target_part property on _Realationship is undefined when target model is External
4 After chunk setting, index model and retrieval setting is done, click "sace & process" button 
5 Embedding completed but failed. Dify's UI shows an error message in the upper right corner: target_part property on _Realationship is undefined when target model is External. 

### ✔️ Expected Behavior

 Embedding completed and successed

### ❌ Actual Behavior

File Segmentation Failed: target_part property on _Realationship is undefined when target model is External

**Comment by majestichou** [comment]
您好：
   您发给我的信件已经收到。
   这是邮件系统自动回复。

                             侯宏伟

**Comment by majestichou** [comment]
@crazywoola @JohnJyong 
I used the latest version 0.6.11 and the error is still there. 
**Note that I'm running the docker image in an offline environment.  I can't download external internet resources while running the program.**
I checked the docker-api-1 container logs and the error is as follows:
```
2024-06-27 09:30:38.583 ERROR [Dummy-1] [app.py:838] - Exception on /console/api/datasets/0513f3f6-bba5-4ffe-bc97-f4b4add28477/batch/20240627093029550913/indexing-estimate [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 225, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.10/site-packages/gevent/resolver/thread.py", line 63, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/usr/local/lib/python3.10/site-packages/gevent/_compat.py", line 49, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/gevent/threadpool.py", line 173, in __run_task
    thread_result.set(func(*args, **kwargs))
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 238, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7fa207945450>: Failed to resolve 'schemas.openxmlformats.org' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='schemas.openxmlformats.org', port=80): Max retries exceeded with url: /officeDocument/2006/relationships/image (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fa207945450>: Failed to resolve 'schemas.openxmlformats.org' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 86, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/datasets/datasets_document.py", line 487, in get
    response = indexing_runner.indexing_estimate(current_user.current_tenant_id, extract_settings,
  File "/app/api/core/indexing_runner.py", line 267, in indexing_estimate
    text_docs = index_processor.extract(extract_setting, process_rule_mode=tmp_processing_rule["mode"])
  File "/app/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 21, in extract
    text_docs = ExtractProcessor.extract(extract_setting=extract_setting,
  File "/app/api/core/rag/extractor/extract_processor.py", line 148, in extract
    return extractor.extract()
  File "/app/api/core/rag/extractor/word_extractor.py", line 59, in extract
    content = self.parse_docx(self.file_path, 'storage')
  File "/app/api/core/rag/extractor/word_extractor.py", line 155, in parse_docx
    image_map = self._extract_images_from_docx(doc, image_folder)
  File "/app/api/core/rag/extractor/word_extractor.py", line 81, in _extract_images_from_docx
    response = requests.get(url, stream=True)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='schemas.openxmlformats.org', port=80): Max retries exceeded with url: /officeDocument/2006/relationships/image (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fa207945450>: Failed to resolve 'schemas.openxmlformats.org' ([Errno -3] Temporary failure in name resolution)"))
```
