### ISSUE TITLE
Failed to perform the hit testing on database

### ISSUE THREAD

**Issue by Faultiness** [langgenius/dify#5041]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Create a database and add several txt document
2. Enable automatic segmentation and cleaning; Enable self-QA mode
3. Set the indexing method to mixed retrieval
4. Wait until finish

### ❌ Actual Behavior

When performing the hit testing. It returns 
`Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_38f171a7_1173_490c_b285_e5c59efad2a5_Node" on type "GetObjectsObj". Did you mean "Vector_index_78ed1ca9_15c0_4fff_8995_d8632964e0a6_Node" or "Vector_index_a37b9418_81e7_43d2_9f0d_11088ccc82e5_Node"?', 'path': None}]`

**Comment by JohnJyong** [comment]
pls provide your embedding model and vdb name, if possible ,pls attache your error logs , tks @Faultiness

**Comment by Faultiness** [comment]
Thanks for your reply.

The embedding model is `text-embedding-3-large` from OpenAI. And, how to check the vdb name?
The log of container `api` when performing the hit testing is:
```
ERROR:root:Hit testing failed.
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/hit_testing.py", line 56, in post
    response = HitTestingService.retrieve(
  File "/app/api/services/hit_testing_service.py", line 58, in retrieve
    all_documents = RetrievalService.retrieve(retrival_method=retrieval_model['search_method'],
  File "/app/api/core/rag/datasource/retrieval_service.py", line 86, in retrieve
    raise Exception(exception_message)
Exception: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_38f171a7_1173_490c_b285_e5c59efad2a5_Node" on type "GetObjectsObj". Did you mean "Vector_index_78ed1ca9_15c0_4fff_8995_d8632964e0a6_Node" or "Vector_index_a37b9418_81e7_43d2_9f0d_11088ccc82e5_Node"?', 'path': None}];
Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_38f171a7_1173_490c_b285_e5c59efad2a5_Node" on type "GetObjectsObj". Did you mean "Vector_index_78ed1ca9_15c0_4fff_8995_d8632964e0a6_Node" or "Vector_index_a37b9418_81e7_43d2_9f0d_11088ccc82e5_Node"?', 'path': None}]
ERROR:app:Exception on /console/api/datasets/38f171a7-1173-490c-b285-e5c59efad2a5/hit-testing [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/hit_testing.py", line 56, in post
    response = HitTestingService.retrieve(
  File "/app/api/services/hit_testing_service.py", line 58, in retrieve
    all_documents = RetrievalService.retrieve(retrival_method=retrieval_model['search_method'],
  File "/app/api/core/rag/datasource/retrieval_service.py", line 86, in retrieve
    raise Exception(exception_message)
Exception: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_38f171a7_1173_490c_b285_e5c59efad2a5_Node" on type "GetObjectsObj". Did you mean "Vector_index_78ed1ca9_15c0_4fff_8995_d8632964e0a6_Node" or "Vector_index_a37b9418_81e7_43d2_9f0d_11088ccc82e5_Node"?', 'path': None}];
Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_38f171a7_1173_490c_b285_e5c59efad2a5_Node" on type "GetObjectsObj". Did you mean "Vector_index_78ed1ca9_15c0_4fff_8995_d8632964e0a6_Node" or "Vector_index_a37b9418_81e7_43d2_9f0d_11088ccc82e5_Node"?', 'path': None}]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 86, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/datasets/hit_testing.py", line 83, in post
    raise InternalServerError(str(e))
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_38f171a7_1173_490c_b285_e5c59efad2a5_Node" on type "GetObjectsObj". Did you mean "Vector_index_78ed1ca9_15c0_4fff_8995_d8632964e0a6_Node" or "Vector_index_a37b9418_81e7_43d2_9f0d_11088ccc82e5_Node"?', 'path': None}];
Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_38f171a7_1173_490c_b285_e5c59efad2a5_Node" on type "GetObjectsObj". Did you mean "Vector_index_78ed1ca9_15c0_4fff_8995_d8632964e0a6_Node" or "Vector_index_a37b9418_81e7_43d2_9f0d_11088ccc82e5_Node"?', 'path': None}]
```

**Comment by AlpineLX** [comment]
I met the same error and the logs are below:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/api/core/rag/datasource/retrieval_service.py", line 121, in embedding_search
    documents = vector.search_by_vector(
  File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 226, in search_by_vector
    return self._vector_processor.search_by_vector(query_vector, **kwargs)
  File "/app/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 194, in search_by_vector
    raise ValueError(f"Error during query: {result['errors']}")
ValueError: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_022c31c8_78db_4366_afac_d70a6fdfad3b_Node" on type "GetObjectsObj". Did you mean "Vector_index_e494c3c2_8dab_4448_877d_52ab4bba51c4_Node"?', 'path': None}]
Exception in thread Thread-153 (embedding_search):
`
The logs are different while the error almost the same.
And about 1 hour later, the system was self-repaired. I'm wondering how it happened.

Thanks!

**Comment by jiaolongxue** [comment]
use **weaviate**
errlog
```
ERROR:app:Exception on /console/api/datasets/4783a214-77f6-4c08-b906-985e764bd2ff/hit-testing [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/hit_testing.py", line 56, in post
    response = HitTestingService.retrieve(
  File "/app/api/services/hit_testing_service.py", line 58, in retrieve
    all_documents = RetrievalService.retrieve(retrival_method=retrieval_model['search_method'],
  File "/app/api/core/rag/datasource/retrieval_service.py", line 86, in retrieve
    raise Exception(exception_message)
Exception: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_4783a214_77f6_4c08_b906_985e764bd2ff_Node" on type "GetObjectsObj". Did you mean "Vector_index_7b33c44a_cf66_410c_b741_9d366eef0d6f_Node", "Vector_index_05be79ff_47f2_40d8_a320_4e8e4b126e5a_Node", "Vector_index_b8c0a266_8213_4c78_a8d7_de611697c079_Node", "Vector_index_e83fd1c5_742d_4943_ba91_57f151842dba_Node", or "Vector_index_923a570d_7d35_46be_99bf_40fe48b875da_Node"?', 'path': None}];
Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_4783a214_77f6_4c08_b906_985e764bd2ff_Node" on type "GetObjectsObj". Did you mean "Vector_index_b8c0a266_8213_4c78_a8d7_de611697c079_Node", "Vector_index_7b33c44a_cf66_410c_b741_9d366eef0d6f_Node", "Vector_index_05be79ff_47f2_40d8_a320_4e8e4b126e5a_Node", "Vector_index_e83fd1c5_742d_4943_ba91_57f151842dba_Node", or "Vector_index_923a570d_7d35_46be_99bf_40fe48b875da_Node"?', 'path': None}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 86, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/datasets/hit_testing.py", line 83, in post
    raise InternalServerError(str(e))
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_4783a214_77f6_4c08_b906_985e764bd2ff_Node" on type "GetObjectsObj". Did you mean "Vector_index_7b33c44a_cf66_410c_b741_9d366eef0d6f_Node", "Vector_index_05be79ff_47f2_40d8_a320_4e8e4b126e5a_Node", "Vector_index_b8c0a266_8213_4c78_a8d7_de611697c079_Node", "Vector_index_e83fd1c5_742d_4943_ba91_57f151842dba_Node", or "Vector_index_923a570d_7d35_46be_99bf_40fe48b875da_Node"?', 'path': None}];
Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'Cannot query field "Vector_index_4783a214_77f6_4c08_b906_985e764bd2ff_Node" on type "GetObjectsObj". Did you mean "Vector_index_b8c0a266_8213_4c78_a8d7_de611697c079_Node", "Vector_index_7b33c44a_cf66_410c_b741_9d366eef0d6f_Node", "Vector_index_05be79ff_47f2_40d8_a320_4e8e4b126e5a_Node", "Vector_index_e83fd1c5_742d_4943_ba91_57f151842dba_Node", or "Vector_index_923a570d_7d35_46be_99bf_40fe48b875da_Node"?', 'path': None}]

```

**Comment by zangkaiqiang** [comment]
same error when change embedding method, and restore to the old embedding can not fix the error

**Comment by hzjkaka** [comment]
**vdb**: Weaviate
**step**:  change text-embedding-ada-002  to  text-embedding-3-large
We have the same error, using the vdb Weaviate, found that after switching to embedding_model, the index data of the previous model will be deleted. 
**Here are our guesses:** 
DatasetService. Update_dataset (dataset_id, data, user) will change the following action to update type after changing the model. After deal_dataset_vector_index_task is executed, the system clears the index and creates a new index after checking whether the update type is correct. Therefore, the old index is deleted in different models, causing the query to fail.
**code are below:**
<img width="679" alt="image" src="https://github.com/user-attachments/assets/2904b30c-30ff-4099-b83d-e8e5725040fc">

<img width="620" alt="image" src="https://github.com/user-attachments/assets/dfb8a778-01e6-4c6f-8c8b-55b081a03e37">

Please help me to tell how it happened. Thanks.

**Comment by crazywoola** [comment]
@JohnJyong

**Comment by soulzzz** [comment]
> same error when change embedding method, and restore to the old embedding can not fix the error

Same here,any fix?
