### ISSUE TITLE
sqlalchemy.exc.InvalidRequestError: Could not refresh instance '<WorkflowNodeExecution at 0x7fad6504f040>'

### ISSUE THREAD

**Issue by NiuBlibing** [langgenius/dify#5796]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

send many requests.

### ✔️ Expected Behavior

All requests is successful.

### ❌ Actual Behavior

Some success failed with 'curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)'.
API error log:
```
[2024-07-01 03:25:06 +0000] [227] [ERROR] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 115, in handle_request
for item in respiter:
File "/usr/local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
return self._next()
File "/usr/local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
for item in iterable:
File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 113, in generator
yield from gen
File "/app/api/libs/helper.py", line 162, in generate
yield from response
File "/app/api/core/app/apps/base_app_generate_response_converter.py", line 28, in _generate
for chunk in cls.convert_stream_full_response(response):
File "/app/api/core/app/apps/workflow/generate_response_converter.py", line 45, in convert_stream_full_response
for chunk in stream_response:
File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 155, in _to_stream_response
for stream_response in generator:
File "/app/api/core/app/apps/workflow/generate_task_pipeline.py", line 180, in _process_stream_response
workflow_node_execution = self._handle_node_start(event)
File "/app/api/core/app/task_pipeline/workflow_cycle_manage.py", line 415, in _handle_node_start
workflow_node_execution = self._init_node_execution_from_workflow_run(
File "/app/api/core/app/task_pipeline/workflow_cycle_manage.py", line 188, in _init_node_execution_from_workflow_run
db.session.refresh(workflow_node_execution)
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 1767, in refresh
return self._proxied.refresh(
File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3169, in refresh
raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Could not refresh instance '<WorkflowNodeExecution at 0x7fad6504f040>'
```

**Comment by NiuBlibing** [comment]
@dosu. not work.

**Comment by NiuBlibing** [comment]
@takatost could you help with this workflow issue?

**Comment by NiuBlibing** [comment]
https://github.com/langgenius/dify/issues/5794
Same reason: postgresql consistency of master and slave.
