### ISSUE TITLE
upgrade  0.6.12-fix1 fail

### ISSUE THREAD

**Issue by lm970585581** [langgenius/dify#5823]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When I upgrade the version using source code, after executing `poetry install` to install dependencies, running `poetry shell` and `flask db upgrade` commands results in a direct error:

```
Traceback (most recent call last):
  File "D:\ProgramData\miniconda3\envs\dify\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\miniconda3\envs\dify\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\miniconda3\envs\dify\Scripts\flask.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\flask\cli.py", line 1105, in main
    cli.main()
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\click\core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\click\core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\flask\cli.py", line 611, in get_command
    app = info.load_app()
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\flask\cli.py", line 339, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
  File "D:\workSpace\algorithm-platform\dify\api\app.py", line 29, in <module>
    from events import event_handlers
  File "D:\workSpace\algorithm-platform\dify\api\events\event_handlers\__init__.py", line 1, in <module>
    from .clean_when_dataset_deleted import handle
  File "D:\workSpace\algorithm-platform\dify\api\events\event_handlers\clean_when_dataset_deleted.py", line 2, in <module>
    from tasks.clean_dataset_task import clean_dataset_task
  File "D:\workSpace\algorithm-platform\dify\api\tasks\clean_dataset_task.py", line 7, in <module>
    from core.rag.index_processor.index_processor_factory import IndexProcessorFactory
  File "D:\workSpace\algorithm-platform\dify\api\core\rag\index_processor\index_processor_factory.py", line 6, in <module>
    from core.rag.index_processor.processor.qa_index_processor import QAIndexProcessor
  File "D:\workSpace\algorithm-platform\dify\api\core\rag\index_processor\processor\qa_index_processor.py", line 12, in <module>
    from core.llm_generator.llm_generator import LLMGenerator
  File "D:\workSpace\algorithm-platform\dify\api\core\llm_generator\llm_generator.py", line 14, in <module>
    from core.ops.ops_trace_manager import TraceQueueManager, TraceTask, TraceTaskName
  File "D:\workSpace\algorithm-platform\dify\api\core\ops\ops_trace_manager.py", line 29, in <module>
    from core.ops.langfuse_trace.langfuse_trace import LangFuseDataTrace
  File "D:\workSpace\algorithm-platform\dify\api\core\ops\langfuse_trace\langfuse_trace.py", line 7, in <module>
    from langfuse import Langfuse
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langfuse\__init__.py", line 3, in <module>
    from .client import Langfuse  # noqa
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langfuse\client.py", line 58, in <module>
    from langfuse.request import LangfuseClient
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langfuse\request.py", line 10, in <module>
    from langfuse.serializer import EventSerializer
    from langchain.load.serializable import Serializable
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langchain\agents\__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langchain\agents\agent.py", line 15, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langchain\agents\agent_iterator.py", line 21, in <module>
    from langchain.callbacks.manager import (
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langchain\callbacks\__init__.py", line 10, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langchain\callbacks\aim_callback.py", line 5, in <module>
    from langchain.schema import AgentAction, AgentFinish, LLMResult
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langchain\schema\__init__.py", line 18, in <module>
    from langchain.schema.output import (
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langchain\schema\output.py", line 49, in <module>
    class ChatGeneration(Generation):
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\langchain\schema\output.py", line 58, in ChatGeneration
    def set_text(cls, values: Dict[str, Any]) -> Dict[str, Any]:
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\pydantic\deprecated\class_validators.py", line 243, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "D:\ProgramData\miniconda3\envs\dify\lib\site-packages\pydantic\deprecated\class_validators.py", line 249, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.     

For further information visit https://errors.pydantic.dev/2.7/u/root-validator-pre-skip

```

Why is this happening? It feels like the dependency versions are incorrect.

**Comment by crazywoola** [comment]
See step 6

```
poetry install
poetry shell
poetry run python -m flask db upgrade
```

**Comment by orangeclk** [comment]
I had the same problem, and this solution does not work.
I still have the conda environment, I don't know if it's affecting it or not, I'll keep trying.

> See step 6
> 
> ```
> poetry install
> poetry shell
> poetry run python -m flask db upgrade
> ```

**Comment by Sumkor** [comment]
I upgrade from 0.6.2 to 0.6.15 and find the same problem.

**Comment by lyy4758** [comment]
> I upgrade from 0.6.2 to 0.6.15 and find the same problem.
> 
> I try to reinstall pydantic but doesn't work.
> 
> ```
> pip uninstall pydantic
> pip install "pydantic==2.*"
> ```
> 
> Instand, it throw this error：
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> langchain 0.0.250 requires dataclasses-json<0.6.0,>=0.5.7, but you have dataclasses-json 0.6.7 which is incompatible.
> langchain 0.0.250 requires langsmith<0.1.0,>=0.0.11, but you have langsmith 0.1.93 which is incompatible.
> langchain 0.0.250 requires pydantic<2,>=1, but you have pydantic 2.8.2 which is incompatible.
> ```
> 
> At last I uninstall langchain and it solved the problem.
> 
> ```
> pip uninstall langchain
> poetry install
> flask db upgrade
> ```

Thank you for the solution, it worked perfectly!
