### ISSUE TITLE
When using code node, we get an `IndexError: list index out of range` error

### ISSUE THREAD

**Issue by xia-huang-411303** [langgenius/dify#6139]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When using code node, code execution returns an 'array[object]' that contains dict with float values.
When the numerical checker `self._check_number` checks precision,  `str(value)` converts the float to scientific notation, 
resulting in a split error and an `'IndexError' : list index out of range `error
For example, when `value = 0.00008`, the result of `str(value)` is '8e-05' with no decimal point, causing a precision check error.

### ❌ Actual Behavior

2024-07-10 11:14:16 2024-07-10 03:14:16,257.257 ERROR [Thread-572 (_generate_worker)] [workflow_engine_manager.py:834] - Node 代码执行 run failed: list index out of range
2024-07-10 11:14:16 Traceback (most recent call last):
2024-07-10 11:14:16   File "/app/api/core/workflow/workflow_engine_manager.py", line 825, in _run_workflow_node
2024-07-10 11:14:16     node_run_result = node.run(
2024-07-10 11:14:16   File "/app/api/core/workflow/nodes/base_node.py", line 90, in run
2024-07-10 11:14:16     result = self._run(
2024-07-10 11:14:16   File "/app/api/core/workflow/nodes/code/code_node.py", line 77, in _run
2024-07-10 11:14:16     result = self._transform_result(result, node_data.outputs)
2024-07-10 11:14:16   File "/app/api/core/workflow/nodes/code/code_node.py", line 276, in _transform_result
2024-07-10 11:14:16     transformed_result[output_name] = [
2024-07-10 11:14:16   File "/app/api/core/workflow/nodes/code/code_node.py", line 277, in <listcomp>
2024-07-10 11:14:16     self._transform_result(
2024-07-10 11:14:16   File "/app/api/core/workflow/nodes/code/code_node.py", line 150, in _transform_result
2024-07-10 11:14:16     self._check_number(
2024-07-10 11:14:16   File "/app/api/core/workflow/nodes/code/code_node.py", line 121, in _check_number
2024-07-10 11:14:16     if len(str(value).split('.')[1]) > MAX_PRECISION:
2024-07-10 11:14:16 IndexError: list index out of range

**Comment by xia-huang-411303** [comment]
Suggestions for modification:
For /app/api/core/workflow/nodes/code/code_node.py >>> CodeNode._check_number
```python
    def _check_number(self, value: Union[int, float], variable: str) -> Union[int, float]:
        """
        Check number
        :param value: value
        :param variable: variable
        :return:
        """
        if not isinstance(value, int | float):
            raise ValueError(f"Output variable `{variable}` must be a number")

        if value > MAX_NUMBER or value < MIN_NUMBER:
            raise ValueError(f'Output variable `{variable}` is out of range, it must be between {MIN_NUMBER} and {MAX_NUMBER}.')

        if isinstance(value, float):
            # raise error if precision is too high
            from decimal import Decimal
            decimal_value = Decimal(str(value))
            if abs(decimal_value.as_tuple().exponent) > MAX_PRECISION:
                raise ValueError(f'Output variable `{variable}` has too high precision, it must be less than {MAX_PRECISION} digits.')

        return value
```

**Comment by crazywoola** [comment]
Please feel free to open a pull request to fix this. :) Much appreciate.
