### ISSUE TITLE
forbidden: user 'anonymous' has insufficient permissions to list schema/*

### ISSUE THREAD

**Issue by boxter007** [langgenius/dify#6262]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.13

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1、Start middleware using docker-compose.middleware.yaml
2、Knowledge-->create knowledge-->choose one file -->index mode (High Quality),vector index(jina-embeddings-v2-base-zh| rerank:jina-reranker-v2-base-multilingual)-->save and process-->ERROR:

```
[2024-07-14 03:31:33,929: ERROR/MainProcess] consume document failed
Traceback (most recent call last):
  File "/home/haojing/code/dify/api/core/indexing_runner.py", line 76, in run
    self._load(
  File "/home/haojing/code/dify/api/core/indexing_runner.py", line 689, in _load
    tokens += future.result()
              ^^^^^^^^^^^^^^^
  File "/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haojing/code/dify/api/core/indexing_runner.py", line 742, in _process_chunk
    index_processor.load(dataset, chunk_documents, with_keywords=False)
  File "/home/haojing/code/dify/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 60, in load
    vector.create(documents)
  File "/home/haojing/code/dify/api/core/rag/datasource/vdb/vector_factory.py", line 99, in create
    self._vector_processor.create(
  File "/home/haojing/code/dify/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 89, in create
    self._create_collection()
  File "/home/haojing/code/dify/api/core/rag/datasource/vdb/weaviate/weaviate_vector.py", line 100, in _create_collection
    if not self._client.schema.contains(schema):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haojing/code/dify/api/.venv/lib/python3.11/site-packages/weaviate/schema/crud_schema.py", line 320, in contains
    loaded_schema = self.get()
                    ^^^^^^^^^^
  File "/home/haojing/code/dify/api/.venv/lib/python3.11/site-packages/weaviate/schema/crud_schema.py", line 506, in get
    raise UnexpectedStatusCodeException("Get schema", response)
weaviate.exceptions.UnexpectedStatusCodeException: Get schema! Unexpected status code: 403, with response body: {'error': [{'message': "forbidden: user 'anonymous' has insufficient permissions to list schema/*"}]}.
```

**Comment by boxter007** [comment]
do not make sence

**Comment by crazywoola** [comment]
I think it's related to this [thread](https://forum.weaviate.io/t/auth-defaults-to-anonymous-when-connecting-from-host-vs-container/634/5)
