### ISSUE TITLE
Error: argument should be a bytes-like object or ASCII string, not 'list'

### ISSUE THREAD

**Issue by lem0ke** [langgenius/dify#6440]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Deployed using docker and with the .env file properly configured, after updating from 0.6.11 to 0.6.14, both the recall test of the knowledgebase and the test into the previously created app report an error:[openai] Error: argument should be a bytes-like object or ASCII string, not 'list'. After opening debug mode, part of the log for container api-1 is as follows:

```
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Preparing database migration...
Start database migration.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Database migration successful!
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
 * Serving Flask app 'app.py'
 * Debug mode: on
2024-07-18 15:34:12,233.233 INFO [MainThread] [_internal.py:97] - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://172.25.0.7:5001
2024-07-18 15:34:12,233.233 INFO [MainThread] [_internal.py:97] - [33mPress CTRL+C to quit[0m
2024-07-18 15:34:12,237.237 INFO [MainThread] [_internal.py:97] -  * Restarting with stat
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2024-07-18 15:34:23,267.267 WARNING [MainThread] [_internal.py:97] -  * Debugger is active!
2024-07-18 15:34:23,267.267 INFO [MainThread] [_internal.py:97] -  * Debugger PIN: 429-943-275
2024-07-18 15:35:52,569.569 INFO [Thread-3 (embedding_search)] [_client.py:1026] - HTTP Request: POST https://api.holdai.top/v1/embeddings "HTTP/1.1 200 OK"
2024-07-18 15:35:52,900.900 ERROR [Thread-2 (process_request_thread)] [hit_testing.py:82] - Hit testing failed.
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/hit_testing.py", line 56, in post
    response = HitTestingService.retrieve(
  File "/app/api/services/hit_testing_service.py", line 41, in retrieve
    all_documents = RetrievalService.retrieve(retrival_method=retrieval_model['search_method'],
  File "/app/api/core/rag/datasource/retrieval_service.py", line 87, in retrieve
    raise Exception(exception_message)
Exception: [openai] Error: argument should be a bytes-like object or ASCII string, not 'list'
2024-07-18 15:35:52,902.902 ERROR [Thread-2 (process_request_thread)] [app.py:838] - Exception on /console/api/datasets/b648cd21-5e6d-423a-8038-a78c6f8f89d6/hit-testing [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/datasets/hit_testing.py", line 56, in post
    response = HitTestingService.retrieve(
  File "/app/api/services/hit_testing_service.py", line 41, in retrieve
    all_documents = RetrievalService.retrieve(retrival_method=retrieval_model['search_method'],
  File "/app/api/core/rag/datasource/retrieval_service.py", line 87, in retrieve
    raise Exception(exception_message)
Exception: [openai] Error: argument should be a bytes-like object or ASCII string, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 74, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 21, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/datasets/hit_testing.py", line 83, in post
    raise InternalServerError(str(e))
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: [openai] Error: argument should be a bytes-like object or ASCII string, not 'list'
2024-07-18 15:35:52,904.904 INFO [Thread-2 (process_request_thread)] [_internal.py:97] - 172.25.0.9 - - [18/Jul/2024 15:35:52] "[35m[1mPOST /console/api/datasets/b648cd21-5e6d-423a-8038-a78c6f8f89d6/hit-testing HTTP/1.1[0m" 500 -
```

**Comment by 1WorldCapture** [comment]
Same issue with version 0.6.14, but the issue is only for openai embedding model.

**Comment by lem0ke** [comment]
How do I temporarily restore my app? Right now it hasn't been working properly because of the issue

**Comment by JohnJyong** [comment]
If you are using a third-party openai service ， pls use the open-ai compatible .
Because for openai embedding service, we are using base64 as the response type to improve return speed
, but the thrid-party doesn't suppport. @lem0ke @1WorldCapture 
![image](https://github.com/user-attachments/assets/e05a550c-16bf-42f4-9058-77fc5fbaf056)

**Comment by lem0ke** [comment]
> If you are using a third-party openai service ， pls use the open-ai compatible . Because for openai embedding service, we are using base64 as the response type to improve return speed , but the thrid-party doesn't suppport. @lem0ke @1WorldCapture ![image](https://private-user-images.githubusercontent.com/76649700/350884891-e05a550c-16bf-42f4-9058-77fc5fbaf056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDQ4NjUsIm5iZiI6MTcyMTY0NDU2NSwicGF0aCI6Ii83NjY0OTcwMC8zNTA4ODQ4OTEtZTA1YTU1MGMtMTZiZi00MmY0LTkwNTgtNzdmYzVmYmFmMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDEwMzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YTQ1MjhjMjc3NWU2NTFmY2M1ZjIyNjBmNTA3ODdmNTdhMDI2YjdkYzliYjJjYTcxMzIzOTJlNDBhYTI3MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hfdyjJ2YIbxrWEpqNQzt8pWzW8uBdllELwfMxSdoipI)

But this is available in 0.6.11

**Comment by rnthking** [comment]
<img width="1940" alt="image" src="https://github.com/user-attachments/assets/a29f8397-abfa-400d-b08e-012e6bbcc1f8">

I met the same problem.  I have done a  testing. I found  the error occur only when I  choose an openai embedding model. hope you guys of dify fixed it as quickly as possible.

**Comment by zcunyi** [comment]
> <img alt="image" width="1940" src="https://private-user-images.githubusercontent.com/4058956/353790886-a29f8397-abfa-400d-b08e-012e6bbcc1f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTMzOTEsIm5iZiI6MTcyNDkxMzA5MSwicGF0aCI6Ii80MDU4OTU2LzM1Mzc5MDg4Ni1hMjlmODM5Ny1hYmZhLTQwMGQtYjA4ZS0wMTJlNmJiY2MxZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDYzMTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjE3MzU0ZTczOTk1ZTlmMmZiNzM3NWE0YTNhZmQzMzBhZTk3ZDhhZjljZjA2ZjJkNjIyYTg3YTg4MmI5MjE0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eiN5j1_JGd5CycpZJDCuNnhDHw5761xZILB7uNUb_W8">
> I met the same problem. I have done a testing which I found the error occur only when I choose an openai embedding model. hope you guys of dify to fixed it as quickly as possible.
> 
> my Dify's version is 0.6.15, the lastest version in recently

I have the same error when I use the DIFY.

**Comment by Clouder0** [comment]
I've tried using OpenAI compatible entry and still got the same error. Any option to switch off base64 optimization?

**Comment by chankwongyin** [comment]
same issue

**Comment by jtsang4** [comment]
Encountered the same issue when using OpenAI compatible API.
