### ISSUE TITLE
Ater finished install steps,flash site then show Application Err

### ISSUE THREAD

**Issue by infoBrainSys** [langgenius/dify#6538]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

`docker-compose logs` looks fine but still an err 
![image](https://github.com/user-attachments/assets/d22025fd-7c31-47b0-b813-7574d91c632e)

```js
TronLink initiated
apps:1 
        
        
       GET https://dify.iscrooge.cn/_next/static/chunks/8853-d72bfb64091bfa07.js net::ERR_ABORTED 502 (Bad Gateway)
apps:1 Refused to execute script from 'https://dify.iscrooge.cn/_next/static/chunks/8853-d72bfb64091bfa07.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
apps:1 
        
        
       GET https://dify.iscrooge.cn/_next/static/chunks/5395-77456fbe6a75b515.js net::ERR_ABORTED 502 (Bad Gateway)
apps:1 Refused to execute script from 'https://dify.iscrooge.cn/_next/static/chunks/5395-77456fbe6a75b515.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
apps:1 
        
        
       GET https://dify.iscrooge.cn/_next/static/chunks/9373-26e75fed19541bb1.js net::ERR_ABORTED 502 (Bad Gateway)
apps:1 Refused to execute script from 'https://dify.iscrooge.cn/_next/static/chunks/9373-26e75fed19541bb1.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
7023-22d2def46e6e81aa.js:1 ChunkLoadError
    at s.f.j (webpack-1dda65bd14bc0fda.js:1:4548)
    at webpack-1dda65bd14bc0fda.js:1:1427
    at Array.reduce (<anonymous>)
    at s.e (webpack-1dda65bd14bc0fda.js:1:1393)
    at 7023-22d2def46e6e81aa.js:2:18878
    at 7023-22d2def46e6e81aa.js:2:19080
    at t (7023-22d2def46e6e81aa.js:2:19283)
window.console.error @ 7023-22d2def46e6e81aa.js:1
l_ @ fd9d1056-7863749520a823c0.js:1
n.callback @ fd9d1056-7863749520a823c0.js:1
nB @ fd9d1056-7863749520a823c0.js:1
nV @ fd9d1056-7863749520a823c0.js:1
aq @ fd9d1056-7863749520a823c0.js:1
aY @ fd9d1056-7863749520a823c0.js:1
a9 @ fd9d1056-7863749520a823c0.js:1
aY @ fd9d1056-7863749520a823c0.js:1
a9 @ fd9d1056-7863749520a823c0.js:1
aY @ fd9d1056-7863749520a823c0.js:1
a9 @ fd9d1056-7863749520a823c0.js:1
aY @ fd9d1056-7863749520a823c0.js:1
a9 @ fd9d1056-7863749520a823c0.js:1
aY @ fd9d1056-7863749520a823c0.js:1
a9 @ fd9d1056-7863749520a823c0.js:1
aY @ fd9d1056-7863749520a823c0.js:1
a9 @ fd9d1056-7863749520a823c0.js:1
aY @ fd9d1056-7863749520a823c0.js:1
a9 @ fd9d1056-7863749520a823c0.js:1
aY @ fd9d1056-7863749520a823c0.js:1
a9 @ fd9d1056-7863749520a823c0.js:1
aY @ fd9d1056-7863749520a823c0.js:1
（匿名） @ fd9d1056-7863749520a823c0.js:1
is @ fd9d1056-7863749520a823c0.js:1
o1 @ fd9d1056-7863749520a823c0.js:1
oZ @ fd9d1056-7863749520a823c0.js:1
T @ 7023-22d2def46e6e81aa.js:1
fd9d1056-7863749520a823c0.js:1 Uncaught Error: Minified React error #423; visit https://react.dev/errors/423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iZ (fd9d1056-7863749520a823c0.js:1:118352)
    at ia (fd9d1056-7863749520a823c0.js:1:95165)
    at fd9d1056-7863749520a823c0.js:1:94987
    at il (fd9d1056-7863749520a823c0.js:1:94994)
    at oJ (fd9d1056-7863749520a823c0.js:1:92350)
    at oZ (fd9d1056-7863749520a823c0.js:1:91769)
    at MessagePort.T (7023-22d2def46e6e81aa.js:1:84205)
```

### ✔️ Expected Behavior

should be run normal

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/6527
