### ISSUE TITLE
poetry run python -m flask db upgrade failed

### ISSUE THREAD

**Issue by rainsoft** [langgenius/dify#6701]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

main branch

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

```shell
poetry run python -m flask db upgrade
```

### ✔️ Expected Behavior

upgrade db success.

### ❌ Actual Behavior

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2024-07-26 03:36:49,564.564 WARNING [MainThread] [ext_mail.py:50] - MAIL_TYPE is not set
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 88072f0caa04 -> 187385f442fc, modify provider model name length
INFO  [alembic.runtime.migration] Running upgrade 187385f442fc -> 89c7899ca936, empty message
INFO  [alembic.runtime.migration] Running upgrade 89c7899ca936 -> 3ef9b2b6bee6, add_assistant_app
INFO  [alembic.runtime.migration] Running upgrade 3ef9b2b6bee6 -> ad472b61a054, add api provider icon
INFO  [alembic.runtime.migration] Running upgrade ad472b61a054 -> 8ec536f3c800, rename api provider credentials
INFO  [alembic.runtime.migration] Running upgrade 8ec536f3c800 -> 00bacef91f18, rename api provider description
INFO  [alembic.runtime.migration] Running upgrade 00bacef91f18 -> f25003750af4, add created/updated at
INFO  [alembic.runtime.migration] Running upgrade f25003750af4 -> c71211c8f604, add tool_invoke_model_log
INFO  [alembic.runtime.migration] Running upgrade c71211c8f604 -> 114eed84c228, remove tool id from model invoke
INFO  [alembic.runtime.migration] Running upgrade 114eed84c228 -> 4829e54d2fee, change message chain id to nullable
INFO  [alembic.runtime.migration] Running upgrade 4829e54d2fee -> 053da0c1d756, add api tool privacy
INFO  [alembic.runtime.migration] Running upgrade 053da0c1d756 -> 4823da1d26cf, add tool file
INFO  [alembic.runtime.migration] Running upgrade 4823da1d26cf -> 9fafbd60eca1, add message file belongs to
INFO  [alembic.runtime.migration] Running upgrade 9fafbd60eca1 -> 8ae9bc661daa, add tool conversation variables idx
INFO  [alembic.runtime.migration] Running upgrade 8ae9bc661daa -> 23db93619b9d, add message files into agent thought
INFO  [alembic.runtime.migration] Running upgrade 23db93619b9d -> de95f5c77138, migration serpapi_api_key
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/flask/__main__.py", line 3, in <module>
    main()
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 1105, in main
    cli.main()
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/flask/cli.py", line 386, in decorator
    return ctx.invoke(f, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/flask_migrate/cli.py", line 154, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/alembic/command.py", line 406, in upgrade
    script.run_env()
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/Rain/Documents/workspace/aip/dify/api/migrations/env.py", line 112, in <module>
    run_migrations_online()
  File "/Users/Rain/Documents/workspace/aip/dify/api/migrations/env.py", line 106, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/Rain/Documents/workspace/aip/dify/api/.venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/Users/Rain/Documents/workspace/aip/dify/api/migrations/versions/de95f5c77138_migration_serpapi_api_key.py", line 59, in upgrade
    id = tool_provider['id']
         ~~~~~~~~~~~~~^^^^^^
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 54, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str

**Comment by crazywoola** [comment]
Can't reproduce  in latest main branch. Also you are using the wrong env setting `.venv/lib/python3.12`.

**Comment by sashasimkin** [comment]
I had the same error on 0.9.1 today.

@crazywoola I assume that it's not reproducible in `main` because `"SELECT * FROM tool_providers WHERE tool_name = 'serpapi'"` returns 0 rows.

Dosu got the issue almost right, and after applying the following path - the migration completed succesfully:
```
diff --git a/api/migrations/versions/de95f5c77138_migration_serpapi_api_key.py b/api/migrations/versions/de95f5c77138_migration_serpapi_api_key.py
index fcca705d2..6806d647a 100644
--- a/api/migrations/versions/de95f5c77138_migration_serpapi_api_key.py
+++ b/api/migrations/versions/de95f5c77138_migration_serpapi_api_key.py
@@ -56,9 +56,9 @@ def upgrade():

     # insert api_key to tool_provider_configs
     for tool_provider in tool_providers:
-        id = tool_provider['id']
-        tenant_id = tool_provider['tenant_id']
-        encrypted_credentials = tool_provider['encrypted_credentials']
+        id = tool_provider[0]
+        tenant_id = tool_provider[1]
+        encrypted_credentials = tool_provider[3]

         try:
             credentials = loads(encrypted_credentials)
@@ -75,11 +75,11 @@ def upgrade():
             sa.text(
                 "SELECT account_id FROM tenant_account_joins WHERE tenant_id = :tenant_id AND role = 'owner'"
             ),
-            tenant_id=tenant_id
-        ).fetchone()['account_id']
+            dict(tenant_id=tenant_id)
+        ).fetchone()[0]

-        created_at = tool_provider['created_at']
-        updated_at = tool_provider['updated_at']
+        created_at = tool_provider[5]
+        updated_at = tool_provider[6]

         # insert to tool_builtin_providers
         # check if exists
@@ -87,7 +87,7 @@ def upgrade():
             sa.text(
                 "SELECT * FROM tool_builtin_providers WHERE tenant_id = :tenant_id AND provider = 'google'"
             ),
-            tenant_id=tenant_id
+            dict(tenant_id=tenant_id)
         ).fetchone()
         if exists:
             continue
@@ -96,15 +96,15 @@ def upgrade():
             sa.text(
                 "INSERT INTO tool_builtin_providers (id, tenant_id, user_id, provider, encrypted_credentials, created_at, updated_at) VALUES (:id, :tenant_id, :user_id, :provider, :encrypted_credentials, :created_at, :updated_at)"
             ),
-            id=id,
+            dict(id=id,
             tenant_id=tenant_id,
             user_id=user_id,
-            provider='google',
+            provider='google',
             encrypted_credentials=encrypted_credentials,
             created_at=created_at,
-            updated_at=updated_at
+            updated_at=updated_at)
         )
-
+
     # ### end Alembic commands ###
```
