### ISSUE TITLE
本地部署dify聊天报错 openaipublic.blob.core.windows.net 443

### ISSUE THREAD

**Issue by zdm0100** [langgenius/dify#694]
dify版本0.3.10
1.本地使用k8s离线部署dify，配置了openai内网代理地址
2.验证open ai的key成功
3.创建聊天英语，聊天报错，错误日志如下：

ERROR:root:Unknown Error in completion
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/api/services/completion_service.py", line 201, in generate_worker
    Completion.generate(
  File "/app/api/core/completion.py", line 52, in generate
    rest_tokens_for_context_and_memory = cls.get_validate_rest_tokens(
  File "/app/api/core/completion.py", line 337, in get_validate_rest_tokens
    else llm.get_num_tokens_from_messages(prompt)
  File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 510, in get_num_tokens_from_messages
    model, encoding = self._get_encoding_model()
  File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 488, in _get_encoding_model
    encoding = tiktoken_.encoding_for_model(model)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 67, in encoding_for_model
    return get_encoding(model_encoding_name)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/usr/local/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 114, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 46, in read_file_cached
    contents = read_file(blobpath)
  File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 24, in read_file
    return requests.get(blobpath).content
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
ERROR:root:internal server error.
Traceback (most recent call last):
  File "/app/api/controllers/console/app/completion.py", line 158, in generate
    for chunk in response:
  File "/app/api/services/completion_service.py", line 408, in generate
    cls.handle_error(result)
  File "/app/api/services/completion_service.py", line 510, in handle_error
    raise Exception(description)
Exception: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
ERROR:app:Exception on /console/api/apps/71a1ca9e-67e8-4fb7-a14c-ddd48227768a/chat-messages [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/app/completion.py", line 158, in generate
    for chunk in response:
  File "/app/api/services/completion_service.py", line 408, in generate
    cls.handle_error(result)
  File "/app/api/services/completion_service.py", line 510, in handle_error
    raise Exception(description)
Exception: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))

**Comment by panmyuan** [comment]
> dify版本0.3.10 1.本地使用k8s离线部署dify，配置了openai内网代理地址 2.验证open ai的key成功 3.创建聊天应用，聊天报错，错误日志如下：
> 
> ERROR:root:Unknown Error in completion Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 607, in connect raise _SocketError(err, strerror(err)) TimeoutError: [Errno 110] Connection timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request self._validate_conn(conn) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn conn.connect() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect self.sock = conn = self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn raise ConnectTimeoutError( urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen retries = retries.increment( File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/app/api/services/completion_service.py", line 201, in generate_worker Completion.generate( File "/app/api/core/completion.py", line 52, in generate rest_tokens_for_context_and_memory = cls.get_validate_rest_tokens( File "/app/api/core/completion.py", line 337, in get_validate_rest_tokens else llm.get_num_tokens_from_messages(prompt) File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 510, in get_num_tokens_from_messages model, encoding = self._get_encoding_model() File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 488, in _get_encoding_model encoding = tiktoken_.encoding_for_model(model) File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 67, in encoding_for_model return get_encoding(model_encoding_name) File "/usr/local/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding enc = Encoding(**constructor()) File "/usr/local/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base mergeable_ranks = load_tiktoken_bpe( File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 114, in load_tiktoken_bpe contents = read_file_cached(tiktoken_bpe_file) File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 46, in read_file_cached contents = read_file(blobpath) File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 24, in read_file return requests.get(blobpath).content File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 507, in send raise ConnectTimeout(e, request=request) requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)')) ERROR:root:internal server error. Traceback (most recent call last): File "/app/api/controllers/console/app/completion.py", line 158, in generate for chunk in response: File "/app/api/services/completion_service.py", line 408, in generate cls.handle_error(result) File "/app/api/services/completion_service.py", line 510, in handle_error raise Exception(description) Exception: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)')) ERROR:app:Exception on /console/api/apps/71a1ca9e-67e8-4fb7-a14c-ddd48227768a/chat-messages [POST] Traceback (most recent call last): File "/app/api/controllers/console/app/completion.py", line 158, in generate for chunk in response: File "/app/api/services/completion_service.py", line 408, in generate cls.handle_error(result) File "/app/api/services/completion_service.py", line 510, in handle_error raise Exception(description) Exception: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))

我也出现这个问题了，请问如何解决的

**Comment by lifeofbow** [comment]
同求

**Comment by Jonny-Smith-GitHub** [comment]
How do you get config api

> dify版本0.3.10 1.本地使用k8s离线部署dify，配置了openai内网代理地址 2.验证open ai的key成功 3.创建聊天应用，聊天报错，错误日志如下：
> 
> ERROR:root:Unknown Error in completion Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 607, in connect raise _SocketError(err, strerror(err)) TimeoutError: [Errno 110] Connection timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request self._validate_conn(conn) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn conn.connect() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect self.sock = conn = self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn raise ConnectTimeoutError( urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)') During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen retries = retries.increment( File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/app/api/services/completion_service.py", line 201, in generate_worker Completion.generate( File "/app/api/core/completion.py", line 52, in generate rest_tokens_for_context_and_memory = cls.get_validate_rest_tokens( File "/app/api/core/completion.py", line 337, in get_validate_rest_tokens else llm.get_num_tokens_from_messages(prompt) File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 510, in get_num_tokens_from_messages model, encoding = self._get_encoding_model() File "/usr/local/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 488, in _get_encoding_model encoding = tiktoken_.encoding_for_model(model) File "/usr/local/lib/python3.10/site-packages/tiktoken/model.py", line 67, in encoding_for_model return get_encoding(model_encoding_name) File "/usr/local/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding enc = Encoding(**constructor()) File "/usr/local/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base mergeable_ranks = load_tiktoken_bpe( File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 114, in load_tiktoken_bpe contents = read_file_cached(tiktoken_bpe_file) File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 46, in read_file_cached contents = read_file(blobpath) File "/usr/local/lib/python3.10/site-packages/tiktoken/load.py", line 24, in read_file return requests.get(blobpath).content File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 507, in send raise ConnectTimeout(e, request=request) requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)')) ERROR:root:internal server error. Traceback (most recent call last): File "/app/api/controllers/console/app/completion.py", line 158, in generate for chunk in response: File "/app/api/services/completion_service.py", line 408, in generate cls.handle_error(result) File "/app/api/services/completion_service.py", line 510, in handle_error raise Exception(description) Exception: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)')) ERROR:app:Exception on /console/api/apps/71a1ca9e-67e8-4fb7-a14c-ddd48227768a/chat-messages [POST] Traceback (most recent call last): File "/app/api/controllers/console/app/completion.py", line 158, in generate for chunk in response: File "/app/api/services/completion_service.py", line 408, in generate cls.handle_error(result) File "/app/api/services/completion_service.py", line 510, in handle_error raise Exception(description) Exception: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5ef676d8d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))

How to config the openai proxy? Which items should be add to docker-compose.yaml?
