### ISSUE TITLE
When the number of segment strings exceeds context_size, resulting in an error.

### ISSUE THREAD

**Issue by nadirvishun** [langgenius/dify#7189]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.16

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

use `qwen text-embedding-v2`，it's context_size is 2048
when add segment or batch add segment, if the content is large more than 2048 ,will get error
![image](https://github.com/user-attachments/assets/0d958d34-02c6-4007-831b-9db70ae19283)

### ✔️ Expected Behavior

should auto truncate by context_size, like `ragflow`, then request api：
```python
texts = [truncate(t, 2048) for t in texts]
```

### ❌ Actual Behavior

```
2024-08-12 07:33:20,288.288 ERROR [Thread-52 (process_request_thread)] [http_request.py:181] - Request: https://dashscope.aliyuncs.com/api/v1/services/embeddings/text-embedding/text-embedding failed,
 status: 400, message: Inference error: Range of input length should be [1, 2048]
--- Logging error ---
Traceback (most recent call last):
  File "/home/vishun/dify/api/core/model_runtime/model_providers/__base/text_embedding_model.py", line 36, in invoke
    return self._invoke(model, credentials, texts, user)
  File "/home/vishun/dify/api/core/model_runtime/model_providers/tongyi/text_embedding/text_embedding.py", line 40, in _invoke
    embeddings, embedding_used_tokens = self.embed_documents(
  File "/home/vishun/dify/api/core/model_runtime/model_providers/tongyi/text_embedding/text_embedding.py", line 107, in embed_documents
    data = response.output["embeddings"][0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by nadirvishun** [comment]
@crazywoola  
I'm just using `qwen` as an example; other embedding models like `jina` should also have a `context_size` limit, right? It should be modified uniformly in a higher-level general method, not just for the `qwen` model alone.
