### ISSUE TITLE
libs.rsa.PrivkeyNotFoundError: Private key not found, tenant_id: 40aed7fc-7294-44b2-89f6-xxxxxxxxxxx 

### ISSUE THREAD

**Issue by cheneyyes** [langgenius/dify#7307]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After adding the api_key of a model, this error is reported，error msg:
2024-08-15 08:29:57,948.948 ERROR [Thread-607 (process_request_thread)] [app.py:838] - Exception on /console/api/workspaces/current/model-providers/zhipuai [POST]
Traceback (most recent call last):
  File "/Users/username/Desktop/dify/dify/api/libs/rsa.py", line 55, in get_decrypt_decoding
    private_key = storage.load(filepath)
  File "/Users/username/Desktop/dify/dify/api/extensions/ext_storage.py", line 55, in load
    return self.load_once(filename)
  File "/Users/username/Desktop/dify/dify/api/extensions/ext_storage.py", line 58, in load_once
    return self.storage_runner.load_once(filename)
  File "/Users/username/Desktop/dify/dify/api/extensions/storage/local_storage.py", line 40, in load_once
    raise FileNotFoundError("File not found")
FileNotFoundError: File not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/controllers/console/setup.py", line 75, in decorated
    return view(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/controllers/console/workspace/model_providers.py", line 112, in post
    model_provider_service.save_provider_credentials(
  File "/Users/username/Desktop/dify/dify/api/services/model_provider_service.py", line 148, in save_provider_credentials
    provider_configurations = self.provider_manager.get_configurations(tenant_id)
  File "/Users/username/Desktop/dify/dify/api/core/provider_manager.py", line 125, in get_configurations
    custom_configuration = self._to_custom_configuration(
  File "/Users/username/Desktop/dify/dify/api/core/provider_manager.py", line 554, in _to_custom_configuration
    self.decoding_rsa_key, self.decoding_cipher_rsa = encrypter.get_decrypt_decoding(tenant_id)
  File "/Users/username/Desktop/dify/dify/api/core/helper/encrypter.py", line 34, in get_decrypt_decoding
    return rsa.get_decrypt_decoding(tenant_id)
  File "/Users/username/Desktop/dify/dify/api/libs/rsa.py", line 57, in get_decrypt_decoding
    raise PrivkeyNotFoundError("Private key not found, tenant_id: {tenant_id}".format(tenant_id=tenant_id))
libs.rsa.PrivkeyNotFoundError: Private key not found, tenant_id: 40aed7fc-7294-44b2-89f6-06bb4af036c1

### ✔️ Expected Behavior

add success

### ❌ Actual Behavior

2024-08-15 08:29:57,948.948 ERROR [Thread-607 (process_request_thread)] [app.py:838] - Exception on /console/api/workspaces/current/model-providers/zhipuai [POST]
Traceback (most recent call last):
  File "/Users/username/Desktop/dify/dify/api/libs/rsa.py", line 55, in get_decrypt_decoding
    private_key = storage.load(filepath)
  File "/Users/username/Desktop/dify/dify/api/extensions/ext_storage.py", line 55, in load
    return self.load_once(filename)
  File "/Users/username/Desktop/dify/dify/api/extensions/ext_storage.py", line 58, in load_once
    return self.storage_runner.load_once(filename)
  File "/Users/username/Desktop/dify/dify/api/extensions/storage/local_storage.py", line 40, in load_once
    raise FileNotFoundError("File not found")
FileNotFoundError: File not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/Users/username/Desktop/dify/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/controllers/console/setup.py", line 75, in decorated
    return view(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/Users/username/Desktop/dify/dify/api/controllers/console/workspace/model_providers.py", line 112, in post
    model_provider_service.save_provider_credentials(
  File "/Users/username/Desktop/dify/dify/api/services/model_provider_service.py", line 148, in save_provider_credentials
    provider_configurations = self.provider_manager.get_configurations(tenant_id)
  File "/Users/username/Desktop/dify/dify/api/core/provider_manager.py", line 125, in get_configurations
    custom_configuration = self._to_custom_configuration(
  File "/Users/username/Desktop/dify/dify/api/core/provider_manager.py", line 554, in _to_custom_configuration
    self.decoding_rsa_key, self.decoding_cipher_rsa = encrypter.get_decrypt_decoding(tenant_id)
  File "/Users/username/Desktop/dify/dify/api/core/helper/encrypter.py", line 34, in get_decrypt_decoding
    return rsa.get_decrypt_decoding(tenant_id)
  File "/Users/username/Desktop/dify/dify/api/libs/rsa.py", line 57, in get_decrypt_decoding
    raise PrivkeyNotFoundError("Private key not found, tenant_id: {tenant_id}".format(tenant_id=tenant_id))
libs.rsa.PrivkeyNotFoundError: Private key not found, tenant_id: 40aed7fc-7294-44b2-89f6-06bb4af036c1

**Comment by wangjian0019** [comment]
"flask reset-encrypt-key-pair" should run after "poetry shell"
