### ISSUE TITLE
导入数据至数据集时报错Meta endpoint! Unexpected status code: 502, with response body: None.

### ISSUE THREAD

**Issue by mengdahuang** [langgenius/dify#734]
问题：导入数据至数据集时前端报错，日志显示导入成功，无法正常命中，请大佬们指点，多谢！
故障截图：
![image](https://github.com/langgenius/dify/assets/32334062/0669f3d5-29fe-48f0-99f5-7a3b09df50e8)

日志截图：
![image](https://github.com/langgenius/dify/assets/32334062/62635d00-be5b-4895-bdaa-bbbc9d3bd49d)

截断显示正常
![image](https://github.com/langgenius/dify/assets/32334062/b38181d2-debe-42bd-b410-d333606eb73f)

禁用一个段落后无法再启用提示错误如下
![image](https://github.com/langgenius/dify/assets/32334062/403ff10a-ad28-4e3d-8ebd-ef9318fc98ab)

**Comment by mengdahuang** [comment]
更新

> 问题：导入数据至数据集时前端报错，日志显示导入成功，无法正常命中，请大佬们指点，多谢！ 故障截图： ![image](https://user-images.githubusercontent.com/32334062/258025487-0669f3d5-29fe-48f0-99f5-7a3b09df50e8.png)
> 
> 日志截图： ![image](https://user-images.githubusercontent.com/32334062/258025616-62635d00-be5b-4895-bdaa-bbbc9d3bd49d.png)
> 
> 截断显示正常 ![image](https://user-images.githubusercontent.com/32334062/258025990-b38181d2-debe-42bd-b410-d333606eb73f.png)
> 
> 禁用一个段落后无法再启用提示错误如下 ![image](https://user-images.githubusercontent.com/32334062/258026155-403ff10a-ad28-4e3d-8ebd-ef9318fc98ab.png)
更新下日志
-----------------
[2023-08-03 07:45:24,904: INFO/MainProcess] Processed dataset: f52d558f-7fbf-4335-ae90-020d57430b57 latency: 0.31325035891495645
[2023-08-03 07:45:24,915: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[3d807b1e-ac0c-4235-9edc-2441415c892e] succeeded in 0.32467947807163s: None
[2023-08-03 08:14:23,397: INFO/MainProcess] Task tasks.clean_dataset_task.clean_dataset_task[b098ad4d-6674-4174-ae5b-e0c58ee60d47] received
[2023-08-03 08:14:23,399: INFO/MainProcess] Start clean dataset when dataset deleted: 584d77b6-d729-418d-91bc-259c9dba985c
[2023-08-03 08:14:23,433: INFO/MainProcess] Cleaned dataset when dataset deleted: 584d77b6-d729-418d-91bc-259c9dba985c latency: 0.03426137496717274
[2023-08-03 08:14:23,447: INFO/MainProcess] Task tasks.clean_dataset_task.clean_dataset_task[b098ad4d-6674-4174-ae5b-e0c58ee60d47] succeeded in 0.04908882989548147s: None
[2023-08-03 08:14:25,673: INFO/MainProcess] Task tasks.clean_dataset_task.clean_dataset_task[1dd32c45-241e-406b-8fb1-bf504427faf6] received
[2023-08-03 08:14:25,674: INFO/MainProcess] Start clean dataset when dataset deleted: f52d558f-7fbf-4335-ae90-020d57430b57
[2023-08-03 08:14:25,924: ERROR/MainProcess] Cleaned dataset when dataset deleted failed
Traceback (most recent call last):
  File "/app/api/tasks/clean_dataset_task.py", line 38, in clean_dataset_task
    vector_index = IndexBuilder.get_index(dataset, 'high_quality')
  File "/app/api/core/index/index.py", line 28, in get_index
    return VectorIndex(
  File "/app/api/core/index/vector_index/vector_index.py", line 15, in __init__
    self._vector_index = self._init_vector_index(dataset, config, embeddings)
  File "/app/api/core/index/vector_index/vector_index.py", line 29, in _init_vector_index
    return WeaviateVectorIndex(
  File "/app/api/core/index/vector_index/weaviate_vector_index.py", line 31, in __init__
    self._client = self._init_client(config)
  File "/app/api/core/index/vector_index/weaviate_vector_index.py", line 39, in _init_client
    client = weaviate.Client(
  File "/usr/local/lib/python3.10/site-packages/weaviate/client.py", line 150, in __init__
    self._connection = Connection(
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 654, in __init__
    self._server_version = self.get_meta()["version"]
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 678, in get_meta
    raise UnexpectedStatusCodeException("Meta endpoint", response)
weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 502, with response body: None.
[2023-08-03 08:14:25,935: INFO/MainProcess] Task tasks.clean_dataset_task.clean_dataset_task[1dd32c45-241e-406b-8fb1-bf504427faf6] succeeded in 0.2615791270509362s: None
[2023-08-03 08:15:23,994: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[733d33a8-1892-4f12-9043-25e65c386287] received
[2023-08-03 08:15:23,994: INFO/MainProcess] Start process document: d067f200-dda0-48ee-9c50-f8d917b7490f
[2023-08-03 08:15:24,307: ERROR/MainProcess] consume document failed
Traceback (most recent call last):
  File "/app/api/core/indexing_runner.py", line 81, in run
    self._build_index(
  File "/app/api/core/indexing_runner.py", line 638, in _build_index
    vector_index = IndexBuilder.get_index(dataset, 'high_quality')
  File "/app/api/core/index/index.py", line 28, in get_index
    return VectorIndex(
  File "/app/api/core/index/vector_index/vector_index.py", line 15, in __init__
    self._vector_index = self._init_vector_index(dataset, config, embeddings)
  File "/app/api/core/index/vector_index/vector_index.py", line 29, in _init_vector_index
    return WeaviateVectorIndex(
  File "/app/api/core/index/vector_index/weaviate_vector_index.py", line 31, in __init__
    self._client = self._init_client(config)
  File "/app/api/core/index/vector_index/weaviate_vector_index.py", line 39, in _init_client
    client = weaviate.Client(
  File "/usr/local/lib/python3.10/site-packages/weaviate/client.py", line 150, in __init__
    self._connection = Connection(
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 654, in __init__
    self._server_version = self.get_meta()["version"]
  File "/usr/local/lib/python3.10/site-packages/weaviate/connect/connection.py", line 678, in get_meta
    raise UnexpectedStatusCodeException("Meta endpoint", response)
weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 502, with response body: None.
[2023-08-03 08:15:24,310: INFO/MainProcess] Processed dataset: 74f16962-b397-43a2-bbad-4fe07393eb09 latency: 0.31583364913240075
[2023-08-03 08:15:24,321: INFO/MainProcess] Task tasks.document_indexing_task.document_indexing_task[733d33a8-1892-4f12-9043-25e65c386287] succeeded in 0.3268825320992619s: None

**Comment by mengdahuang** [comment]
> 

Hi, John 
Thanks for your quickly reply.
this app run my local server based on docker compose service.
below is the weaviate service log from docker 
-----
![image](https://github.com/langgenius/dify/assets/32334062/86a10b73-a287-44e5-87be-c67f1457fba5)

yes, no any more logs here. i can ping the weaviate vhost from my server based on docker network. but cannot access the port from intranet or host self.
![image](https://github.com/langgenius/dify/assets/32334062/aef1bdab-e7d9-403b-9352-b74a4981b126)

**Comment by mengdahuang** [comment]
Hi, I have deleted all the relevant Docker containers and locally cloned directories, and then directly re-cloned them according to official documentation without modifying any configuration files, and then started Docker directly (see the figure below).
<img width="1186" alt="image" src="https://github.com/langgenius/dify/assets/32334062/c9897bbf-f8f3-484f-a8a7-5a85aab8e47f">

When I reconfigured and entered the Dify system, set up Azure AI and OpenAI, and confirmed that I could have a conversation in the live chat. Then, when I tried to upload any document (I tried txt, excel, pdf), it would give an error like below.
<img width="1440" alt="image" src="https://github.com/langgenius/dify/assets/32334062/47f9fe1e-7a7f-41e8-99b6-91200a853a97">
<img width="1491" alt="image" src="https://github.com/langgenius/dify/assets/32334062/4abc5801-e878-493a-84d4-d736a6ac58cc">

anybody can help me take a look at the issue I encountered? thanks a lot

**Comment by takatost** [comment]
This error might be caused by the incorrect startup of Weaviate. You can check the logs of Weaviate by using the following command:
```
docker logs -f -n 500 docker-weaviate-1
```

**Comment by mengdahuang** [comment]
Local Environment Configuration Issues

**Comment by kevinhqf** [comment]
> Local Environment Configuration Issues

什么配置出错了，我也遇到同样问题，能说一说吗

**Comment by kevinhqf** [comment]
@mengdahuang

**Comment by Fsm000814** [comment]
+1,我也遇到一样的问题

**Comment by johnhelf** [comment]
我遇到的情况：如果使用了代理，代理会无法解析weaviate这个域名，导致上面的问题，我把docker-compose.yaml配置中的http://weaviate:8080换成ip地址方式直接访问就好了

**Comment by shelltea** [comment]
遇到相同的问题，在`docker/docker-compose.yaml`文件的worker部分增加`NO_PROXY `配置后重启容器，可解决此问题。

```
no_proxy: 'localhost,127.0.0.1,172.17.*.*,.local,weaviate'
```

**Comment by HuQi1120** [comment]
我修改了端口映射，然后上传知识库时报错：weaviate.exceptions.UnexpectedStatusCodeException: Meta endpoint! Unexpected status code: 404, with response body: {'detail': 'Not Found'}.应该如何解决

**Comment by HuQi1120** [comment]
请问weaviate这个需不需自己进行配置

**Comment by zwfcrazy** [comment]
> 遇到相同的问题，在`docker/docker-compose.yaml`文件的worker部分增加`NO_PROXY `配置后重启容器，可解决此问题。
> 
> ```
> services:
>   worker:
>       environment:
>         no_proxy: 'localhost,127.0.0.1,172.17.*.*,.local,weaviate'
> ```

在api服务下面也需要加no_proxy
