### ISSUE TITLE
[openai] Error: argument should be a bytes-like object or ASCII string, not 'list'

### ISSUE THREAD

**Issue by Cassianvale** [langgenius/dify#7351]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I used docker to deploy and configure the .env file correctly, and then built docker, the version I used is 0.7.0, this error occurred during the text segmentation and cleaning process, by checking the previous issue, I found that the same problem existed in the previous versions and fixed it, I don't know why it appeared again in the 0.7.0 version, and I don't know how I should I don't know how to fix it.
The Embedding model I use is `text-embedding-v2`
The docker-worker-1 detailed error log is as follows:
```
[2024-08-16 08:14:58,191: WARNING/MainProcess]   File "/usr/local/lib/python3.10/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
[2024-08-16 08:14:58,191: WARNING/MainProcess]   File "/usr/local/lib/python3.10/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
[2024-08-16 08:14:58,191: WARNING/MainProcess] TypeError: argument should be a bytes-like object or ASCII string, not 'list'
[2024-08-16 08:14:58,191: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:
[2024-08-16 08:14:58,191: WARNING/MainProcess] Traceback (most recent call last):
[2024-08-16 08:14:58,191: WARNING/MainProcess]   File "/app/api/core/embedding/cached_embedding.py", line 51, in embed_documents
    embedding_result = self._model_instance.invoke_text_embedding(
[2024-08-16 08:14:58,191: WARNING/MainProcess]   File "/app/api/core/model_manager.py", line 170, in invoke_text_embedding
    return self._round_robin_invoke(
[2024-08-16 08:14:58,191: WARNING/MainProcess]   File "/app/api/core/model_manager.py", line 302, in _round_robin_invoke
    return function(*args, **kwargs)
[2024-08-16 08:14:58,191: WARNING/MainProcess]   File "/app/api/core/model_runtime/model_providers/__base/text_embedding_model.py", line 38, in invoke
    raise self._transform_invoke_error(e)
[2024-08-16 08:14:58,191: WARNING/MainProcess] core.model_runtime.errors.invoke.InvokeError: [openai] Error: argument should be a bytes-like object or ASCII string, not 'list'
[2024-08-16 08:14:58,191: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:
[2024-08-16 08:14:58,191: WARNING/MainProcess] Traceback (most recent call last):
[2024-08-16 08:14:58,191: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/app/api/.venv/lib/python3.10/site-packages/celery/utils/log.py", line 146, in format
    msg = super().format(record)
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2024-08-16 08:14:58,192: WARNING/MainProcess] TypeError: not all arguments converted during string formatting
[2024-08-16 08:14:58,192: WARNING/MainProcess] Call stack:
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/app/api/core/indexing_runner.py", line 743, in _process_chunk
    index_processor.load(dataset, chunk_documents, with_keywords=False)
[2024-08-16 08:14:58,192: WARNING/MainProcess]   File "/app/api/core/rag/index_processor/processor/qa_index_processor.py", line 101, in load
    vector.create(documents)
[2024-08-16 08:14:58,193: WARNING/MainProcess]   File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 100, in create
    embeddings = self._embeddings.embed_documents([document.page_content for document in texts])
[2024-08-16 08:14:58,193: WARNING/MainProcess]   File "/app/api/core/embedding/cached_embedding.py", line 81, in embed_documents
    logger.error('Failed to embed documents: ', ex)
[2024-08-16 08:14:58,193: WARNING/MainProcess] Message: 'Failed to embed documents: '
Arguments: (InvokeError(),)
[2024-08-16 08:14:58,193: ERROR/MainProcess] consume document failed
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/__base/text_embedding_model.py", line 36, in invoke
    return self._invoke(model, credentials, texts, user)
  File "/app/api/core/model_runtime/model_providers/openai/text_embedding/text_embedding.py", line 71, in _invoke
    embeddings_batch, embedding_used_tokens = self._embedding_invoke(
  File "/app/api/core/model_runtime/model_providers/openai/text_embedding/text_embedding.py", line 184, in _embedding_invoke
    return ([list(np.frombuffer(base64.b64decode(data.embedding), dtype="float32")) for data in response.data],
  File "/app/api/core/model_runtime/model_providers/openai/text_embedding/text_embedding.py", line 184, in <listcomp>
    return ([list(np.frombuffer(base64.b64decode(data.embedding), dtype="float32")) for data in response.data],
  File "/usr/local/lib/python3.10/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/local/lib/python3.10/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/core/indexing_runner.py", line 77, in run
    self._load(
  File "/app/api/core/indexing_runner.py", line 690, in _load
    tokens += future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/api/core/indexing_runner.py", line 743, in _process_chunk
    index_processor.load(dataset, chunk_documents, with_keywords=False)
  File "/app/api/core/rag/index_processor/processor/qa_index_processor.py", line 101, in load
    vector.create(documents)
  File "/app/api/core/rag/datasource/vdb/vector_factory.py", line 100, in create
    embeddings = self._embeddings.embed_documents([document.page_content for document in texts])
  File "/app/api/core/embedding/cached_embedding.py", line 82, in embed_documents
    raise ex
  File "/app/api/core/embedding/cached_embedding.py", line 51, in embed_documents
    embedding_result = self._model_instance.invoke_text_embedding(
  File "/app/api/core/model_manager.py", line 170, in invoke_text_embedding
    return self._round_robin_invoke(
  File "/app/api/core/model_manager.py", line 302, in _round_robin_invoke
    return function(*args, **kwargs)
  File "/app/api/core/model_runtime/model_providers/__base/text_embedding_model.py", line 38, in invoke
    raise self._transform_invoke_error(e)
core.model_runtime.errors.invoke.InvokeError: [openai] Error: argument should be a bytes-like object or ASCII string, not 'list'
```

**Comment by crazywoola** [comment]
This is because the third party OpenAI api does not return the  correct response in base64. We force it on our side for a better performance.

**Comment by Cassianvale** [comment]
> This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.

I see. Thanks for the reply.

**Comment by cumtsd** [comment]
> > This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.
> 
> I see. Thanks for the reply.

你好 请问解决了吗。我也是用的第三方的api，方便的话可否告知解决方式，谢谢

**Comment by Cassianvale** [comment]
> > > This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.
> > 
> > 
> > I see. Thanks for the reply.
> 
> 你好 请问解决了吗。我也是用的第三方的api，方便的话可否告知解决方式，谢谢

我在数据清晰的时候不使用混合检索就不会有任何问题，我不知道你那边是否同样适用

**Comment by Cassianvale** [comment]
> > > This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.
> > 
> > 
> > I see. Thanks for the reply.
> 
> 你好 请问解决了吗。我也是用的第三方的api，方便的话可否告知解决方式，谢谢

并且在嵌入的时候需要保证你的文档里没有图片，否则同样会报标题中的错误

**Comment by cumtsd** [comment]
> > > > This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.
> > > 
> > > 
> > > I see. Thanks for the reply.
> > 
> > 
> > 你好 请问解决了吗。我也是用的第三方的api，方便的话可否告知解决方式，谢谢
> 
> 我在数据清洗的时候不使用混合检索就不会有任何问题，我不知道你那边是否同样适用

我并没有使用混合检索，使用的是全文检索未使用rerank模型，而且知识库的pdf难免有图片的  囧。不过我发现可以使用dify自带的第三方OpenAI-API-compatible模型

**Comment by cumtsd** [comment]
> > > > This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.
> > > 
> > > 
> > > I see. Thanks for the reply.
> > 
> > 
> > 你好 请问解决了吗。我也是用的第三方的api，方便的话可否告知解决方式，谢谢
> 
> 我在数据清洗的时候不使用混合检索就不会有任何问题，我不知道你那边是否同样适用

不过即便使用第三方兼容模型，还是遇到了其他问题，不知道怎么解决

**Comment by Cassianvale** [comment]
> 

我是使用的阿里免费额度的千问和第三方中转gpt-4o

**Comment by Cassianvale** [comment]
> > > > > This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.
> > > > 
> > > > 
> > > > I see. Thanks for the reply.
> > > 
> > > 
> > > 你好 请问解决了吗。我也是用的第三方的api，方便的话可否告知解决方式，谢谢
> > 
> > 
> > 我在数据清洗的时候不使用混合检索就不会有任何问题，我不知道你那边是否同样适用
> 
> 我并没有使用混合检索，使用的是全文检索未使用rerank模型，而且知识库的pdf难免有图片的 囧。不过我发现可以使用dify自带的第三方OpenAI-API-compatible模型

我是使用的阿里免费额度的千问和第三方中转gpt-4o

**Comment by cumtsd** [comment]
> > > > > > This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.
> > > > > 
> > > > > 
> > > > > I see. Thanks for the reply.
> > > > 
> > > > 
> > > > 你好 请问解决了吗。我也是用的第三方的api，方便的话可否告知解决方式，谢谢
> > > 
> > > 
> > > 我在数据清洗的时候不使用混合检索就不会有任何问题，我不知道你那边是否同样适用
> > 
> > 
> > 我并没有使用混合检索，使用的是全文检索未使用rerank模型，而且知识库的pdf难免有图片的 囧。不过我发现可以使用dify自带的第三方OpenAI-API-compatible模型
> 
> 我是使用的阿里免费额度的千问和第三方中转gpt-4o

v  sdcumt

**Comment by mwcodefun** [comment]
> This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.

I've encountered the same problem, but I'm not quite clear about the key to the issue. The format returned by the third-party OpenAI API I'm using should be consistent with that of the official OpenAI Embedded API. And I haven't seen the content being returned in the Base64 encoding format in the official API either. Did I miss something? Looking forward to your reply.

**Comment by lydbupt** [comment]
> > > > > > > This is because the third party OpenAI api does not return the correct response in base64. We force it on our side for a better performance.
> > > > > > 
> > > > > > 
> > > > > > I see. Thanks for the reply.
> > > > > 
> > > > > 
> > > > > 你好 请问解决了吗。我也是用的第三方的api，方便的话可否告知解决方式，谢谢
> > > > 
> > > > 
> > > > 我在数据清洗的时候不使用混合检索就不会有任何问题，我不知道你那边是否同样适用
> > > 
> > > 
> > > 我并没有使用混合检索，使用的是全文检索未使用rerank模型，而且知识库的pdf难免有图片的 囧。不过我发现可以使用dify自带的第三方OpenAI-API-compatible模型
> > 
> > 
> > 我是使用的阿里免费额度的千问和第三方中转gpt-4o
> 
> 现在已经能用了。谢谢！

@cumtsd  请问你最后是怎么解决的？

**Comment by cumtsd** [comment]
可以使用dify自带的第三方OpenAI-API-compatible模型

lydbupt ***@***.***> 于2024年12月13日周五 13:44写道：
