### ISSUE TITLE
0.7.0 import DSL error

### ISSUE THREAD

**Issue by qkzsky** [langgenius/dify#7359]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/1e3d4df9-4218-40c5-927f-63eaef9a9459)

```
2024-08-16 14:09:20,555.555 ERROR [Dummy-97] [app.py:838] - Exception on /console/api/apps/3d006580-3581-40eb-bb80-a18268120bbf/workflows/draft/import [POST]
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 75, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 91, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/app/wraps.py", line 49, in decorated_view
    return view_func(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 696, in wrapper
    resp = f(*args, **kwargs)
  File "/app/api/controllers/console/app/workflow.py", line 144, in post
    workflow = AppDslService.import_and_overwrite_workflow(
  File "/app/api/services/app_dsl_service.py", line 147, in import_and_overwrite_workflow
    return cls._import_and_overwrite_workflow_based_app(
  File "/app/api/services/app_dsl_service.py", line 288, in _import_and_overwrite_workflow_based_app
    draft_workflow = workflow_service.sync_draft_workflow(
TypeError: WorkflowService.sync_draft_workflow() missing 1 required keyword-only argument: 'conversation_variables'
```

**Comment by crazywoola** [comment]
Already fixed in #7304
