### ISSUE TITLE
Package not found err while uploading files into database

### ISSUE THREAD

**Issue by pkunight** [langgenius/dify#7394]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When uploading local files to the knowledge base, there is a certain chance of an error occurring during Text Segmentation and Cleaning phase if the file size exceeds approximately 2MB. If the file size exceeds 3MB, an error is almost guaranteed.
在向知识库上传本地文件时, 只要文件大小超过约2MB, 就有一定几率在文本分段与清洗阶段报错; 如果文件大小超过3MB, 基本必定报错.

After reviewing the error and the code, first, we suspect that there may be an issue with the scope of tempfile in extract_processor.py. This could cause the temporary files to be deleted prematurely during the index phase, leading to index failure.
在检查过报错和代码后, 我们首先猜测extract_processor.py中的tempfile作用域可能存在问题, 会导致生成的临时文件在index阶段被提前删除, 导致index失败.

But in fact, the issue persists even when not using tempfile paths. The file exists before calling docx.Document. We are still in the process of diagnosing and analyzing the problem.
但实际上我们不使用tempfile的路径也会存在这个问题, 在调用docx库的Document之前文件是存在的. 还在定位分析中.

Additional information: We have deployed Dify locally and are using an Nginx layer for request forwarding. Nginx is configured with `client_max_body_size 100M` to ensure large file transfers.
补充说明: 我们将dify部署在本地, 同时使用了一层nginx进行请求转发, nginx已配置`client_max_body_size: 100M`来保证大文件传输

We are still investigating the issue. If anyone has encountered similar errors, we would appreciate your help.
我们还在追查问题中, 如果大家有遇到过相关报错, 也希望能够帮助我们.

The error (Some of the logs are ones I added myself, to track changes in file paths):
为了跟踪文件路径变化, 有些日志是我自己加上的.
```
2024-08-19 04:11:18,742.742 INFO [Thread-21 (process_request_thread)] [_internal.py:97] - 127.0.0.1 - - [19/Aug/2024 04:11:18] "[35m[1mPOST /console/api/files/upload?source=datasets HTTP/1.0[0m" 201 -
2024-08-19 04:11:22,456.456 INFO [Thread-22 (process_request_thread)] [_internal.py:97] - 127.0.0.1 - - [19/Aug/2024 04:11:22] "GET /console/api/workspaces/current/default-model?model_type=rerank HTTP/1.0" 200 -
2024-08-19 04:11:22,456.456 INFO [Thread-25 (process_request_thread)] [_internal.py:97] - 127.0.0.1 - - [19/Aug/2024 04:11:22] "GET /console/api/datasets/process-rule HTTP/1.0" 200 -
2024-08-19 04:11:22,467.467 INFO [Thread-23 (process_request_thread)] [_internal.py:97] - 127.0.0.1 - - [19/Aug/2024 04:11:22] "GET /console/api/workspaces/current/models/model-types/rerank HTTP/1.0" 200 -
2024-08-19 04:11:22,467.467 INFO [Thread-24 (process_request_thread)] [extract_processor.py:92] - Origin file path: None
2024-08-19 04:11:22,473.473 INFO [Thread-24 (process_request_thread)] [local_storage.py:76] - LocalStorage shutil copyfile success: /tmp/tmprn5h2ost/va5thka1.docx
2024-08-19 04:11:22,473.473 INFO [Thread-24 (process_request_thread)] [extract_processor.py:98] - Download upload_files/16a6e5c4-8868-468f-9364-d3325c15f008/c06479e7-bde4-405a-bc07-198da97e9482.docx to /tmp/tmprn5h2ost/va5thka1.docx
2024-08-19 04:11:22,473.473 INFO [Thread-24 (process_request_thread)] [word_extractor.py:59] - Local file path: /tmp/tmprn5h2ost/va5thka1.docx
2024-08-19 04:11:22,476.476 ERROR [Thread-24 (process_request_thread)] [app.py:838] - Exception on /console/api/datasets/indexing-estimate [POST]
Traceback (most recent call last):
  File "/root/dify/api/controllers/console/datasets/datasets.py", line 388, in post
    response = indexing_runner.indexing_estimate(current_user.current_tenant_id, extract_settings,
  File "/root/dify/api/core/indexing_runner.py", line 268, in indexing_estimate
    text_docs = index_processor.extract(extract_setting, process_rule_mode=tmp_processing_rule["mode"])
  File "/root/dify/api/core/rag/index_processor/processor/paragraph_index_processor.py", line 21, in extract
    text_docs = ExtractProcessor.extract(extract_setting=extract_setting,
  File "/root/dify/api/core/rag/extractor/extract_processor.py", line 152, in extract
    return extractor.extract()
  File "/root/dify/api/core/rag/extractor/word_extractor.py", line 67, in extract
    content = self.parse_docx(self.file_path, 'storage')
  File "/root/dify/api/core/rag/extractor/word_extractor.py", line 201, in parse_docx
    doc = DocxDocument(docx_path)
  File "/root/miniconda3/envs/dify/lib/python3.10/site-packages/docx/api.py", line 27, in Document
    document_part = cast("DocumentPart", Package.open(docx).main_document_part)
  File "/root/miniconda3/envs/dify/lib/python3.10/site-packages/docx/opc/package.py", line 127, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/root/miniconda3/envs/dify/lib/python3.10/site-packages/docx/opc/pkgreader.py", line 22, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/root/miniconda3/envs/dify/lib/python3.10/site-packages/docx/opc/phys_pkg.py", line 21, in __new__
    raise PackageNotFoundError("Package not found at '%s'" % pkg_file)
docx.opc.exceptions.PackageNotFoundError: Package not found at '/tmp/tmprn5h2ost/va5thka1.docx'
```

### ✔️ Expected Behavior

The file was successfully stored in the database

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/f9c49313-1d48-45dd-9f33-df877d214bfa)

**Comment by pkunight** [comment]
Sorry, in fact, the issue persists even when not using tempfile paths. We are still in the process of diagnosing and analyzing the problem.
