### ISSUE TITLE
Instance <Provider at 0x7d21b5bcbd60> has a NULL identity key

### ISSUE THREAD

**Issue by shengxiagit** [langgenius/dify#7521]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.7.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

When I add a model voucher, an error message appears, like this:

··
sqlalchemy.orm.exc.FlushError: Instance <Provider at 0x7d21b5a12f80> has a NULL identity key.  If this is an auto-generated value, check that the database table allows generation of new primary key values, and that the mapped Column object is configured to expect these generated values.  Ensure also that this flush() is not occurring at an inappropriate time, such as within a load() event.

### ✔️ Expected Behavior

model provider add success

### ❌ Actual Behavior

```
2024-08-22 01:34:45,263.263 INFO [Dummy-1] [_client.py:1026] - HTTP Request: POST https://api.aigc369.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-08-22 01:34:45,273.273 ERROR [Dummy-1] [app.py:838] - Exception on /console/api/workspaces/current/model-providers/openai [POST]
Traceback (most recent call last):
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/project/dify-api/api/controllers/console/setup.py", line 75, in decorated
    return view(*args, **kwargs)
  File "/opt/project/dify-api/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/opt/project/dify-api/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/opt/project/dify-api/api/controllers/console/workspace/model_providers.py", line 112, in post
    model_provider_service.save_provider_credentials(
  File "/opt/project/dify-api/api/services/model_provider_service.py", line 157, in save_provider_credentials
    provider_configuration.add_or_update_custom_credentials(credentials)
  File "/opt/project/dify-api/api/core/entities/provider_configuration.py", line 245, in add_or_update_custom_credentials
    db.session.commit()
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4454, in _flush
    flush_context.finalize_flush_changes()
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 487, in finalize_flush_changes
    self.session._register_persistent(other)
  File "/opt/module/anaconda3/envs/dify-local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3353, in _register_persistent
    raise exc.FlushError(
sqlalchemy.orm.exc.FlushError: Instance <Provider at 0x7d21b5a12f80> has a NULL identity key.  If this is an auto-generated value, check that the database table allows generation of new primary key values, and that the mapped Column object is configured to expect these generated values.  Ensure also that this flush() is not occurring at an inappropriate time, such as within a load() event.
```

**Comment by laipz8200** [comment]
Is this issue still present in the latest version?
