### ISSUE TITLE
Agent example run faild when use Xinference as backend

### ISSUE THREAD

**Issue by lordk911** [langgenius/dify#7711]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、add the agent: Investment Analysis Report Copilot to my workspace
![image](https://github.com/user-attachments/assets/38d77fb1-320d-4fc7-895e-03593b75cc05)

2、config to use Xinference, which backend chat model is qwen2-instruct
3、try to run the agent
4、will get error: 
`[xinference] Server Unavailable Error, Error code: 500 - {'detail': '[address=10.9.27.41:37255, pid=1756204] Object of type list_iterator is not JSON serializable'}`
5、the xinference's Supervisor log is : 
```
2024-08-27 17:10:49,126 xinference.api.restful_api 1693802 ERROR    [address=10.9.27.41:37255, pid=1756204] Object of type list_iterator is not JSON serializable
Traceback (most recent call last):
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1752, in create_chat_completion
    data = await model.chat(
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 536, in chat
    response = await self._call_wrapper_json(
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 401, in _call_wrapper_json
    return await self._call_wrapper("json", fn, *args, **kwargs)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 410, in _call_wrapper
    ret = await fn(*args, **kwargs)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/sglang/core.py", line 434, in async_chat
    c = await self.async_generate(full_prompt, generate_config)  # type: ignore
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/sglang/core.py", line 332, in async_generate
    state = await self._non_stream_generate(prompt, **sanitized_generate_config)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/sglang/core.py", line 307, in _non_stream_generate
    async with session.post(
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/aiohttp/client.py", line 499, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/aiohttp/payload.py", line 397, in __init__
    dumps(value).encode(encoding),
  File "/data/miniconda3/envs/xinference/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/data/miniconda3/envs/xinference/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data/miniconda3/envs/xinference/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/data/miniconda3/envs/xinference/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: [address=10.9.27.41:37255, pid=1756204] Object of type list_iterator is not JSON serializable
```
6、xinference/api/restful_api.py:1752
```
try:
                data = await model.chat(
                    prompt,
                    system_prompt,
                    chat_history,
                    kwargs,
                    raw_params=raw_kwargs,
                )
                return Response(content=data, media_type="application/json")
```
7、from xinference's Worker log I found that param: kwargs is : 
`{'frequency_penalty': 0.0, 'max_tokens': 512, 'presence_penalty': 0.0, 'temperature': 1.0, 'tools': <list_iterator object at 0x7faf6b7e7e20>, 'top_p': 0.7, 'stream': False}`

![c7e62e6d-8d12-4491-aa8f-04ce050fc345](https://github.com/user-attachments/assets/97e8254b-67c0-4206-86fa-1ebeaf6007f9)

**Comment by lordk911** [comment]
I've tried to use Zhipu AI ,there is no problem.
