### ISSUE TITLE
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ISSUE THREAD

**Issue by Sure0520** [langgenius/dify#7881]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/091ee5a6-561a-49af-b22c-2497e830df09)

```
2024-09-02 02:37:27,095.095 ERROR [Dummy-27] [workflow.py:190] - internal server error.
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "workflow__conversation_variables" does not exist
LINE 2: FROM workflow__conversation_variables
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/controllers/console/app/workflow.py", line 174, in post
    response = AppGenerateService.generate(
  File "/app/api/services/app_generate_service.py", line 65, in generate
    return rate_limit.generate(AdvancedChatAppGenerator().generate(
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 122, in generate
    return self._generate(
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 236, in _generate
    conversation_variables = session.scalars(stmt).all()
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2470, in scalars
    return self._execute_internal(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "workflow__conversation_variables" does not exist
LINE 2: FROM workflow__conversation_variables
             ^

[SQL: SELECT workflow__conversation_variables.id, workflow__conversation_variables.conversation_id, workflow__conversation_variables.app_id, workflow__conversation_variables.data, workflow__conversation_variables.created_at, workflow__conversation_variables.updated_at
FROM workflow__conversation_variables
WHERE workflow__conversation_variables.app_id = %(app_id_1)s::UUID AND workflow__conversation_variables.conversation_id = %(conversation_id_1)s::UUID]
[parameters: {'app_id_1': '22e9b395-05a4-4622-a815-a94233bfb9e9', 'conversation_id_1': '94a91c13-0101-4eaa-bddc-3b242afc0a35'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-09-02 02:37:27,096.096 ERROR [Dummy-27] [app.py:838] - Exception on /console/api/apps/22e9b395-05a4-4622-a815-a94233bfb9e9/advanced-chat/workflows/draft/run [POST]
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "workflow__conversation_variables" does not exist
LINE 2: FROM workflow__conversation_variables
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/controllers/console/app/workflow.py", line 174, in post
    response = AppGenerateService.generate(
  File "/app/api/services/app_generate_service.py", line 65, in generate
    return rate_limit.generate(AdvancedChatAppGenerator().generate(
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 122, in generate
    return self._generate(
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 236, in _generate
    conversation_variables = session.scalars(stmt).all()
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2470, in scalars
    return self._execute_internal(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "workflow__conversation_variables" does not exist
LINE 2: FROM workflow__conversation_variables
             ^

[SQL: SELECT workflow__conversation_variables.id, workflow__conversation_variables.conversation_id, workflow__conversation_variables.app_id, workflow__conversation_variables.data, workflow__conversation_variables.created_at, workflow__conversation_variables.updated_at
FROM workflow__conversation_variables
WHERE workflow__conversation_variables.app_id = %(app_id_1)s::UUID AND workflow__conversation_variables.conversation_id = %(conversation_id_1)s::UUID]
[parameters: {'app_id_1': '22e9b395-05a4-4622-a815-a94233bfb9e9', 'conversation_id_1': '94a91c13-0101-4eaa-bddc-3b242afc0a35'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 75, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/app/wraps.py", line 49, in decorated_view
    return view_func(*args, **kwargs)
  File "/app/api/controllers/console/app/workflow.py", line 191, in post
    raise InternalServerError()
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

### ❌ Actual Behavior

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by crazywoola** [comment]
Please upgrade to latest version and make sure you ran the migration.

**Comment by Sure0520** [comment]
> Please upgrade to latest version and make sure you ran the migration.

However, in version 0.7.2, the variable output using code cannot exceed 30 characters.
