### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by lynnroyal** [langgenius/dify#8]
使用Docker Compose 启动完成后，发现一个容器一直起不来，打开http://localhost 后一直提示502
然后看了一下容器如下
![image](https://github.com/langgenius/dify/assets/624684/d5188472-7567-41cd-ade2-e7dbd4d8198d)
然后看了一下logs如下
![image](https://github.com/langgenius/dify/assets/624684/c3ad4503-7bf7-4779-9a47-15e837048d84)

**Comment by camelgeek** [comment]
<img width="1038" alt="CleanShot 2023-05-15 at 11 51 33@2x" src="https://github.com/langgenius/dify/assets/52606523/4f52b37b-0a1b-46ec-87c4-660f73ed4a61">
同样的错误

**Comment by takatost** [comment]
感谢反馈，这个问题我们在看了

**Comment by takatost** [comment]
refer #5

**Comment by takatost** [comment]
已修复 @lynnroyal @camelgeek

**Comment by camelgeek** [comment]
刚拉了最新代码，发现还有问题，日志如下：
```
docker-api-1       | Running migrations
docker-nginx-1     | 172.21.0.1 - - [15/May/2023:04:59:03 +0000] "GET / HTTP/1.1" 307 15 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
docker-nginx-1     | 172.21.0.1 - - [15/May/2023:04:59:08 +0000] "GET /console/api/apps HTTP/1.1" 502 559 "http://localhost/apps" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
docker-nginx-1     | 2023/05/15 04:59:08 [error] 29#29: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /console/api/apps HTTP/1.1", upstream: "http://172.21.0.6:5001/console/api/apps", host: "localhost", referrer: "http://localhost/apps"
docker-nginx-1     | 2023/05/15 04:59:08 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /console/api/account/profile HTTP/1.1", upstream: "http://172.21.0.6:5001/console/api/account/profile", host: "localhost", referrer: "http://localhost/apps"
docker-nginx-1     | 172.21.0.1 - - [15/May/2023:04:59:08 +0000] "GET /console/api/account/profile HTTP/1.1" 502 559 "http://localhost/apps" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
docker-nginx-1     | 172.21.0.1 - - [15/May/2023:04:59:08 +0000] "GET /apps HTTP/1.1" 200 5377 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
docker-nginx-1     | 172.21.0.1 - - [15/May/2023:04:59:10 +0000] "GET /favicon.ico HTTP/1.1" 304 0 "http://localhost/apps" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
docker-nginx-1     | 2023/05/15 04:59:13 [error] 28#28: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /console/api/apps HTTP/1.1", upstream: "http://172.21.0.6:5001/console/api/apps", host: "localhost", referrer: "http://localhost/apps"
docker-nginx-1     | 172.21.0.1 - - [15/May/2023:04:59:13 +0000] "GET /console/api/apps HTTP/1.1" 502 559 "http://localhost/apps" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
docker-nginx-1     | 2023/05/15 04:59:18 [error] 28#28: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /console/api/account/profile HTTP/1.1", upstream: "http://172.21.0.6:5001/console/api/account/profile", host: "localhost", referrer: "http://localhost/apps"
docker-nginx-1     | 172.21.0.1 - - [15/May/2023:04:59:18 +0000] "GET /console/api/account/profile HTTP/1.1" 502 559 "http://localhost/apps" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
docker-api-1       | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
docker-api-1       | INFO  [alembic.runtime.migration] Will assume transactional DDL.
docker-api-1       | INFO  [alembic.runtime.migration] Running upgrade  -> 64b051264f32, init
docker-db-1        | 2023-05-15 04:59:25.636 UTC [60] ERROR:  function uuid_generate_v4() does not exist at character 53
docker-db-1        | 2023-05-15 04:59:25.636 UTC [60] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
docker-db-1        | 2023-05-15 04:59:25.636 UTC [60] STATEMENT:
docker-db-1        | 	CREATE TABLE account_integrates (
docker-db-1        | 		id UUID DEFAULT uuid_generate_v4() NOT NULL,
docker-db-1        | 		account_id UUID NOT NULL,
docker-db-1        | 		provider VARCHAR(16) NOT NULL,
docker-db-1        | 		open_id VARCHAR(255) NOT NULL,
docker-db-1        | 		encrypted_token VARCHAR(255) NOT NULL,
docker-db-1        | 		created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
docker-db-1        | 		updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
docker-db-1        | 		CONSTRAINT account_integrate_pkey PRIMARY KEY (id),
docker-db-1        | 		CONSTRAINT unique_account_provider UNIQUE (account_id, provider),
docker-db-1        | 		CONSTRAINT unique_provider_open_id UNIQUE (provider, open_id)
docker-db-1        | 	)
docker-db-1        |
docker-db-1        |
docker-api-1       | Traceback (most recent call last):
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
docker-api-1       |     self.dialect.do_execute(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
docker-api-1       |     cursor.execute(statement, parameters)
docker-api-1       | psycopg2.errors.UndefinedFunction: function uuid_generate_v4() does not exist
docker-api-1       | LINE 3:  id UUID DEFAULT uuid_generate_v4() NOT NULL,
docker-api-1       |                          ^
docker-api-1       | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
docker-api-1       |
docker-api-1       |
docker-api-1       | The above exception was the direct cause of the following exception:
docker-api-1       |
docker-api-1       | Traceback (most recent call last):
docker-api-1       |   File "/usr/local/bin/flask", line 8, in <module>
docker-api-1       |     sys.exit(main())
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1063, in main
docker-api-1       |     cli.main()
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
docker-api-1       |     rv = self.invoke(ctx)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
docker-api-1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
docker-api-1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
docker-api-1       |     return ctx.invoke(self.callback, **ctx.params)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
docker-api-1       |     return __callback(*args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
docker-api-1       |     return f(get_current_context(), *args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
docker-api-1       |     return __ctx.invoke(f, *args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
docker-api-1       |     return __callback(*args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask_migrate/cli.py", line 150, in upgrade
docker-api-1       |     _upgrade(directory, revision, sql, tag, x_arg)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 111, in wrapped
docker-api-1       |     f(*args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 200, in upgrade
docker-api-1       |     command.upgrade(config, revision, sql=sql, tag=tag)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
docker-api-1       |     script.run_env()
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
docker-api-1       |     util.load_python_file(self.dir, "env.py")
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
docker-api-1       |     module = load_module_py(module_id, path)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
docker-api-1       |     spec.loader.exec_module(module)  # type: ignore
docker-api-1       |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
docker-api-1       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
docker-api-1       |   File "/app/api/migrations/env.py", line 113, in <module>
docker-api-1       |     run_migrations_online()
docker-api-1       |   File "/app/api/migrations/env.py", line 107, in run_migrations_online
docker-api-1       |     context.run_migrations()
docker-api-1       |   File "<string>", line 8, in run_migrations
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 868, in run_migrations
docker-api-1       |     self.get_context().run_migrations(**kw)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 622, in run_migrations
docker-api-1       |     step.migration_fn(**kw)
docker-api-1       |   File "/app/api/migrations/versions/64b051264f32_init.py", line 21, in upgrade
docker-api-1       |     op.create_table('account_integrates',
docker-api-1       |   File "<string>", line 8, in create_table
docker-api-1       |   File "<string>", line 3, in create_table
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/ops.py", line 1255, in create_table
docker-api-1       |     return operations.invoke(op)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/base.py", line 401, in invoke
docker-api-1       |     return fn(self, operation)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 114, in create_table
docker-api-1       |     operations.impl.create_table(table)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 354, in create_table
docker-api-1       |     self._exec(schema.CreateTable(table))
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 193, in _exec
docker-api-1       |     return conn.execute(  # type: ignore[call-overload]
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
docker-api-1       |     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
docker-api-1       |     return connection._execute_ddl(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
docker-api-1       |     ret = self._execute_context(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1948, in _execute_context
docker-api-1       |     self._handle_dbapi_exception(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2129, in _handle_dbapi_exception
docker-api-1       |     util.raise_(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
docker-api-1       |     raise exception
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
docker-api-1       |     self.dialect.do_execute(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
docker-api-1       |     cursor.execute(statement, parameters)
docker-api-1       | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function uuid_generate_v4() does not exist
docker-api-1       | LINE 3:  id UUID DEFAULT uuid_generate_v4() NOT NULL,
docker-api-1       |                          ^
docker-api-1       | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
docker-api-1       |
docker-api-1       | [SQL:
docker-api-1       | CREATE TABLE account_integrates (
docker-api-1       | 	id UUID DEFAULT uuid_generate_v4() NOT NULL,
docker-api-1       | 	account_id UUID NOT NULL,
docker-api-1       | 	provider VARCHAR(16) NOT NULL,
docker-api-1       | 	open_id VARCHAR(255) NOT NULL,
docker-api-1       | 	encrypted_token VARCHAR(255) NOT NULL,
docker-api-1       | 	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
docker-api-1       | 	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
docker-api-1       | 	CONSTRAINT account_integrate_pkey PRIMARY KEY (id),
docker-api-1       | 	CONSTRAINT unique_account_provider UNIQUE (account_id, provider),
docker-api-1       | 	CONSTRAINT unique_provider_open_id UNIQUE (provider, open_id)
docker-api-1       | )
docker-api-1       |
docker-api-1       | ]
docker-api-1       | (Background on this error at: https://sqlalche.me/e/14/f405)
docker-api-1 exited with code 1
docker-api-1       | Running migrations
docker-nginx-1     | 2023/05/15 04:59:38 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /console/api/account/profile HTTP/1.1", upstream: "http://172.21.0.6:5001/console/api/account/profile", host: "localhost", referrer: "http://localhost/apps"
docker-nginx-1     | 172.21.0.1 - - [15/May/2023:04:59:38 +0000] "GET /console/api/account/profile HTTP/1.1" 502 559 "http://localhost/apps" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
docker-nginx-1     | 2023/05/15 04:59:38 [error] 28#28: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET /console/api/apps HTTP/1.1", upstream: "http://172.21.0.6:5001/console/api/apps", host: "localhost", referrer: "http://localhost/apps"
docker-nginx-1     | 172.21.0.1 - - [15/May/2023:04:59:38 +0000] "GET /console/api/apps HTTP/1.1" 502 559 "http://localhost/apps" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
docker-api-1       | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
docker-api-1       | INFO  [alembic.runtime.migration] Will assume transactional DDL.
docker-api-1       | INFO  [alembic.runtime.migration] Running upgrade  -> 64b051264f32, init
docker-db-1        | 2023-05-15 04:59:51.967 UTC [62] ERROR:  function uuid_generate_v4() does not exist at character 53
docker-db-1        | 2023-05-15 04:59:51.967 UTC [62] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
docker-db-1        | 2023-05-15 04:59:51.967 UTC [62] STATEMENT:
docker-db-1        | 	CREATE TABLE account_integrates (
docker-db-1        | 		id UUID DEFAULT uuid_generate_v4() NOT NULL,
docker-db-1        | 		account_id UUID NOT NULL,
docker-db-1        | 		provider VARCHAR(16) NOT NULL,
docker-db-1        | 		open_id VARCHAR(255) NOT NULL,
docker-db-1        | 		encrypted_token VARCHAR(255) NOT NULL,
docker-db-1        | 		created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
docker-db-1        | 		updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
docker-db-1        | 		CONSTRAINT account_integrate_pkey PRIMARY KEY (id),
docker-db-1        | 		CONSTRAINT unique_account_provider UNIQUE (account_id, provider),
docker-db-1        | 		CONSTRAINT unique_provider_open_id UNIQUE (provider, open_id)
docker-db-1        | 	)
docker-db-1        |
docker-db-1        |
docker-api-1       | Traceback (most recent call last):
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
docker-api-1       |     self.dialect.do_execute(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
docker-api-1       |     cursor.execute(statement, parameters)
docker-api-1       | psycopg2.errors.UndefinedFunction: function uuid_generate_v4() does not exist
docker-api-1       | LINE 3:  id UUID DEFAULT uuid_generate_v4() NOT NULL,
docker-api-1       |                          ^
docker-api-1       | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
docker-api-1       |
docker-api-1       |
docker-api-1       | The above exception was the direct cause of the following exception:
docker-api-1       |
docker-api-1       | Traceback (most recent call last):
docker-api-1       |   File "/usr/local/bin/flask", line 8, in <module>
docker-api-1       |     sys.exit(main())
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1063, in main
docker-api-1       |     cli.main()
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
docker-api-1       |     rv = self.invoke(ctx)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
docker-api-1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
docker-api-1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
docker-api-1       |     return ctx.invoke(self.callback, **ctx.params)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
docker-api-1       |     return __callback(*args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
docker-api-1       |     return f(get_current_context(), *args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
docker-api-1       |     return __ctx.invoke(f, *args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
docker-api-1       |     return __callback(*args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask_migrate/cli.py", line 150, in upgrade
docker-api-1       |     _upgrade(directory, revision, sql, tag, x_arg)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 111, in wrapped
docker-api-1       |     f(*args, **kwargs)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/flask_migrate/__init__.py", line 200, in upgrade
docker-api-1       |     command.upgrade(config, revision, sql=sql, tag=tag)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
docker-api-1       |     script.run_env()
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
docker-api-1       |     util.load_python_file(self.dir, "env.py")
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
docker-api-1       |     module = load_module_py(module_id, path)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
docker-api-1       |     spec.loader.exec_module(module)  # type: ignore
docker-api-1       |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
docker-api-1       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
docker-api-1       |   File "/app/api/migrations/env.py", line 113, in <module>
docker-api-1       |     run_migrations_online()
docker-api-1       |   File "/app/api/migrations/env.py", line 107, in run_migrations_online
docker-api-1       |     context.run_migrations()
docker-api-1       |   File "<string>", line 8, in run_migrations
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 868, in run_migrations
docker-api-1       |     self.get_context().run_migrations(**kw)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 622, in run_migrations
docker-api-1       |     step.migration_fn(**kw)
docker-api-1       |   File "/app/api/migrations/versions/64b051264f32_init.py", line 21, in upgrade
docker-api-1       |     op.create_table('account_integrates',
docker-api-1       |   File "<string>", line 8, in create_table
docker-api-1       |   File "<string>", line 3, in create_table
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/ops.py", line 1255, in create_table
docker-api-1       |     return operations.invoke(op)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/base.py", line 401, in invoke
docker-api-1       |     return fn(self, operation)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 114, in create_table
docker-api-1       |     operations.impl.create_table(table)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 354, in create_table
docker-api-1       |     self._exec(schema.CreateTable(table))
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 193, in _exec
docker-api-1       |     return conn.execute(  # type: ignore[call-overload]
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
docker-api-1       |     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
docker-api-1       |     return connection._execute_ddl(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
docker-api-1       |     ret = self._execute_context(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1948, in _execute_context
docker-api-1       |     self._handle_dbapi_exception(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2129, in _handle_dbapi_exception
docker-api-1       |     util.raise_(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
docker-api-1       |     raise exception
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1905, in _execute_context
docker-api-1       |     self.dialect.do_execute(
docker-api-1       |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
docker-api-1       |     cursor.execute(statement, parameters)
docker-api-1       | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function uuid_generate_v4() does not exist
docker-api-1       | LINE 3:  id UUID DEFAULT uuid_generate_v4() NOT NULL,
docker-api-1       |                          ^
docker-api-1       | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
docker-api-1       |
docker-api-1       | [SQL:
docker-api-1       | CREATE TABLE account_integrates (
docker-api-1       | 	id UUID DEFAULT uuid_generate_v4() NOT NULL,
docker-api-1       | 	account_id UUID NOT NULL,
docker-api-1       | 	provider VARCHAR(16) NOT NULL,
docker-api-1       | 	open_id VARCHAR(255) NOT NULL,
docker-api-1       | 	encrypted_token VARCHAR(255) NOT NULL,
docker-api-1       | 	created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
docker-api-1       | 	updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
docker-api-1       | 	CONSTRAINT account_integrate_pkey PRIMARY KEY (id),
docker-api-1       | 	CONSTRAINT unique_account_provider UNIQUE (account_id, provider),
docker-api-1       | 	CONSTRAINT unique_provider_open_id UNIQUE (provider, open_id)
docker-api-1       | )
docker-api-1       |
docker-api-1       | ]
docker-api-1       | (Background on this error at: https://sqlalche.me/e/14/f405)
docker-api-1 exited with code 1
docker-api-1       | Running migrations
```

**Comment by takatost** [comment]
不好意思忘了说了，拉一下最新镜像哈
 docker pull langgenius/dify:latest

**Comment by camelgeek** [comment]
> 不好意思忘了说了，拉一下最新镜像哈 docker pull langgenius/dify-api:latest

好的，我将 image 改成本地 Dockerfile 了，重新"docker-compose build"之后，也可以了。
```
  api:
    build: 
      context: ../api
      dockerfile: Dockerfile
```

**Comment by lynnroyal** [comment]
> 不好意思忘了说了，拉一下最新镜像哈 docker pull langgenius/dify-api:latest

嗯，辛苦了，已经好了
