### ISSUE TITLE
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

### ISSUE THREAD

**Issue by JiangYain** [langgenius/dify#8094]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

2024-09-08 10:19:04,620.620 ERROR [Dummy-2042] [workflow.py:184] - internal server error.
Traceback (most recent call last):
  File "/app/api/controllers/console/app/workflow.py", line 172, in post
    response = AppGenerateService.generate(
  File "/app/api/services/app_generate_service.py", line 67, in generate
    AdvancedChatAppGenerator().generate(
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 143, in generate
    return self._generate(
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 267, in _generate
    conversation_variables = [item.to_variable() for item in conversation_variables]
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 267, in <listcomp>
    conversation_variables = [item.to_variable() for item in conversation_variables]
  File "/app/api/models/workflow.py", line 768, in to_variable
    return factory.build_variable_from_mapping(mapping)
  File "/app/api/core/app/segments/factory.py", line 59, in build_variable_from_mapping
    raise VariableError(f'variable size {result.size} exceeds limit {dify_config.MAX_VARIABLE_SIZE}')
core.app.segments.exc.VariableError: variable size 13070 exceeds limit 5120
2024-09-08 10:19:04,621.621 ERROR [Dummy-2042] [app.py:838] - Exception on /console/api/apps/4971d3dd-2a29-4a6a-8713-4657f084bc7a/advanced-chat/workflows/draft/run [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/app/workflow.py", line 172, in post
    response = AppGenerateService.generate(
  File "/app/api/services/app_generate_service.py", line 67, in generate
    AdvancedChatAppGenerator().generate(
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 143, in generate
    return self._generate(
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 267, in _generate
    conversation_variables = [item.to_variable() for item in conversation_variables]
  File "/app/api/core/app/apps/advanced_chat/app_generator.py", line 267, in <listcomp>
    conversation_variables = [item.to_variable() for item in conversation_variables]
  File "/app/api/models/workflow.py", line 768, in to_variable
    return factory.build_variable_from_mapping(mapping)
  File "/app/api/core/app/segments/factory.py", line 59, in build_variable_from_mapping
    raise VariableError(f'variable size {result.size} exceeds limit {dify_config.MAX_VARIABLE_SIZE}')
core.app.segments.exc.VariableError: variable size 13070 exceeds limit 5120

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/app/wraps.py", line 48, in decorated_view
    return view_func(*args, **kwargs)
  File "/app/api/controllers/console/app/workflow.py", line 185, in post
    raise InternalServerError()
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### ✔️ Expected Behavior

Normal operation chatflow

### ❌ Actual Behavior

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

**Comment by JiangYain** [comment]
Can you explain in detail how to modify MAX_VARIABLE_SIZE? I use Docker deployment, maybe you need to give me a tutorial

> 我找到了一个类似的已关闭问题，它可能会帮助您解决此问题。该问题与 Docker 设置中的`web`和服务之间的版本不匹配有关。具体来说，服务正在使用，而服务正在使用。确保服务使用相同的版本解决了两个问题[[1]](https://github.com/langgenius/dify/issues/5457)。`api``web``langgenius/dify-web:0.6.10``api``langgenius/dify-api:0.6.11`[](https://github.com/langgenius/dify/issues/5457)
> 
> 在您的示例中，错误消息表明变量大小超出了配置中定义的限制（`dify_config.MAX_VARIABLE_SIZE`）。限制设置为 5120 字节，而您的变量大小为 13070 字节。这导致`VariableError`被提升。
> 
> 要解决此问题，您可以：
> 
> 1. **减少变量的大小**：确保正在处理的数据不超过 5120 字节的限制。
> 2. **增加`MAX_VARIABLE_SIZE`限制**：如果减少器件大小无法安装，则可以`MAX_VARIABLE_SIZE`在配置中增加限制。
> 
> 以下是变量大小超出限制时引发错误的相关代码片段：
> 
> ```python
> if result.size > dify_config.MAX_VARIABLE_SIZE:
>     raise VariableError(f'variable size {result.size} exceeds limit {dify_config.MAX_VARIABLE_SIZE}')
> ```
> 
> 另外，您可能还需要检查`docker-compose.yaml`文件中是否存在可能影响配置参数大小或错误处理的设置。具体来说，查找以下环境变量：
> 
> * `UPLOAD_FILE_SIZE_LIMIT`
> * `UPLOAD_IMAGE_FILE_SIZE_LIMIT`
> * `NGINX_CLIENT_MAX_BODY_SIZE`
> 
> 这些设置会影响各种类型的上传和请求的大小限制，从而影响与大小限制相关的错误处理[[2]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)。
> 
> 通过解决变量大小问题或调整配置设置，您应该能够解决内部服务器错误。
> 
> _要继续与[Dosu](https://dosu.dev)交谈，请提及@dosu。_
