### ISSUE TITLE
datasets query error

### ISSUE THREAD

**Issue by soulzzz** [langgenius/dify#8211]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

After upgrading the version, some of my knowledge datasets cannot be queried！！！
And i try to create a new dataset and the same error occurred
1.creating a new dataset,and upload 1 file 
2.try a hit testing

```
2024-09-10 09:18:55,802.802 INFO [Thread-218 (process_request_thread)] [_internal.py:97] - 10.8.8.141 - - [10/Sep/2024 09:18:55] "OPTIONS /console/api/datasets/beb7e2e4-fa97-46fc-93c9-26612c3858f0/hit-testing HTTP/1.1" 200 -
2024-09-10 09:18:55,845.845 ERROR [Thread-219 (process_request_thread)] [hit_testing.py:82] - Hit testing failed.
Traceback (most recent call last):
  File "/home/sky/Second/dify/api/controllers/console/datasets/hit_testing.py", line 55, in post
    response = HitTestingService.retrieve(
  File "/home/sky/Second/dify/api/services/hit_testing_service.py", line 38, in retrieve
    all_documents = RetrievalService.retrieve(
  File "/home/sky/Second/dify/api/core/rag/datasource/retrieval_service.py", line 100, in retrieve
    raise Exception(exception_message)
Exception: Error during query: [{'locations': [{'column': 22885, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_beb7e2e4_fa97_46fc_93c9_26612c3858f0_Node".', 'path': None}]
2024-09-10 09:18:55,845.845 ERROR [Thread-219 (process_request_thread)] [app.py:838] - Exception on /console/api/datasets/beb7e2e4-fa97-46fc-93c9-26612c3858f0/hit-testing [POST]
Traceback (most recent call last):
  File "/home/sky/Second/dify/api/controllers/console/datasets/hit_testing.py", line 55, in post
    response = HitTestingService.retrieve(
  File "/home/sky/Second/dify/api/services/hit_testing_service.py", line 38, in retrieve
    all_documents = RetrievalService.retrieve(
  File "/home/sky/Second/dify/api/core/rag/datasource/retrieval_service.py", line 100, in retrieve
    raise Exception(exception_message)
Exception: Error during query: [{'locations': [{'column': 22885, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_beb7e2e4_fa97_46fc_93c9_26612c3858f0_Node".', 'path': None}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/sky/anaconda3/envs/dify/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/sky/Second/dify/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/home/sky/Second/dify/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/sky/Second/dify/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/home/sky/Second/dify/api/controllers/console/datasets/hit_testing.py", line 83, in post
    raise InternalServerError(str(e))
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Error during query: [{'locations': [{'column': 22885, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_beb7e2e4_fa97_46fc_93c9_26612c3858f0_Node".', 'path': None}]
2024-09-10 09:18:55,846.846 INFO [Thread-219 (process_request_thread)] [_internal.py:97] - 10.8.8.141 - - [10/Sep/2024 09:18:55] "POST /console/api/datasets/beb7e2e4-fa97-46fc-93c9-26612c3858f0/hit-testing HTTP/1.1" 500 -
```

### ✔️ Expected Behavior

queried Successfully

### ❌ Actual Behavior

queried fail

**Comment by AAEE86** [comment]
`Error during query: [{'locations': [{'column': 161, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_ed9112e3_6883_4e92_bb39_13f56f4dbe18_Node".', 'path': None}]; Error during query: [{'locations': [{'column': 17089, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_ed9112e3_6883_4e92_bb39_13f56f4dbe18_Node".', 'path': None}]`

**Comment by Howe829** [comment]
I'll put some related issues here #8117 #8175

**Comment by AAEE86** [comment]
`Error during query: [{'locations': [{'column': 22888, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_ed9112e3_6883_4e92_bb39_13f56f4dbe18_Node".', 'path': None}]



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request

    rv = self.dispatch_request()

  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]

  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper

    resp = resource(*args, **kwargs)

  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view

    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]

  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request

    resp = meth(*args, **kwargs)

  File "/app/api/controllers/console/setup.py", line 65, in decorated

    return view(*args, **kwargs)

  File "/app/api/libs/login.py", line 93, in decorated_view

    return current_app.ensure_sync(func)(*args, **kwargs)

  File "/app/api/controllers/console/wraps.py", line 22, in decorated

    return view(*args, **kwargs)

  File "/app/api/controllers/console/datasets/hit_testing.py", line 83, in post

    raise InternalServerError(str(e))

werkzeug.exceptions.InternalServerError: 500 Internal Server Error: Error during query: [{'locations': [{'column': 150, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_ed9112e3_6883_4e92_bb39_13f56f4dbe18_Node".', 'path': None}];

Error during query: [{'locations': [{'column': 22888, 'line': 1}], 'message': 'Cannot query field "page" on type "Vector_index_ed9112e3_6883_4e92_bb39_13f56f4dbe18_Node".', 'path': None}]`

**Comment by crazywoola** [comment]
I think this is introduced in this pr https://github.com/langgenius/dify/pull/7749

**Comment by Howe829** [comment]
> I think this is introduced in this pr #7749

No wonder, I tried the pdf file the hit-testing works well, but the txt file failed.

**Comment by soulzzz** [comment]
> I think this is introduced in this pr #7749

I think this is the root cause of the problem，i'm using weaviate DB as default DB

**Comment by Howe829** [comment]
https://github.com/langgenius/dify/blob/86f7f245e4331d6025496a27a80fd4bcc72e0802/api/core/rag/datasource/vdb/vector_factory.py#L33 
remove the 'page' from attributes it will be solved.
