### ISSUE TITLE
api and worker can not run in docker

### ISSUE THREAD

**Issue by wwwsec** [langgenius/dify#8512]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

langgenius/dify-api:0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

api and worker can not run in docker
this is the log
2024-09-18 12:15:17 Traceback (most recent call last):
2024-09-18 12:15:17   File "/app/api/.venv/bin/flask", line 8, in <module>
2024-09-18 12:15:17     sys.exit(main())
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 1105, in main
2024-09-18 12:15:17     cli.main()
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
2024-09-18 12:15:17     rv = self.invoke(ctx)
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1682, in invoke
2024-09-18 12:15:17     cmd_name, cmd, args = self.resolve_command(ctx, args)
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1729, in resolve_command
2024-09-18 12:15:17     cmd = self.get_command(ctx, cmd_name)
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 611, in get_command
2024-09-18 12:15:17     app = info.load_app()
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 335, in load_app
2024-09-18 12:15:17     app = locate_app(import_name, name)
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 245, in locate_app
2024-09-18 12:15:17     __import__(module_name)
2024-09-18 12:15:17   File "/app/api/app.py", line 24, in <module>
2024-09-18 12:15:17     import contexts
2024-09-18 12:15:17   File "/app/api/contexts/__init__.py", line 3, in <module>
2024-09-18 12:15:17     from core.workflow.entities.variable_pool import VariablePool
2024-09-18 12:15:17   File "/app/api/core/workflow/entities/variable_pool.py", line 8, in <module>
2024-09-18 12:15:17     from core.app.segments import Segment, Variable, factory
2024-09-18 12:15:17   File "/app/api/core/app/segments/__init__.py", line 13, in <module>
2024-09-18 12:15:17     from .variables import (
2024-09-18 12:15:17   File "/app/api/core/app/segments/variables.py", line 3, in <module>
2024-09-18 12:15:17     from core.helper import encrypter
2024-09-18 12:15:17   File "/app/api/core/helper/encrypter.py", line 4, in <module>
2024-09-18 12:15:17     from libs import rsa
2024-09-18 12:15:17   File "/app/api/libs/rsa.py", line 9, in <module>
2024-09-18 12:15:17     from extensions.ext_storage import storage
2024-09-18 12:15:17   File "/app/api/extensions/ext_storage.py", line 7, in <module>
2024-09-18 12:15:17     from extensions.storage.azure_storage import AzureStorage
2024-09-18 12:15:17   File "/app/api/extensions/storage/azure_storage.py", line 4, in <module>
2024-09-18 12:15:17     from azure.storage.blob import AccountSasPermissions, BlobServiceClient, ResourceTypes, generate_account_sas
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/azure/storage/blob/__init__.py", line 10, in <module>
2024-09-18 12:15:17     from ._blob_client import BlobClient
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 24, in <module>
2024-09-18 12:15:17     from ._shared.base_client import StorageAccountHostsMixin, parse_connection_str, parse_query, TransportWrapper
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/base_client.py", line 37, in <module>
2024-09-18 12:15:17     from .constants import CONNECTION_TIMEOUT, READ_TIMEOUT, SERVICE_HOST_BASE
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/constants.py", line 7, in <module>
2024-09-18 12:15:17     from .._serialize import _SUPPORTED_API_VERSIONS
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/azure/storage/blob/_serialize.py", line 18, in <module>
2024-09-18 12:15:17     from ._models import (
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/azure/storage/blob/_models.py", line 18, in <module>
2024-09-18 12:15:17     from ._generated.models import ArrowField
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/azure/storage/blob/_generated/__init__.py", line 9, in <module>
2024-09-18 12:15:17     from ._azure_blob_storage import AzureBlobStorage
2024-09-18 12:15:17   File "/app/api/.venv/lib/python3.10/site-packages/azure/storage/blob/_generated/_azure_blob_storage.py", line 12, in <module>
2024-09-18 12:15:17     from msrest import Deserializer, Serializer
2024-09-18 12:15:17 ValueError: source code string cannot contain null bytes
2024-09-18 12:15:18 Exception ignored in: <function Redis.__del__ at 0x7f847e2e9480>
2024-09-18 12:15:18 Traceback (most recent call last):
2024-09-18 12:15:18   File "/app/api/.venv/lib/python3.10/site-packages/redis/client.py", line 503, in __del__
2024-09-18 12:15:18   File "/app/api/.venv/lib/python3.10/site-packages/redis/client.py", line 509, in close
2024-09-18 12:15:18   File "/app/api/extensions/ext_redis.py", line 36, in __getattr__
2024-09-18 12:15:18 RuntimeError: Redis client is not initialized. Call init_app first.

### ✔️ Expected Behavior

none

### ❌ Actual Behavior

none

**Comment by wwwsec** [comment]
I have retrieved the image again, and now it's okay.
 
 @dosu thanks!
