### ISSUE TITLE
timeout when add llama3.1 model as text embedding model

### ISSUE THREAD

**Issue by caolizhong-pm** [langgenius/dify#8636]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

timeout when add llama3.1 70b model as text embedding model, but local llama3 8b model has no issue

### ✔️ Expected Behavior

llama3.1 70b model can be added as text embedding model

### ❌ Actual Behavior

saving failed in GUI and timeout in backend log

**Comment by crazywoola** [comment]
Are there any logs or errors that can help us to investigate?

**Comment by caolizhong-pm** [comment]
docker-api-1         | Traceback (most recent call last):
docker-api-1         |   File "/app/api/controllers/console/workspace/models.py", line 151, in post
docker-api-1         |     model_provider_service.save_model_credentials(
docker-api-1         |   File "/app/api/services/model_provider_service.py", line 250, in save_model_credentials
docker-api-1         |     provider_configuration.add_or_update_custom_model_credentials(
docker-api-1         |   File "/app/api/core/entities/provider_configuration.py", line 390, in add_or_update_custom_model_credentials
docker-api-1         |     provider_model_record, credentials = self.custom_model_credentials_validate(model_type, model, credentials)
docker-api-1         |   File "/app/api/core/entities/provider_configuration.py", line 370, in custom_model_credentials_validate
docker-api-1         |     credentials = model_provider_factory.model_credentials_validate(
docker-api-1         |   File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 123, in model_credentials_validate
docker-api-1         |     model_instance.validate_credentials(model, filtered_credentials)
docker-api-1         |   File "/app/api/core/model_runtime/model_providers/ollama/text_embedding/text_embedding.py", line 123, in validate_credentials
docker-api-1         |     raise CredentialsValidateFailedError(f"An error occurred during credentials validation: {str(ex)}")
docker-api-1         | core.model_runtime.errors.validate.CredentialsValidateFailedError: An error occurred during credentials validation: HTTPConnectionPool(host='hzllmapi.dyn.nesc.nokia.net', port=8080): Read timed out. (read timeout=300)

**Comment by crazywoola** [comment]
It seems to be a general network issue to me. Can you call this model with api?

**Comment by caolizhong-pm** [comment]
yes, call model is normal and also able to add this model as chat model

**Comment by caolizhong-pm** [comment]
Hi, any update

**Comment by crazywoola** [comment]
Nope
