### ISSUE TITLE
Exception: Invalid provider: Jina AI

### ISSUE THREAD

**Issue by ycoe** [langgenius/dify#8714]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

2024-09-24 07:05:10,420.420 INFO [Thread-144 (process_request_thread)] [_internal.py:97] - 127.0.0.1 - - [24/Sep/2024 07:05:10] "GET /console/api/workspaces/current/models/model-types/text-embedding HTTP/1.1" 500 -

### ❌ Actual Behavior

2024-09-24 07:05:10,418.418 ERROR [Thread-144 (process_request_thread)] [app.py:838] - Exception on /console/api/workspaces/current/models/model-types/text-embedding [GET]
Traceback (most recent call last):
  File "/home/python/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/dify/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/python/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/python/dify/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/python/dify/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/python/dify/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/home/python/dify/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/python/dify/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/home/python/dify/api/controllers/console/workspace/models.py", line 354, in get
    models = model_provider_service.get_models_by_model_type(tenant_id=tenant_id, model_type=model_type)
  File "/home/python/dify/api/services/model_provider_service.py", line 287, in get_models_by_model_type
    models = provider_configurations.get_models(model_type=ModelType.value_of(model_type))
  File "/home/python/dify/api/core/entities/provider_configuration.py", line 1024, in get_models
    all_models.extend(provider_configuration.get_provider_models(model_type, only_active))
  File "/home/python/dify/api/core/entities/provider_configuration.py", line 737, in get_provider_models
    provider_instance = self.get_provider_instance()
  File "/home/python/dify/api/core/entities/provider_configuration.py", line 628, in get_provider_instance
    return model_provider_factory.get_provider_instance(self.provider.provider)
  File "/home/python/dify/api/core/model_runtime/model_providers/model_provider_factory.py", line 200, in get_provider_instance
    raise Exception(f"Invalid provider: {provider}")
Exception: Invalid provider: Jina AI

**Comment by crazywoola** [comment]
Fixed (#8710)
