### ISSUE TITLE
Editing Retrieval Setting in knowledge base return error 

### ISSUE THREAD

**Issue by damadorPL** [langgenius/dify#8933]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.0 and previous

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Edit any data knowledge base - change serttings from vector search to hybrid for example or change TOP K - or anything 

### ❌ Actual Behavior
```
2024-09-30 12:15:33,041.041 ERROR [Dummy-15] [app.py:838] - Exception on /console/api/datasets/551a1f2f-039c-4847-8ed4-1dd98aaa5237 [PATCH]
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/datasets/datasets.py", line 278, in patch
    dataset = DatasetService.update_dataset(dataset_id_str, args, current_user)
  File "/app/api/services/dataset_service.py", line 320, in update_dataset
    dataset.query.filter_by(id=dataset_id).update(filtered_data)
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3247, in update
    upd = upd.values(values)
  File "<string>", line 2, in values
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 279, in _generative
    x = fn(self, *args, **kw)
  File "<string>", line 2, in values
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 312, in check
    return fn(self, *args, **kw)
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/sql/dml.py", line 1159, in values
    coerced_arg = dict(kv_generator(self, arg.items(), True))
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 478, in _get_crud_kv_pairs
    return list(
  File "/app/api/.venv/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 419, in _get_orm_crud_kv_pairs
    desc._bulk_update_tuples(v),
AttributeError: 'property' object has no attribute '_bulk_update_tuples'
```

**Comment by crazywoola** [comment]
Fixed in https://github.com/langgenius/dify/pull/8940

**Comment by daizy008** [comment]
i have the same problem too
