### ISSUE TITLE
Run failed: [huggingface_tei] Error: timed out

### ISSUE THREAD

**Issue by Nico197705** [langgenius/dify#8995]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Mac Book Pro
Install Dify 0.8.3 as described in the user guide.
Start TEI using BAAI/bge-reranker-v2-m3
Start Dify 0.8.3 using `docker-compose up -d`
Add this reranker model using Dify settings (and Embedding & System Reasonning models) 
Create a workflow using many a quite heavy knowledge base (many elements)
Start preview.

### ✔️ Expected Behavior

Retrieving knowledge for query

### ❌ Actual Behavior

Run failed: [huggingface_tei] Error: timed out
```

`docker-compose logs -f` shows a stack trace error:
docker-api-1`         | 2024-10-03 06:54:55,595.595 INFO [Thread-7 (embedding_search)] [_client.py:1038] - HTTP Request: POST http://host.docker.internal:8082/rerank "HTTP/1.1 200 OK"
docker-api-1         | 2024-10-03 06:55:00,642.642 ERROR [Thread-3 (_generate_worker)] [knowledge_retrieval_node.py:59] - Error when running knowledge retrieval node
docker-api-1         | Traceback (most recent call last):
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
docker-api-1         |     yield
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
docker-api-1         |     resp = self._pool.handle_request(req)
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
docker-api-1         |     raise exc from None
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
docker-api-1         |     response = connection.handle_request(
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
docker-api-1         |     return self._connection.handle_request(request)
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
docker-api-1         |     raise exc
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
docker-api-1         |     ) = self._receive_response_headers(**kwargs)
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
docker-api-1         |     event = self._receive_event(timeout=timeout)
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
docker-api-1         |     data = self._network_stream.read(
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 124, in read
docker-api-1         |     with map_exceptions(exc_map):
docker-api-1         |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
docker-api-1         |     self.gen.throw(typ, value, traceback)
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
docker-api-1         |     raise to_exc(exc) from exc
docker-api-1         | httpcore.ReadTimeout: timed out
docker-api-1         | 
docker-api-1         | The above exception was the direct cause of the following exception:
docker-api-1         | 
docker-api-1         | Traceback (most recent call last):
docker-api-1         |   File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 42, in invoke
docker-api-1         |     return self._invoke(model, credentials, query, docs, score_threshold, top_n, user)
docker-api-1         |   File "/app/api/core/model_runtime/model_providers/huggingface_tei/rerank/rerank.py", line 55, in _invoke
docker-api-1         |     results = TeiHelper.invoke_rerank(server_url, query, docs)
docker-api-1         |   File "/app/api/core/model_runtime/model_providers/huggingface_tei/tei_helper.py", line 177, in invoke_rerank
docker-api-1         |     response = httpx.post(
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_api.py", line 331, in post
docker-api-1         |     return request(
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_api.py", line 118, in request
docker-api-1         |     return client.request(
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_client.py", line 837, in request
docker-api-1         |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
docker-api-1         |     response = self._send_handling_auth(
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
docker-api-1         |     response = self._send_handling_redirects(
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
docker-api-1         |     response = self._send_single_request(request)
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
docker-api-1         |     response = transport.handle_request(request)
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 235, in handle_request
docker-api-1         |     with map_httpcore_exceptions():
docker-api-1         |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
docker-api-1         |     self.gen.throw(typ, value, traceback)
docker-api-1         |   File "/app/api/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
docker-api-1         |     raise mapped_exc(message) from exc
docker-api-1         | httpx.ReadTimeout: timed out
docker-api-1         | 
docker-api-1         | During handling of the above exception, another exception occurred:
docker-api-1         | 
docker-api-1         | Traceback (most recent call last):
docker-api-1         |   File "/app/api/core/workflow/nodes/knowledge_retrieval/knowledge_retrieval_node.py", line 52, in _run
docker-api-1         |     results = self._fetch_dataset_retriever(node_data=node_data, query=query)
docker-api-1         |   File "/app/api/core/workflow/nodes/knowledge_retrieval/knowledge_retrieval_node.py", line 145, in _fetch_dataset_retriever
docker-api-1         |     all_documents = dataset_retrieval.multiple_retrieve(
docker-api-1         |   File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 339, in multiple_retrieve
docker-api-1         |     all_documents = data_post_processor.invoke(
docker-api-1         |   File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 37, in invoke
docker-api-1         |     documents = self.rerank_runner.run(query, documents, score_threshold, top_n, user)
docker-api-1         |   File "/app/api/core/rag/rerank/rerank_model.py", line 39, in run
docker-api-1         |     rerank_result = self.rerank_model_instance.invoke_rerank(
docker-api-1         |   File "/app/api/core/model_manager.py", line 221, in invoke_rerank
docker-api-1         |     return self._round_robin_invoke(
docker-api-1         |   File "/app/api/core/model_manager.py", line 305, in _round_robin_invoke
docker-api-1         |     return function(*args, **kwargs)
docker-api-1         |   File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 44, in invoke
docker-api-1         |     raise self._transform_invoke_error(e)
docker-api-1         | core.model_runtime.errors.invoke.InvokeError: [huggingface_tei] Error: timed out
```

**Comment by crazywoola** [comment]
This is a general network issue, please use a VPN to make sure you can access it.
