### ISSUE TITLE
redis.exceptions.ResponseError: 'BRPOP' command keys must in same slot

### ISSUE THREAD

**Issue by TChengZ** [langgenius/dify#9154]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

run
`python3 -m celery -A app.celery worker -P gevent -c 1 --loglevel INFO -Q dataset,generation,mail,ops_trace,app_deletion`

### ✔️ Expected Behavior

no error happen

### ❌ Actual Behavior

`[2024-10-10 03:49:02,396: INFO/MainProcess] Connected to redis://:**@xxxxxxxxx:6379/1
[2024-10-10 03:49:02,925: INFO/MainProcess] mingle: searching for neighbors
[2024-10-10 03:49:05,081: CRITICAL/MainProcess] Unrecoverable error: ResponseError("'BRPOP' command keys must in same slot")
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 37, in start
    self.sync(c)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
    replies = self.send_hello(c)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/app/control.py", line 389, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kombu/pidbox.py", line 346, in _broadcast
    return self._collect(reply_ticket, limit=limit,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kombu/pidbox.py", line 388, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kombu/transport/redis.py", line 591, in get
    ret = self.handle_event(fileno, event)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kombu/transport/redis.py", line 573, in handle_event
    return self.on_readable(fileno), self
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kombu/transport/redis.py", line 569, in on_readable
    chan.handlers[type]()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kombu/transport/redis.py", line 967, in _brpop_read
    dest__item = self.client.parse_response(self.client.connection,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kombu/transport/redis.py", line 247, in parse_response
    ret = super().parse_response(connection, command_name, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/redis/client.py", line 565, in parse_response
    response = connection.read_response()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/redis/connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: 'BRPOP' command keys must in same slot
`

**Comment by crazywoola** [comment]
If you are trying to use Aliyun. Then you will meet this problem.

**Comment by TChengZ** [comment]
> If you are trying to use Aliyun. Then you will meet this problem. It's not the problem of our side.
> 
> https://help.aliyun.com/zh/redis/developer-reference/limits-on-commands-supported-by-cluster-and-read-write-splitting-instances

how can i fix this problem, i did use aliyun。From the article u provided，it seems a way to solve
![image](https://github.com/user-attachments/assets/607d4993-1363-4263-9664-92230268f4a2)
how to use this way in dify?

**Comment by mboo2005** [comment]
any progress? How to use redis cluster in dify expecially celery

**Comment by TChengZ** [comment]
> any progress? How to use redis cluster in dify expecially celery

the way to solve is to change redis that doesn't support cluster model， i change other aliyun redis to fix this.
