### ISSUE TITLE
panic: runtime error: slice bounds out of range [:9349989] with capacity 4194304 (docker-weaviate-1 semitechnologies/weaviate:1.19.0)

### ISSUE THREAD

**Issue by Liangwei-0521** [langgenius/dify#9158]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce
```
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex.(*Header).PrimaryIndex(0x1b89f20?, {0x7f2f9ead2000?, 0x0?, 0x400000?})
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex/header.go:62 +0x145
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db/lsmkv.newSegment({0xc003e88200, 0x80}, {0x1bae970?, 0xc003ea2150}, 0x0, 0xc003deb218?)
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment.go:96 +0x239
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db/lsmkv.newSegmentGroup({0xc003e90230, 0x61}, {0x1bae970, 0xc003ea2150}, 0x0, 0x0, {0x17a6603, 0x7}, 0x1)
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_group.go:118 +0x985
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db/lsmkv.NewBucket({0x1b9b100, 0xc002dfade0}, {0xc003e90230, 0x61}, {0xc0000480a6, 0x11}, {0x1bae970?, 0xc003ea2150?}, 0x0, {0xc003deb830, ...})
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/bucket.go:118 +0x2c5
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Store).CreateOrLoadBucket(0xc003118420, {0x1b9b100, 0xc002dfade0}, {0x17a638d, 0x7}, {0xc003deb830, 0x5, 0x5})
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/store.go:118 +0x128
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db.(*Shard).initLSMStore(0xc002da3500, {0x1b9b100, 0xc002dfade0})
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:235 +0x3b0
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db.(*Shard).initNonVector(0xc002da3500, {0x1b9b100?, 0xc002dfade0?}, 0x80?)
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:170 +0x4b
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db.NewShard({0x1b9b100, 0xc002dfade0}, 0x0, {0xc0031e3040, 0xc}, 0xc0031dd380, 0x3?, 0xc002dfb080)
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:120 +0x612
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db.NewIndex({_, _}, {{0xc0000480a6, 0x11}, {0xc0030a7140, 0x36}, 0x2710, {{0x50, 0x5a}, {0x50, ...}}, ...}, ...)
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:140 +0x777
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db.(*DB).init(0xc0030dd4a0, {0x1b9b100, 0xc002dfade0})
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/init.go:57 +0x565
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/repos/db.(*DB).WaitForStartup(0xc0030dd4a0, {0x1b9b100?, 0xc002dfade0?})
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/repos/db/repo.go:81 +0x28
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/handlers/rest.configureAPI(0xc000427800)
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/configure_api.go:261 +0x2214
2024-10-10 11:37:06 github.com/weaviate/weaviate/adapters/handlers/rest.(*Server).ConfigureAPI(...)
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/server.go:68
2024-10-10 11:37:06 main.main()
2024-10-10 11:37:06     /go/src/github.com/weaviate/weaviate/cmd/weaviate-server/main.go:62 +0x475
2024-10-10 11:37:08 {"action":"startup","default_vectorizer_module":"none","level":"info","msg":"the default vectorizer modules is set to \"none\", as a result all new schema classes without an explicit vectorizer setting, will use this vectorizer","time":"2024-10-10T03:37:08Z"}
2024-10-10 11:37:08 {"action":"startup","auto_schema_enabled":true,"level":"info","msg":"auto schema enabled setting is set to \"true\"","time":"2024-10-10T03:37:08Z"}
2024-10-10 11:37:08 panic: runtime error: slice bounds out of range [:9349989] with capacity 4194304
2024-10-10 11:37:08 
2024-10-10 11:37:08 goroutine 1 [running]:
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex.(*Header).PrimaryIndex(0x1b89f20?, {0x7f228600e000?, 0x0?, 0x400000?})
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segmentindex/header.go:62 +0x145
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db/lsmkv.newSegment({0xc003a86880, 0x80}, {0x1bae970?, 0xc003d22150}, 0x0, 0xc003ce3218?)
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment.go:96 +0x239
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db/lsmkv.newSegmentGroup({0xc003d10230, 0x61}, {0x1bae970, 0xc003d22150}, 0x0, 0x0, {0x17a6603, 0x7}, 0x1)
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/segment_group.go:118 +0x985
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db/lsmkv.NewBucket({0x1b9b100, 0xc002db8de0}, {0xc003d10230, 0x61}, {0xc0000480a6, 0x11}, {0x1bae970?, 0xc003d22150?}, 0x0, {0xc003ce3830, ...})
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/bucket.go:118 +0x2c5
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Store).CreateOrLoadBucket(0xc003d12240, {0x1b9b100, 0xc002db8de0}, {0x17a638d, 0x7}, {0xc003ce3830, 0x5, 0x5})
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/lsmkv/store.go:118 +0x128
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db.(*Shard).initLSMStore(0xc002d8f500, {0x1b9b100, 0xc002db8de0})
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:235 +0x3b0
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db.(*Shard).initNonVector(0xc002d8f500, {0x1b9b100?, 0xc002db8de0?}, 0x80?)
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:170 +0x4b
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db.NewShard({0x1b9b100, 0xc002db8de0}, 0x0, {0xc00311f040, 0xc}, 0xc003119040, 0x3?, 0xc002db9080)
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/shard.go:120 +0x612
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db.NewIndex({_, _}, {{0xc0000480a6, 0x11}, {0xc003057140, 0x36}, 0x2710, {{0x50, 0x5a}, {0x50, ...}}, ...}, ...)
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/index.go:140 +0x777
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db.(*DB).init(0xc00308b4a0, {0x1b9b100, 0xc002db8de0})
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/init.go:57 +0x565
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/repos/db.(*DB).WaitForStartup(0xc00308b4a0, {0x1b9b100?, 0xc002db8de0?})
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/repos/db/repo.go:81 +0x28
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/handlers/rest.configureAPI(0xc00044cc00)
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/configure_api.go:261 +0x2214
2024-10-10 11:37:08 github.com/weaviate/weaviate/adapters/handlers/rest.(*Server).ConfigureAPI(...)
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/adapters/handlers/rest/server.go:68
2024-10-10 11:37:08 main.main()
2024-10-10 11:37:08     /go/src/github.com/weaviate/weaviate/cmd/weaviate-server/main.go:62 +0x475
```

### ❌ Actual Behavior

I strictly follow the tutorial for installation:

```
(base) liangwei@LAPTOP-RBVCU2OF:~/dify/docker$ ls
README.md  certbot  docker-compose.middleware.yaml  docker-compose.png  docker-compose.yaml  middleware.env.example  nginx  ssrf_proxy  startupscripts  volumes
(base) liangwei@LAPTOP-RBVCU2OF:~/dify/docker$ vi docker-compose.yaml
(base) liangwei@LAPTOP-RBVCU2OF:~/dify/docker$ cp .env.example .env
(base) liangwei@LAPTOP-RBVCU2OF:~/dify/docker$ docker compose up -d
[+] Running 74/9
 ✔ weaviate Pulled                                                                                                                                                                                        264.6s
 ✔ api Pulled                                                                                                                                                                                             466.6s
 ✔ web Pulled                                                                                                                                                                                              76.2s
 ✔ redis Pulled                                                                                                                                                                                           216.7s
 ✔ sandbox Pulled                                                                                                                                                                                         247.0s
 ✔ worker Pulled                                                                                                                                                                                          466.6s
 ✔ db Pulled                                                                                                                                                                                               31.7s
 ✔ ssrf_proxy Pulled                                                                                                                                                                                       72.5s
 ✔ nginx Pulled                                                                                                                                                                                           253.5s
[+] Running 11/11
 ✔ Network docker_ssrf_proxy_network  Created                                                                                                                                                               0.0s
 ✔ Network docker_default             Created                                                                                                                                                               0.1s
 ✔ Container docker-redis-1           Started                                                                                                                                                               2.2s
 ✔ Container docker-ssrf_proxy-1      Started                                                                                                                                                               2.2s
 ✔ Container docker-sandbox-1         Started                                                                                                                                                               2.2s
 ✔ Container docker-db-1              Started                                                                                                                                                               1.9s
 ✔ Container docker-weaviate-1        Started                                                                                                                                                               2.2s
 ✔ Container docker-web-1             Started                                                                                                                                                               2.2s
 ✔ Container docker-worker-1          Started                                                                                                                                                               3.0s
 ✔ Container docker-api-1             Started                                                                                                                                                               2.9s
 ✔ Container docker-nginx-1           Started                                                                                                                                                               3.8s
(base) liangwei@LAPTOP-RBVCU2OF:~/dify/docker$ 
```

**Comment by crazywoola** [comment]
We can not fix weaviate for you, please open an issue in their repo.
