### ISSUE TITLE
Azure openai chat :403 Forbidden

### ISSUE THREAD

**Issue by dale22** [langgenius/dify#9481]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1，Setup azure openai model is ok
2，but use this  model chat, docker-api logs:403
logs;docker-api-1 
2024-10-18 04:16:55,655.655 INFO [Thread-4 (_generate_worker)] [_client.py:1038] - HTTP Request: POST https://xxxxxx/openai/deployments/GPT-4o-2024-05-13/chat/completions?api-version=2024-05-01-preview "HTTP/1.1 403 Forbidden"

### ✔️ Expected Behavior

return result

### ❌ Actual Behavior

return 403

**Comment by dale22** [comment]
1，set model is ok，so API Key and Endpoint and deployment name is ok
![image](https://github.com/user-attachments/assets/e3bb19de-4835-4122-ac23-503a089c260e)
2，Curl requests on the same machine are fine
![image](https://github.com/user-attachments/assets/c4dd051d-aaf4-43d2-abea-7f952aca317a)
3，but dify chat is error， docker-api logs:403 
![image](https://github.com/user-attachments/assets/a7f7b449-1b12-48b1-8d63-b4c180ce1481)

**Comment by dale22** [comment]
chat ui return
![image](https://github.com/user-attachments/assets/e84e5228-be8e-4e73-85a8-e4d85b25f328)

**Comment by dale22** [comment]
chat return 
![image](https://github.com/user-attachments/assets/1d3b321b-0238-4d15-ac47-d4b4697f437e)

**Comment by crazywoola** [comment]
Please check the deployment in Azure Console, the 403 error is not raised by us.

**Comment by dale22** [comment]
Azure Console, feedback，Streaming requests are not yet allowed.
open ai is not support streaming , how can I close streaming param.
[
2024-10-21 08:05:21,141.141 ERROR [Thread-141 (_generate_worker)] [logging_callback.py:169] - Error code: 403 - {'message': 'Streaming requests are not yet allowed.'}
Traceback (most recent call last):
]

**Comment by dale22** [comment]
2024-10-21 08:05:21,141.141 ERROR [Thread-141 (_generate_worker)] [logging_callback.py:169] - Error code: 403 - {'message': 'Streaming requests are not yet allowed.'}
Traceback (most recent call last):
  File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 110, in invoke
    result = self._invoke(model, credentials, prompt_messages, model_parameters, tools, stop, stream, user)
  File "/app/api/core/model_runtime/model_providers/azure_openai/llm/llm.py", line 55, in _invoke
    return self._chat_generate(
  File "/app/api/core/model_runtime/model_providers/azure_openai/llm/llm.py", line 331, in _chat_generate
    response = client.chat.completions.create(
  File "/app/api/.venv/lib/python3.10/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 590, in create
    return self._post(
  File "/app/api/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/app/api/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/app/api/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.PermissionDeniedError: Error code: 403 - {'message': 'Streaming requests are not yet allowed.'}
