### ISSUE TITLE
Stream options are not available for Azure openAI

### ISSUE THREAD

**Issue by dale22** [langgenius/dify#9591]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Azure openAI not support stream options 

2024-10-21 08:05:21,141.141 ERROR [Thread-141 (_generate_worker)] [logging_callback.py:169] - Error code: 403 - {'message': 'Streaming requests are not yet allowed.'}
Traceback (most recent call last):
File "/app/api/core/model_runtime/model_providers/__base/large_language_model.py", line 110, in invoke
result = self._invoke(model, credentials, prompt_messages, model_parameters, tools, stop, stream, user)
File "/app/api/core/model_runtime/model_providers/azure_openai/llm/llm.py", line 55, in _invoke
return self._chat_generate(
File "/app/api/core/model_runtime/model_providers/azure_openai/llm/llm.py", line 331, in _chat_generate
response = client.chat.completions.create(
File "/app/api/.venv/lib/python3.10/site-packages/openai/_utils/_utils.py", line 277, in wrapper
return func(*args, **kwargs)
File "/app/api/.venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 590, in create
return self._post(
File "/app/api/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1240, in post
return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
File "/app/api/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 921, in request
return self._request(
File "/app/api/.venv/lib/python3.10/site-packages/openai/_base_client.py", line 1020, in _request
raise self._make_status_error_from_response(err.response) from None
openai.PermissionDeniedError: Error code: 403 - {'message': 'Streaming requests are not yet allowed.'}

![image](https://github.com/user-attachments/assets/a2a5498b-4f16-4d12-a9a2-4fa9ffe24615)

### ✔️ Expected Behavior

return result

### ❌ Actual Behavior

return 403

**Comment by crazywoola** [comment]
We have removed this options in latest version, please upgrade to v0.10.0
