### ISSUE TITLE
The visual model encounters an error when recognizing images through image links

### ISSUE THREAD

**Issue by andylzming** [langgenius/dify#9754]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- The visual model encounters an error when recognizing images through image links.

![0](https://github.com/user-attachments/assets/f3ae7baf-07ee-43f0-866f-6ec48cad0e32)

- error
![1](https://github.com/user-attachments/assets/6046ade3-9bc5-4932-8af7-4c5ad6da60fd)

- error logs
```
2024-10-24 15:47:57,611.611 ERROR [Dummy-8] [completion.py:148] - internal server error.
Traceback (most recent call last):
  File "/app/api/controllers/console/app/completion.py", line 123, in post
    response = AppGenerateService.generate(
  File "/app/api/services/app_generate_service.py", line 60, in generate
    ChatAppGenerator().generate(
  File "/app/api/core/app/apps/chat/app_generator.py", line 110, in generate
    file_objs = file_factory.build_from_mappings(
  File "/app/api/factories/file_factory.py", line 102, in build_from_mappings
    files = [
  File "/app/api/factories/file_factory.py", line 103, in <listcomp>
    build_from_mapping(
  File "/app/api/factories/file_factory.py", line 62, in build_from_mapping
    file = _build_from_remote_url(
  File "/app/api/factories/file_factory.py", line 181, in _build_from_remote_url
    resp.raise_for_status()
  File "/app/api/.venv/lib/python3.10/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'http://192.22.149.190:30081/base/micro/oss/file/preview/dfa97051e4a54af8a70ad6a6c1329bdf/a5ec78bc-1e5f-4e07-b982-6565e734f884.png'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
2024-10-24 15:47:57,612.612 ERROR [Dummy-8] [app.py:838] - Exception on /console/api/apps/2cddb66d-cf78-4d44-86a3-a2963c2acb10/chat-messages [POST]
Traceback (most recent call last):
  File "/app/api/controllers/console/app/completion.py", line 123, in post
    response = AppGenerateService.generate(
  File "/app/api/services/app_generate_service.py", line 60, in generate
    ChatAppGenerator().generate(
  File "/app/api/core/app/apps/chat/app_generator.py", line 110, in generate
    file_objs = file_factory.build_from_mappings(
  File "/app/api/factories/file_factory.py", line 102, in build_from_mappings
    files = [
  File "/app/api/factories/file_factory.py", line 103, in <listcomp>
    build_from_mapping(
  File "/app/api/factories/file_factory.py", line 62, in build_from_mapping
    file = _build_from_remote_url(
  File "/app/api/factories/file_factory.py", line 181, in _build_from_remote_url
    resp.raise_for_status()
  File "/app/api/.venv/lib/python3.10/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'http://192.22.149.190:30081/base/micro/oss/file/preview/dfa97051e4a54af8a70ad6a6c1329bdf/a5ec78bc-1e5f-4e07-b982-6565e734f884.png'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/console/setup.py", line 65, in decorated
    return view(*args, **kwargs)
  File "/app/api/libs/login.py", line 93, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/api/controllers/console/wraps.py", line 22, in decorated
    return view(*args, **kwargs)
  File "/app/api/controllers/console/app/wraps.py", line 49, in decorated_view
    return view_func(*args, **kwargs)
  File "/app/api/controllers/console/app/completion.py", line 149, in post
    raise InternalServerError()
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by hanfangyuan4396** [comment]
same in v0.10.1

**Comment by andylzming** [comment]
> same in v0.10.1

Has this issue been resolved in version v0.10.1?

**Comment by Erincrying** [comment]
I have encountered the same problem as you, have you solved it？

**Comment by andylzming** [comment]
> I have encountered the same problem as you, have you solved it？

No
