### ISSUE TITLE
Paste file link

### ISSUE THREAD

**Issue by eemirtekin** [langgenius/dify#9788]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I upload file via paste file url, I get error "500 (INTERNAL SERVER ERROR)"

![Screenshot 2024-10-24 at 12 15 02](https://github.com/user-attachments/assets/50e0d7f6-24ac-49e8-a6e6-db83e49e7128)

**Comment by crazywoola** [comment]
Please provide the logs of the api container.

**Comment by eemirtekin** [comment]
2024-10-24 09:03:46,002.002 INFO [Dummy-1] [_client.py:1038] - HTTP Request: HEAD https://bmcmededuc.biomedcentral.com/counter/pdf/10.1186/s12909-024-06026-5.pdf "HTTP/1.1 200 OK"
2024-10-24 09:03:47,575.575 ERROR [Dummy-2] [app.py:838] - Exception on /api/workflows/run [POST]
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/web/wraps.py", line 19, in decorated
    app_model, end_user = decode_jwt_token()
  File "/app/api/controllers/web/wraps.py", line 48, in decode_jwt_token
    app_model = db.session.query(App).filter(App.id == decoded["app_id"]).first()
KeyError: 'app_id'
2024-10-24 09:04:14,229.229 INFO [Dummy-3] [_client.py:1038] - HTTP Request: HEAD https://bmcmededuc.biomedcentral.com/counter/pdf/10.1186/s12909-024-06026-5.pdf "HTTP/1.1 200 OK"
2024-10-24 09:04:23,039.039 ERROR [Dummy-4] [app.py:838] - Exception on /api/workflows/run [POST]
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/web/wraps.py", line 19, in decorated
    app_model, end_user = decode_jwt_token()
  File "/app/api/controllers/web/wraps.py", line 48, in decode_jwt_token
    app_model = db.session.query(App).filter(App.id == decoded["app_id"]).first()
KeyError: 'app_id'
2024-10-24 09:13:49,213.213 INFO [Thread-7 (_generate_worker)] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-10-24 09:14:09,630.630 INFO [Dummy-8] [_client.py:1038] - HTTP Request: HEAD https://bmcmededuc.biomedcentral.com/counter/pdf/10.1186/s12909-024-06026-5.pdf "HTTP/1.1 200 OK"
2024-10-24 09:14:20,075.075 ERROR [Dummy-9] [app.py:838] - Exception on /api/workflows/run [POST]
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api/controllers/web/wraps.py", line 19, in decorated
    app_model, end_user = decode_jwt_token()
  File "/app/api/controllers/web/wraps.py", line 48, in decode_jwt_token
    app_model = db.session.query(App).filter(App.id == decoded["app_id"]).first()
KeyError: 'app_id'

**Comment by crazywoola** [comment]
> ```
> 2024-10-24 09:03:46,002.002 INFO [Dummy-1] [_client.py:1038] - HTTP Request: HEAD https://bmcmededuc.biomedcentral.com/counter/pdf/10.1186/s12909-024-06026-5.pdf "HTTP/1.1 200 OK"
> 2024-10-24 09:03:47,575.575 ERROR [Dummy-2] [app.py:838] - Exception on /api/workflows/run [POST]
> Traceback (most recent call last):
>   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
>   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
>     resp = resource(*args, **kwargs)
>   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
>     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
>   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
>     resp = meth(*args, **kwargs)
>   File "/app/api/controllers/web/wraps.py", line 19, in decorated
>     app_model, end_user = decode_jwt_token()
>   File "/app/api/controllers/web/wraps.py", line 48, in decode_jwt_token
>     app_model = db.session.query(App).filter(App.id == decoded["app_id"]).first()
> KeyError: 'app_id'
> 2024-10-24 09:04:14,229.229 INFO [Dummy-3] [_client.py:1038] - HTTP Request: HEAD https://bmcmededuc.biomedcentral.com/counter/pdf/10.1186/s12909-024-06026-5.pdf "HTTP/1.1 200 OK"
> 2024-10-24 09:04:23,039.039 ERROR [Dummy-4] [app.py:838] - Exception on /api/workflows/run [POST]
> Traceback (most recent call last):
>   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
>   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
>     resp = resource(*args, **kwargs)
>   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
>     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
>   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
>     resp = meth(*args, **kwargs)
>   File "/app/api/controllers/web/wraps.py", line 19, in decorated
>     app_model, end_user = decode_jwt_token()
>   File "/app/api/controllers/web/wraps.py", line 48, in decode_jwt_token
>     app_model = db.session.query(App).filter(App.id == decoded["app_id"]).first()
> KeyError: 'app_id'
> 2024-10-24 09:13:49,213.213 INFO [Thread-7 (_generate_worker)] [_client.py:1038] - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
> 2024-10-24 09:14:09,630.630 INFO [Dummy-8] [_client.py:1038] - HTTP Request: HEAD https://bmcmededuc.biomedcentral.com/counter/pdf/10.1186/s12909-024-06026-5.pdf "HTTP/1.1 200 OK"
> 2024-10-24 09:14:20,075.075 ERROR [Dummy-9] [app.py:838] - Exception on /api/workflows/run [POST]
> Traceback (most recent call last):
>   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/app/api/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
>   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
>     resp = resource(*args, **kwargs)
>   File "/app/api/.venv/lib/python3.10/site-packages/flask/views.py", line 110, in view
>     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
>   File "/app/api/.venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
>     resp = meth(*args, **kwargs)
>   File "/app/api/controllers/web/wraps.py", line 19, in decorated
>     app_model, end_user = decode_jwt_token()
>   File "/app/api/controllers/web/wraps.py", line 48, in decode_jwt_token
>     app_model = db.session.query(App).filter(App.id == decoded["app_id"]).first()
> KeyError: 'app_id'
> ```

@dosu generate a fix for above
